### ISSUE TITLE
Adding new record from subgrid

### ISSUE THREAD

**Issue by jorgeolive** [Microsoft/EasyRepro#100]
Hello,

I need to create a new record from a subgrid. This pops up a new form, so not sure how to manage this. Is this feature covered somehow? Been navigating through the documentation but no luck. 

Thanks,
Jorge.

**Comment by TYLEROL** [comment]
Thanks @jorgeolive  - I'll review this scenario, however one extra question so I can compare internally:

- Are quick create forms enabled on the entity?

Regards,
Tyler

**Comment by TYLEROL** [comment]
@jorgeolive - I have included a couple examples below for both a **Quick Create Form** scenario and a **traditional pop-up window** scenario if quick create forms are not enabled.

There is a caveat to this - in the traditional pop-up scenario you'll want to save the new record from grid creation _as the last step_. We're looking into an issue where the main window does not come back to focus if you perform the grid create and then attempt to interact with the original entity record.

**Give either of these a try depending on your scenario. If you have any questions or encounter issues, please let us know.**

1. **Quick Create Form Example**

```
    //Open Primary Entity record
 	            xrmBrowser.Grid.OpenRecord(0);

                    xrmBrowser.ThinkTime(3000);

                //Click Add button on the desired subgrid
                    xrmBrowser.Entity.ClickSubgridAddButton("Contacts", 4000);

                //Switch to the Quick Create form that opens
                    xrmBrowser.Entity.SwitchToQuickCreateFrame();

                //Set Values on the Quick Create form
                    xrmBrowser.QuickCreate.SetValue("firstname", "Test");
                    xrmBrowser.QuickCreate.SetValue("lastname", "Contact");

                //Save the Quick create form
                    xrmBrowser.QuickCreate.Save(3000);

                //Switch back to the main content frame of the form to enter additional content and save
                    xrmBrowser.Entity.SwitchToContentFrame();
                    xrmBrowser.Entity.SetValue("fieldname", "Sample Text.");
                    xrmBrowser.Entity.Save(3000);
```



2. **Traditional Pop-up Window Example**

```
//Open Primary Entity record
                xrmBrowser.Grid.OpenRecord(0);

                xrmBrowser.ThinkTime(3000);

                xrmBrowser.Entity.SetValue("fieldname", "Sample Text");
                xrmBrowser.Entity.Save(3000);

                //Click Add button on the desired subgrid (Contacts)
                xrmBrowser.Entity.ClickSubgridAddButton("Contacts", 4000);

                //Switch to Popup create window for grid entity
                xrmBrowser.Entity.SwitchToPopupWindow();

                //Define values for Composite Control input
                var fields = new List<Field>
                {
                    new Field() {Id = "firstname", Value = "Test"},
                    new Field() {Id = "lastname", Value = "Contact"}
                };

                //Set value of Full Name field
                xrmBrowser.Entity.SetValue(new CompositeControl() { Id = "fullname", Fields = fields });
                
                //Save the new entity record from popup window
                xrmBrowser.Entity.Save(4000);
```
 Thanks,
Tyler

**Comment by jorgeolive** [comment]
Thank you very much for the support. This library is awesome! :+1:

**Comment by Cornholio1337** [comment]
Hey guys.
Could it be, that xrmBrowser.Entity.ClickSubgridAddButton function is not implemented at the moment?

Greetings

**Comment by shariquekhan1997** [comment]
I get this error while using the traditional method (2.) "Exception has been thrown by the target of an invocation." Any Update on this #100 issue?
