### ISSUE TITLE
Regarding Unified Interface

### ISSUE THREAD

**Issue by abrahamjoji** [Microsoft/EasyRepro#101]
I would like to know the details regarding new UI called Unified Interface for D365. So it will be great if you let us know the tentative release dates of Unified Interface along with this we want to know Unified Interface EasyRepro libraries are also releasing with same UI.

As we already started UI automation using existing EasyRepro libraries. By any chance do we need to re-script/modify when we migrate to Unified UI and any major changes in libraries?

**Comment by TYLEROL** [comment]
@abrahamjoji - Support for Unified Interface APIs is on our roadmap and is currently targeted to be available in the next couple months (tentatively May 2018).  More information will be provided as we get closer to the release date.

In regards to automation using existing libraries - you will need to re-script anything that changes to the Unified UI. The Unified Interface client is separate from the existing Web Client and as a result will use a different set of APIs. As we work to expand our documentation, I'll add an item to the backlog to include examples scenarios for changing over from WebClient API calls to Unified Interface API calls.

**Comment by abrahamjoji** [comment]
@TYLEROL Thank you
