### ISSUE TITLE
[FEATURE] S2S (Server-2-Server) connection to have Application user support (Client Secret)

### ISSUE THREAD

**Issue by nakhtar-ntg** [Microsoft/EasyRepro#1015]
**Describe the feature**  
I am looking to connect EasyRepro through the application user/client secret key (Azure app registration).

**Explain why this feature is needed**  
Most of the time we have non-interactive test executions. we don't want to use the functional account which utilizes a license in Dynamics 365. Therefore, the application user is the best option to connect any application with dynamics 365. Below is the reference of the user type I am talking about;

https://docs.microsoft.com/en-us/power-platform/admin/create-users-assign-online-security-roles#create-an-application-user

**Additional context**  
N/a

**Comment by ewingjm** [comment]
I'm not sure that's going to be possible. I think application users by their very nature are non-interactive, so not suitable for UI testing. I might be wrong, though.

**Comment by TYLEROL** [comment]
Hello @nakhtar-ntg,

As @ewingjm correctly stated, application users are intended to be a non-interactive service account that operates in the background to securely and seamlessly communicate between Dataverse and your web applications and service.

The account is not intended to access UI elements required for UI Automation testing with EasyRepro.

Warm Regards,
Tyler
