### ISSUE TITLE
Guys, While trying to use this framework,One issue found while using this tool which we are facing is while logging in to the CRM application with Windows pop up for authentication. We are using CRM 2016 application with a windows pop up for the user to login. How do we handle such scenarios through Easy Repro ?

### ISSUE THREAD

**Issue by RohitNabhi** [Microsoft/EasyRepro#102]

**Comment by TYLEROL** [comment]
Hello @RohitNabhi 

I have not been able to test this scenario, as it is not in the current roadmap for EasyRepro, however you may be able to do something like the following within your Login code:

```
            IAlert alert = driver.SwitchTo().Alert();
            alert.SetAuthenticationCredentials(username.ToUnsecureString(), password.ToUnsecureString());
            driver.SwitchTo().DefaultContent();
```

If the above does not work, then you may need to review external options such as AutoAuth for Firefox, or implementations such as AutoIT. 

It's not currently clear on future support plans for setting authentication values via alerts through Selenium ([see v3.8 change log details here indicating removal of alert.authenticate code](https://github.com/SeleniumHQ/selenium/blob/2430a644d793496c4d3ba1f96e19e9e64d9fb8cb/java/CHANGELOG#L22)) - so if the code above does work now it may not work in the future.

Thanks,
Tyler
