### ISSUE TITLE
Issue in Identifying a Control

### ISSUE THREAD

**Issue by RohitNabhi** [Microsoft/EasyRepro#103]
Hi, 

We are using a D365 CRM application where the navigation to the entities from the home page is a bit different. The xrmBrowser.Navigation.OpenSubArea("Settings", "Users"); doesn't seem to work here and i've tried adding a new control by replacing OpenSubArea by detecting the class name/ID, but it doesn't seem to work. I need to click on the down arrow mark just beside Workplace to see the list of Entities. PFA screenshot. Is there any way to handle this in EasyRepro ?
<img width="633" alt="easyrepro control" src="https://user-images.githubusercontent.com/37740764/37864827-abc0d2a4-2f99-11e8-9712-cbdbc4110f88.png">

**Comment by TYLEROL** [comment]
Hello @RohitNabhi,

Which version of Dynamics 2016 are you using (8.0.X.XXX, 8.1.X.XXX, or 8.2.X.XXX)? This should work on 8.1 and 8.2 versions, however once you've confirmed I can re-test this implementation.

Additionally, if you use the browser dev tools to inspect the element on 'Workplace', what ID tags do you see listed?

Thanks,
Tyler

**Comment by RohitNabhi** [comment]
Hi @TYLEROL :- We are using 8.2 Versions. I did some R&D behind this yesterday, and could acheive it adding the Code "driver.FindElement(By.XPath("//*[@id='TabWorkplace']/a")).Click();" in OpenMenu under OpenSubArea method.

**Comment by RohitNabhi** [comment]
@TYLEROL :- I had also posted another question, looks like that is deleted/closed. Can we handle windows pop up controls for User Login using Easyrepro? Below pic shows the pop up which I need to handle. Can you please help here ?

![image](https://user-images.githubusercontent.com/37740764/37952982-318ffd2a-31bf-11e8-94b4-45195fee05bd.png)

**Comment by TYLEROL** [comment]
Thanks @RohitNabhi - I'll add an item to our backlog to review sitemap configurations containing the 'Workplace' tab. This was removed from most Dynamics CRM Online instances during the 2013/2015 versions, so when the latest versions of EasysRepro were built and tested the Workplace tab would not have been present. The existing code should be resilient to detect/identify all Areas available for selection when using the OpenSubArea() method, but it appears the Workplace tab is causing issues with that.

Thank you again for raising this issue. In regards to Issue #102 that you posted, hopefully these options provide you with an alternative means to working around this Selenium limitation with Windows Authentication prompts. Here is another article for alternative options you may be able to try with the Chrome browser (https://stackoverflow.com/questions/19357634/handle-windows-authentication-pop-up-on-chrome)

Thanks,
-Tyler

**Comment by RohitNabhi** [comment]
Thanks a lot @TYLEROL for your comment. Appreciate your help in identifying options around handling windows controls using Easyrepro. Thanks again !
