### ISSUE TITLE
[HOW-TO] Maximize the chrome browser with easyrepro

### ISSUE THREAD

**Issue by itsmyownview** [Microsoft/EasyRepro#1030]
## Question

In my local machine when I run my easyrepro code using chrome browser, it opens with 1920x1080 size. But when I run the same code in my Azure pipeline in headless mode, It is not coming as maximized. I added some debug logs, and understood that height and width is of 600x800. And as a result some of the command bar buttons trapped inside the "More Options".

Could you please guide me how to start the chrome browser in full screen or maximized way ?

Note : I tried the below options.
1. `options.AddArgument("--start-maximized");`
2. Tried to set Full Screen option from the Window, `client->Browser->Window->FullScreen`
3. Tried to set the size of browser from chrome options

**Comment by ewingjm** [comment]
You do this by passing a `BrowserOptions` object to the `WebClient` constructor. In my experience, `StartMaximized` needs to be explicitly set to `false` and `Height` and `Width` need to be set when running in headless mode on Azure Pipelines hosted agents.

**Comment by TYLEROL** [comment]
Another option you can try is to either force the agent resolution with PowerShell script, or use the 'Screen Resolution Utility' build task. Call either of these in the build pipeline prior to test execution and the maximized browser window should match the display resolution you set on the agent:

- [Screen Resolution Utility](https://marketplace.visualstudio.com/items?itemName=ms-autotest.screen-resolution-utility-task#overview)
- PShell script option (either file ref or inline):
```
# Set agent screen resolution to 1920x1080 to avoid sizing issues with browser
Set-DisplayResolution -Width 1920 -Height 1080 -Force

# Wait 10 seconds
Start-Sleep -s 10

# Verify Screen Resolution is set to 1920x1080
Get-DisplayResolution
```

**Comment by Shakevg** [comment]
@itsmyownview Next steps are working for me for browser in Headless mode on Azure Hosted Agent(ScreenWidth=1920; ScreenHeight=1080):
1. Set "Display Settings" = "Optimal Resolution" settings using [Screen Resolution Utility](https://marketplace.visualstudio.com/items?itemName=ms-autotest.screen-resolution-utility-task#overview)
2. Set browser size for Headless mode
```CSharp
var client = new WebClient(TestSettings.Options);
if (TestSettings.Options.Headless) // set browser size for Headless mode
    client.Browser.Driver.SetSize(ScreenWidth, ScreenHeight)
```
