### ISSUE TITLE
Advanced Find Query execution ... if and when?

### ISSUE THREAD

**Issue by TAJStewart** [Microsoft/EasyRepro#104]
Really need this functionality. Is this functionality planned ?

**Comment by TYLEROL** [comment]
Hello @TAJStewart - We have this on the backlog of items for expanding EasyRepro capabilities, however no ETA on completion of this work.

As of today, the only available API for Advanced Find is the OpenAdvancedFind method, to test and verify there are no issues with opening the Advanced Find window:

`xrmBrowser.Navigation.OpenAdvancedFind(6000);`

Do you have an example scenario that you are trying to accomplish? We can try to provide some pointers for manual implementation _(e.g. no API, but manually finding elements and inputting/selecting values)_ and possibly an example depending on what you're doing.

Regards,
Tyler

**Comment by TAJStewart** [comment]
Thanks Tyler.  Yes, knew about the OpenAdvancedFind() method, but actually needed to do Adv Find queries. I have linked to my existing Selenium Adv Find query methods for now.

**Comment by TYLEROL** [comment]
As mentioned earlier, we have this in our backlog for feature consideration @TAJStewart 

If you have any additional questions or concerns, please let us know. You are also welcome to submit a pull request with your Advanced Find query methods for consideration by our team into the larger project.

Thanks again for raising this item and we hope you're having a great experience using this Dynamics 365 UI Automation test library.

-Tyler

**Comment by sagarbajad** [comment]
Is there any same method for UCI? like "xrmApp.Navigation.OpenAdvancedFind()" ?

**Comment by Khushbukumaripathak** [comment]
"xrmApp.Navigation.OpenAdvancedFind()" is not working as of now.
