### ISSUE TITLE
How can i Lunch Chrome when  lower version of ChromDriver[85] and upper version of chrome? 

### ISSUE THREAD

**Issue by sanatlami** [Microsoft/EasyRepro#1057]
I have ChromeDriver 85 version in code which is the biggest in the NuGet but my system chrome version is  87. How can i handle this condition please help ?

![image](https://user-images.githubusercontent.com/51536031/104744034-03389600-5712-11eb-97ee-4913b4cb89cb.png)
![image](https://user-images.githubusercontent.com/51536031/104744150-28c59f80-5712-11eb-82d1-5db16684a338.png)
![image](https://user-images.githubusercontent.com/51536031/104744178-32e79e00-5712-11eb-8379-4973043ffabe.png)

**Comment by aliyoussefi** [comment]
Hi @sanatlami,

The NuGet package needs to be updated in the test assembly. You can find this by managing the NuGet Packages with the Package manager in Visual Studio. Please refer to this video which includes a demo: [EasyRepro - Troubleshooting - SessionNotCreated Exception](https://www.youtube.com/watch?v=bXCbx1gM6MM&list=PLtQtmfRDxadM6iYpmiivgrACsQrzFa_t6)

**Comment by sanatlami** [comment]
Thank you @aliyoussefi for your reply. 

i did update that but in my case NuGet has only 85 the latest one but Chrome in Version 87. I have attached the picture of NuGet and Chrome.  
![image](https://user-images.githubusercontent.com/51536031/104777825-0186c680-5742-11eb-8d8b-3e7f5f4a2a18.png)
![image](https://user-images.githubusercontent.com/51536031/104777844-08add480-5742-11eb-9cba-46fba42892f0.png)

**Comment by thathi** [comment]
for workaround you can try this webdriver. 

![image](https://user-images.githubusercontent.com/15817637/104779087-5f350600-5776-11eb-8dbc-31f654a1097e.png)

**Comment by thathi** [comment]
you can use this package as workaround @sanatlami
![image](https://user-images.githubusercontent.com/15817637/104779229-9efbed80-5776-11eb-9034-478eff36b7f6.png)

**Comment by aliyoussefi** [comment]
Hi @sanatlami Please review @thathi comment as this is the correct package to use moving forward. I will create an issue to update the assembly in the source. Please confirm so we can close this out.

**Comment by aliyoussefi** [comment]
> Hi @sanatlami Please review @thathi comment as this is the correct package to use moving forward. I will create an issue to update the assembly in the source. Please confirm so we can close this out.

https://github.com/microsoft/EasyRepro/issues/1058

**Comment by sanatlami** [comment]
Hi @aliyoussefi yes i am able to lunch the chrome with @thathi way. I am getting some error i dont think that's related to chrome.
