### ISSUE TITLE
[BUG] - Unable to identify Web Elements using the LookupItem and OptionSet options

### ISSUE THREAD

**Issue by VikramKurri** [Microsoft/EasyRepro#1073]
**Case 1**: unable to identify the lookup field using the LookupItem functionality we have in Easy Repro even using BusinessProcessFlow

Here’s the code that I am using, 

LookupItem Origin = new LookupItem { Name = "header_process_aac_originid.fieldControl-LookupResultsDropdown_aac_originid_textInputBox_with_filter_new", Value = "DFW" };                        
xrmApp.Entity.SetValue(Origin);

![Lookupfield](https://user-images.githubusercontent.com/38299120/106307439-fdb87100-6224-11eb-9134-2c07f11fd0ea.jpg)

Here are some of the other names I used in the ‘Name’ field.

header_process_aac_originid
header_process_aac_originid-header_process_aac_originid-FieldSectionItemContainer
header_process_aac_originid-header_process_aac_originid-field-label
header_process_aac_originid.fieldControl-Lookup_aac_originid
header_process_aac_originid.fieldControl-LookupResultsDropdown_aac_originid_InputSearch
header_process_aac_originid.fieldControl-LookupResultsDropdown_aac_originid_textInputBox_with_filter_new

Here is the Error I am getting, while I execute the above line of code and it is throwing at this xrmApp.Enity.SetValue(Origin) step.

Error : System.ArgumentException: 'MoveToElement cannot move to a null element with no offset. Parameter name: toElement'

**Case2**:  unable to identify using the Optionset functionality we have in Easy Repro for Option set field. 

Here is the code that I executed for identifying and running the Optionset
xrmApp.Entity.SetValue(new OptionSet { Name = "header_process_aac_product", Value = "GCX" });
or 
xrmApp.BusinessProcessFlow.SetValue(new OptionSet { Name = "header_process_aac_product", Value = "GCX" });

![OptionsetField](https://user-images.githubusercontent.com/38299120/106307482-0a3cc980-6225-11eb-83e2-7d50a015f27c.jpg)

Error: System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Comment by VikramKurri** [comment]
Used the BusinessProcessFlow code available in framework and it worked. Please use that.

**Comment by chandramohand** [comment]
Hi @VikramKurri, Me too facing the same issue on Quick form where Lookups not working, I tried all the ways even with Business process flow.  Could you please provide some more details how the Business process flow worked for you?
Thanks,
Chandra.
