### ISSUE TITLE
Does it support Potassium? - SetValue  not working while Updating

### ISSUE THREAD

**Issue by anilkumarpotluri** [Microsoft/EasyRepro#108]
We have seen quite a few issues(Ex: SetValue not working while updating the existing data) in potassium, would like to know whether it's support Potassium or not?

Thanks,
Anil.

**Comment by TYLEROL** [comment]
Hi @anilkumarpotluri 

Can you provide some information on the following:

- Browser and Browser Version
- WebDriver version (e.g. ChromeDriver v2.31)
- Behavior observed when using SetValue (e.g. when using SetValue to update a field that has existing data, do you see an error? does nothing appear to change?

The SetValue functions are supported with Potassium builds, specifically for the WebClient. The Unified Interface will be supported in a future release, though my assumption here is that you are utilizing the WebClient.

Thanks,
Tyler

**Comment by anilkumarpotluri** [comment]
Yes we are using ChromeDriver v2.33 and supported Chrome Browser.
It's working fine while we creating any entity, we have issue only while updating 

**Repro steps:**

1. Run Using Chrome Driver
2. Open any existing Entity.
3. Try to update the  any mandatory text field , even you enter the value it show's error message.


It's working fine when we tested it manually.

Thanks,
Anil.

**Comment by eccountable** [comment]
Why are you using SetValue() instead of SendKeys?

**Comment by TYLEROL** [comment]
@eccountable - The SetValue() method is provided as part of the EasyRepro APIs. I've included an example of SetValue() method for a Date field within Dynamics 365.

The idea behind this is to make configuring your tests easier - in this case a single line of code instead of 50+ lines of code. Call SetValue() of the appropriate method type based on the field you want to apply a value to, and we'll handle the rest via the underlying Selenium code. Under the covers, we're using SendKeys() as you would normally expect.

In this specific scenario, the problem with SetValue() is that the method is firing in some cases prior to the field element being available on the web page due to page load delays. This timing issue started popping up with the v2.37 ChromeDriver implementation. Adding in xrmBrowser.ThinkTime(2000) method calls with a time delay will work around those problems for now. We're working to enhance this in the future to be more resilient depending on how long it takes to load the form.

 Hope that helps!


```
  /// <summary>
        /// Sets the value of a Date Field.
        /// </summary>
        /// <param name="field">The field id or name.</param>
        /// <param name="date">DateTime value.</param>
        /// <example> xrmBrowser.Entity.SetValue("birthdate", DateTime.Parse("11/1/1980"));</example>
        public BrowserCommandResult<bool> SetValue(string field, DateTime date)
        {
            return this.Execute(GetOptions($"Set Value: {field}"), driver =>
            {
                if (driver.HasElement(By.Id(field)))
                {
                    var fieldElement = driver.ClickWhenAvailable(By.Id(field));

                    //For dateTime fields present on appointment form
                    if (fieldElement.IsVisible(By.Id($"{field}_iDateInput")) && fieldElement.IsVisible(By.Id($"{field}_iTimeInput")))
                    {
                        var input = fieldElement.FindElement(By.TagName("input"));
                        if (input.GetAttribute("value").Length > 0)
                        {
                            input.Clear();
                            /* field element click not required as click event is happend already */
                            fieldElement.Click();
                            input.SendKeys(date.ToShortDateString());
                            input.SendKeys(Keys.Enter);
                        }
                        else
                        {
                            input.SendKeys(date.ToShortDateString());
                            input.SendKeys(Keys.Enter);
                        }
                    }

                    //For Normal dateTime(date only) fields present on other form
                    else
                    {
                        //Check to see if focus is on field already
                        if (fieldElement.FindElement(By.ClassName(Elements.CssClass[Reference.SetValue.EditClass])) != null)
                            fieldElement.FindElement(By.ClassName(Elements.CssClass[Reference.SetValue.EditClass])).Click();
                        else
                            fieldElement.FindElement(By.ClassName(Elements.CssClass[Reference.SetValue.ValueClass])).Click();
               
                        var input = fieldElement.FindElement(By.TagName("input"));
                        if (input.GetAttribute("value").Length > 0)
                        {
                            input.Clear();
                            /* field element click not required as click event is happend already */
                            //fieldElement.Click();
                            input.SendKeys(date.ToShortDateString());
                            input.SendKeys(Keys.Enter);
                        }
                        else
                        {
                            input.SendKeys(date.ToShortDateString());
                            input.SendKeys(Keys.Enter);
                        }
                    }
                }
                else
                    throw new InvalidOperationException($"Field: {field} Does not exist");

                return true;
            });
        }
```

Regards,
Tyler

**Comment by dtu11** [comment]
Closing issue.  If you are still experiencing this issue then either reopen issue or create a new issue.
