### ISSUE TITLE
[HOW-TO] When executing simple login and opening Dashboard test from Jenkins getting Null  Reference  Exception

### ISSUE THREAD

**Issue by PavanMudigonda** [Microsoft/EasyRepro#1081]
## When executing simple login and opening Dashboard test from my organization Jenkins I am getting Null Reference Exception. But when I run locally from Visual Studio by selecting method and right click and run it works without any issues and passes. I have been struggling from last 24 hours. Any help or suggestions would be appreciated. Please see image below.

**What is your question?**
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/29324338/107382985-80abb800-6abe-11eb-8edf-df471e034433.png">

**Comment by PavanMudigonda** [comment]
Issue is happening on line number 16. I enter user name password and Crm URL in app settings but it's not working 

![image](https://user-images.githubusercontent.com/29324338/107419671-0db63780-6ae6-11eb-9508-5882cce0bb52.png)

**Comment by Shakevg** [comment]
@mnpawan Could you check that app settings (e.g. look on file source) are really contained "OnlineUsername" when you run a test on Jenkins?

**Comment by PavanMudigonda** [comment]
You can close this. I managed to fix it.
