### ISSUE TITLE
Why am i getting this Error while clicking save button. 

### ISSUE THREAD

**Issue by sanatlami** [Microsoft/EasyRepro#1105]
The form is under PCF control, i had to use Selenium to click on those fields, every fields is working except few button to click save is not working. I am getting "Object reference not set to an instance of an object". this Same code was working with my previous solution but when new version came this  same code is not working. I am able to track the xpath but when i use that xpath its not in VS code its not clicking save button. Please someone help me. 

![image](https://user-images.githubusercontent.com/51536031/110175949-2bff1280-7dc8-11eb-9e32-ad2d6f0990f6.png)

**Comment by badarmunirr** [comment]
easyrepro version you are? using

**Comment by sanatlami** [comment]
@badarmunirr code is up to date with git hub. 

![image](https://user-images.githubusercontent.com/51536031/110505552-deceb980-80c3-11eb-91c2-be21dae5ec2f.png)

**Comment by Shakevg** [comment]
@sanatlami Could you provide steps and code to reproduce?
Are you using custom methods(XPaths) or provided by the library?
Did you check that issue related to EasyRepro changes but not the D365 update (run the same code with the previous versionlibrary)?

**Comment by sanatlami** [comment]
@Shakevg 
Steps to reproduce: 
1. Create Account-> create Custom form 1 from Sub grid. Populate everything Save. _[This far everything working fine with Easyrepro basice code]._
2. Create Custome form2 from Form1 sub grid. [**_This form is build under PCF control]_**
3. Form lunch , Populate all the fields using Selenium Code **[ _basic EasyPro code doesn't work in this form so i used Selenium code to populate all the fields]._** 
4. Issue. when i try to Save this form its not clicking the button. I used XrmApp.CommandBar.ClickCommand("Save"); No Luck, i used Selenium Code No Luck, it doent find correct Xpath, but when i use in Inspect it work but not in code.

Question: Is there a way i can use Key event using EasyRepro? like Press CTRL+S ? Why EasyRepro not working in  PCF control forms?

**Comment by Shakevg** [comment]
@sanatlami I suppose your form2 has the frame and you need to switch to it before XrmApp.CommandBar.ClickCommand("Save");
Could you show the form screen and markup?

**Comment by sanatlami** [comment]
I did figure this issue. to resolve this, i had to create two layer of Xpath and click the button.
