### ISSUE TITLE
[BUG] ChromeDriver issue

### ISSUE THREAD

**Issue by smallteam1** [Microsoft/EasyRepro#1107]
After Chrome browser updates, I am getting below error:

System.Exception: session not created: This version of ChromeDriver only supports Chrome version 87
    Current browser version is 89.0.4389.82 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)

I changed the packages.config, still not working 
  <package id="Selenium.WebDriver.ChromeDriver" version="89.0.4389.82" targetFramework="net462" />

**Comment by ewingjm** [comment]
What version did you update the Chrome driver version to?

**Comment by smallteam1** [comment]
![image](https://user-images.githubusercontent.com/18255804/110885430-d7e6b780-830c-11eb-9f56-58c4aa6a7a98.png)


```
  <package id="Selenium.Chrome.WebDriver" version="85.0.0" targetFramework="net462" />
  <package id="Selenium.Firefox.WebDriver" version="0.27.0" targetFramework="net462" />
  <package id="Selenium.Support" version="3.141.0" targetFramework="net462" />
  <package id="Selenium.WebDriver" version="3.141.0" targetFramework="net462" />
  <package id="Selenium.WebDriver.ChromeDriver" version="89.0.4389.82" targetFramework="net462" />
```

  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Selenium.WebDriver.ChromeDriver.89.0.4389.82' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'Selenium.WebDriver.ChromeDriver.89.0.4389.82' is not found on source 'https://api.nuget.org/v3/index.json'.

**Comment by smallteam1** [comment]
Issue is resolved.
1) From nuget I have installed latest "Selenium.WebDriver.ChromeDriver"
2) Packages.config got automatically updated with` <package id="Selenium.WebDriver.ChromeDriver" version="89.0.4389.2300" targetFramework="net462" />`
