### ISSUE TITLE
[HOW-TO] <Login to CRM2016 OnPrem 8.2 not working>

### ISSUE THREAD

**Issue by vdro** [Microsoft/EasyRepro#1109]
Welcome community.

My current project runs 8,2 Dynamics CRM OnPremise version.
for this i am using code from: https://github.com/microsoft/EasyRepro/tree/releases/OnPremise

- i was trying to use VS 2017 and 2019 - no luck - should i stick to 2017?
- what Google Chrome version should i use to make it work? is it matter at all?
Current version is 89 as i remember correctly.
i was trying on **85** - still no luck

- using a default Nuget packages

more details:

my on premise app.confing contains data
   ```
<add key="OnlineUsername" value="localdomain\user" />   (i was trying with localdomain and without)
    <add key="OnlinePassword" value="password" />
    <add key="OnlineCrmUrl" value="url" />
    <add key="AzureKey" value="" />
```

data provided are not filled when login pop up is visible
i have no way to catch and interact with login popup window

i was trying also  to pass credentials by: 
                driver.Navigate().GoToUrl("http://user:pass@url");
still no luck

when i manually log into CRM  -  test was "doing" something, so i guess the interaction works.

can you please give me some tip? what i am doing wrong? 
thank you very much

**Comment by muhammad-naderi** [comment]
hey there

looks like this approach works

```
using (var xrmBrowser = new Api.Browser(TestSettings.Options))
{
     xrmBrowser.GoToXrmUri(_xrmUri);
     xrmBrowser.Driver.Url = "https://user:pass@crmdev.domain.local/CrmDevelopment";
     xrmBrowser.Driver.Navigate();
     // ... continue test
}
```

**Comment by vdro** [comment]
hello,
thanks for the hint.
worked!
