### ISSUE TITLE
[BUG]System.InvalidOperationException: Timeout after 10 seconds. Expected: 9:58 AM. Actual: 09:58

### ISSUE THREAD

**Issue by jane188** [Microsoft/EasyRepro#1112]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [ ] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
UCI (XrmApp)

**Online or On Premise**
Online

**Browser**
Chrome

**Describe the bug**  
Get timeout error after set a Datetime field

**Special formatting / display**  

**Code to reproduce**  
xrmApp.Entity.SetValue("datetimefield", DateTime.Now, "dd/MM/yyyy", "H:mm:ss");

```csharp
xrmApp.Entity.SetValue("datetimefield", DateTime.Now, "dd/MM/yyyy", "H:mm:ss");
also try this format, but get same error
 xrmApp.Entity.SetValue(new DateTimeControl("datetimefield") { Value = DateTime.Parse(dateString) }); 
 
**Expected behavior**  
no error

**Screenshots**  
<!-- You are encouraged to add screenshots to help diagnose your problem. -->

**Additional context**  
<!-- Add any other context about the issue or things you've already tried here. -->

**Comment by Peter-Crook** [comment]
I'm seeing something similar on other field types: Error: Timeout after 10 seconds. Expected: 98. Actual: 98.00. It's not repeatable, failing inconsistently.

**Comment by jane188** [comment]
To work around it, I  used try{} catch() block. But ideally, it should work without timeout error.
