### ISSUE TITLE
Get grid items not working in case more than one grid is on the page

### ISSUE THREAD

**Issue by mariana58** [Microsoft/EasyRepro#113]
get grid items should be handled by grid id, it gets the items of the first grid

**Comment by TYLEROL** [comment]
Hello @mariana58 - Could you share a sample of your code / test steps in which you are using to call the GetGridItems() method?

I'll review the scenario and report back accordingly.

Thanks!
Tyler

**Comment by MDendura** [comment]
It would be useful to be able to select a subgrid from the form by name, as I'm facing the same problem on the default System User form.

Here's the form I'm testing with: ![systemuser form](https://user-images.githubusercontent.com/917692/42462407-1ba5e4ce-839b-11e8-8f2f-aa207963ba05.png)

You can see there's a couple of subgrids on this form.

And here's the code from one of my tests:

```csharp
[TestMethod]
public void Verify_UserQueues()
{
    using (var xrmBrowser = new Browser(BrowserOptions))
    {
        xrmBrowser.Navigation.OpenSubArea("Settings", "Security", 1000);

        xrmBrowser.Administration.OpenFeature("Users");

        xrmBrowser.Grid.Search("Matt Dendura");

        xrmBrowser.Grid.OpenRecord(0, 1000);

        xrmBrowser.Entity.SelectSubgridLookup("PrivateQueuesSubGrid");

        // BUG: This next line gets me back items from the teams grid, rather than the queues one.
        IEnumerable<string> queueNames = xrmBrowser.Grid.GetGridItems().Value.Select(q => q.GetAttribute<string>("name")).ToList();

        CollectionAssert.AreEquivalent(queueNames, this.ExpectedQueues);
    }
}
```

Perhaps there is a way to select the queues subgrid by name that I have missed.

EDIT: Also worth nothing that I'm testing against Dynamics 365 Online Version 1612 (9.0.2.449) (DB 9.0.2.438)

**Comment by TYLEROL** [comment]
@mariana58 - After reviewing @MDendura's related issue posting, we believe we have a better understanding of your issue which is a missing feature enhancement.

I've added an item to our backlog to add this feature enhancmenet which would allow usage of GetGridItems with subgrids on an entity form. The current intended design of the GetGridItems() method is for use with an entity grid (the stage prior to open a record form).

If we've misunderstood, please let me know and we're happy to re-evaluate your scenario.

Best Regards,
Tyler
