### ISSUE TITLE
SelectLookup by text not working if item not exist on the first shown items

### ISSUE THREAD

**Issue by mariana58** [Microsoft/EasyRepro#114]
in case lookup contains more than 10 items and i need to select an item with text it act as lookup only contains that 10 items

**Comment by TYLEROL** [comment]
Thanks @mariana58. We're looking into this and will report back on our findings or if more information is necessary.

In the meantime, would you be able to share your code / test steps when calling the SelectLookup() method? We have a Lookup.Search() method available that can be called after selecting the lookup, and then perform a text search to select the desired record from the lookup picker. This method generally expects that the searched result will be unique. 

-Tyler
