### ISSUE TITLE
why xrmApp.Entity.GetValue() return null reference if the text field is hidden

### ISSUE THREAD

**Issue by jane188** [Microsoft/EasyRepro#1144]
## Question
I try to get a value from a hidden text field by using xrmApp.Entity.GetValue() and I get the null reference error. See error details:
System.NullReferenceException: Object reference not set to an instance of an object.

We don't want to show this text field.

Why does it happen? how to fix it?

Thanks for your help!

**Comment by AngelRodriguez8008** [comment]
That is the standard behavior of EasyRepro. If the User don't see it, you are not able to check it with EasyRepro. You can just simulate the user interaction.

I added the funcionallity long time ago. But the MS-Guys don't wanted to included it in the Master Branch.
  
  result = xrmApp.FormJS.GetAttributeValue<string>("name");
  
https://github.com/AngelRodriguez8008/EasyRepro/blob/a34bf32339fe928259b482c34991597df5e486a6/Microsoft.Dynamics365.UIAutomation.Sample/UCI/FormJS/CreateAccount.cs#L207

**Comment by jane188** [comment]
Thank you very much for your help and all the information! Appreciate all of your work!
