### ISSUE TITLE
[HOW-TO] Avoid the exception: Field does not exist

### ISSUE THREAD

**Issue by PawelWas1985** [Microsoft/EasyRepro#1145]
## Question

**Could anyone helps me with the problem to SetValue in regular input field? I'm working with the UCI tests. One of the field that i have to fill out is firstname - this field is on the bottom of the site. When i'm scrolling down manually during running tests everything works fine but without any manually action during running test the exception appears: OpenQA.Selenium.NoSuchElementException: Field with name firstname does not exist.**

Code:
```
`public void UCITestCreateCandidate()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, client.ADFSLoginAction);

                xrmApp.Navigation.OpenSubArea("Sales", "Candidates");
                
                xrmApp.CommandBar.ClickCommand("New");
                
              
                xrmApp.ThinkTime(5000);

                xrmApp.Entity.SetValue("firstname", "Jack");

                

            }
        }`
```

**Comment by Shakevg** [comment]
@PawelWas1985 EasyRepro as Selenium base library cannot work with controls that not available.
You should make control available using custom code. E.g. scroll to some control near your field https://stackoverflow.com/questions/3401343/scroll-element-into-view-with-selenium. You can check in the markup which control is available near your field, maybe you can try section tab4_section_name name.

**Comment by PawelWas1985** [comment]
@Shakevg Thanks for advices but unfortunately nothing helps. i tried:
1. ` public void test()
        {
            
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                
                
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, client.ADFSLoginAction);

                xrmApp.Navigation.OpenSubArea("Sales", "Candidates");

                xrmApp.CommandBar.ClickCommand("New");
    
                IJavaScriptExecutor js = client.Browser.Driver as IJavaScriptExecutor;
                js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
                
           }

        }`
2. `public void test()
        {
            
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                
                
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, client.ADFSLoginAction);

                xrmApp.Navigation.OpenSubArea("Sales", "Candidates");

                xrmApp.CommandBar.ClickCommand("New");
    
              Actions actions = new Actions(client.Browser.Driver);
              actions.SendKeys(Keys.PageDown);
              actions.Build().Perform();
                
           }

        }`
3. `public void test()
        {
            
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                
                
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, client.ADFSLoginAction);

                xrmApp.Navigation.OpenSubArea("Sales", "Candidates");

                xrmApp.CommandBar.ClickCommand("New");
                IWebElement firstName = client.Browser.Driver.FindElement(By.XPath("//input[@aria-label='First Name']"));
    
            
                
           }

        }` here i received NoSuchElementException so i tried try and catch block   - also NoSuchElementException
4. `public void test()
        {
            
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                
                
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, client.ADFSLoginAction);

                xrmApp.Navigation.OpenSubArea("Sales", "Candidates");

                xrmApp.CommandBar.ClickCommand("New");
                try
                {
                    IWebElement firstName = client.Browser.Driver.FindElement(By.XPath("//input[@aria-label='First Name']"));
                }catch(OpenQA.Selenium.NoSuchElementException ex)
                {
                    IWebElement firstName = client.Browser.Driver.FindElement(By.XPath("//input[@aria-label='First Name']"));
                    firstName.SendKeys("dupa");

                
    
            
                
           }

        }`
5. Also tried to handle with waits
`public void test()
        {
            
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                
                
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, client.ADFSLoginAction);

                xrmApp.Navigation.OpenSubArea("Sales", "Candidates");

                xrmApp.CommandBar.ClickCommand("New");
                IWebElement firstName = client.Browser.Driver.WaitUntilClickable(By.XPath("//input[@aria-label='First Name']"));
                firstName.SendKeys("Jack");

        }`
6. `public void test()
        {
            
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                
                
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, client.ADFSLoginAction);

                xrmApp.Navigation.OpenSubArea("Sales", "Candidates");

                xrmApp.CommandBar.ClickCommand("New");
               WebDriverWait wait = new WebDriverWait(client.Browser.Driver, new TimeSpan(0, 0, 10));
               wait.Until(ExpectedConditions.ElementIsVisible(By.Xpath("//input[@aria-label='First Name']")));

        }`

Nothin helped. Anyway if i'm on the tested page and trying to find any of element in this way: IWebElement firstName = client.Browser.Driver.WaitUntilClickable(By.XPath("//input[@aria-label='First Name']")); i've got the NoSuchElementException each time of each element. To be honest i completely don't know what is wrong.

**Comment by Shakevg** [comment]
@PawelWas1985 
1,2. Will work only if you have full page scroll, but in your case, it is scroll for some container inside page 
3-6. You should scroll to the first available (you can check in page source) element (the 'first name' is not available until you scroll to it manually).
I propose to scroll to each section:
```
IJavaScriptExecutor js = client.Browser.Driver as IJavaScriptExecutor
var sectionName = client.Browser.Driver.FindElement(By.XPath("//*[@text()='EXPECTATIONS']"));
js.executeScript("arguments[0].scrollIntoView(true);", sectionName );
sectionName = client.Browser.Driver.FindElement(By.XPath("//*[@text()='WORK CIRCUMSTANCES']"));
js.executeScript("arguments[0].scrollIntoView(true);", sectionName );
sectionName = client.Browser.Driver.FindElement(By.XPath("//*[@text()='OWNERSHIP']"));
js.executeScript("arguments[0].scrollIntoView(true);", sectionName );
sectionName = client.Browser.Driver.FindElement(By.XPath("//*[@text()='COMMENTS']"));
js.executeScript("arguments[0].scrollIntoView(true);", sectionName );
sectionName = client.Browser.Driver.FindElement(By.XPath("//*[@text()='PERSONAL DETAILS']"));
js.executeScript("arguments[0].scrollIntoView(true);", sectionName );
```

**Comment by PawelWas1985** [comment]
Hi @Shakevg 
The problem is that the driver is not able to find even first element:
![2021-06-25 10_23_17-Movies   TV](https://user-images.githubusercontent.com/84560651/123394622-9e764700-d59f-11eb-9a87-12ee0c28a3b8.png)
I'm wondering why such code doesn't work:
```
var executor = client.Browser.Driver as IJavaScriptExecutor;
executor.ExecuteScript("window.scrollBy(0, 1000)");
```
Do you have any idea? i will be very grateful for any advices.

**Comment by Shakevg** [comment]
@PawelWas1985 I suppose because it is inside Frame. You need to switch to Frame first that search text: https://www.guru99.com/handling-iframes-selenium.html
Then switch back driver.switchTo().defaultContent(); after actions with Frame
