### ISSUE TITLE
Error when attempting to login - System.InvalidOperationException

### ISSUE THREAD

**Issue by VikramKurri** [Microsoft/EasyRepro#115]
File Name:
LoginPage.cs

Line Number:
71

Method Signature:
public BrowserCommandResult<LoginResult> Login(Uri uri, SecureString username, SecureString password)

Error Message:
An exception of type 'System.InvalidOperationException' occurred in Microsoft.Dynamics365.UIAutomation.Browser.dll but was not handled in user code

**Comment by TYLEROL** [comment]
@vicky0904 - It looks like this is a compatibility issue with the version of Chrome being used and the ChromeDriver implemented in the project.

We've recently observed issues with the Chrome 65+ Update and the ChromeDriver (v2.31) included in the current GitHub project. For compatibility, please update to v2.37 of the ChromeDriver

The following [article](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui) describes how you can update the NuGet package for the ChromeDriver. For Chrome v64-66, please install the Selenium.Chrome.WebDriver v2.37 in your projects. 

**Note: We're also looking into issues with Selenium via the latest ChromeDriver. Code execution appears to be much more aggressive in the latest version so additional ThinkTime may be required between methods in your code tests. We're testing the API's internally to resolve some of these issues to not require ThinkTime methods.**

Please let me know whether this resolves your login issues.

Thanks,
Tyler

**Comment by TYLEROL** [comment]
@vicky0904 - Wanted to let you know that an updated version of APIs were released last night to support v8.2, v9.0, and the latest v9.0.2 branch for Dynamics 365. The v9.0.2 branch adds support for the Unified Interface.

There are a wide array of fixes included, some of which will resolve issues with aggressive code execution, though in some scenarios ThinkTime may still be required. 

If you have any issues with the latest branches of code, please raise any new issues as required. Thanks again for using the APIs!

Regards,
Tyler
