### ISSUE TITLE
[HOW-TO] Select Tab

### ISSUE THREAD

**Issue by VikariiCGI** [Microsoft/EasyRepro#1156]
How can I select entity tab via XrmApp?

**Comment by AngelRodriguez8008** [comment]
https://github.com/microsoft/EasyRepro/search?q=SelectTab

xrmApp.Entity.SelectTab("Details");
xrmApp.Entity.SelectTab("Related","Contacts");

**Comment by VikariiCGI** [comment]
@AngelRodriguez8008,
Thanks !
