### ISSUE TITLE
Running automatically from VSTS online

### ISSUE THREAD

**Issue by rbasten** [Microsoft/EasyRepro#116]
Hi,

Can anyone help me setting Easy Repro up for running in VSTS online, scheduled or within builds?
or guide me in the right way..

Kind regards,

Rick

**Comment by TYLEROL** [comment]
Hi @rbasten - Are you looking for something like the following: [Run Your Independent Automated Tests Using vNext Build In Visual Studio Online
](https://blogs.msdn.microsoft.com/testingspot/2017/07/26/run-your-independent-automated-tests-using-vnext-build-in-visual-studio-online/)

I can discuss this with the team in further detail to see if we can consider setting up a Wiki article to outline this scenario. If you find that the article above will suit your needs, please let me know!

Best Regards,
Tyler

**Comment by yoadster** [comment]
Are you still having difficulties here? I've set up a full automated Azure DevOps with easy repro, Specflow and MsTest. The tests can be easily executed on demand or scheduled.
