### ISSUE TITLE
OpenRecord method not working - Getting OpenQA.Selenium.ElementNotInteractableException: element not interactable: [object HTMLDivElement] has no size and location

### ISSUE THREAD

**Issue by amars4u** [Microsoft/EasyRepro#1190]
## Bug Report
Below method is not working when trying to open record from grid.
xrmApp.Grid.OpenRecord(0);
OpenQA.Selenium.ElementNotInteractableException: element not interactable: [object HTMLDivElement] has no size and location

 CRM Online version:
2021 release wave 1 enabled
Server version: 9.2.21081.00147
Client version: 1.4.3101-2108.1
 
**UCI or Classic Web**
  - [ ] UCI (XrmApp)

**Online or On Premise**
  - [ ] Online

**Browser**
  - [ ] Chrome

**Describe the bug**  
Using below code from latest EasyRepro framework to open record first record from a grid view but its not working and given error provided below
xrmApp.Grid.OpenRecord(0);

Code:
        internal BrowserCommandResult<bool> OpenRecord(int index, int thinkTime = Constants.DefaultThinkTime, bool checkRecord = false)
        {
            ThinkTime(thinkTime);
            return Execute(GetOptions("Open Grid Record"), driver =>
            {
                var xpathToGrid = By.XPath(AppElements.Xpath[AppReference.Grid.Container]);
                IWebElement control = driver.WaitUntilAvailable(xpathToGrid);

                Func<Actions, Actions> action;
                if (checkRecord)
                    action = e => e.Click();
                else
                    action = e => e.DoubleClick();

                var xpathToCell = By.XPath($".//div[@data-id='cell-{index}-1']");
                control.WaitUntilClickable(xpathToCell,
                    cell =>
                    {
                        var emptyDiv = cell.FindElement(By.TagName("div"));
                        driver.Perform(action, cell, cell.LeftTo(emptyDiv));
                    },
                    $"An error occur trying to open the record at position {index}"
                    );

                driver.WaitForTransaction();
                return true;
            });
        }

Error:
OpenQA.Selenium.ElementNotInteractableException: element not interactable: [object HTMLDivElement] has no size and location
 
**Expected behavior**  
First record should open

**Additional context**  
This was working fine since last week and has started failing since 9/12/2021

**Comment by AmarSinghMSFT** [comment]
@aliyoussefi Thank you. I test the fix and it works perfectly fine.

**Comment by amars4u** [comment]
Working fine now.
