### ISSUE TITLE
Testscript fails while running in Azure pipeline but passes in local

### ISSUE THREAD

**Issue by AddalaDeviPriya** [Microsoft/EasyRepro#1194]
My testcase fails in azure pipeline with the below error while clicking the button in the ribbon. It works well in local
Am I missing anything here?

![image](https://user-images.githubusercontent.com/40159922/134637774-7d113c50-2188-4ddd-8c12-ddb9ac935676.png)

Element <button id="OverflowButton_button2$button" aria-label="More commands for Prospect" aria-describedby="openflyout_description_OverflowButton_button2" aria-expanded="false" aria-haspopup="true" role="menuitem" tabindex="-1" data-id="OverflowButton" data-lp-id="Form:lead-OverflowButton" type="button" class="pa-av pa-fp pa-fj pa-fv pa-dh pa-au pa-o pa-fw flexbox">...</button> is not clickable at point (851, 68). Other element would receive the click: <span style="flex: 0 0 30px; color: white; font-style: normal; font-size: 20px;">...</span>

**Comment by Shakevg** [comment]
@AddalaDeviPriya According to my experience it can be different reasons (another browser version, other user settings, more quick test behavior, etc..).
Try to capture a screenshot and look witch control block click.

**Comment by AddalaDeviPriya** [comment]
Working after adding Screen resolution utility to pipeline
