### ISSUE TITLE
Microsoft.Dynamics365.UIAutomation.Api.UCI project is not found 

### ISSUE THREAD

**Issue by seanmcne** [Microsoft/EasyRepro#121]
![image](https://user-images.githubusercontent.com/2292260/40132569-c15d677a-5902-11e8-8f63-bae2a99fac4d.png)

**Comment by TYLEROL** [comment]
@seanmcne - Thanks for raising this. It looks like the 8.2 and 9.0 branches contain a reference to the Api.UCI project which is not applicable for those branches.

We'll get this updated and push out an update to correct the v8.2/v9.0 branches.

Regards,
Tyler

**Comment by TYLEROL** [comment]
@seanmcne - The v9 branch has been updated to correct this invalid project reference. Thanks again for raising this issue to us!

Regards,
Tyler

**Comment by ryan-4** [comment]
This bug appears to be in latest NuGet package. It contains the UCI assembly but is missing the Api assembly, so when a user updates from the previous version, they can't compile.

**Comment by TYLEROL** [comment]
@ryan-4 - Thanks for catching this. We just published an updated package Version 9.0.2.3, can you give that a try and confirm it resolves your missing assembly issue?

We also caught a problem in which dependencies were not being pulled on install as well, which should be resolved with this latest update.

We'll be publishing fixes later today for the 8.2 and 9.0 packages regarding the dependencies issue.

Thanks,
Tyler

**Comment by ryan-4** [comment]
Thanks for the quick response! I've tested 9.0.2.3 and it's working well.
