### ISSUE TITLE
[BUG] Grid.SwitchView() no longer working in Wave 2

### ISSUE THREAD

**Issue by aalad** [Microsoft/EasyRepro#1218]
## Bug Report
After Wave 2 2021, the function XrmApp.Grid.SwitchView("My View") runs in time out

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
After Wave 2 2021, the function XrmApp.Grid.SwitchView("My View") is no longer working. It's looking for the view selector until it times out. This is with most recent EasyRepro version from September 2021

**Code to reproduce**  

```csharp
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
xrmApp.Navigation.OpenApp(UCIAppName.Sales);
xrmApp.Navigation.OpenSubArea("My CRM", "Accounts");
xrmApp.Grid.SwitchView("Active Accounts");  // tries to find selector until time out
```
 -->
 
**Expected behavior**  
The given view is selected in the view selector.

**Comment by Shakevg** [comment]
@aalad Wave 2 will work only with a special branch, this functionality is already fixed on it.
Did you use develop-2021ReleaseWave2](https://github.com/microsoft/EasyRepro/tree/develop-2021ReleaseWave2) brunch for Wave 2? 
If yes, please post a screenshot with your item in view.

**Comment by aalad** [comment]
I see, thanks for the info. I will check out this branch then, as I was still on the releases/v9.1 version
So this bug can be closed, thank you.
