### ISSUE TITLE
Allow adding of arbitrary browseroption arguments/options

### ISSUE THREAD

**Issue by seanmcne** [Microsoft/EasyRepro#122]
There is a need, when attempting headless testing, to add arbitrary debug options such as: <br><br>

options.AddArgument("no-sandbox");<br>
options.AddArgument("window-size=1920x1080")<br><br>

And these would be somewhat different for different browsers and browser modes (chrome vs ie, headless vs full browser). <br><br>

Screenshot for reference: <br>
![image](https://user-images.githubusercontent.com/2292260/40134251-79590c54-5907-11e8-8410-9776a9844922.png)

**Comment by NicolasPrats** [comment]
Hello @seanmcne,

You can do this by extending the class BrowserOptions and overriding the method ToChrome().

![image](https://user-images.githubusercontent.com/33152924/47446866-76b1fe00-d7bc-11e8-8c3f-34ea94cf8112.png)
