### ISSUE TITLE
Wave 2 NuGet Package Release Date

### ISSUE THREAD

**Issue by AmarSinghMSFT** [Microsoft/EasyRepro#1230]
## Question

**What is the planned release date of EasyRepro NuGet Package (Dynamics365.UIAutomation.Api) for Wave 2 code base? Is it possible to release an early beta version for Wave 2 code base?

All test and production environment in my project is upgraded to Wave 2 last weekend and we are using NuGet Package. So it will be very difficult to wait until Dec, 31st. Please advice what can be done here.**

**Comment by JakeObrienMercuryXrm** [comment]
Hey, I had the same issue, however there are pre-release versions out that you can update your project with. When you click to manage nuget packages make sure you have ticked 'Include prerelease'. As you can see in the screenshot, the version I have it a Wave 2 preview release. It has fixed a lot of things, although I still have issues opening Subgrid rows and a few other issues.

![image](https://user-images.githubusercontent.com/59575810/140087642-5e7165cd-c14e-4cf2-bf4c-b909101d8029.png)
 
Hope this helps :)

**Comment by AmarSinghMSFT** [comment]
> Hey, I had the same issue, however there are pre-release versions out that you can update your project with. When you click to manage nuget packages make sure you have ticked 'Include prerelease'. As you can see in the screenshot, the version I have it a Wave 2 preview release. It has fixed a lot of things, although I still have issues opening Subgrid rows and a few other issues.
> 
> ![image](https://user-images.githubusercontent.com/59575810/140087642-5e7165cd-c14e-4cf2-bf4c-b909101d8029.png)
> 
> Hope this helps :)

Thank you @JakeObrienMercuryXrm

**Comment by JakeObrienMercuryXrm** [comment]
@AmarSinghMSFT You're welcome :)
