### ISSUE TITLE
[HOW-TO] Add timeline entries without specifying all string values where not needed

### ISSUE THREAD

**Issue by JakeObrienMercuryXrm** [Microsoft/EasyRepro#1238]
## Question

When creating timeline entries, Phone Call for this example, you have to specify (string subject, string phoneNumber, string description, string duration) however, the software I am automating does not need the phoneNumber or the duration and these fields are not on the quick create form when opened. Is there a way to specify this as null? I have tried using null as shown below but it still falls over.  

xrmApp.Timeline.AddPhoneCall("New job available", null, "A new job that may be of interest to the contact", null);
xrmApp.Timeline.AddPhoneCall("New job available", "", "A new job that may be of interest to the contact", "");

**Comment by Shakevg** [comment]
@JakeObrienMercuryXrm It is not possible using the current implementation.
You can look at the AddPhoneCall implementation and create your own method.

**Comment by JakeObrienMercuryXrm** [comment]
Hi @Shakevg thanks for the response. Yeah that was my plan B :)
