### ISSUE TITLE
Issue with SelectTab, ExpandTab and CollapseTab

### ISSUE THREAD

**Issue by SolzIT** [Microsoft/EasyRepro#124]
Hi, 
I have a latest v9 CRM online edition and when I use the commands say - 
xrmBrowser.Entity.SelectTab("Product_Line_Items"); or
xrmBrowser.Entity.CollapseTab("Summary");

It gives me an exception indicating the tab was not found. 

Not sure I was doing something wrong or if it is a bug. Anyways to fix the same I made the below changes and it is working fine now.

**FileName: Microsoft.Dynamics365.UIAutomation.Api\DTOs\ElementReference.cs** 
            
           //Entity
            //{ "Entity_TabId"       , "[NAME]_TAB_header_image_div"},  //COMMENTED THIS LINE
              { "Entity_TabId"       , "[NAME]_header_image_div"},   //ADDED THIS LINE

**FileName: Microsoft.Dynamics365.UIAutomation.Api\Pages\Entity.cs**
_Made below changes to ExpandTab, SelectTab and CollapseTab functions_

               //if(!driver.HasElement(By.Id(Elements.ElementId[Reference.Entity.Tab].Replace("[NAME]", name.ToUpper())))) //COMMENTED THIS LINE
                if (!driver.HasElement(By.Id(Elements.ElementId[Reference.Entity.Tab].Replace("[NAME]", name))))  //ADDED THIS LINE

                //var section = driver.FindElement(By.Id(Elements.ElementId[Reference.Entity.Tab].Replace("[NAME]", name.ToUpper()))); //COMMENTED THIS LINE
                var section = driver.FindElement(By.Id(Elements.ElementId[Reference.Entity.Tab].Replace("[NAME]", name)));  //ADDED THIS LINE

Regards,
Nikhil

**Comment by TYLEROL** [comment]
Thanks @SolzIT (Nikhil) for raising this issue. We'll take a look at the Element References to see what/why these may have changed. A couple of questions for you:

1. What is the version of your Dynamics 365 instance (9.0.X.XXX)?

2. Was this functionality working previously and broke after an update? Or was this your first attempt to utilize the Tab methods?

Regards,
Tyler

**Comment by SolzIT** [comment]
Hi Tyler, 
The Dynamics CRM instance version is 9.0.2.189 and this was my first attempt to utilize the Tab methods.

Regards,
Nikhil

**Comment by TYLEROL** [comment]
@SolzIT - Updating to confirm that I can replicate these issues. We're going to look at refactoring the underlying code to be more resilient depending on the Name value passed into the method.

The method was built to handle display name input, however it made an assumption that the _Schema Name_ would be [NAME]_TAB. Your workaround should unblock you for now, however be aware that case syntax should match the schema name exactly as shown in the form editor.

I'll update once a fix is made available for this scenario. Thank you again for raising this issue to us!

Regards,
Tyler

**Comment by TYLEROL** [comment]
@SolzIT - I pushed a change this afternoon to utilize XPath for the SelectTab, ExpandTab, and CollapseTab methods. This change should allow usage of the _Display Name_ as seen on the form instead of the Schema Name. 

If you have any problems with the new implementation behind this, please re-open this issue.

Thanks!
Tyler
