### ISSUE TITLE
[HOW-TO] Checking for "Saving..." overlay instead of using Thinktime or Thread.sleep

### ISSUE THREAD

**Issue by MattAtTelstra** [Microsoft/EasyRepro#1245]
## Question ##

When you click save after creating a new workflow , you get a "Saving..." overlay which can take for our tests anywhere up to 10 seconds to save the workflow, we are trying not to use any sleep or waits in case the saving takes longer.

Does anyone have a different method of checking when that overlay is no longer visible/stopping any interaction with the other buttons?

**Comment by miiwo** [comment]
I would recommend to use a WebClient method for this: `client.Browser.Driver.WaitForTransaction()` whenever you see a "Saving..." overlay so that it waits the appropriate amount before continuing on with your program. Cheers!

**Comment by MattAtTelstra** [comment]
Actually found a great way to fix this this without sleeping: 

 public void WaitForSavingOverlay()
        {
            while (_driver.FindElement(By.Id("mainContent")).GetAttribute("aria-live") == "polite")
            {
                Thread.Sleep(100);

            }
        }
