### ISSUE TITLE
[BUG] <Save not working in EasyRepro>

### ISSUE THREAD

**Issue by smallteam1** [Microsoft/EasyRepro#1253]
Save and some events are stopped working. Currently we are using EasyRepro "9.2.21084.148" which is available in Nuget.
Could we please know by when the EasyRepro supported version for Dynamics 365 will be available in Nuget package

System.Exception: Save Buttton is not available

inspect element showing as Save (Ctrl+S)
![Capture](https://user-images.githubusercontent.com/18255804/145207482-51ec3291-7600-40d4-96b1-f207dffface0.JPG)

**Comment by ychandra888** [comment]
xrmApp.CommandBar.ClickCommand("Save (CTRL+S)");

above line will work, for me It's working fine

**Comment by smallteam1** [comment]
Thanks for your reply ychandra888, there are 37+ tests which I need to change and not only Save, there are some other events where I am getting errors. 

System.Exception: Unable to click the View Picker

is easyrepro team planning  to fix these issues?

**Comment by ychandra888** [comment]
Hi,

I am not sure product team will fix or not but after wave 2 enable, some of
commands are not working in this EasyRepro.

Thanks & Regards,
Chandra Mohan

**Comment by smallteam1** [comment]
Thanks Chandra...

https://www.nuget.org/packages/Dynamics365.UIAutomation.Api/9.2.21101.119-RW2-Preview

installed through PM console 
Install-Package Dynamics365.UIAutomation.Api -Version 9.2.21101.119-RW2-Preview

I have tested few tests and they are working fine...

Thanks 
Narasimha
