### ISSUE TITLE
xrmApp.Entity.Save() is not working -System.InvalidOperationException: 'Save Button is not available'

### ISSUE THREAD

**Issue by ritesh035** [Microsoft/EasyRepro#1266]
I have created a blank unit test project and I am facing an issue with record save code.

I have installed the below packages  with the latest version  and I have built code on dot net version 4.6 
1)Dynamics365.UIAutomation.API 
2)Selenium.WebDriver.ChromeDriver

Below is code snippet .
using (var xrmapp = new XrmApp(client))
            {
                xrmapp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey);
                xrmapp.Navigation.OpenApp(UCIAppName.Sales);
                xrmapp.Navigation.OpenSubArea("Sales", "Contacts");
                xrmapp.ThinkTime(4000);
                xrmapp.CommandBar.ClickCommand("New");

                xrmapp.Entity.SetValue("firstname", "test");
                xrmapp.Entity.SetValue("lastname", "contact");
                
                
                xrmapp.Entity.Save();

            }

Please correct me in case I have missed anything.

**Comment by Sekhon92** [comment]
Hi, Did you find a solution to it?
I am struggling with the same problem.
