### ISSUE TITLE
SelectLookup gives error when the same attribute is present twice on the form.

### ISSUE THREAD

**Issue by SolzIT** [Microsoft/EasyRepro#130]
Hi, 
We have a situation where the same lookup field is present on the form in two different tabs/ sections. At any given point in time one of the attribute is displayed based on certain condition.

When we try to use XrmBrowser.Entity.SelectLookup it gives an error. Is the way we can workaround this or may be using XPath?

Regards,
Nikhil

**Comment by SolzIT** [comment]
Actually I got it working. Just had to suffix the field name with index

Thanks.

**Comment by TYLEROL** [comment]
Thanks @SolzIT for raising awareness for this use case. I've added an item to the backlog for review to consider additional means of handling this scenario or at a minimum documenting the scenario in code examples.

Regards,
Tyler
