### ISSUE TITLE
[BUG] Release Wave 2 2022: Sort not working as expected.

### ISSUE THREAD

**Issue by aliyoussefi** [Microsoft/EasyRepro#1324]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome 105
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
```csharp
xrmApp.Grid.Sort("Account Name", "Sort Z to A"); 
```
not working as expected.
Error:
no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@ref,'gridHeader')]//label[@title='Account Name']"}
  (Session info: chrome=105.0.5195.127)'

**Special formatting / display**  
No

**Code to reproduce**  

 
**Expected behavior**  
Select correct column and sort ascending and descending

**Screenshots**  

**Additional context**

**Comment by aliyoussefi** [comment]
Updated XPath and sample test. working as expected pending commit and merge

**Comment by aliyoussefi** [comment]
Completed with merge of PR #1325

**Comment by kthirapatpibul** [comment]
I'm getting the same issue again with Chrome 116 running the sample UCITestGetActiveGridItems()

OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@role,'columnheader')]//label[@title='Account Name']"}
