### ISSUE TITLE
[HOW-TO] <Click automatically on the USE A VERIFICATION CODE>

### ISSUE THREAD

**Issue by RicardoJacobsen** [Microsoft/EasyRepro#1348]
## Question

**Why in the login process the automation does not work for USE A VERIFICATION CODE? (It should click automatically in use a verification code)**

The automation is working fine till reaches this part
![image](https://user-images.githubusercontent.com/79985787/206075260-c62198b0-3ae9-44a2-bff6-cf199ce2d7d9.png)

I have to click manually on the part where it says use a verification code. After I click there the automation continues fine.

How to click on it automatically, so the test flows without human interaction?

Another thing that I would like to know is, how I prevent the web browser to be closed use the same the other test cases?

**Comment by RicardoJacobsen** [comment]
@aliyoussefi  any suggestion?

**Comment by Shakevg** [comment]
[RicardoJacobsen](https://github.com/RicardoJacobsen) EasyRepro is not supported this for now.
You should implement your own login method.
Did you configure the account by [instruction](https://github.com/microsoft/EasyRepro#mfa-support)?
Also, you should set added by instruction MFA option as default.

**Comment by RicardoJacobsen** [comment]
> [RicardoJacobsen](https://github.com/RicardoJacobsen) EasyRepro is not supported this for now. You should implement your own login method. Did you configure the account by [instruction](https://github.com/microsoft/EasyRepro#mfa-support)? Also, you should set added by instruction MFA option as default.

Yes I did configured as in [instruction](https://github.com/microsoft/EasyRepro#mfa-support). I did everything as in instructions to MFA Support. It's working beautifully till this part. Any workaround for this? Maybe alter the login method and add a selenium instruction to find the text " Use a verification code" and click on it?

**Comment by RicardoJacobsen** [comment]
I found a simple workaround for that. 
I simply  created the method below:

 ```
  private static bool ClickUseVerificatioCode(IWebDriver driver)
        {
            var x = driver.FindElements(By.XPath("//*[contains(text(), 'Use a verification code')]"));
            x[1].Click();           
            return true;
        }
```

AND inserted after the method to input the password (WebClient.cs file).

Here is where I called the method;

```
   EnterPassword(driver, password);
                ThinkTime(2000);  
            }
            
            ClickUseVerificatioCode(driver); // This is where I placed the code

            int attempts = 0;
            bool entered;
```
