### ISSUE TITLE
[HOW-TO] <Open Chrome Profile>

### ISSUE THREAD

**Issue by RicardoJacobsen** [Microsoft/EasyRepro#1349]
## Question

**How to set up easyrepro to open an specific chrome profile?**

I came across this DownloadsPath in BrowserOptions, that is actualy options.AddUserProfilePreference("download.default_directory", DownloadsPath);

I set the DownloadsPath = "My profile".  However, this is still opening a standard Profile 1 in chrome.

What should I do in this case?

**Comment by Shakevg** [comment]
[RicardoJacobsen](https://github.com/RicardoJacobsen)
It is not supported for now https://github.com/microsoft/EasyRepro/blob/46dbe57e5e07254b960baa05bcf5ac45d76cbd10/Microsoft.Dynamics365.UIAutomation.Browser/BrowserOptions.cs
But you can add this feature: it is should be something like [here](https://stackoverflow.com/a/71339611/8951897)

**Comment by RicardoJacobsen** [comment]
I tried to add this line to BrowserOptions.cs:
options.AddArgument("user-data-dir=C:/Users/RicardoJacobsen/AppData/Local/Google/Chrome/User Data/RICARDO JACOBSEN");

However, it persists to open the profile 1.

Any suggestions here?

@Shakevg

**Comment by RicardoJacobsen** [comment]
I found a solution for it.

In Microsoft.Dynamics365.UIAutomation.Browser >> BrowserOptions.cs I added:
this.UseProfile = true;

like image below
![image](https://user-images.githubusercontent.com/79985787/212637688-9fd8dd71-dafc-4016-b28a-fb310def045d.png)

Scrolling a little bit in the same BrowserOptions.cs

I inserted the the following code:
 public bool UseProfile { get; set; }

Like image below
![image](https://user-images.githubusercontent.com/79985787/212639431-29d5d564-cc5a-4bd2-a6b9-f5c6546be9e6.png)

To finalize, scrolling a little bit more, I inserted the following code:

            if (this.UseProfile)
            {
                options.BinaryLocation = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
                options.AddArgument("--user-data-dir=C:\\Users\\RicardoJacobsen\\AppData\\Local\\Google\\Chrome\\User Data");
                options.AddArgument("--profile-directory=Profile 6");
                options.AddArgument("--remote-debugging-port=9222");
            }

As image below:
![image](https://user-images.githubusercontent.com/79985787/212639875-89479341-0f86-4de9-a2bb-989d1085caa0.png)

To get the correct profile that I wanted I clicked with the right button on the Chrome profile and went to properties.

As img below:
![image](https://user-images.githubusercontent.com/79985787/212640256-889da7e5-7a67-4790-8f98-a5609d76082d.png)


It's good to mention that after configuring all this, insanely I had to restart the computer to this changes work. hahahaha

**Comment by Shakevg** [comment]
[RicardoJacobsen](https://github.com/RicardoJacobsen) It will be a good idea to push your solution to git with the profile name as a parameter.

**Comment by RicardoJacobsen** [comment]
Hello Shakevg. Thanks for reaching out.

No worries, will do that.

Any other suggestions please let me know.

Kind regards
Ricardo Jacobsen

Sent on the go with Vodafone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AngelRodriguez8008** [comment]
It doesn't work for me.
