### ISSUE TITLE
avoid stay signed in message?

### ISSUE THREAD

**Issue by AdotMdot100** [Microsoft/EasyRepro#1357]
Is there a way to avoid the stay signed in message? I'm using Easyrepro with MFA and have my MFAsecret key defined in the app.config and during login, it will automatically enter my username, password, and 6 digit code but within about 30 seconds I receive the following that can only be bypassed by me interacting and clicking the element on screen:

![image](https://user-images.githubusercontent.com/122094019/211003260-253a79f5-50ec-45ac-86f5-b14a4932b9d9.png)
 
public void UCITestCreateAccount()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey);

                xrmApp.Navigation.OpenApp(UCIAppName.MYCUSTOMAPP);

                xrmApp.Navigation.OpenSubArea("Workspace", "Organisations");

                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.Entity.SetValue("name", "AM automated ui test" + " " + TestSettings.GetRandomString(5,15));

                xrmApp.ThinkTime(2000);

                xrmApp.Entity.SetValue("websiteurl", "UITest");

                xrmApp.Entity.Save();
                
            }
            
        }

**Comment by Shakevg** [comment]
[AdotMdot100](https://github.com/AdotMdot100) Look on https://github.com/microsoft/EasyRepro/issues/1338

**Comment by AdotMdot100** [comment]
Perfect thank you! @Shakevg changing the cookie control option to 0 in the browseroptions class file has done the trick for me!
