### ISSUE TITLE
[HOW-TO] Visit an specific URL

### ISSUE THREAD

**Issue by pochopd** [Microsoft/EasyRepro#1368]
Hi, is there any way to visit a specific link after login like
"https://cne-tst-300930.crm.dynamics.com/main.aspx?appid=b140c46e-1492-ec11-b400-0022480b4078"
I'm trying to use less steps to fill a form.
Thank you.

**Comment by Shakevg** [comment]
[pochopd](https://github.com/pochopd) 
Use next code
``` csharp
client.Browser.Driver.Navigate().GoToUrl("https://cne-tst-300930.crm.dynamics.com/main.aspx?appid=b140c46e-1492-ec11-b400-0022480b4078");
```
