### ISSUE TITLE
[BUG] UCI test is unable to open the Accounts SubArea

### ISSUE THREAD

**Issue by 8its** [Microsoft/EasyRepro#1371]
**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
I´ve run the UCITestOpenActiveAccount test successfully in my local VS. I´ve associated this test to a Test Case in a DevOps project. Then I have a pipeline that runs the Test Case using Visual Studio Test. I get the following error:
```
BrowserAutomation Information: 9000 : BrowserInitialized invoked.
BrowserAutomation Information: 9001 : BrowserInitialized completed.
BrowserAutomation Information: 10001 : Command Start: Login - Attempt 1/5
BrowserAutomation Information: 10002 : Command Success: Login - 1 attempts - total execution time 14357.6912ms - Return Result: Success
BrowserAutomation Information: 10001 : Command Start: Initialize Unified Interface Modes - Attempt 1/5
BrowserAutomation Information: 10002 : Command Success: Initialize Unified Interface Modes - 1 attempts - total execution time 15074.0335ms - Return Result: True
BrowserAutomation Information: 10001 : Command Start: Open App Sales Hub - Attempt 1/5
BrowserAutomation Information: 10001 : Command Start: Initialize Unified Interface Modes - Attempt 1/5
BrowserAutomation Information: 10002 : Command Success: Initialize Unified Interface Modes - 1 attempts - total execution time 25190.825ms - Return Result: True
BrowserAutomation Information: 10002 : Command Success: Open App Sales Hub - 1 attempts - total execution time 25750.4388ms - Return Result: True
BrowserAutomation Information: 10001 : Command Start: Open Sub Area - Attempt 1/5
BrowserAutomation Information: 10004 : Command Retry: Open Sub Area - System.InvalidOperationException: Unable to click element. - Retry 2/5 initiated
BrowserAutomation Information: 10004 : Command Retry: Open Sub Area - System.InvalidOperationException: Unable to click element. - Retry 3/5 initiated
BrowserAutomation Information: 10003 : Command Failure: Open Sub Area - 3 attempts - total execution time 100722.0422ms - Return Result: System.InvalidOperationException: Unable to click element.
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass52_0.<WaitUntilClickable>b__0() in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 520
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 582
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 528
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, String exceptionMessage) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 520
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(ISearchContext driver, By by, Nullable`1 timeout, String errorMessage) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 43
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.GetSubAreaMenuItems(IWebDriver driver) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 722
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.TryOpenSubArea(IWebDriver driver, String subarea) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 561
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass34_0.<OpenSubArea>b__0(IWebDriver driver) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 525
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 103
BrowserAutomation Information: 9000 : BrowserDisposing invoked.
BrowserAutomation Information: 9001 : BrowserDisposing completed.
``` 
I´m trying to run the following code:
```
public void UCITestOpenActiveAccount()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey);

                xrmApp.Navigation.OpenApp(UCIAppName.Sales);

                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

                xrmApp.Grid.SwitchView("All Accounts");

                xrmApp.Grid.Search("A. Datum");

                xrmApp.Grid.OpenRecord(0);

                xrmApp.ThinkTime(3000);

            }
        }
```

All packages have been updated to the latest stable version.
 
**Expected behavior**  
Finish the test successfully

**Comment by Shakevg** [comment]
[8its](https://github.com/8its) Could you make a screenshot on an error and check it https://github.com/microsoft/EasyRepro/blob/3dc3570c5ad72e812381c4b874110ede5d93a507/Microsoft.Dynamics365.UIAutomation.Sample/AzureDevOps/UCI/RegressionTests.cs#L148

**Comment by 8its** [comment]
![image](https://user-images.githubusercontent.com/18676174/234784551-b54e2fcd-c305-410c-a495-70694303ed77.png)

![image](https://user-images.githubusercontent.com/18676174/234784863-ffad0264-8416-4654-8780-08f54f5772f0.png)

not too sure if this is what you asked for...

**Comment by 8its** [comment]
![image](https://user-images.githubusercontent.com/18676174/234820016-909abd4d-5851-42ba-b272-a799e00bdcb4.png)

![image](https://user-images.githubusercontent.com/18676174/234820441-47151d2f-dade-4548-ab90-48a51222f87c.png)

![image](https://user-images.githubusercontent.com/18676174/234820734-2dbc1a17-abef-48b7-9053-5e72b262fb24.png)

onlineusername, password and crm url are set in EasyRepro.runsettings file.
what I am missing?

thank you

**Comment by 8its** [comment]
... and after modifying the code to make it runnable, same error as in the beginning

![image](https://user-images.githubusercontent.com/18676174/234883656-3ddfc7f7-d4af-4c61-93ce-d2a678b30e41.png)

here the results of a local test execution

![image](https://user-images.githubusercontent.com/18676174/234883990-d264d6f0-7c9c-49c0-b153-3d0d9386989a.png)

any hint will be welcome
thank you.

**Comment by Shakevg** [comment]
Please take a screenshot in Azure DevOps of how you pass parameters to run test step

**Comment by 8its** [comment]
This is how we call the test plan
![image](https://user-images.githubusercontent.com/18676174/234918363-556baedf-c7df-4fe7-9032-123ba7125ca7.png)

this is the task in YAML format
`steps:
- task: VSTest@2
  displayName: 'VsTest - testAssemblies TEST'
  inputs:
    testSelector: testPlan
    testPlan: 2799
    testSuite: '2800,2801'
    testConfiguration: 7
    searchFolder: '$(System.DefaultWorkingDirectory)\Microsoft.Dynamics365.UIAutomation.Sample\bin\Debug'
    resultsFolder: '$(Common.TestResultsDirectory)'
    uiTests: true
    vsTestVersion: toolsInstaller
    runInParallel: false
    codeCoverageEnabled: true
    diagnosticsEnabled: true
  continueOnError: true`

The Test plan has been defined as follows
![image](https://user-images.githubusercontent.com/18676174/234919271-759ba600-d812-4c24-8915-b06312dfd808.png)

**Comment by Shakevg** [comment]
You should specify Settings file or path to it in task: EasyRepro.runsettings
![image](https://user-images.githubusercontent.com/42133199/234961203-794edb7c-634b-48ae-b6a2-8c67ded663a6.png)

**Comment by 8its** [comment]
I´ve updated the RegressionTests.cs file, to open the Sales Hub app and commented everything after that.
![image](https://user-images.githubusercontent.com/18676174/235092748-4e020bd7-92db-49ec-85c6-2ec9b626323c.png)

EasyRepro.runsettings has been configured in the Pipeline
![image](https://user-images.githubusercontent.com/18676174/235093198-41fedce0-7d52-45aa-bdd3-3156f5427c93.png)

Error after running the pipeline
![image](https://user-images.githubusercontent.com/18676174/235094033-99cad10e-fb7d-41cf-8af9-5a411b4498b4.png)

Standard_Console_Output.log
`BrowserAutomation Information: 9000 : BrowserInitialized invoked.
BrowserAutomation Information: 9001 : BrowserInitialized completed.
BrowserAutomation Information: 10001 : Command Start: Login - Attempt 1/5
BrowserAutomation Information: 10002 : Command Success: Login - 1 attempts - total execution time 9770.4938ms - Return Result: Success
BrowserAutomation Information: 10001 : Command Start: Initialize Unified Interface Modes - Attempt 1/5
BrowserAutomation Information: 10002 : Command Success: Initialize Unified Interface Modes - 1 attempts - total execution time 16342.4372ms - Return Result: True
BrowserAutomation Information: 10001 : Command Start: Open personalSettings SettingsMenu.About - Attempt 1/5
BrowserAutomation Information: 10002 : Command Success: Open personalSettings SettingsMenu.About - 1 attempts - total execution time 699.7381ms - Return Result: True
BrowserAutomation Information: 10001 : Command Start: Dialog Click OK - Attempt 1/5
BrowserAutomation Information: 10002 : Command Success: Dialog Click OK - 1 attempts - total execution time 30161.6847ms - Return Result: True
BrowserAutomation Information: 10001 : Command Start: Open App Sales Hub - Attempt 1/5
BrowserAutomation Information: 10004 : Command Retry: Open App Sales Hub - OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <iframe id="AppLandingPage" title="AppLandingPage" src="/%7b638181253350000220%7d/webresources/msdyn_appmanagementcontrol" class="pa-bk pa-cu pa-cm " cd_frame_id_="2c6d3d49d2b56fb748b123519a3223fe"></iframe> is not clickable at point (364, 591). Other element would receive the click: <div id="modalDialogRoot_1_1" tabindex="-1" class="pa-f pa-bk pa-a pa-p pa-au flexbox">...</div>
  (Session info: chrome=112.0.5615.138) - Retry 2/5 initiated
BrowserAutomation Information: 10004 : Command Retry: Open App Sales Hub - OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <iframe id="AppLandingPage" title="AppLandingPage" src="/%7b638181253350000220%7d/webresources/msdyn_appmanagementcontrol" class="pa-bk pa-cu pa-cm " cd_frame_id_="099429835a801af46ddbc37d05218efd"></iframe> is not clickable at point (364, 591). Other element would receive the click: <div id="modalDialogRoot_1_1" tabindex="-1" class="pa-f pa-bk pa-a pa-p pa-au flexbox">...</div>
  (Session info: chrome=112.0.5615.138) - Retry 3/5 initiated
BrowserAutomation Information: 10003 : Command Failure: Open App Sales Hub - 3 attempts - total execution time 13885.1272ms - Return Result: OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <iframe id="AppLandingPage" title="AppLandingPage" src="/%7b638181253350000220%7d/webresources/msdyn_appmanagementcontrol" class="pa-bk pa-cu pa-cm " cd_frame_id_="94c362b2284f45407006e69b57d8d26e"></iframe> is not clickable at point (364, 591). Other element would receive the click: <div id="modalDialogRoot_1_1" tabindex="-1" class="pa-f pa-bk pa-a pa-p pa-au flexbox">...</div>
  (Session info: chrome=112.0.5615.138)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c.<ClickWhenAvailable>b__2_0(IWebElement e) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 43
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 578
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 528
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, String exceptionMessage) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 520
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(ISearchContext driver, By by, Nullable`1 timeout, String errorMessage) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 43
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass32_0.<TryToClickInAppTile>b__1(IWebElement appContainer) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 475
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 578
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilVisible(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 503
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.TryToClickInAppTile(String appName, IWebDriver driver) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 474
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass29_0.<OpenApp>b__0(IWebDriver driver) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 398
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 103
Creating Page Source file with name EXCEPTION_Source_20230428080731.html
BrowserAutomation Information: 9000 : BrowserDisposing invoked.
BrowserAutomation Information: 9001 : BrowserDisposing completed.



Debug Trace:
Creating Page Source file with name EXCEPTION_Source_20230428080731.html

`

**Comment by Shakevg** [comment]
Enable video recording and check what is happening, it looks like some extra dialog is opening.
https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#videorecorder-data-collector

**Comment by 8its** [comment]
Nice feature! Now I can see that the test is not able to simulate a click on Sales, Accounts, so the test is stuck in the command `xrmApp.Navigation.OpenSubArea("Sales",` "Accounts");` The error message is the same "Unable to click element" as I mentioned at the beginning.

One thing that is so confusing is that when I run the test Regression_EntityControls_GetValue_SetValue locally it works but when running in the pipeline it does not. Is there any particular reason for this behavior?

Thank you for your support.

**Comment by Shakevg** [comment]
Post screenshot please

**Comment by 8its** [comment]
Regression_EntityConttrols_GetValue_SetValue(). Some code is commented to avoid issues.
```

public void Regression_EntityControls_GetValue_SetValue()
        {
            var telemetry = new Microsoft.ApplicationInsights.TelemetryClient { InstrumentationKey = _azureKey };
            telemetry.Context.Operation.Id = Guid.NewGuid().ToString();
            telemetry.Context.Operation.ParentId = _sessionId;
            telemetry.Context.GlobalProperties.Add("Test", TestContext.TestName);
            var client = new WebClient(TestSettings.Options);
            var xrmApp = new XrmApp(client);
            try
            {
                telemetry.TrackTrace("Login Started");
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey);
                telemetry.TrackTrace("Login Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());
                //xrmApp.Navigation.OpenApp(UCIAppName.Sales);

                //telemetry.TrackTrace("OpenAbout Started");
                //xrmApp.Navigation.OpenAbout();
                //telemetry.TrackTrace("OpenAbout Completed");
                //TakeScreenshot(client, xrmApp.CommandResults.Last());
                //xrmApp.Dialogs.ClickOk();

                telemetry.TrackTrace("Open Sales Hub Started");
                xrmApp.Navigation.OpenApp(UCIAppName.Sales);
                telemetry.TrackTrace("Open Sales Hub Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());

                telemetry.TrackTrace("OpenSubArea Started");
                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");
                telemetry.TrackTrace("OpenSubArea Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());

                telemetry.TrackTrace("SwitchView Started");
                xrmApp.Grid.SwitchView("All Accounts");
                telemetry.TrackTrace("SwitchView Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());

                //telemetry.TrackTrace("GetGridControl Started");
                //var gridHtml = xrmApp.Grid.GetGridControl();
                //WriteSource("GRID_", gridHtml);
                //telemetry.TrackTrace("GetGridControl Completed");

                telemetry.TrackTrace("Search Started");
                xrmApp.Grid.Search("Economic");
                telemetry.TrackTrace("Search Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());

                telemetry.TrackTrace("OpenRecord Started");
                xrmApp.Grid.OpenRecord(0);
                telemetry.TrackTrace("OpenRecord Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());

                #region Boolean
                telemetry.TrackTrace("GetValue-Text Started");
                xrmApp.Entity.GetValue("telephone1");
                telemetry.TrackTrace("GetValue-Text Completed");

                telemetry.TrackTrace("SetValue-Text Started");
                xrmApp.Entity.SetValue("telephone1","867-5309");
                telemetry.TrackTrace("SetValue-Text Completed");
                #endregion
                TakeScreenshot(client, xrmApp.CommandResults.Last());
                //#region Lookup
                //telemetry.TrackTrace("SetValue-LookupItem Started");
                //xrmApp.Entity.SetValue(new LookupItem { Name = "customerid", Value = "maria campbell", Index = 0 });

                //telemetry.TrackTrace("SetValue-LookupItem Completed");
                //#endregion


                telemetry.TrackEvent(String.Format("{0} is successful.", TestContext.TestName));
            }
            catch (System.Exception ex)
            {
                telemetry.TrackException(ex);
                WriteSource("EXCEPTION_Source_", client.Browser.Driver.PageSource);
                TakeScreenshot(client, xrmApp.CommandResults.Last());
                throw ex;
            }
            finally
            {
                xrmApp.Dispose();
                telemetry.Flush();
            }
        }

```

Execution from Visual Studio locally
![image](https://user-images.githubusercontent.com/18676174/235160970-3533c928-89d5-4625-b5a2-d77741753b6e.png)

Execution from Pipeline
![image](https://user-images.githubusercontent.com/18676174/235161597-07272e51-7109-4d1f-905f-27ca1c7c0b79.png)

**Comment by Shakevg** [comment]
I meant dynamics web app screenshot when error appeared

**Comment by 8its** [comment]
There is no error at all. The following is a screenshot of the ScreenCapture.wmv file created during the test.

![image](https://user-images.githubusercontent.com/18676174/235171829-7a8433cf-5ed6-4875-b991-b54ec3abde75.png)

In the video I can see the same screen from minute1.15 until the end at min 2.49

**Comment by 8its** [comment]
This is the video screen capture. At the end, after closing the blue bubble at top right, the test doesn´t do anything else, and it should open the Accounts list.

https://user-images.githubusercontent.com/18676174/235177187-a0959c11-8112-48dd-b407-959c70b755ef.mp4

I hope this could help

**Comment by Shakevg** [comment]
Could please post screen for full stacktrace
Looks like issue with blue drop that block any click on app, you should close it before.
Do you use the same account for local and Azure test run?
Do you see this drop on local run?

**Comment by 8its** [comment]
> Could please post screen for full stacktrace Looks like issue with blue drop that block any click on app, you should close it before. Do you use the same account for local and Azure test run? Do you see this drop on local run?

Sorry Shakevg, I don´t know where to get the full stacktrace.
I use the same account for local and pipeline runs.
In local run the blue bubble does not appear.

Thank you

**Comment by 8its** [comment]
Hello.

Here is the Error and Stack Trace pointing at line 335:
`Error message
Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.RegressionTests.Regression_EntityControls_GetValue_SetValue threw exception: 
System.InvalidOperationException: Unable to click element.
Stack trace
at Microsoft.Dynamics365.UIAutomation.Sample.UCI.RegressionTests.Regression_EntityControls_GetValue_SetValue() in \Microsoft.Dynamics365.UIAutomation.Sample\AzureDevOps\UCI\RegressionTests.cs:line 335`

Here is the function that I am testing. Line 335 is the `throw ex` in the `catch` at the end
```
        public void Regression_EntityControls_GetValue_SetValue()
        {
            var telemetry = new Microsoft.ApplicationInsights.TelemetryClient { InstrumentationKey = _azureKey };
            telemetry.Context.Operation.Id = Guid.NewGuid().ToString();
            telemetry.Context.Operation.ParentId = _sessionId;
            telemetry.Context.GlobalProperties.Add("Test", TestContext.TestName);
            var client = new WebClient(TestSettings.Options);
            var xrmApp = new XrmApp(client);
            try
            {
                telemetry.TrackTrace("Login Started");
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey);
                telemetry.TrackTrace("Login Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());
                //xrmApp.Navigation.OpenApp(UCIAppName.Sales);

                // ***
                //telemetry.TrackTrace("OpenAbout Started");
                //xrmApp.Navigation.OpenAbout();
                //telemetry.TrackTrace("OpenAbout Completed");
                //TakeScreenshot(client, xrmApp.CommandResults.Last());
                //xrmApp.Dialogs.ClickOk();

                //telemetry.TrackTrace("Open Sales Hub Started");
                //xrmApp.Navigation.OpenApp(UCIAppName.Sales);
                //telemetry.TrackTrace("Open Sales Hub Completed");
                //TakeScreenshot(client, xrmApp.CommandResults.Last());

                telemetry.TrackTrace("OpenSubArea Started");
                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");
                telemetry.TrackTrace("OpenSubArea Completed");
                TakeScreenshot(client, xrmApp.CommandResults.Last());

                //telemetry.TrackTrace("SwitchView Started");
                //xrmApp.Grid.SwitchView("All Accounts");
                //telemetry.TrackTrace("SwitchView Completed");
                //TakeScreenshot(client, xrmApp.CommandResults.Last());

                // ***
                //telemetry.TrackTrace("GetGridControl Started");
                //var gridHtml = xrmApp.Grid.GetGridControl();
                //WriteSource("GRID_", gridHtml);
                //telemetry.TrackTrace("GetGridControl Completed");

                //telemetry.TrackTrace("Search Started");
                //xrmApp.Grid.Search("Economic");
                //telemetry.TrackTrace("Search Completed");
                //TakeScreenshot(client, xrmApp.CommandResults.Last());

                //telemetry.TrackTrace("OpenRecord Started");
                //xrmApp.Grid.OpenRecord(0);
                //telemetry.TrackTrace("OpenRecord Completed");
                //TakeScreenshot(client, xrmApp.CommandResults.Last());

                //#region Boolean
                //telemetry.TrackTrace("GetValue-Text Started");
                //xrmApp.Entity.GetValue("telephone1");
                //telemetry.TrackTrace("GetValue-Text Completed");

                //telemetry.TrackTrace("SetValue-Text Started");
                //xrmApp.Entity.SetValue("telephone1","867-5309");
                //telemetry.TrackTrace("SetValue-Text Completed");
                //#endregion
                //TakeScreenshot(client, xrmApp.CommandResults.Last());

                // ***
                //#region Lookup
                //telemetry.TrackTrace("SetValue-LookupItem Started");
                //xrmApp.Entity.SetValue(new LookupItem { Name = "customerid", Value = "maria campbell", Index = 0 });

                //telemetry.TrackTrace("SetValue-LookupItem Completed");
                //#endregion


                telemetry.TrackEvent(String.Format("{0} is successful.", TestContext.TestName));
            }
            catch (System.Exception ex)
            {
                telemetry.TrackException(ex);
                WriteSource("EXCEPTION_Source_", client.Browser.Driver.PageSource);
                TakeScreenshot(client, xrmApp.CommandResults.Last());
                throw ex; // line 335
            }
            finally
            {
                xrmApp.Dispose();
                telemetry.Flush();
            }
        }
```

**Comment by 8its** [comment]
Oh my gosh! You won't believe it.

I've found [this question](https://github.com/microsoft/EasyRepro/issues/1030), and now my pipeline is working after adding a task to resize the screen.

Thank you for your help, after all I've learned several things.
