### ISSUE TITLE
[HOW-TO] Using .NET Core

### ISSUE THREAD

**Issue by jchalmd** [Microsoft/EasyRepro#1419]
## Question
How in support is the features/dotnet/core branch of Easy Repro? I'd like to use .net core if possible but before using it what's the support status? Is this considered branch stable?

This question has been raised in 2020 (#700 & #1010) though this branch now appears to be more frequently updated than the default develop branch.

**Comment by Shakevg** [comment]
@aliyoussefi Could you please answer and help, because it is critical for the community?
Could you please just create nuget for features/dotnet/core branch?

**Comment by jchalmd** [comment]
@Shakevg I discussed this with ali, and it is not quite ready yet. Currently the direction is to make it framework agnostic so it can work with Selenium & Playwright.
I do use this branch currently but it does requires a good amount of editing in order to make it work well. I will create pull requests with some of these edits to help out.
Going to close this issue as I believe this answers it.
