### ISSUE TITLE
How does EasyRepro supports Dynamics 365 Online with ADFS authentication

### ISSUE THREAD

**Issue by harryzang** [Microsoft/EasyRepro#143]
Hi, we have a D365 Online environment with ADFS authentication, so in this case we need to login twice:
1 First login through the D365 login page (this step is supported by EasyRepro)
2 After signing, there is an additional page for ADFS login, we need to enter the credential again.
In the second ADFS login, the EasyRepro is no longer supported.
Just ask is it possible to use EasyRepro to supports both D365 and our own ADFS page?
Many thanks.

**Comment by harryzang** [comment]
Never mind,
I implemented my own function for ADFS login, attached on LoginDialog.cs, and calling the following code in my test cases, it works for my case now.
xrmBrowser.LoginPage.LoginADFS( _username, _password); 

`

        public BrowserCommandResult<LoginResult> LoginADFS(SecureString username, SecureString password)
        {
            return this.Execute(GetOptions("Login"), this.ADFSLogin, username, password);
        }
        private LoginResult ADFSLogin(IWebDriver driver, SecureString username, SecureString password)
        {
         
            //driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.UserId])).SendKeys(username.ToUnsecureString());
            //driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.UserId])).SendKeys(Keys.Tab);
            //driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.UserId])).SendKeys(Keys.Enter);

            Thread.Sleep(1000);

            //Check if account selection screen is present (AAD vs MSA accounts)
            if (driver.IsVisible(By.Id("aadTile")))
            {
                driver.FindElement(By.Id("aadTile")).Click(true);
            }

            Thread.Sleep(1000);

            driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(password.ToUnsecureString());
            driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(Keys.Tab);
            driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).Submit();

            if (driver.IsVisible(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])))
            {
                driver.ClickWhenAvailable(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn]));
                driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])).Submit();
            }

            driver.WaitUntilVisible(By.XPath(Elements.Xpath[Reference.Login.CrmMainPage])
                , new TimeSpan(0, 0, 60),
                e =>
                {
                    e.WaitForPageToLoad();
                    e.SwitchTo().Frame(0);
                    e.WaitForPageToLoad();
                },
                f => { throw new Exception("Login page failed."); });

            return LoginResult.Success;
        }

`

**Comment by TYLEROL** [comment]
@harryzang - Thanks for trying out EasyRepro! The method you have utilized should work fine, however you may miss out on future updates in the event the Login method is ever altered in the future.

The preferred approach would be to use the overloaded Login method that allows you to pass a _CustomLoginAction_. This would allow you to customize your actions depending on the layout/design of your ADFS portal.


The sample below shows how you could accomplish this. It looks like the ADFSLogin sample was accidentally cut from the v8.2, v9.0 and v9.0.2 branches - however if you take a look at the v8.1 branch there is an ADFSLogin.cs file in the Sample project that also includes a similar configuration.

The biggest items will be the element names in the event of a non-standard ADFS configuration. If you have any additional questions about this, please re-open this issue and let us know.

Best Regards,
Tyler

```
[TestMethod]
        public void TestCustomLogin()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, CustomLoginAction);
            }
        }

        public void CustomLoginAction(LoginRedirectEventArgs args)
        {
            //Login Page details go here.  You will need to find out the id of the password field on the form as well as the submit button. 
            //You will also need to add a reference to the Selenium Webdriver to use the base driver. 

            //Example
            //--------------------------------------------------------------------------------------
            var d = args.Driver;
            d.FindElement(By.Id("passwordInput")).SendKeys(args.Password.ToUnsecureString());
            d.ClickWhenAvailable(By.Id("submitButton"), new TimeSpan(0, 0, 2));

            //Insert any additional code as required for the SSO scenario

            //Wait for CRM Page to load
            d.WaitUntilVisible(By.XPath(Elements.Xpath[Reference.Login.CrmMainPage])
                , new TimeSpan(0, 0, 60),
            e =>
            {
                e.WaitForPageToLoad();
                e.SwitchTo().Frame(0);
                e.WaitForPageToLoad();
            },
                f => { throw new Exception("Login page failed."); });
            //--------------------------------------------------------------------------------------
        }
```
