### ISSUE TITLE
OpenQA.Selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by tipsey** [Microsoft/EasyRepro#147]
Version:  releases/OnPremise
Scenario: Customized Login
Code Snippet:  (Note if I used .submit it will not click the SubmitButton)
Note:  If I used Submit on releases/v9.0 it works only on IE 11
Browser:  Chrome, IE 11 on releases/OnPremise

 ` [TestMethod]
        public void TestAcrmLogin()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
          

            {
                String xpath = "//*[@id='search']";
                //xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
              
                xrmBrowser.GoToXrmUri(_xrmUri);
                xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_UsernameTextBox")).SendKeys(_username);
                xrmBrowser.ThinkTime(1000);
                xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_PasswordTextBox")).SendKeys(_password);
                xrmBrowser.ThinkTime(1000);
                xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_SubmitButton")).Click();

                xrmBrowser.ThinkTime(10000);
                xrmBrowser.Driver.WaitUntilVisible(By.XPath(xpath)
                        , new TimeSpan(0, 0, 60),
              e => { xrmBrowser.Driver.WaitForPageToLoad(); },
              f => { throw new Exception("Login failed."); });

            }
        }`

**Comment by TYLEROL** [comment]
@tipsey - Sorry for the delay in getting back to you on this. In the Browser project, SeleniumExtensions.cs file, custom Click methods have been overloaded for a couple different scenarios. By default, the ignoreStaleElementException parameter is false if no parameters are supplied.

If you pass True, then it should catch and ignore the stale element exception you're seeing. Can you confirm if this resolves the problem with your custom login scenario?

Best Regards,
Tyler

```
[TestMethod]
public void TestAcrmLogin()
{
using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
        {
            String xpath = "//*[@id='search']";
            //xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
          
            xrmBrowser.GoToXrmUri(_xrmUri);
            xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_UsernameTextBox")).SendKeys(_username);
            xrmBrowser.ThinkTime(1000);
            xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_PasswordTextBox")).SendKeys(_password);
            xrmBrowser.ThinkTime(1000);
            xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_SubmitButton")).Click(true);

            xrmBrowser.ThinkTime(10000);
            xrmBrowser.Driver.WaitUntilVisible(By.XPath(xpath)
                    , new TimeSpan(0, 0, 60),
          e => { xrmBrowser.Driver.WaitForPageToLoad(); },
          f => { throw new Exception("Login failed."); });


        }
    }

```

**Comment by tipsey** [comment]
SeleniumExtensions.cs: Modified to this >  public static void Click(this IWebElement element, bool ignoreStaleElementException = true).  When I use the Chrome Driver 2.40 with Click still get error, when using with Submit, it weirdly clears the password textbox and stops.  I can only get this to work with IEDriver 3.5.1 x64 with Submit. (so hence all testing can only be done with IE for now.  Note: I have a workaround but using pure Selenium in Chrome it works).  Thanks for your help!

OpenQA.Selenium.StaleElementReferenceException: 'stale element reference: element is not attached to the page document
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64)'

**Comment by TYLEROL** [comment]
@tipsey - Can you replicate this issue using ChromeDriver v2.38 with version 3.11.2 for the Selenium.Support and Selenium.WebDriver packages? I took a quick look and I see on multiple projects in the OnPremises branch are using out of date versions for all three of those packages.

Can you confirm whether this specific version configuration provides you better results?

Thanks,
Tyler

**Comment by tipsey** [comment]
Context:  
Using On-Premise Version:  (8.1.1.1005)(DB 8.1.1.1005)
EasyRepro Version:  releases/v9.0  (just cloned with no changes other than Login)  Does it matter which release version to use??  Seem to have more success with releases/v9.0.
Selenium.Chrome.WebDriver = 2.38
Selenium.WebDriver = 3.11.2
Using .Click() on Chrome get stack error:

`  at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.get_Location()
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.EventDriver_ElementClicked(Object sender, WebElementEventArgs e) in C:\Repos\EasyRepro2\Microsoft.Dynamics365.UIAutomation.Browser\InteractiveBrowser.cs:line 458
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.OnElementClicked(WebElementEventArgs e)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.AddConnection.WEBTestAddConnectionToContact() in C:\Repos\EasyRepro2\Microsoft.Dynamics365.UIAutomation.Sample\Web\AddConnection.cs:line 34`

**Comment by tipsey** [comment]
Had to use try / catch to workaround issue in Chrome:

 try
                {
                    xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_SubmitButton")).Click();

                    xrmBrowser.ThinkTime(10000);
                    xrmBrowser.Driver.WaitUntilVisible(By.XPath(xpath)
                            , new TimeSpan(0, 0, 60),
                  e => { xrmBrowser.Driver.WaitForPageToLoad(); },
                  f => { throw new Exception("Login failed."); });
                }
                catch (StaleElementReferenceException e)
                {
                    //old element has gone
                    Thread.Sleep(5000);
                }
