### ISSUE TITLE
Hangs using IE 11

### ISSUE THREAD

**Issue by markleavesley** [Microsoft/EasyRepro#150]
Selenium with IE works fine, but using IE in EasyRepro does not, it just hangs for many minutes and then throws a timeout exception. Here is the call stack:

![image](https://user-images.githubusercontent.com/12860709/42035563-29eb5906-7adb-11e8-8acc-26f2e35736a3.png)

I don't see the iexplore process, only IEDriverServer.

IE version:

![image](https://user-images.githubusercontent.com/12860709/42035676-72eb1966-7adb-11e8-963b-c43a79acf655.png)

Windows 10 Build 1803 (17134.112)

EasyRepro v9 as downloaded from here 18th June.

The code works fine with Chrome.

**Comment by markleavesley** [comment]
This issue goes away if you update IEDriver to 3.13, but you'll have to be sure it goes into your bin and not the copy from nuget, which is still on 3.12.

Now I can't login but that's a whole different issue.

**Comment by TYLEROL** [comment]
@markleavesley - Do you face these issues when using version 3.4 of the [IEDriver](http://selenium-release.storage.googleapis.com/3.4/IEDriverServer_x64_3.4.0.zip)? 

You'll also want to check and make sure that the Selenium.Support and Selenium.WebDriver versions are on 3.11.2 as these were the most recent versions that we've done test passes against.

_Note: The IEDriver linked above is X64. The 32bit version can be found [here ](http://selenium-release.storage.googleapis.com/3.4/IEDriverServer_Win32_3.4.0.zip
) if required._

Please let us know if you still encounter issues with these matching versions.

Thanks,
Tyler

**Comment by markleavesley** [comment]
@TYLEROL I'm using the latest nuget packages (3.13)

I've tried the IEDriver x86 above and nuget versions you suggest and it hangs, works with x64 version. I am running Selenium to control another IE browser at the same time if that makes any difference. 

With the x64 version I still get the login problem but I believe that to be an IE/domain/auto-login issue.

**Comment by cnusrini** [comment]
@markleavesley I had the same issue yesterday. 
Solution : in the TestSettings.cs file, change the privateMode to false. It will switch to non private mode and it will work as expected.
