### ISSUE TITLE
Unable to add values to lookup column

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#151]
Hello Techies,

Unable to add values to lookup columns.

Here are the column names: Preferred Language and Country.
I used the below code : 

xrmBrowser.Entity.SelectLookup("FieldID", "Tester"); 
xrmBrowser.Entity.SetValue(new Lookup { Name = "FieldID", Value = "Tester" });
xrmBrowser.Entity.SelectLookup("FieldID", 0);

**Comment by TYLEROL** [comment]
@SachinAnnam - Does your test fail with any exceptions in this scenario? Does it occur in all conditions, or is it specific to when the lookup field already contains existing data?

Thanks,
Tyler

**Comment by SachchinAnnam** [comment]
Yups it fails with below exception:
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateContact.WEBTestCreateNewContact threw exception: 
System.InvalidOperationException: Unable to click element.

It fails for the below lines:

xrmBrowser.Entity.SelectLookup("ColumnID-Preferred Language", "English");
xrmBrowser.Entity.SelectLookup("ColumnID-Country", "India");

**Comment by SachchinAnnam** [comment]
Closing this thread as the issue has been resolved.
I wasn't giving the proper data-attribute name for a lookup field.

**Comment by TYLEROL** [comment]
@SachinAnnam - My apologies for the delayed reply on this. For any of the _field_ based methods (GetValue, SetValue, SelectLookup, etc..), you should utilize the **schema name** of the attribute when referencing it as a parameter of these methods.

I'm glad you were able to resolve your issue. If you encounter any other problems, please continue to open issues as appropriate and we'll get to them as soon as possible. 

Thanks again for utilizing the Automated UI Testing APIs for Dynamics 365!


Warm Regards,
Tyler
