### ISSUE TITLE
IE11/v9 login problem

### ISSUE THREAD

**Issue by markleavesley** [Microsoft/EasyRepro#152]
I saw in a previous issue that EasyRepro supports v9, but I am having problems logging in with IE. The code as is works fine with Chrome, and is a lot faster too. I changed LoginDialog.Login to handle the fact that IE automatically tries, and fails, to login using my domain credentials. This involves signing out when you get the "notifications" error page, choosing a different "use another account" button from the one the it already looks for and then logging in by finding the "next" button by ID rather than tabbing to it. I then had to disable the code that looks for and clicks "stay logged in" as it always fails.

I can now login but I wonder if there was an easier way I could have done this, some option I need to turn on maybe?

**Comment by TYLEROL** [comment]
@markleavesley - I've had some issues with the IE browser doing this as well while using our Microsoft corporate network. For IE or Edge based scenarios, I use a non-domain user account which allows me to test without being forced to login as my corporate account. I'll add an item to our backlog to look at integrating this type of scenario into the login check.

In regards, to the Stay Signed In dialog, I recently noticed that IE wants to move past this nearly every time I tested. To mitigate it, I added Thread.Sleep() and WaitUntilVisible methods to force the code to slow down.

A set of fixes was checked into the v9.0.2 branch for this regarding the UCI client. These changes need to be ported into the regular web client for v8.2, v9, and v9.0.2. I've included an example below for that if you want to test it on your side. If you have issues re: stay signed in and these changes don't resolve that, please let me know so I can re-evaluate before trying to port them to the other release branches.

```
                else
                {
                    Thread.Sleep(1000);

                    driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(password.ToUnsecureString());
                    driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(Keys.Tab);
                    driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).Submit();

                    Thread.Sleep(1000);

                    driver.WaitUntilVisible(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn]), new TimeSpan(0, 0, 5)); 

                    if (driver.IsVisible(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])))
                    {
                            driver.ClickWhenAvailable(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])); 
                    }
```

Thanks,
Tyler

**Comment by markleavesley** [comment]
Apologies for the long delay in responding. I got pulled off onto another project but I'm back on this, for the moment at least. 

@TYLEROL Attached is my version of the LoginDialog.cs which seems to work for IE and other browsers against v9. Doubtless the changes can be far better implemented and with less exceptions.

[LoginDialog.zip](https://github.com/Microsoft/EasyRepro/files/2244325/LoginDialog.zip)

**Comment by TYLEROL** [comment]
Hey @markleavesley - thanks again for providing your sample. We'll review this and see what we can do to enhance the login scenarios based on issues you've encountered.

If you encounter any other problems, or have questions about using EasyRepro, please raise a new issue.

Best Regards,
Tyler
