### ISSUE TITLE
Installation of Nuget package failure

### ISSUE THREAD

**Issue by lshraybman** [Microsoft/EasyRepro#163]
Installing package in VS 2017 (15.7.5) fails throwing an error
Could not install package 'Dynamics365.UIAutomation.Api 9.0.2.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
In the description section of the package Dependency  .NETFramework, Version=v0.0

**Comment by TYLEROL** [comment]
Thanks for raising this issue @lshraybman . I've added an item to our backlog for the team to look into this and verify your findings.

We'll update once we're able to repro and have a fix available, or if we need additional information.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
@lshraybman - Sorry for the delay on getting back to you with this. We pushed an updated NuGet package this morning (v9.0.2.5). Could you give that a try and let us know if the reference to 'net46' has resolved this problem for you?

Best Regards,
Tyler

**Comment by lshraybman** [comment]
Tyler,

Thank you for getting back to me. I am away from the environment till
Tuesday.  Will try when I get back to the office and let you know.

 Best regards
Leo.

**Comment by TYLEROL** [comment]
@lshraybman - Sorry for not checking back in on this one. We have not seen a response, so I hope this means that the NuGet change worked to your satisfaction.

If not, please let us know right away by re-opening this issue and the current status of any issues should they exist.

Best Regards,
Tyler
