### ISSUE TITLE
Not able to create HTML reports using EasyRepro with mstest.

### ISSUE THREAD

**Issue by rselva22** [Microsoft/EasyRepro#167]
Im using same easyrepro framework to test the dynamics 365.But the challenge is not able to generate html report. Can any one help to create html report?

**Comment by dtu11** [comment]
What specifically are you wanting to generate an HTML report out of?   Are you wanting to generate a report out of the results?

**Comment by TYLEROL** [comment]
@rselva22 - If this is still an issue, please re-open the issue and provide more details per @dtu11's request.

Best Regards,
Tyler
