### ISSUE TITLE
Missing support for other languages

### ISSUE THREAD

**Issue by scubaracer** [Microsoft/EasyRepro#168]
Hi,
I'm testing the new UCI api and i notice all code is written for the English user interface, the xpaths are on labels. 
We use dutch for the user interface. 
For example the function OpenSubArea, this uses xpath to find label ‘All Areas’ in dutch it is ‘Alle gebieden’. 
Could you add support for other languages?

**Comment by TYLEROL** [comment]
Thanks for raising this request @scubaracer. I've taken this request and added to our backlog to enhance the underlying code to use elements that would not be specific to a locale.

I've included your example, but this will take some time for a broad sweep and correction for additional scenarios where the code is currently locale specific. 

Best Regards,
-Tyler

**Comment by scubaracer** [comment]
Hi,
A method to overwrite the xpaths would also be a possibility and likely less work to support all other languages.
Kind regards,
Daniel

**Comment by TYLEROL** [comment]
This is under consideration for future releases. We are doing our best to keep the controls language agnostic. If you have specific issues that are not working across language, please raise each as a new issue and the use-case behind them. We'll try to address any by avoiding language constraints where possible.
