### ISSUE TITLE
Close popup window/switch back to entity

### ISSUE THREAD

**Issue by mxwsxr** [Microsoft/EasyRepro#169]
Hello EasyRepro Team!

We are trying to utilize your very cool software solution.
We're facing an issue because we can't seem to switch back to the entity page after opening a popup window.
How do we close the popup window and switch back to the entity page on CRM?

We're greately appreciating your feedback.

Yours sincerely

mxwsxr

**Comment by TYLEROL** [comment]
Thanks @mxwsxr for both using the Automated UI testing API for Dynamics 365 and raising this issue.

Could you provide some more details about one of your specific pop-up scenarios? It sounds like you may be referring to _Dialog_ scenarios, examples being **Close Opportunity**, **Qualify Lead**, **Duplicate Detection**, **Assign**, etc..

If you have any generic screenshots that can be shared, that would also be helpful. I look forward to your update and providing further assistance to you on this inquiry.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
@mxwsxr - As this is pending additional information, we will close this issue for now. Please re-open and share additional details when you're able.

Best Regards,
Tyler
