### ISSUE TITLE
Add Some Unit Test to EasyRepro

### ISSUE THREAD

**Issue by AngelRodriguez8008** [Microsoft/EasyRepro#170]
Hi, 

I worked in the last days with EasyRepro, trying to understand how it works. The idea is great; there is a lot nice features. However, it does work always as expected. I needed to extend the library to achieve some goals, there is some Issues Open in this direction, but I think they are for Unit Testing essential. For example:
Bugs:
-	Override Text Value Fields
-	Override Lookup Value Fields
-	Set Value (incomplete, don’t trigger the JS logic or Business Rule Logic)

Features:
-	Get Save Result, get Error Message
-	Clear Fields
-	Get Value for Hidden Fields
-	Get Fields Visibility
-	Get Fields Requirement Level
-	Get Fields IsDirty vs. All Dirty Fields
-	Command Bar: Is Command Visible, or Enable
-	Business Process Bar: Is Visible

I solve some of these scenarios using “Form JS”, using the actually the deprecated “Xrm.Page.”
I want to contribute to the project, sharing my unit tests and extensions classes with you; maybe you find a better solution than I do. Is it possible?

Thanks & Best regards 
Angel A.

**Comment by dtu11** [comment]
Yes we would love your contributions.  Just submit a PR with the functionality you think the rest of the community could probably use and I'll review.

**Comment by AngelRodriguez8008** [comment]
Hi, 

Thank. I'm trying to create a PR and I get follow Error creating a new Branch (users/AngelRodriguez8008/FormJS) or in (releases/v8.2)

git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks -c credential.helper= -c credential.helper="C:/Users/rodang/AppData/Local/ATLASS~1/SOURCE~1/GIT_EX~1/GIT-CR~1.EXE" push -v --tags --set-upstream origin users/AngelRodriguez8008/FormJS:users/AngelRodriguez8008/FormJS
remote: Permission to Microsoft/EasyRepro.git denied to AngelRodriguez8008.
fatal: unable to access 'https://github.com/Microsoft/EasyRepro.git/': The requested URL returned error: 403

Pushing to https://github.com/Microsoft/EasyRepro.git
Completed with errors, see above.

What should i do?

BR

**Comment by TYLEROL** [comment]
Thanks for raising this PR @AngelRodriguez8008 - I'll review with @dtu11 tomorrow and provide an update on status of the PR.

Best Regards,
Tyler

**Comment by cnusrini** [comment]
Can I use easyRepro to perform CRM client side unit testing ?
