### ISSUE TITLE
Switching Between Windows 

### ISSUE THREAD

**Issue by SantoshDutt** [Microsoft/EasyRepro#173]
Can anyone help me out with any piece of working code which would do window handling, switching from one window to another and catching the element in the new window. I have used xrmBrowser.Driver.LastWindow(); to switch to the new window but not able to get the control back to the Previous window.  

Also, does EasyRepro have methods to click on the (+New) Button of the Lookup Dialog - refer the screenshot below. 
![image](https://user-images.githubusercontent.com/41611923/44386989-cae0fd80-a541-11e8-8aad-13c0e6401f0a.png)

**Comment by TYLEROL** [comment]
Hello @SantoshDutt - Thanks for raising this issue.

In regards to your window switching scenario - could you share more details about what you're attempting to interact with? If it's an issue related to iframes within Dynamics 365 - you could try calling driver.SwitchTo().DefaultContent() and see if that helps with establishing control over the default window frame.


If that does not work, please share more information about your steps and we're happy to review with you.


In regards to the New button on the Lookup Dialog, I've added an item to the backlog to review this scenario to allow interaction with the new button.

Best Regards,
Tyler

**Comment by SantoshDutt** [comment]
Hello @TYLEROL Thanks for the advice! In my scenario I am trying to click on a Subgrid(+) button which opens a new window and I am using  **xrmBrowser.Driver.LastWindow()**; to switch to the current window I am about to automate. 
Then I am saving the form and closing it using this piece - **xrmBrowser.Driver.Close();**
        Which closes the new window. And to get back to the First Window, I have used this - **xrmBrowser.Driver.LastWindow();** and it is working as expected.

**Comment by TYLEROL** [comment]
Excellent @SantoshDutt! We're happy to hear you have a working solution. Based on the scenario you described, this is how we would have handled it as well.

If you encounter any other issues or have questions about using EasyRepro, please don't hesitate to open a new issue.

Best Regards,
Tyler
