### ISSUE TITLE
How do you use SetValue for a checkbox

### ISSUE THREAD

**Issue by farrows3** [Microsoft/EasyRepro#174]
Hi, Have a form I am populating from script, and 1 item is a checkbox.  when I am using SetValue to tick the box , It is returning an error saying field is not selectable. 

xrmApp.Entity.SetValue("suitableforsurvey", "Yes");

OpenQA.Selenium.InvalidElementStateException: invalid element state: Element must be user-editable in order to clear it.

The field is definitely editable from manual execution, and have checked setup, and it is a Yes/No config.

Any help appreciated

**Comment by tipsey** [comment]
xrmApp.Entity.SetValue("suitableforsurvey", true);    //check the box
xrmApp.Entity.SetValue("suitableforsurvey", false);    //uncheck the box

Have you tried the above?  I use a different branch and have used this
successfully:

xrmBrowser.Entity.SetValue("gm_peerreview_english", true);

**Comment by farrows3** [comment]
Hi, I tried that option, but then it is returning following error.
Argument 2: cannot convert from 'bool' to 'string'

**Comment by veerasekharbathala** [comment]
@farrows3 - I am using beta-v9.0.2 branch and i am able to setvalue using below code.
 xrmBrowser.Entity.SetValue(new Field { Id = "checkboxcontrolHTMLid", Name = "checkboxfieldname", Value = "True" });
