### ISSUE TITLE
OpenSubArea fails if there are multiple sub items with the same name

### ISSUE THREAD

**Issue by ryan-4** [Microsoft/EasyRepro#176]
Under the 'Sales' menu area we have and 'Events' link under both the 'Sales' category and the 'Extensions' category. This causes the OpenSubArea method to fail when it's trying to add the second Events item to a dictionary (because it's a duplicate). 
It fails for all sub areas under Sales, not just Events.

When there are multiple sub areas with the same name, it's not possible to specify which one should be opened using OpenSubArea, unless another parameter were added to indicate the category that it appears under.

A more straightforward fix would be to simply edit the failing line 447 of Navigation.cs to replace:
**dictionary.Add(subItem.Text.ToLowerString(), subItem);**
with:
**dictionary[subItem.Text.ToLowerString()] = subItem;**

This would perform an insert/update on the dictionary which won't fail when it encounters duplicates.

**Comment by TYLEROL** [comment]
Thanks for raising this issue @ryan-4. I've added this to our backlog for our team to review and apply a fix accordingly.

If you have a working scenario completed and would like to contribute to the GitHub repo via a pull request, please submit one and our team can also review for approval.


Best Regards,
Tyler

**Comment by TYLEROL** [comment]
This has been fixed in the most recent releases/v9.1 branch of EasyRepro. The new implementation will select the first element in the list if duplicates are present. If a specific use case appears that requires specific selection from the subarea list, please let us know.
