### ISSUE TITLE
Change Chrome Webdriver to development dependency

### ISSUE THREAD

**Issue by kcouck** [Microsoft/EasyRepro#181]
Hello, the package now forces the Chrome webdriver as a dependency, even if we don't want/use it (for now). Could you change it to a development dependency, so the automatic dependency download doesn't try to download it on our build server?

**Comment by jlattimer** [comment]
Looks like dependency was removed awhile back

**Comment by kcouck** [comment]
See NugetSpecs/Microsoft.Dynamics365.UIAutomation.Api.9.0.0.0.nuspec:
`        <dependency id="Selenium.Chrome.WebDriver" version="2.31" />`
Is still in there...

In case this nuspec is auto-generated, you can add 'developmentDependency="true" ' to the package.config to avoid inclusion:
`<package id="Selenium.Chrome.WebDriver" version="74.0.0" targetFramework="net46" developmentDependency="true" />`

**Comment by jlattimer** [comment]
It doesn't appear the latest .nuspec for 9.1 is there. If you check what is published on [NuGet](https://www.nuget.org/packages/Dynamics365.UIAutomation.Api/) there isn't dependency on Selenium.Chrome.WebDriver anymore.

**Comment by kcouck** [comment]
You are right, it's gone since 9.0.2. Thanks for checking!
