### ISSUE TITLE
AAD Tile stopped working

### ISSUE THREAD

**Issue by zordanian** [Microsoft/EasyRepro#182]
Hi,

We have before used this code to successfully login to dymamics and aad, but its not working anymore (If evaluates to false). I dont know if the id has changed, i have tried to find it but i have ben unsuccessful. 

if (driver.IsVisible(By.Id("aadTile")))
 {
 driver.FindElement(By.Id("aadTile")).SendKeys(Keys.Enter);
 }

**Comment by TYLEROL** [comment]
Hi @zordanian ,

Thanks for raising this. In the past, I recall this scenario being susceptible to timing issues. You could try temporarily adding the following line of code before the driver.IsVisible call to see if that corrects the problem. If it does, then the driver may be trying to evaluate faster than the page load.

Example:
```
               Thread.Sleep(3000);

                if (driver.IsVisible(By.Id("aadTile")))
                {
                    driver.FindElement(By.Id("aadTile")).Click(true);
                }
```


If that does not work, then you can use the element inspector tool in the browser to see if the Id for the 'aadTile' element has changed. Click on the Inspector, and then the aadTile.

I'll try to check this as soon as I can once I can replicate the scenario again - but if you have any findings in the meantime please update this issue accordingly.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
@zordanian - I tested this with the latest Chrome (v69) and IE browsers but was unable to reproduce an issue.

I am using the default code from LoginDialog.cs in the beta/v9.0.2 branch for EasyRepro. I've included a snippet from lines 101-112 if you'd like to compare to your local version, but I expect it should be the same.

If you continue to experience issues, please re-open this issue and we can re-evaluate. I inspected the elements that I've observed in my repro and the Element IDs have remained the same.

```
driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.UserId])).SendKeys(username.ToUnsecureString());
                driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.UserId])).SendKeys(Keys.Tab);
                driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.UserId])).SendKeys(Keys.Enter);

                Thread.Sleep(1000);

                if (driver.IsVisible(By.Id("aadTile")))
                {
                    driver.FindElement(By.Id("aadTile")).Click(true);
                }

                Thread.Sleep(1000);
```

Best Regards,
Tyler
