### ISSUE TITLE
QuickCreate.SelectLookup selects first item in the lookup list

### ISSUE THREAD

**Issue by TYLEROL** [Microsoft/EasyRepro#183]
Using v9.0 branch on On-premise solution and also having problem selecting lookup value. It always selects the first item in the lookup list:  ie.  Lookup list is in this order:  Phone Call, Voicemail, Email, Other

```
xrmBrowser.QuickCreate.SelectLookup("caseorigincode", "Email");
xrmBrowser.QuickCreate.SelectLookup("caseorigincode", 2);
```

Result:  It always populates the field with "Phone Call" instead of "Email".  Any workarounds to this?  Thank you.

_Originally posted by @tipsey in https://github.com/Microsoft/EasyRepro/issues/111#issuecomment-414360384_

**Comment by TYLEROL** [comment]
@tipsey - Splitting this into a separate issue from #111.

Thanks for posting, we'll review this behavior and get back to you as soon as we can.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
@tipsey - Could you try this using the SetValue() method and see if it gives you better results in the interim?

` xrmBrowser.QuickCreate.SetValue(new OptionSet { Name = "caseorigincode", Value="Email" });`

This should at least allow you to select the correct value for your scenario. I'm reviewing the SelectLookup() method with the creator to understand the intent and whether we need to enhance that method or create a different one for Option Set scenarios.

Thanks again for your patience on this. If you have issues using the code example listed above, please let me know.

Best Regards,
Tyler

**Comment by tipsey** [comment]
I tried xrmBrowser.QuickCreate.SetValue(new OptionSet { Name = "caseorigincode", Value="Email" }); in both 9.0 and beta.v9.0.2 and I still have the same problem.  It always selects the first in the list.  I have replicated the issue using both IE Driver 3.5.1 and Chrome Driver 2.38. Thanks.

**Comment by tipsey** [comment]
//Workaround Bug
                xrmBrowser.QuickCreate.SetValue(new OptionSet { Name = "gendercode", Value = "Female" });

This worked on the Quick Create Contact form .  Thanks

**Comment by TYLEROL** [comment]
We've made changes in the latest releases/v9.1 branch that should resolve this scenario. If you continue to observe issues with the implementation, please let us know.

**Comment by UdayUday330** [comment]
In Debug mode it is working fine. but in direct run taking first value.
