### ISSUE TITLE
Unified Interface GetValue() method not working after using SetValue()

### ISSUE THREAD

**Issue by TYLEROL** [Microsoft/EasyRepro#196]
_Originally posted by @lucasalexander in https://github.com/Microsoft/EasyRepro/issues/185#issuecomment-427184872_

Thanks! It didn't occur to me to validate that I was actually testing a UCI app. Once I changed to open "Sales Hub," that error went away, but I am now having a problem getting a value from the form to validate a process executed on save.  Here's the relevant code:

```
                xrmApp.ThinkTime(500);
                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

                xrmApp.ThinkTime(500);
                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.Entity.SetValue("name", "Test UCI Account");
                xrmApp.Entity.SetValue("telephone1", "555-9345");

                xrmApp.Entity.Save();
                xrmApp.ThinkTime(2000);
                var phone1 = xrmApp.Entity.GetValue("telephone1");
                Assert.AreEqual<string>("8675309", phone1);
```

I have a real-time workflow that always sets the value of telephone1 to "8675309," and when I view accounts in a separate browser session I can see the value was set correctly after the Entity.Save. In the browser session that Easy Repro is running, the number doesn't change from the original "555-9345," and the value of the attribute is null when I try to check it using Entity.GetValue. When I manually create an account record in the Sales Hub app, the phone number does update after the save, so I'm not sure why it's not working here.

**Comment by TYLEROL** [comment]
@lucasalexander - I've submit and merged a new PR this morning into the beta/v9.0.2 branch to correct the NULL value issue with Entity.GetValue() via #197.

Could you test this latest change and see if this helps with your behavior? I have not setup the workflow scenario you setup, so I'd be interested to see your observed behavior with GetValue and whether it returns 555-9345 or 8675309. My expectation is that it will return 8675309 barring a UI/Refresh issue.

I look forward to hearing back from you.

_Edit: You may want to test adjusting your xrmApp.ThinkTime() call after the Save() method and increase this to something higher to rule out race condition scenarios._

Best Regards,
Tyler

**Comment by lucasalexander** [comment]
It's working now, thanks! I did proactively up the wait time from 2000ms to 5000ms.

**Comment by TYLEROL** [comment]
Excellent! Thanks for confirming @lucasalexander !

If you have any other issues, please open a ticket and we'll try to look at it as soon as we can.

Best Regards,
Tyler
