### ISSUE TITLE
No such frame exception thrown when switching to a Look Up Record dialog

### ISSUE THREAD

**Issue by Tinutza** [Microsoft/EasyRepro#200]
Hi,

I am trying to switch to a frame and call an element inside and I am getting the “OpenQA.Selenium.NoSuchFrameException : no such frame” exception. Is there a more elegant way to be handling this and if not, at least a working way?
As you can see from the photo, the iFrame name looks clear:
<iframe id="InlineDialog_Iframe" name="InlineDialog_Iframe" src="/CRM-DEV/_controls/lookup/lookupinfo.aspx?AllowFilterOff=0&amp;DefaultType=1&amp;DisableQuickFind=0&amp;DisableViewPicker=0&amp;IsTypeUnresolved=1&amp;LookupStyle=single&amp;ShowNewButton=1&amp;browse=0&amp;currentObjectType=3&amp;currentid=&amp;dType=1&amp;isRegardingFieldPopulated=false&amp;mrsh=false&amp;objecttypes=1%2c2" style="height: 100%; width: 100%; border: 0px;"></iframe>

<img width="606" alt="lookupdialog_iframe" src="https://user-images.githubusercontent.com/40760768/46667211-356cfc00-cbc9-11e8-951c-bfb289f2fbcb.png">

Have tried in multiple ways:
- Try to switch directly to the frame: ErDriver.XrmBrowser.Driver.SwitchTo().Frame(3) or Frame(“InlineDialog_Iframe”)
           -> OpenQA.Selenium.NoSuchFrameException : No frame element found with name or id InlineDialog_Iframe
-	Try to switch through the parent frame and then back into the dialog:
ErDriver.XrmBrowser.Driver.SwitchTo().DefaultContent();
ErDriver.XrmBrowser.Driver.SwitchTo().Frame(3); or .Frame(“InlineDialog_Iframe”)

Or 
 ErDriver.XrmBrowser.Driver.SwitchTo().ParentFrame();
 ErDriver.XrmBrowser.Driver.SwitchTo().Frame(3); or .Frame(“InlineDialog_Iframe”)

Or
String whandle = ErDriver.XrmBrowser.Driver.CurrentWindowHandle;
ErDriver.XrmBrowser.Driver.SwitchTo().Window(whandle);
ErDriver.XrmBrowser.Driver.SwitchTo().Frame(3); or .Frame(“InlineDialog_Iframe”)

      -> OpenQA.Selenium.NoSuchFrameException : no such frame

Selenium IDE returns this:
![ide](https://user-images.githubusercontent.com/40760768/46667250-5fbeb980-cbc9-11e8-99ea-6055abf202d2.png)

I wonder if this part will work after:
<\select id="selObjects" name="selObjects" defaultselected="1" class="ms-crm-SelectBox " tabindex="1" onchange="OnRecordTypeChange(this, false)" sort="ascending">
              <\option value="2" guid="{A2D479C5-53E3-4C69-ADDD-802327E67A0D}" 
title="Contact">Contact<\/option>
              <\/option value="1" selected="selected" guid="{A9AF0AB8-861D-4CFA-92A5-C6281FED7FAB}" title="Customer">Customer<\/option>
<\/select>

var lookForDd = ErDriver.XrmBrowser.Driver.FindElement(By.Id("selObjects"));
var selectElement = new SelectElement(lookForDd);
selectElement.SelectByText("Customer");

Also to mention:
CRM version: Microsoft Dynamics 365 on-premise
Version 1612 (8.2.2.1862).232-bit)
Easy Repro version 8.2 from 2 months ago
I run tests on a separate VM, not on the local one, through remote driver.

Thanks,
Tina

**Comment by TYLEROL** [comment]
Hello @Tinutza 

Could you share some more detail about what you're trying to perform? Specifically, what actions you'd like to perform on the Lookup Dialog window? If you could list each "click" in an ordered list, it would be helpful for our understanding.

We have actions for setting lookup field values which should handle some of your interaction with the dialog window. Lookup.cs in the UIAutomation.API project is what should be currently available to perform.

The reason I ask for more detail about your scenario is that if we're missing a feature gap, I'd like to better understand it and get it added to our backlog to improve overall functionality of our APIs. I also don't recall needing to perform frame switches to interact with the lookup dialog, but your scenario may be different and I hope we can better assist!

Best Regards,
Tyler

**Comment by Tinutza** [comment]
Hi,

I still couldn't figure it out. Below the info and the screenshots of the clicks:
1. Open the LookupDialog for [Customer] field.
Managed to do this by clicking [Look Up More Records]
2. When Lookup Dialog opens,  switch to it and 
3. Select the [Customer] option from the first dropdown.
4.  Select the [Active Customers] option from the second dropdown.
5. Click [Add].

<img width="319" alt="step1" src="https://user-images.githubusercontent.com/40760768/48064143-4eb49880-e1c7-11e8-907f-f647e53265d4.PNG">
<img width="345" alt="step2" src="https://user-images.githubusercontent.com/40760768/48064147-5116f280-e1c7-11e8-98b3-effb586bd30c.png">
<img width="335" alt="step3" src="https://user-images.githubusercontent.com/40760768/48064152-53794c80-e1c7-11e8-9211-202975a4c50c.png">


1.First dropdown:

- select id="selObjects" name="selObjects" defaultselected="1" class="ms-crm-SelectBox " tabindex="1" onchange="OnRecordTypeChange(this, false)" sort="ascending"
 - option value="2" guid="{A2D479C5-53E3-4C69-ADDD-802327E67A0D}" 
    title="Contact">Contact</option>

2.Second dropdown = grid:
- select gridid="crmGrid" quickfindquery="{2D1187C4-23FE-4BB5-9647-43BB1C6DDBD1}" tabindex="2" returnedtypecode="1" id="crmGrid_SavedQuerySelector" name="crmGrid_SavedQuerySelector" defaultselected="{A9AF0AB8-861D-4CFA-92A5-C6281FED7FAB}" class="ms-crm-SelectBox " onchange="handleView(this, $find('crmGrid'))">
          - optgroup label="System Views" id="AppSystemViews">
                      - option value="{00000000-0000-0000-00AA-000010001002}" type="1039" title="Active Customers">Active Customers

Please let me know what functions I could use to interact with the lookup.
Kind regards,
Cristina

**Comment by SantoshDutt** [comment]
Hi @Tinutza ,
We have a method  xrmBrowser.Lookup.SwitchEntity("EntityName"); - Customer, in your scenario which Helps you switch the first dropdown to what ever entity you want to switch your lookup view to. 
Then, use 
xrmBrowser.Driver.SwitchTo().DefaultContent();
xrmBrowser.Driver.SwitchTo().Frame("InlineDialog_Iframe");           
            try
            {
                xrmBrowser.Driver.FindElement(OpenQA.Selenium.By.XPath("//*[@id='crmGrid_SavedQuerySelector']")).Click(); or with the //Select[@id='crmGrid_SavedQuerySelector']
            }
            catch (StaleElementReferenceException ex)
            {
               
            }
xrmBrowser.Driver.SwitchTo().DefaultContent();
xrmBrowser.Driver.SwitchTo().Frame("InlineDialog_Iframe");           
            try
            {
                xrmBrowser.Driver.FindElement(OpenQA.Selenium.By.XPath("//option[@title='Active Customers']")).Click(); 
            }
            catch (StaleElementReferenceException ex)
            {
               //this catch would prevent the test case from throwing a stale element exception which we see in most of the cases. 
            }
This should help, 

Regards, 
Santosh Dutt

**Comment by TYLEROL** [comment]
There are two unique methods available in the latest releases/v9.1 branch that will help accomplish what SantoshDutt has shown.

the first is SwitchToDefaultContent() and then the second is SwitchToDialog(). Both can be called without any input parameters and should be able to target the dialog frames as needed.

If you have any issues with the implementation, please let us know.
