### ISSUE TITLE
Get ID of Entity

### ISSUE THREAD

**Issue by s-bauer** [Microsoft/EasyRepro#201]
HEy, I was wondering if there is any possibility to get the id of the currently opened entity. I didn't see any Property or Method to do this!

**Comment by NicolasPrats** [comment]
Hi @s-bauer ,

As workaround, I can suggest to popout the record and to parse the URL:
```
XrmTestBrowser.Entity.Popout();
XrmTestBrowser.ThinkTime(1000);
XrmTestBrowser.Driver.SwitchTo().Window(XrmTestBrowser.Driver.WindowHandles[1]);

var url = XrmTestBrowser.Driver.Url;
var id = System.Web.HttpUtility.ParseQueryString(url)["id"];
```

Or you can also inject Javascript code into the form to retrieve the ID.

**Comment by TYLEROL** [comment]
A new Entity.GetRecordGuid() method has been added to the releases/v9.1 branch. Please let us know if you have any issues with this implementation.
