### ISSUE TITLE
Integrating Extent Reports Into Easy Repro

### ISSUE THREAD

**Issue by SantoshDutt** [Microsoft/EasyRepro#204]
Hi @TYLEROL We are planning to create rich Html Reports for our test cases using Easy Repro. Can we integrate the Extent Reports **http://extentreports.com/docs/versions/2/net/** into the Easy Repro Solution in any means? 
Or atleast generate any kind of test reports from Easy Repro?

**Comment by koslazorkin** [comment]
Also interested in this!

**Comment by jlattimer** [comment]
#435

**Comment by jlattimer** [comment]
I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.

**Comment by 14003163** [comment]
Hi

Can you give access to this mail id lavanya.modukuru@gmail.com to read your blog

**Comment by VictoriaB81** [comment]
Hi, please give access to mail id victoriabaretto81@gmail.com. to your blog. Thanks

**Comment by Roshini1986** [comment]
Hi ,please can u give access to roshini.gudisa6@gmail.com to read your blog. Thanks in advance

**Comment by Alok08101991** [comment]
> I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.

Could you pplease provide access to this email id: alok.105043@gmail.com

**Comment by man9035206** [comment]
> I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.

Could you please provide access to man9035206@gmail.com
