### ISSUE TITLE
Duplicate Detection in UI

### ISSUE THREAD

**Issue by petemossuk** [Microsoft/EasyRepro#219]
Hi,

I can't seem to progress past saving a record once a duplicate has been detected. It looks like its meant to be handled in the xrmApp.Entity.Save(); or xrmApp.CommandBar.ClickCommand("Save & Close"); but both fail as per below. Please advise.

Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.XXX.XXX.threw exception: 
System.InvalidOperationException: unknown error: Element <button id="id-48" aria-expanded="false" aria-haspopup="true" data-id="quick-launch-more-options-btn" data-lp-id="sitemap-areaBar-more-btn" type="button" class="y m ak j p k ag ah cr cs ct cu cv cz t " aria-label="All Areas">...</button> is not clickable at point (24, 162). Other element would receive the click: <div id="dialogRoot_4" tabindex="-1" class="f w a q r flexbox">...</div>
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.17134 x86_64)

**Comment by TYLEROL** [comment]
Hello @petemossuk , thanks for raising this issue to us.

Could you try commenting out line 552 within **WebClient.cs** in the **Microsoft.Dynamics365.UIAutomation.API.UCI** prject?

```
                    //Select the first record in the grid
                    (552) driver.FindElements(By.XPath("//div[contains(@class,'data-selectable')]"))[0].Click();
```

The current design is built to choose the **Ignore and Save** button, so this line should be unnecessary and may be contributing to the issue. We'll need to add in additional functionality for further control over the Duplicate Detection dialog.

**Could you try this out and report back if it helps with the xrmApp.Entity.Save() scenario?** 

_Note: From reviewing the current project structure, CommandBar.ClickCommand("Save & Close") would require an additional API call to interact with any dialogs, if present. This is not currently available for UCI, but I've added an item to the back log to add this functionality as well._

Best Regards,
Tyler

**Comment by petemossuk** [comment]
Thanks @TYLEROL 

I tried that which allowed the save but the Dialog was still present meaning you couldn't browse anywhere. I dug a bit deeper and found that it's just a timing issue, If you add in a wait to the HandleSaveDialog in WebCLient.cs then it works perfectly :)

        internal BrowserCommandResult<bool> HandleSaveDialog()
        {
            Browser.ThinkTime(1000);

Cheers
Pete

**Comment by TYLEROL** [comment]
Thanks again @petemossuk for helping confirm. We'll evaluate this in the future when we look to make the api's more resilient to timing issues like these.

For now, I've added the same Browser.ThinkTime method to the core code to help alleviate this problem for all.

Best Regards,
Tyler
