### ISSUE TITLE
Tab Testing

### ISSUE THREAD

**Issue by lp12354** [Microsoft/EasyRepro#221]
Is there a way to test whether a tab is expanded or collapsed on a form? Right now the SelectTab, CollapseTab and ExpandTab function seem to only click on the tab to open them. We would like a way to check on the form if a tab is expanded.

**Comment by TYLEROL** [comment]
Hello @lp12354, thanks for raising this issue to us.

Currently there is not an API available to check the state of a tab, however I've added an item to our backlog to add this capability. 

We'll update again once this functionality has been added.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
A new Entity.GetTabState() method has been added in the latest releases/v9.1 branch. Please let us know if you have any issues with this implementation.
