### ISSUE TITLE
UI: GetValue of fields in Footer

### ISSUE THREAD

**Issue by petemossuk** [Microsoft/EasyRepro#226]
Is there a way to get the value of a field that's displayed on the Header/Footer of a form? GetValue doesn't recognise it.

xrmApp.Entity.GetValue(FieldName);

Thanks

**Comment by SantoshDutt** [comment]
Hi @petemossuk ,

string HeaderORFooter = xrmBrowser.Driver.FindElement(OpenQA.Selenium.By.XPath("//Xpath of the Element")).Text;

will help you get this value i suppose. Try it out.

**Comment by TYLEROL** [comment]
Field support has been added for both Header and Footer fields (e.g. Entity.GetHeaderValue / Entity.GetFooterValue). Please let us know if you have any issues with the implementation in the latest releases/v9.1 branch.
