### ISSUE TITLE
UI: Setting fields in the BPF - CRM 9.1

### ISSUE THREAD

**Issue by petemossuk** [Microsoft/EasyRepro#228]
Is it possible to set fields in the BPF (CRM v9.1)? if so, how? - Fields that aren't also on the form,

Thanks

**Comment by TYLEROL** [comment]
Hello @petemossuk ,

From reviewing the feature set currently available, this is not yet possible. I've added an item to the backlog to add this feature enhancement. The field element naming between standard form fields and BPFs are different so this will require some additional work to add.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
Clear/Set/Get value methods have been added for BusinessProcessFlows in the releases/v9.1 branch. Please let us know if you have any issues with this implementation.
