### ISSUE TITLE
Setting value of Two Options type field

### ISSUE THREAD

**Issue by bwmodular** [Microsoft/EasyRepro#233]
Is there a method which allows for the setting of the value of an entity of type 'Two Options'?

This seems like it _should_ be the right method to call:
`xrmBrowser.Entity.SetValue(new OptionSet { Name = "bsp_highrisk", Value = "No" });`
but in fact all it does is toggle the existing value.

Here's a form with four such fields, two have a default Yes, two have a default No:
![defaults](https://user-images.githubusercontent.com/1889586/47358697-6f0e2e80-d6c2-11e8-99c2-5233cd149a01.png)

If we try and set them all to No like this:
`                xrmBrowser.Entity.SetValue(new OptionSet { Name = "bsp_highrisk", Value = "No" });
                xrmBrowser.Entity.SetValue(new OptionSet { Name = "bsp_tradesanctionsapply", Value = "No" });
                xrmBrowser.Entity.SetValue(new OptionSet { Name = "bsp_iscountry", Value = "No" });
                xrmBrowser.Entity.SetValue(new OptionSet { Name = "bsp_isdemonym", Value = "No" });`
we end up with values like this:
![allno](https://user-images.githubusercontent.com/1889586/47358740-8d742a00-d6c2-11e8-944b-f71d6924891f.png)
and we end up with the same results if we try and set them to Yes.
So I think all that is happening is that the 'SetValue' command is selecting the field and thereby toggling the value.

I also tried this:
`xrmBrowser.Entity.SetValue("bsp_highrisk", true);`
but this does nothing, which is to be expected as this is the method for checkboxes.

I _could_ deal with this by checking the value of the field before changing it, but wondered if there is a better way to do this, or anything coming in a future release to address this.

**Comment by SantoshDutt** [comment]
Hi @bwmodular,

I have also faced this issue and I am using this below scenario to overcome such risk. 
You can try this. 
 
 string IsCountryOptionPrior = xrmBrowser.Entity.GetValue(new OptionSet { Name = "bsp_iscountry" });
            if (IsCountryOptionPrior == "Yes")
            {
                xrmBrowser.Entity.SetValue(new OptionSet { Name = "bsp_iscountry", Value = "No" }); 
            }
Or vice versa if you want any field to set it as Yes.

**Comment by bwmodular** [comment]
Thanks @SantoshDutt - That will work perfectly until the team add a more permanent fix to 'SetValue'. Maybe I'll even post a PR if I have time...

**Comment by TYLEROL** [comment]
TwoOption field capability has been added to the latest releases/v9.1 branch. Please let us know if you have any issues with the current implementation.

**Comment by watsonthecat** [comment]
@TYLEROL will TwoOption field capability be added for UCI (xrmApp)? 

or do you have a suggestion on how to GetValue of a TwoOption field?

**Comment by jimmymunoz83** [comment]
hello, you have been able to solve the problem of attributes of two options ... I can not set the value of two options

**Comment by RobNightingale-LSL** [comment]
> hello, you have been able to solve the problem of attributes of two options ... I can not set the value of two options

Yes @jimmymunoz83 , use this format passing in a boolean for the value:

`xrmBrowser.Entity.SetValue(new TwoOption { Name = "fieldname", Value = "false" });`

**Comment by rahiltg** [comment]
I am using UCI on-premise and still unable to change a value from option set. I have tried below:

XrmApp.Entity.SetValue(new Api.UCI.OptionSet { Name = "vrp_isuploaded", Value = "Yes" });
XrmApp.Entity.SetValue(new Api.UCI.OptionSet { Name = "vrp_isuploaded", Value = "1" });

Please guide me if anyone has a solution
