### ISSUE TITLE
EasyRepro Support to Dynamics 365 Finance and Operations 

### ISSUE THREAD

**Issue by muralidharau** [Microsoft/EasyRepro#235]
Hi ,
Just wanted to know is there any update on EasyRepro support to Dynamics 365 Finance and Operation 

Thanks.

**Comment by TYLEROL** [comment]
Hi @muralidharau ,

While this is on the roadmap as a desired enhancement to the UIAutomation APIs, we do not have a timeline for when that work will be started. As of today, all current efforts are focused on bringing parity to Dynamics 365 Customer Engagement for the supported web clients of that platform.

Best Regards,
Tyler

**Comment by suryapatharlapalli** [comment]
Hi,
One of the method called "SetValue(new OptionSet { Name = , Value =) " is not working for "Case Type" field which is used to create a new case in Case Entity of the Service module of CRM . It is not selecting the specified value from the list and by default it is taking the first value.
It is also not throwing any exception if the text and attribute value is not matching with the specified value as mentioned in the respective method.
Please advice.
