### ISSUE TITLE
How to add Reporting in Easy Repro

### ISSUE THREAD

**Issue by flirtuser** [Microsoft/EasyRepro#238]
From where we can get the reports for Test Results for executed test. 
Also is there any script to send email for Test Results.

**Comment by jlattimer** [comment]
#435

**Comment by jlattimer** [comment]
I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.

**Comment by VishalaShreshta** [comment]
Can you please give access to vishalu.vs@gmail.com on - how to set up Extent Reports with an EasyRepro project

**Comment by praneethar-qz** [comment]
> Can you please give access to [vishalu.vs@gmail.com](mailto:vishalu.vs@gmail.com) on - how to set up Extent Reports with an EasyRepro project

Can you please share the details, if you have got any clue on this?

**Comment by untoldstory69** [comment]
Recently I've done some work on ExtentReport in EasyRepro. Please feel free to have a look [here](https://kishorsharma69.wordpress.com/2023/11/13/extent-report-with-easyrepro/).
