### ISSUE TITLE
xrmBrowser.Related.SetValue is returning Field does not exist error

### ISSUE THREAD

**Issue by veerasekharbathala** [Microsoft/EasyRepro#239]
Hi Team,

I am trying use xrmBrowser.Related.SetValue method to set field data on related record’s related entity and I am getting Field does not exist error.

1.	Workplace -> contacts -> select and open existing contact (contact has 1:N relationship with custom entity)
2.	Navigate to related custom entity associated view (from contact record) using navigation pane -> select and open existing custom entity record (custom entity has 1:N relationship with activities)
3.	Navigate to related open activities associated view (from custom entity record) using navigation pane -> Add New Activity -> Phone Call (trying to create new phone call. Phone call form has opened in new window) -> xrmBrowser.Related.SetValue -> returning Field does not exist error

When I checked list of commands using below line, I am getting open activities associated view command buttons from custom entity instead of phone call command buttons. 
How to access related record’s related entity form and fields? How can I set the data on related record’s related entity fields?

var buttons = xrmBrowser.Related.GetCommands(false).Value

Please find version details below.
EasyRepro version is beta-v9.0.2
D365 version is Version 1710 (9.1.0.288) online
Selenium.Chrome.WebDriver is 2.42.0
Selenium.WebDriver is 3.14.0
Selenium.Support is 3.14.0

Thanks,
Veera

**Comment by TYLEROL** [comment]
Hello @veerasekharbathala 

In Step 3, when the new phone call form has opened, have you tried using the SwitchToPopupWindow() method?

xrmBrowser.Related.SwitchToPopupWindow();
xrmBrowser.Related.SetValue(); 
....

When you're done and the pop-up is closed, if you encounter issues re-targeting the main window, you could try:

xrmBrowser.Related.SwitchToDefaultContent();

Could you try these approaches out and let me know if it helps alleviate your issue? If not, please let me know and I'll evaluate with the team internally on the best approach to handle this scenario moving forward.

Best Regards,
Tyler

**Comment by veerasekharbathala** [comment]
Thanks Tyler for the response. 

Yes, I did tried xrmBrowser.Related.SwitchToPopupWindow() and this line of code is executed successfully. However, when i try to execute xrmBrowser.Related.SetValue() code after xrmBrowser.Related.SwitchToPopupWindow() then I got below error.

Test Name:	CreatePhoneCall
Test FullName:	D365.UIAutomation.UnitTest.PhoneCall.CreatePhoneCall

Test Outcome:	Failed
Test Duration:	0:03:32.1230061

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteTargetLocator.Frame(String frameName)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringTargetLocator.Frame(String frameName)
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.SwitchToRelated()
   at Microsoft.Dynamics365.UIAutomation.Api.RelatedGrid..ctor(InteractiveBrowser browser)
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.GetPage[T]()
   at Microsoft.Dynamics365.UIAutomation.Api.Browser.get_Related()
   at D365.UIAutomation.UnitTest.PhoneCall.CreatePhoneCall() 
Result Message:	
Test method D365.UIAutomation.UnitTest.PhoneCall.CreatePhoneCall threw exception: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> OpenQA.Selenium.NoSuchFrameException: No frame element found with name or id areaActivitiesFrame

**Comment by TYLEROL** [comment]
Whoops, my mistake here @veerasekharbathala 

Once the pop-up is in focus, can you revert to setting entity field values like you would on a form?

`xrmBrowser.Entity.SetValue(...);`

Each time we call .Related, it initializes the RelatedGrid page, which does a SwitchToRelated() method that will no longer work in this context.

In the case of Entity, if the pop-up window switch worked, then the Entity page will be initialized and should switch into the main content window, allowing you to interact with the Phone Call form. 

If you encounter issues with this, could you post your test code (feel free to adjust custom entity naming and parameter values accordingly if you want to keep anything private). I can then try to setup a repro with that to verify your steps and see what we're missing. :)

Best Regards,
Tyler

**Comment by veerasekharbathala** [comment]
Thanks Tyler. I am able to interact with Phone call form using below approach.
xrmBrowser.Related.SwitchToPopupWindow();
xrmBrowser.Entity.SetValue

**Comment by TYLEROL** [comment]
Thanks @veerasekharbathala . I'll close this out as resolved. If you have any further issues and/or questions, please open a new issue.
