### ISSUE TITLE
Switching to a dialog and selecting a button for a customized form

### ISSUE THREAD

**Issue by sujaybarooah** [Microsoft/EasyRepro#24]
I was trying to extend the tests for a customized form. In my case, before saving a form, a dialog might pop-up in certain conditions. Does the API provide any option to switch to the dialog and accept/ reject the dialog?
Please see the attached screenshots.

![dom](https://user-images.githubusercontent.com/3263699/30572018-579d7c78-9d3f-11e7-9c16-b0a183704e84.png)
![screenshot](https://user-images.githubusercontent.com/3263699/30572017-579b4c46-9d3f-11e7-8c7c-0cef59092738.png)

**Comment by dtu11** [comment]
Since it looks like the dialog is not within an iFrame the existing SwitchToDialogFrame will not work.  I would add a explicit wait to look for the dialog.    Here is a example you can try. You may have to adjust the logic a little but it will wait for 2 seconds and if the dialog becomes visible then it will click the "Ok" button. 

xrmBrowser.Driver.WaitUntilVisible(By.XPath("id(\"alertJs-dialog\")"),
                                                    new TimeSpan(0, 0, 2),
                                                    x => { x.FindElement(By.XPath("id(\"alertJs-tdDialogFooter\")/button[1]")).Click(); });

**Comment by dtu11** [comment]
Let me know if that worked for you and I will close the issue. 

Thanks

**Comment by sujaybarooah** [comment]
Hi, thank you for the reply. I followed your suggestion and used WaitUntilVisible. However, it seems the control does not go to the dialog box. The system interacts with UI elements in the background, and closes the entity form after the wait times and the dialog remains hanging. Please see the attachment.

![testcase](https://user-images.githubusercontent.com/3263699/30792502-3ee6bb0e-a217-11e7-9a02-432623ab6502.png)

[ScriptExecutionRecording.zip](https://github.com/Microsoft/EasyRepro/files/1328248/ScriptExecutionRecording.zip)

**Comment by sujaybarooah** [comment]
Hi, I am closing this issue. 
I have been able to resolve this by switching to DefaultContent() before selecting the button in the custom dialog.
Thanks for your assistance.
