### ISSUE TITLE
Report Window with Easy Repro

### ISSUE THREAD

**Issue by lp12354** [Microsoft/EasyRepro#241]
Running some tests with reports but I'm unsure of how I'm able to test it. For starters I'm unable to swtich to a report window when I run it. I know there's some commands for switching windows, but I've tried Dialogs.SwitchToPopupWindow() and Dialogs.SwitchToRelatedFrame(). And I'm unable to get the frame.

**Comment by TYLEROL** [comment]
Hello @lp12354 - We have very limited capabilties for Reporting currently. Some of this is similar to the lack of support for the Advanced Find UI (as Reporting shares some of this same UI).

In the sample project, there is a Reports.cs file located under \Web\Reports that may provide some help with APIs to get the report to run (a few different sample tests are available using the OOB Account Overview report).

Once the report executes however, we do not have any APIs available for validation that it ran successfully.

This is in our backlog as a future feature enhancement, but I do not have an ETA for that availability.

Best Regards,
Tyler
