### ISSUE TITLE
composite control data verification issue

### ISSUE THREAD

**Issue by kamranRehman** [Microsoft/EasyRepro#245]
Hi,

I've a address control which is validating fine on 9.02 version successfully, however on 9.02 beta, the validation always FAILED for me.

following code I'm using to setup the composite control.

 var primaryAddress = new List<Field>
                        {
                            new Field() {Id = "address1_line1", Value = "A"},
                            new Field() {Id = "address1_line2", Value = "B"},
                            new Field() {Id = "address1_line3", Value = "C"},
                            new Field() {Id = "address1_city", Value = "D"},
                            new Field() {Id = "address1_stateorprovince", Value = "E"},
                            new Field() {Id = "address1_postalcode", Value = "F"},
                            new Field() {Id = "address1_country", Value = "G"},
                        };
                xrmBrowser.Entity.SetValue(new CompositeControl() { Id = "address1_composite", Fields = primaryAddress });
                xrmBrowser.ThinkTime(1000);

While validating it, using the following code.

                string primaryAdd = xrmBrowser.Entity.GetValue("address1_composite").Value;
                 Assert.IsTrue(primaryAdd.Equals(primaryAddress));

Failing on 9.02Beta but passing the validation with the same code on 9.0.

**Comment by TYLEROL** [comment]
Thanks for raising this issue @kamranRehman. One quick item of clarification - is the only different in your testing the branches of EasyRepro code? Testing against the same Dynamics organization?

We'll start taking a look and look forward to hearing back from you.

Regards,
Tyler

**Comment by kamranRehman** [comment]
Yes I'm using the same EASYREPRO code in the same Dynamics Organization.....

**Comment by TYLEROL** [comment]
Hello @kamranRehman - This isn't checked in officially yet, but in the linked PR we've made some changes to improve CompositeControl SetValue, GetValue, and new ClearValue methods.

I've included a new example test, shown below, in the Sample project Web\Entity.cs file.

```
        public void WEBTestSetGetClearCompositeValues()
        {
            XrmTestBrowser.CommandBar.ClickCommand("New");

            List<Field> fields = new List<Field>
                {
                    new Field() {Id = "firstname", Value = "EasyRepro"},
                    new Field() {Id = "lastname", Value = "Entity Test"}
                };

            XrmTestBrowser.Entity.SetValue(new CompositeControl { Id = "fullname", Fields = fields}); //Composite Field
            var fullNameValue = XrmTestBrowser.Entity.GetValue(new CompositeControl { Id = "fullname", Fields = fields }).Value; //Composite Field
            var fullNameTest = string.Join(" ", fields.Select(x => x.Value).ToArray());
            Assert.IsTrue(fullNameValue.Equals(fullNameTest));
            
            // The code below is an example of using ClearValue on a CompositeControl 
            // In this example, one of the fields is required and as a result we cannot clear the composite field.
            // Throw exception on the test to alert this issue

            // XrmTestBrowser.Entity.ClearValue(new CompositeControl { Id = "fullname", Fields = fields }); //Composite Required Field Example --> EXCEPTION

            XrmTestBrowser.ThinkTime(5000);
        }
```

The output from the GetValue<CompositeControl> will return a concatenated list of  strings, using " " as a separator.

I've included a working sample above, for how you could accomplish this with your address list once we publish a new Master branch. We're hoping to make this new branch available later next week.

Please let me know if you have any questions about this.

Regards,
Tyler

**Comment by TYLEROL** [comment]
This has been added to the latest releases/v9.1 branch. Please let us know if you have any issues using the implementation.
