### ISSUE TITLE
Clear data from field

### ISSUE THREAD

**Issue by PallaviSrivastava05** [Microsoft/EasyRepro#247]
How to clear data from the field?

**Comment by TYLEROL** [comment]
@PallaviSrivastava05 - We are missing an API to clear values currently.

This was added to our backlog, however we're currently working on support for v9.1 of Dynamics 365. I'll discuss with my colleagues on whether we can update the APIs to include a a ClearValue() API for both the legacy web client and new unified interface. I don't anticipate this being too much extra work, but need to verify that we can fit this in. The v9.1 work should be done in the next ~3 weeks. We'll update here to confirm if the new API is available at that time.

Best Regards,
Tyler

**Comment by PallaviSrivastava05** [comment]
@TYLEROL 
I have found a solution for the same.
I am using sendkeys and then select all and clear after finding the web element using an instance of Selenium Webdriver.

**Comment by TYLEROL** [comment]
@PallaviSrivastava05 - We've added ClearValue methods to the latest releases/v9.1 that should allow you to clear a field value for various field types in the system. Please let us know if you have any issues in using this implementation.
