### ISSUE TITLE
OpenSubArea("Project Service","Customers") not working in UCI

### ISSUE THREAD

**Issue by triciasinclair** [Microsoft/EasyRepro#252]
Ive been able to open the Project Service App but trying to open the customers area produces the error "Object reference not set to an instance of an object.". It cannot seem to locate the area "Project Service". Using in the CRM Hub works though. Is this an issue or is the syntax (  xrmApp.Navigation.OpenSubArea("msdyn_ProjectServiceArea", "Customers");) for this incorrect.

**Comment by TYLEROL** [comment]
Hi @triciasinclair,

The expected syntax here would be to supply the display names for the areas you wish to select. If the name of your parent area is '**Project Service**', and you're trying to access an entity named **'Customers**' that is visible, then the following should be the correct syntax.

`xrmApp.Navigation.OpenSubArea("Project Service", "Customers");`

It looks like you may have tried this, but the syntax between your title and post is different. Could you confirm that, as well as the version of your Dynamics 365 organization?

Best Regards,
Tyler

**Comment by kamranRehman** [comment]
Hi Tyler,

I've been facing the same issue while accessing one of custom entity.

Following is code I've been using, I'm on BETA 9.02 version.

  {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, client.ADFSLoginAction);
                xrmApp.ThinkTime(20000);
         
                xrmApp.Navigation.OpenApp("UCI");
                xrmApp.ThinkTime(100000);
                xrmApp.Navigation.OpenSubArea("Area Name", "Subarea name");
                xrmApp.ThinkTime(10000);
                xrmApp.Grid.SwitchView("Patients");
                xrmApp.ThinkTime(10000);
                xrmApp.CommandBar.ClickCommand("NEW");
                xrmApp.ThinkTime(5000);
                xrmApp.Entity.SetValue("firstname", patientFirstName);
                xrmApp.Entity.SetValue("middlename", patientMiddleName);
                xrmApp.Entity.SetValue("lastname", patientLastName);
                xrmApp.ThinkTime(5000);
            }
        }

Following is the exception I'm getting.
Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.XXXX.PatientCRUDUnifiedView.TstABC  threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/45043140/48711874-23519500-ec2e-11e8-9ef5-a601ef6ee55c.png)


Thanks.
-Kamran.

**Comment by triciasinclair** [comment]
> Hi @triciasinclair,
> 
> The expected syntax here would be to supply the display names for the areas you wish to select. If the name of your Unified Interface app is '**Project Service**', and you're trying to access an entity named **'Customers**' that is visible, then the following should be the correct syntax.
> 
> `xrmApp.Navigation.OpenSubArea("Project Service", "Customers");`
> 
> It looks like you may have tried this, but the syntax between your title and post is different. Could you confirm that, as well as the version of your Dynamics 365 organization?
> 
> Best Regards,
> Tyler

Hi Tyler,

Yes. I've tried this. However, it doesnt work. I found if I add an additional area that it will work. This means there is a defect which can be replicated by trying to open a sub area in an app with one area. The opensubarea method will not be able to find the area.

**Comment by TYLEROL** [comment]
I'll try to see how quickly we can get a fix out for this, but it looks like this may have broke in the latest 9.1 update for Dynamics 365.

@triciasinclair and @kamranRehman - Can you confirm that your Dynamics organizations are running on version 9.1 as well?

Thanks,
Tyler

**Comment by kamranRehman** [comment]
Hi Tyler,

Yes, the organization is running on 9.1.

Thanks.
-Kamran.

**Comment by kamranRehman** [comment]
Hi Tyler,

Wondering, did you get a chance to look into this and how long do you think you guys would be able to provide this fix for this issue?

Thanks.
-Kamran.

**Comment by TYLEROL** [comment]
@kamranRehman and @triciasinclair - Thank you both for your patience on this.

I've submit a PR for a fix to the existing behavior. I am still reviewing with colleagues internally however on whether to simply restore the existing functionality, or whether we should adjust the design to handle scenarios in which the Sitemap contains multiple references to a single entity (e.g. Accounts under both Customers and My Work groups in the sitemap).

I suspect we'll approve to unblock, and then add a feature backlog item to add support for sitemaps that contain multiple references to the same display name. This behavior with multiple sitemap references would have been broken in prior design.

**In the meantime, if you'd like to test my fix, you can pull down the [dev/tylerol/UCI_Issue252](https://github.com/Microsoft/EasyRepro/tree/dev/tylerol/UCI_Issue252) branch. This should restore original functionality from v9.0.2, however please note that the test will fail if the sitemap via the app contains multiple references to the same entity.**

Best regards,
Tyler

**Comment by TYLEROL** [comment]
@triciasinclair and @kamranRehman - We've merged a fix into the beta/v9.0.2 branch for this issue.

Please let us know if you encounter any further issues. In scenarios where duplicate sitemap sub-areas are present, we only add the first item to the collection and will click that (e.g. so if Contacts exists under both Sales and Service and the Sales header came first, that's the Contact entity element that would be clicked).

Best Regards,
Tyler

**Comment by kamranRehman** [comment]
Hi Tyler,

Thanks for providing the fix, i will check and will get back to you in case of any questions and or queries.

Thanks.
-Kamran.

**Comment by triciasinclair** [comment]
Thanks Tyler! I’ll have a look and let you know as well.
