### ISSUE TITLE
Stay Signed In Dialog is not clicked in Firefox during Login

### ISSUE THREAD

**Issue by TYLEROL** [Microsoft/EasyRepro#253]
Good Day.

I'm facing the same issue "System.InvalidOperationException: unknown error: Xrm is not defined" but in a different browser-Firefox.
I'm getting this error once after the username and password is entered automatically it gets stuck in the Stay Sign In dialog and it is not redirected to the CRM home page. 

![firefox page](https://user-images.githubusercontent.com/45093818/48620039-8fc95b80-e9c4-11e8-9004-697a96d1eb12.PNG)
![xrm is not defined](https://user-images.githubusercontent.com/45093818/48620040-9061f200-e9c4-11e8-8cd4-b95812233e67.PNG)

I tried with your fix code but after that I'm getting-"System.NullReferenceException: Object reference not set to an instance of an object. And this time it gets stuck in the password page itself by not entering the password

Firefox version - 63.0.3 (64 bit)
geckodriver - v0.23.0-win64

Hope you can help me to resolve this issue.Thank You

Regards,
Sindhuja

_Originally posted by @SindhujaElangovan in https://github.com/Microsoft/EasyRepro/issues/187#issuecomment-439373254_

**Comment by TYLEROL** [comment]
@SindhujaElangovan - I've added a small change to the default login method to try and mitigate this issue for you in the Firefox browser.

Please pull down the latest changes for the beta/v9.0.2 branch and let me know if you still have issues with the Stay Signed In dialog not being clicked.

Best Regards,
Tyler

**Comment by SindhujaElangovan** [comment]
@TYLEROL - Thank You for the update.

Will let you know once after checking the beta/v9.0.2.

**Comment by TYLEROL** [comment]
@SindhujaElangovan - Were you able to test out the latest change in the beta/v9.0.2 branch to see if this resolved your issue?

Thanks,
Tyler

**Comment by TYLEROL** [comment]
@SindhujaElangovan - I am going to mark this as resolved for now. We are using similar automation internally with the Firefox browser and currently have not faced this issue.

If you still encounter problems, please re-open this issue and let us know.

Best Regards,
Tyler

**Comment by SindhujaElangovan** [comment]
@TYLEROL 
Sorry for the delay in response, was busy.

Could you please guide me how to pull the latest changes for the beta/v9.0.2 branch.

**Comment by TYLEROL** [comment]
@SindhujaElangovan - You can do this in the UI from Visual Studio Team Explorer. In Team Explorer, select Branches, and then double-click the beta/v9.0.2 branch in your list to check it out (it should show as your active branch in the lower right of the Visual Studio footer):

![image](https://user-images.githubusercontent.com/29415524/50126977-cc42de00-0234-11e9-89bd-3ae07dd738c8.png)

![image](https://user-images.githubusercontent.com/29415524/50127076-2a6fc100-0235-11e9-8cbe-b91438e3dae6.png)

Once you've confirmed that you're active on the beta/v9.0.2 branch, you can pull the latest changes. Right-click on the branch in the list and select 'Pull':

![image](https://user-images.githubusercontent.com/29415524/50127104-4e330700-0235-11e9-8a1e-fefd55c53c47.png)

This will pull down the latest changes from the repo and sync them with your local branch.

Please let me know if you have any issues.

Thanks,
Tyler
