### ISSUE TITLE
Reporting capability

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#255]
Hello Team,
Do we have any reporting capability in EasyRepro like:

When systems toggle between controls  - need to trace them in excel
When test is executed need to save the executed test results in excel.

I tried with EPPlus :https://github.com/JanKallman/EPPlus
But the test scenario fails without any errors

**Comment by spasupuleti27** [comment]
I have tried generating HTML Report and it working by installing few package  (N Unit, N Unit Cosole.) and including the configuration in OneTime Setup, Afterclass and TearDown
Below is the sample example:

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Dynamics365.UIAutomation.Api;
using Microsoft.Dynamics365.UIAutomation.Browser;
using System;
using System.Collections.Generic;
using System.Security;
using OpenQA.Selenium;
using NUnit.Framework;
using RelevantCodes.ExtentReports;
using NUnit.Framework.Interfaces;
using System.Diagnostics;

namespace Microsoft.Dynamics365.UIAutomation.Sample.Web.Banking_Automation
{
    [TestClass]
    public class CreateContact
    {
        private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());
        public static ExtentReports extent;
        public static ExtentTest test;

        [OneTimeSetUp]
        public void StartReport()
        {
            string path = System.Reflection.Assembly.GetCallingAssembly().CodeBase;
            string actualPath = path.Substring(0, path.LastIndexOf("bin"));
            string projectPath = new Uri(actualPath).LocalPath;
            string reportPath = projectPath + "Reports\\ContactValidation.html";

            extent = new ExtentReports(reportPath, true);
            extent
             .AddSystemInfo("Host Name", "Sudha")
            .AddSystemInfo("Environment", "HSBanking")
            .AddSystemInfo("User Name", "Sri Sudha Pasupuleti")
            .AddSystemInfo("Test Name", "Contact Validation")
            .LoadConfig(projectPath + "extent-config.xml");
        }

        [TearDown]

        public void AfterClass()

        {

            //StackTrace details for failed Testcases

            var status = NUnit.Framework.TestContext.CurrentContext.Result.Outcome.Status;
            var stackTrace = "" + NUnit.Framework.TestContext.CurrentContext.Result.StackTrace + "";
            var errorMessage = NUnit.Framework.TestContext.CurrentContext.Result.Message;
            if (status == TestStatus.Failed)
            {
                test.Log(LogStatus.Fail, stackTrace + errorMessage);
            }
            else
            {
                test.Log(LogStatus.Pass, "Automation of this Contact entity is successful");
            }

       
            //End test report
            extent.EndTest(test);
        }


        [OneTimeTearDown]
        public void EndReport()

        {
            //End Report
            extent.Flush();
            extent.Close();
            //Kill the browser Process

            //Kill the command process
            foreach (Process p in Process.GetProcesses())
            {
                if (p.ProcessName == "cmd")
                {
                    p.Kill();
                }
            }

        }


        [Test]

        public void  <MethodName>()
{
/* Add the code as per ur requirement
}

**Comment by SachchinAnnam** [comment]
@spasupuleti27 : which version of ExtentReports you've used in your solution. While trying your code it throw below errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1729	'ExtentReports' does not contain a constructor that takes 1 arguments	Microsoft.Dynamics365.UIAutomation.Sample	C:\EasyRepro-releases-v9.0_ExtentReport\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateContact.cs	55	Active


Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'LogStatus' does not exist in the current context	Microsoft.Dynamics365.UIAutomation.Sample	C:\EasyRepro-releases-v9.0_ExtentReport\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateContact.cs	76	Active


Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ExtentReports' does not contain a definition for 'EndTest' and no extension method 'EndTest' accepting a first argument of type 'ExtentReports' could be found (are you missing a using directive or an assembly reference?)	Microsoft.Dynamics365.UIAutomation.Sample	C:\EasyRepro-releases-v9.0_ExtentReport\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateContact.cs	85	Active

**Comment by spasupuleti27** [comment]
@SachinAnnam, version that we used for Extent report is 2.41.0.
try to import all these package if relevant to ur code and they try:
![image](https://user-images.githubusercontent.com/42530506/49921369-59073800-fed3-11e8-81c6-a500312d782e.png)

**Comment by jlattimer** [comment]
I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.
