### ISSUE TITLE
Dynamics CRM V9 UCI Automation

### ISSUE THREAD

**Issue by nehagupta08** [Microsoft/EasyRepro#257]
Does Github support UCI automation as well, if yes please let me know how i can get it working. I am currently working on Dynamics CRM version 9.1.0.643 on,ine

**Comment by TYLEROL** [comment]
Hello @nehagupta08 - We do support UCI automation. The core APIs for UCI are in the Microsoft.Dynamics365.UIAutomation.Api.UCI project of the **beta/v9.0.2** branch.

There is an active issue #252 currently open that may present some problems with initial navigation that started occurring in the v9.1 update. We're working on getting that fixed and will post an update as soon as we can.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
@nehagupta08 - The issue from #252 has been resolved.

Have you been able to test out the Unified Interface, or do you have any specific questions about how to use it? You'll want to make sure you're using the beta/v9.0.2 branch of EasyRepro as that contains the additional project to support UCI automation.

Regards,
Tyler
