### ISSUE TITLE
In Browser.cs bug with internal constructor

### ISSUE THREAD

**Issue by Testirovishik** [Microsoft/EasyRepro#261]
I need to use driver constructor to run tests with Selenium Grid.

This is a workaround I am doing using reflection

```
public void CreateCRMDriver()
{
Browser browser = CreateInstance<Browser>(new RemoteWebDriver(options));
}

        public static T CreateInstance<T>(params object[] args)
        {
            var type = typeof(T);
            var instance = type.Assembly.CreateInstance(
                type.FullName, false,
                BindingFlags.Instance | BindingFlags.NonPublic,
                null, args, null, null);
            return (T)instance;
        }
```

but should be simply doing this with a public constructor:

```
public void CreateCRMDriver()
{
Browser browser = new Browser(new RemoteWebDriver(options));
}
```

**Comment by TYLEROL** [comment]
Thanks for raising this @Testirovishik. We'll review this scenario and provide an update as soon as we can.

Best Regards,
Tyler

**Comment by Testirovishik** [comment]
Awesome! Thank you for quick reply!

**Comment by TYLEROL** [comment]
Hello @Testirovishik - We're currently working on changes for version 9.1 support for both WebClient and Unified Interface. We don't have an ETA for when we can get this change added in as of yet.

It may be quicker if you're able to put a change together and submit a PR. We could quickly review that and merge it with the appropriate branch.

If not, we'll try to get to this as soon as we can.

Warm Regards,
Tyler

**Comment by jlattimer** [comment]
RemoteWebDriver support was added in PR #493
