### ISSUE TITLE
How to clear a value in 'search field' in a grid 

### ISSUE THREAD

**Issue by spasupuleti27** [Microsoft/EasyRepro#264]
I am trying to clear a value in the search field in a grid. can please help me out on this.
trying on D365
![image](https://user-images.githubusercontent.com/42530506/49501286-81ba7c80-f898-11e8-8592-a58e3bff5099.png)

**Comment by TYLEROL** [comment]
Hello @spasupuleti27 - Are you looking for just a simple method to remove the text? Or something in which you want to clear and enter a new search term?

I thought we had this functionality, but it looks like it was restricted to Lookups. I'll try to get the above scenarios added for Grid searching as well for both WebClient and UCI.

If you have a scenario outside of the two I described above, please let me know and I'll try to make sure it's covered in the fix.

Thanks,
Tyler

**Comment by spasupuleti27** [comment]
Hi @TYLEROL , thanks for quick response.
I would like to clear the existing item and search for the new item in the "Search field" in grid.
For time being I am refreshing the form and entering the new search. But, it will be good if i could get a better solution/fix so that i can reduce the time of execution.

**Comment by spasupuleti27** [comment]
Hi @TYLEROL, can i know when can i expect the solution for the enhancement?

**Comment by TYLEROL** [comment]
Hello @spasupuleti27 - My apologies for the delay in getting to this one. After getting a chance to look at this today, the enhancement was a bit easier than anticipated.

The beta/v9.0.2 branch has been updated for both the WebClient and Unified Interface.

By default, the Grid.Search("search criteria") method will clear the search box for both WebClient and Unified Interface scenarios.

I've also created a new method, Grid.ClearSearch(). This method will simply clear the search box of any text.

Please let us know if you encounter any problems with these changes by re-opening this issue.

Best Regards,
Tyler
