### ISSUE TITLE
How to configure CICD on VSTS for Easyrepro 

### ISSUE THREAD

**Issue by rselva22** [Microsoft/EasyRepro#275]
I have created scripts for Dynamic 365 using Easyrepro and now I want it to trigger the scripts from VSTS on daily basis.

**Comment by rselva22** [comment]
I want to run my UI scripts daily using VSTS. So can any one please suggest me suitable way to do it ijn VSTS

**Comment by bwmodular** [comment]
Do you already have an automated CI process using VSTS, which you would like to add these tests to, or are you starting from scratch?
If you are starting from scratch, then this article details how to set up a VM to run tests automatically: https://blogs.msdn.microsoft.com/testingspot/2017/07/26/run-your-independent-automated-tests-using-vnext-build-in-visual-studio-online/

Your release pipeline can be configured to run automatically after each build, or on a schedule, so you should just be able to add a 'Run Visual Studio Tests' task in your release definition, tell it which dll your tests are contained in and which runsettings file to use if appropriate.

Hope this is of some help...

**Comment by rselva22** [comment]
Thanks for the Reply. As of now I dont have Azure environment. So I want to know how to trigger the scripts in our local VCloud from VSTS.

**Comment by bwmodular** [comment]
I think that Microsoft are now offering at least one free pipeline, so you may not even need to have an Azure environment to get things going:
https://azure.microsoft.com/en-gb/services/devops/pipelines/

However, if you do want to run the process locally, the steps are going to be something like this:
1.) Install the vsts agent on the machine that you are using as your build / release server
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts

2.) Create a Build definition, triggered on check in of the solution which contains your tests
This should perform a build, and then publish any artefacts needed by the tests (such as the built dll containing the tests, and possibly one or more runsettings files)

3.) Create a release pipeline, which can either be triggered by the build, or can be scheduled to run periodically.
To run the tests you can use the 'Visual Studio Test' task, pointing at the dll which was published by the build.
If you want to run the tests against different environments, or with different browsers, or in some other way you want to parameterise your tests, I'd reccomend using a 'runsettings' file - this allows you to run the same set of tests multiple times, each with a different set of parameters. You can chose the runsettings file when running the tests locally in Visual studio, or you can specify the runsettings file in your release task setup and have multiple tasks, one for each runsetting file that you want to use.

I think that this is probably the best place for you to get started:
https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/index?view=vsts
It explains build definitions, release pipelines, etc.

**Comment by jlattimer** [comment]
Documentation has been added to the wiki for this: [https://github.com/Microsoft/EasyRepro/wiki/Azure-DevOps-Test-Execution](https://github.com/Microsoft/EasyRepro/wiki/Azure-DevOps-Test-Execution)

I've also written a [blog post](https://jlattimer.blogspot.com/2019/03/run-your-automated-d365-ce-ui-tests_15.html) on it
