### ISSUE TITLE
Does EasyRepro supports Automation for New UI?

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#276]
Hello @TYLEROL ,
We've upgraded our CRM instance to New UI and in regards to UI automation, please help me to know whether easy repro supports New UI or not?

**Comment by TYLEROL** [comment]
Hello @SachinAnnam 

In terms of the Unified Interface, we released support for that in the beta/v9.0.2 branch. The new Unified Interface APIs are part of the Microsoft.Dynamics365.UIAutomation.Api.UCI project. There are also samples for the Unified Interface via the Samples project UCI folder.

I also want to note that we are still working on full support for both the legacy web client and the unified interface for the v9.1 Dynamics 365 code base. This is currently being handled via the beta/v9.x branch, with some changes being ported into the beta/v9.0.2 branch to unblock other scenarios that may have changed or no longer work as expected.

If you encounter issues, or missing features, please let us know via additional GitHub issues and we'll work to tackle them accordingly.

Best Regards,
Tyler

**Comment by HIREN-AITC** [comment]
@TYLEROL Is this release yet or any probable date when will it be released as full version? And how can I download beta version from NuGet?
