### ISSUE TITLE
How to search for lookup for UCI automation(using v9.0.2)

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#278]
Hello @TYLEROL ,
Am using branch v9.0.2 for New UI automation, could you please help how to search for lookup items.
There are field like Country and Preferred language in the form which are of look up fields.

**Comment by TYLEROL** [comment]
Hi @SachinAnnam,

For the Unified Interface, we currently support setting values for Lookups, however some features are not yet available compared to the legacy web client.

`xrmApp.Entity.SetValue({Name="lookfieldname", Value="LookupValue"});`

For other functionality, like interacting with the Lookup Page in the Unified Interface, we hope to include in a future update to support the v9.1 release of Dynamics. We don't have an ETA for this yet, however it shouldn't be too far off.

Best Regards,
Tyler

**Comment by ggeiszle** [comment]
Hey @SachinAnnam - thanks for bringing this issue to our attention.  We have added support for LookupItems in UCI in the 9.1 branch. If you continue to see issues with it, please let us know and we will do our best to address them.

**Comment by SachchinAnnam** [comment]
Hello @ggeiszle  and @TYLEROL 
I tried below snippet for lookup but it didn't worked:
xrmApp.Entity.SetValue({ Name = "language", Value = "English"});
Even SelectLookup isn't helping.
xrmApp.Entity.SelectLookup("language");

Please help with some options.
