### ISSUE TITLE
UCI - Clicking on related Menu 

### ISSUE THREAD

**Issue by watsonthecat** [Microsoft/EasyRepro#279]
Using _xrmapp.Entity.SelectTab("Related","Alert") to get associated Alerts to this Account (Shown at 1-2)

This opens/shows alerts related to this Account and from here, I want to click the Add New Alert button (Shown in Second Image at 3). 

Doesn't seem like existing Navigation/CommandBar/Entity have controls for this - am I missing something or is this still in development?

![image](https://user-images.githubusercontent.com/31329210/50565751-af5bdf80-0cf7-11e9-94d0-92959c44583f.png)
![image](https://user-images.githubusercontent.com/31329210/50565755-b84cb100-0cf7-11e9-8d2d-af183e8757a2.png)

**Comment by watsonthecat** [comment]
I tried _xrmapp.CommandBar.ClickCommand("Add New Alert") and that didn't work

**Comment by TYLEROL** [comment]
Thanks for raising this issue @watsonthecat. You are correct in your findings, these items are in the backlog for development as part of our work to support the latest v9.1 release of Dynamics 365 and to bring parity between legacy web client capabilities and the new Unified Interface.

I don't have an ETA to provide at this time, but I'll update again as soon as I have more information to share.

Best Regards,
Tyler

**Comment by watsonthecat** [comment]
@TYLEROL I didn't see this added in v9.1 - has this been added?

**Comment by TYLEROL** [comment]
Hey @watsonthecat - Apologies for not circling back on this one. My colleague did most of the UCI work, and after cross-checking, this should be in though I haven't been able to validate it myself.

The first step would be to utilize **Entity.SelectTab("Related", "{subTabName}")** from the entity form. After this, you can then use the **RelatedGrid.ClickCommand("CommandName", "{optionalSubCommandName}")** method to use the inner command bar that shows up for the in-line related grid.

If you have issues with those methods not accessing the Related tab sub-tree, and the Related command bar, please let us know.

Best Regards,
Tyler

**Comment by watsonthecat** [comment]
@TYLEROL - getting exception with the RelatedGrid.ClickCommand, could you tell me if I'm doing something wrong here?

Steps:
_xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
_xrmApp.Navigation.OpenApp("Canada FTC/ISI");
_xrmApp.Navigation.OpenSubArea(area, subarea);
_xrmApp.CommandBar.ClickCommand("New");
_xrmApp.Entity.SetValue("name", "Test Account Automated");
_xrmApp.CommandBar.ClickCommand("Save");
//Navigate to KYC Account Tab and click button
_xrmApp.Entity.SelectTab("KYC Accounts");
​_xrmApp.RelatedGrid.ClickCommand("Add New KYC Account"); **//Test Fails at this step**

Exception: 
OpenQA.Selenium.NotFoundException: Add New KYC Account button not found. Button names are case sensitive. Please check for proper casing of button name.

Screenshots:
![image](https://user-images.githubusercontent.com/31329210/55506267-9c201f00-561a-11e9-8de8-bc42c9b3ebc4.png)

![image](https://user-images.githubusercontent.com/31329210/55506258-9591a780-561a-11e9-986f-4f2d428c2199.png)
![image](https://user-images.githubusercontent.com/31329210/55506262-99252e80-561a-11e9-85e5-a9aaaff5e4b3.png)




StackTrace:
```
Result StackTrace: 
at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass53_0.<ClickRelatedCommand>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.ClickRelatedCommand(String name, String subName)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.RelatedGrid.ClickCommand(String name, String subName)
   at Canada_EasyRepro_Iteration.Tests.Steps.XrmAppSteps.WhenIClickRelatedGridButton(String p0) in C:\Users\jplemel\source\repos\Canada_EasyRepro_Iteration.Tests\Canada_EasyRepro_Iteration.Tests\Steps\XrmAppSteps.cs:line 214
   at Canada_EasyRepro_Iteration.Tests.Tests.AccountTest.Account_AssociateKYCAccount() in C:\Users\jplemel\source\repos\Canada_EasyRepro_Iteration.Tests\Canada_EasyRepro_Iteration.Tests\Tests\AccountTest.cs:line 35
Result Message: 
Test method Canada_EasyRepro_Iteration.Tests.Tests.AccountTest.Account_AssociateKYCAccount threw exception: 
OpenQA.Selenium.NotFoundException: Add New KYC Account button not found. Button names are case sensitive. Please check for proper casing of button name.
```

**Comment by rcjohnson113** [comment]
There isn't a method for clicking sub-grid commands that are on the form. I created one:

XrmApp.Entity.ClickCommandOnSubGrid("Account KYC Records", "Add New KYC Account");


Microsoft.Dynamics365.UIAutomation.Api.UCI class add methods:

```
public void ClickCommandOnSubGrid(string subgridName, string subgridButtonName)
        {
            _client.ClickCommandOnSubGrid(subgridName, subgridButtonName);
        }
```

```
internal BrowserCommandResult<bool> ClickCommandOnSubGrid(string subgridName, string subgridButtonName)
        {
            return Execute(GetOptions($"Select Subgrid {subgridName} button {subgridButtonName}"), driver =>
            {
                IWebElement parentElement;
                if (driver.HasElement(By.XPath($"//div[text() = '{subgridName}']")))
                {
                    IWebElement divElement = driver.FindElement(By.XPath($"//div[text() = '{subgridName}']"));
                    parentElement = divElement.FindElement(By.XPath("parent::*"));

                }
                else if (driver.HasElement(By.XPath($"//section[@aria-label='{subgridName}']")))
                {
                    parentElement = driver.FindElement(By.XPath($"//section[@aria-label='{subgridName}']"));
                }
                else
                {
                    throw new NotFoundException($"Subgrid {subgridName} not found on form.");
                }
                var items = parentElement.FindElements(By.TagName("li"));

                //Is the button in the ribbon?
                if (items.Any(x => x.GetAttribute("aria-label").Equals(subgridButtonName, StringComparison.OrdinalIgnoreCase)))
                {
                    items.FirstOrDefault(x => x.GetAttribute("aria-label").Equals(subgridButtonName, StringComparison.OrdinalIgnoreCase)).Click(true);
                    driver.WaitForTransaction();
                }
                return true;
            });
        }
```

Also there isn't a way to select the record in a sub grid that is on the form. You have to create something similar to achieve this operation.

**Comment by remyanambala** [comment]
Hi,

I faced same issue with an Add button and on debugging found that the Xpath in App reference is different to what is in page. It worked for me after changing xpath slightly - removed the "Associated " text from search.

code:
 xrmApp.RelatedGrid.ClickCommand("Add");


AppElementReference.cs
change below line:
{ "Related_CommandBarButton", "//button[contains(., '[NAME]') and contains(@data-id,'SubGridAssociated')]"},
to:
{ "Related_CommandBarButton", "//button[contains(., '[NAME]') and contains(@data-id,'SubGrid')]"},

I am not sure whether  above will affect some other tests, so I added code to directly access the element instead. Please find below the code:
IWebElement elementAdd = client.Browser.Driver.FindElement(OpenQA.Selenium.By.XPath("//button[@aria-label='Add']"));
                elementAdd.Click();

Hope this helps.

Regards
Remya

**Comment by Haywaii** [comment]
@TYLEROL does this one is supposed to be merge on master for a later release?
