### ISSUE TITLE
Get no of records on a sub grid

### ISSUE THREAD

**Issue by hasinthanagodavithana** [Microsoft/EasyRepro#280]
Hi, 

I need to get the record count of a sub grid on entity form.  I can't find any method available for this purpose.  I tried this with using xpath and did not have much success yet. Can you help me on this?

Regards,
Hasi

**Comment by hmatsuoka** [comment]
You can use web resources and using Web API in it. Following blog may be useful for you.
https://hihaj.com/retrieve-the-accurate-total-count-of-entities-via-dynamics-crm-web-api-6e777fae650d

**Comment by hasinthanagodavithana** [comment]
Hi, 
I found a workaround for this. By using findEvelemt method you can get the number of records available on the current sub-grid view 1st page. However, it will rerun only the no of record visible in the 1st page (Max up to 10) of the sub-grid.  In my case I just wanted to see whether sub grid has only one record. So For my scenario, this works fine. 


var  dataTable = xrmBrowser.Driver.FindElement(By.Id("{subgridName}_divDataArea"));
var recordList = dataTable.FindElements(By.ClassName("ms-crm-List-Data"));
if (recordList.Count != 1)

**Comment by TYLEROL** [comment]
Thanks for raising this @hasinthanagodavithana. I've added this to our backlog. 

We're currently working on a new master branch that will support the latest v9.1 update for both the legacy Web Client and new Unified Interface. This should be available in the next three weeks.

We'll try to get a new API added in to support getting the number of records on the subgrid. At a minimum it should return whatever records are displayed in the first page of the grid - and we'll see what we can do to get full page support on the grid as well.

Best Regards,
Tyler
