### ISSUE TITLE
Easy Repro integration with VSTS

### ISSUE THREAD

**Issue by krishnacs1993** [Microsoft/EasyRepro#281]
I am exploring the Easy Repro framework for Dynamics 365 CRM Automation. 
Can anybody confirm if it is possible to integrate Easy Repro with VSTS and steps to do it.

**Comment by bwmodular** [comment]
@krishnacs1993 Running EasyRepro tests as part of your VSTS CI process is really no different from running any other sort of test in VSTS. Configure a 'Visual Studio Test' task in your build or release pipeline which picks up your tests. You'll need the right browser to be installed on the machine on which the tests are running.
Issue #275 has some ideas to get you going in the right direction...

**Comment by krishnacs1993** [comment]
@bwmodular Thank you so much.

**Comment by jlattimer** [comment]
Documentation has been added to the wiki for this: [https://github.com/Microsoft/EasyRepro/wiki/Azure-DevOps-Test-Execution](https://github.com/Microsoft/EasyRepro/wiki/Azure-DevOps-Test-Execution)

I've also written a [blog post](https://jlattimer.blogspot.com/2019/03/run-your-automated-d365-ce-ui-tests_15.html) on it

**Comment by jlattimer** [comment]
Closing
