### ISSUE TITLE
Data Driven Testing with Easy Repro

### ISSUE THREAD

**Issue by krishnacs1993** [Microsoft/EasyRepro#284]
Hi There,

Is it possible to have **data driven testing(Pass test data from Excel)** with Easy Repro framework instead of hard coding the data in the code?

Thanks in advance.

**Comment by bwmodular** [comment]
Hi @krishnacs1993,
this isn't really a question about EasyRepro, more about data driven testing in general. If you know how to acheive data driven testing, then you can apply the same methods to any tests, whether they are EasyRepro tests or any others.
There are two main ways to do data driven testing in c#. The first, lite, version can be done in most test frameworks. For example, MSTest v2 supports Data Driven tests which are written in this format:
```
[TestClass]
public class MathTests
{
    [DataTestMethod]
    [DataRow(1, 1, 2)]
    [DataRow(12, 30, 42)]
    [DataRow(14, 1, 15)]
    public void Test_Add(int a, int b, int expected)
    {
        var actual = MathHelper.Add(a, b);
        Assert.AreEqual(expected, actual);
    }
}
```

When you execute this test, it will actually run the test three times with the different parameters, and will display the results as three different tests in your test runner. You could use this to pass different values to your test. Here's more info on this: https://blogs.msmvps.com/bsonnino/2017/03/18/parametrized-tests-with-ms-test/ 

The other commonly used test frameworks (NUnit, XUnit) have similar ways of doing this.

The second, more complex, method is the one I'd recommend for anything other than the simplest type of parameterisation. This is using a BDD tool like SpecFlow. Specflow integrates Visual Studio and allows you to write your tests in the following format:
```
Feature: Calculator
       In order to avoid silly mistakes
       As a math idiot
       I want to be told the sum of two numbers

Scenario: Add two numbers
       Given I have entered 50 into the calculator
       And I have also entered 70 into the calculator
       When I press add
       Then the result should be 120 on the screen
```   
The values in the scenario are treated as parameters, so you can have multiple scenarios which all have different parameters and the test runner will pass the parameters in to the test. 
The advantage of using SpecFlow is that you define your 'scenarios' in human readable form, which means that they are not only easy for you to read, but can also be validated (or even created) by end users or business analysts. They can also be more complex than data driven tests - for example, you can pass in tables of data as parameters. Lots of good tutorials online, but the place to get started is this:
https://specflow.org/getting-started/#AddingFeature	   

I'd also recommend most of the tutorials on the Execute Automation YouTube channel. He has quite a few on SpecFlow:
https://www.youtube.com/channel/UCO1aucBAJgFR8odzfXOZ5uw/search?query=specflow 

I hope this is helpful. There _are_ ways of driving tests from Excel also - but I'd recommend either of the above as good ways of achieving the same thing.

**Comment by jordimontana82** [comment]
+1 

Re excel, I don't personally like using external data sources (like Excel) in unit tests, they can become quickly out of date and disconnected from the unit tests when the data model changes and it essentially can become a pain to maintain.  And there's no possibility to refactor either :)

**Comment by krishnacs1993** [comment]
Thank You @bwmodular
