### ISSUE TITLE
SetValue method does not work for Datetime fields

### ISSUE THREAD

**Issue by hasinthanagodavithana** [Microsoft/EasyRepro#287]
SetValue method does not work for Date-time fields

I am trying to update the start time of activity entity which is a date time field. I tried the SetValue method but it doesn't update the field correctly. It just clear off the field existing value.  Can you please help me on this?

Regards,
Hasi

**Comment by TYLEROL** [comment]
Thanks for raising this issue @hasinthanagodavithana. 

As mentioned on another issue - we're currently working on a new master branch to support the latest v9.1 update for Dynamics 365. I've added this issue to our work log and will do our best to include a fix within that branch.

If you could, please let us know if this is occurirng for your tests in the Unified Interface, or the legacy web client, as well as the version of Dynamics you are using.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
This has been fixed in the latest releases/v9.1 branch. If you have any further issues, please let us know.

**Comment by kavitham1985** [comment]
Can this be created for UCI too. Adding Datetime value in UCI throws error. @jlattimer @TYLEROL

**Comment by kavitham1985** [comment]
It was working until last week, now it gives a blank page when I use 
xrmApp.Entity.SetValue("test_evaldate", DateTime.Today.ToShortDateString());

**Comment by jlattimer** [comment]
@kavitham1985 - can you raise a new issue for this?

**Comment by kavitham1985** [comment]
Created an issue https://github.com/microsoft/EasyRepro/issues/523 @jlattimer
