### ISSUE TITLE
beta / 9.0.2 – Unified Interface : compatibility with the new sitemap

### ISSUE THREAD

**Issue by NicolasPrats** [Microsoft/EasyRepro#290]
Hello,

The method `Microsoft.Dynamics365.UIAutomation.Api.UCI.Navigation.OpenSubArea(string area, string subarea)` is not working with the new sitemap ([the one expanded by default](https://blogs.msdn.microsoft.com/crm/2018/10/01/announcing-ui-updates-in-october-for-sitemap-and-command-bar%E2%80%A)).

Could you please add code to support this sitemap please ?

**Comment by TYLEROL** [comment]
Hello @NicolasPrats . Thanks for raising this up. We do have an item in our backlog for the v9.1 update work currently in progress on this. We're working on a means to support both the old sitemap, and this new version, as the new one will be opt-in for some period of time for previously existing organizations (versus newly created organizations where it is enabled by default)

Regards,
Tyler

**Comment by triciasinclair** [comment]
hi @TYLEROL do you have a estimated date for this?

**Comment by ggeiszle** [comment]
Hello @NicolasPrats and @triciasinclair (Sorry - I forgot to @ you earlier),

Please try the latest branch for 9.1.  We added functionality this week to provide support for the new sitemap changes.  If you have any issues with it, please let us know and we'll do the best that we can address them.
Thanks!

**Comment by NicolasPrats** [comment]
Hello @ggeiszle ,

Thanks you for this update. I confirm it's working in my case.

**Comment by NinjaSakshi** [comment]
Hi,

It is still not working in my case even with the latest branch. Error Given is as following:

```
Code Snippet: 
xrmApp.Navigation.OpenSubArea("Service Management", "Service Requests");

Test Outcome:	Failed
Test Duration:	0:01:21.0845611

System.InvalidOperationException: No area with the name 'service management' exists.
```
The Area exists as per the screen shot below:

![image](https://user-images.githubusercontent.com/40410459/53151628-8f221000-3618-11e9-9aa9-9c5628e45fdc.png)

**Comment by NinjaSakshi** [comment]
I did some tests on this and turn out that it won't work if you just have one Area and one group under your SiteMap.
It works if you have more than one Area and Group

**Comment by jlattimer** [comment]
Closing - @NinjaSakshi raise a new issue if this is still an issue
