### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Digit-89** [Microsoft/EasyRepro#30]
Hi, I'm facing an issue actually while testing your API.
I'm working on an european computer with european locals. My CRM instance is an US one. When I run any test with a date putting a DateTime.Now, it put the date in dd/MM/yyyy because of my computer locals so the test fails.

I can easily modify it on my side, but it could be very nice to detect this format conflict and/or set in the app.config the output DateTime region (en-US, gb-GB, ...)

**Comment by dtu11** [comment]
Thanks for the feedback. I'll add a work item on our end to look into this.

**Comment by dtu11** [comment]
Just wanted to provide an update.  This is still on our backlog as pending.

**Comment by TYLEROL** [comment]
@Digit-89 - I've attempted to reproduce this behavior, however as my machines are setup on a US computer, I attempted to adjust my locales manually but have not experienced the same problems you've described.

During my tests, I could see the date input in European format, however as the test would move on from that field, the format auto-adjusted to the format selected in the user's settings for my US based instance.

Could you please confirm whether or not you still observe this behavior using the most recent version? I'll try to cooridnate with a colleague in Europe for some additional testing. If you do still observe this behavior, can you please provide the following:

- Region settings (Format / Date+Time Formats)
- Time Zone
- Browser Version/Type
- Dynamics 365 org version
- Field settings in Dynamics for the date field you are setting


_Note: While my tests did not fail, I did notice with scenarios like today (March 2nd) the date input can vary. The data was entered successfully, but in this scenario the US format of the instance now shows February 3rd._ 

Thanks,
Tyler

**Comment by TYLEROL** [comment]
Closing this as no repro, however @Digit-89 if you find this is still an issue, please re-open the comment and provide the following bits of information:

- Region settings (Format / Date+Time Formats)
- Time Zone
- Browser Version/Type
- Dynamics 365 org version
- Field settings in Dynamics for the date field you are setting

Thanks,
Tyler
