### ISSUE TITLE
Test if a field is enabled

### ISSUE THREAD

**Issue by rinou92** [Microsoft/EasyRepro#32]
Hi,

I'm currently playing with the API and it's very nice, but I haven't found how to test if a field is enabled. 
May be I missed something, but if not, it would be nice to have this possibility :-)

**Comment by dtu11** [comment]
This is something we don't have a specific API for currently but can access the enabled attribute on the element.    You can use the xrmBrowser.Document.getElementById("firstname").GetAttribute("disabled");  try get the details.

**Comment by troyyer** [comment]
Sorry but could you provide some more help with this. When I tried grabbing a field with 

`var FName = xrmBrowser.Document.getElementById("firstname")`

I can see the full element in the watcher. However if I try 

`var FNameDisplay = xrmBrowser.Document.getElementById("firstname").GetAttribute("disabled"); `
or 
`var FNameDisplay = xrmBrowser.Document.getElementById("firstname").GetAttribute("Displayed");`
it comes up as null in the watcher. What am I doing wrong?

**Comment by dtu11** [comment]
Ok, it looks like there will be a span that has a lock image. The disabled setting is never set.   Try something like this. 

if (xrmBrowser.Document.getElementById("firstname_lock") != null)
                {
                    //do something
                }

**Comment by dtu11** [comment]
You can also execute client script that will get the control disabled status.   

xrmBrowser.Driver.ExecuteScript("Xrm.Page.ui.controls.get('firstname').getDisabled();").ToString();  

That should return True or False.

**Comment by troyyer** [comment]
So I was still getting an error with 
`xrmBrowser.Driver.ExecuteScript("Xrm.Page.ui.controls.get('firstname').getDisabled();").ToString();`
I was getting a NullReferenceException 

We ended up realising it was already present in the IWebElement properties.....
`var FNameDisplay = xrmBrowser.Document.getElementById("firstname").Displayed`

**Comment by mariokrajmer** [comment]
this actually works 
`xrmBrowser.Driver.ExecuteScript($"return Xrm.Page.getControl('firstname').getDisabled();");`

so the previous 
`xrmBrowser.Driver.ExecuteScript("Xrm.Page.ui.controls.get('firstname').getDisabled();").ToString();`
was missing the "`return`"
