### ISSUE TITLE
get the test results into a file

### ISSUE THREAD

**Issue by hasinthanagodavithana** [Microsoft/EasyRepro#320]
Hi, 

I am wondering is there any way that I can get the total test result/details into a file or email so we can refer it later to identify the issues. Currently when I run the tests in VS it gives very high level details but it does not provide consolidated single results file.

**Comment by TYLEROL** [comment]
Hello @hasinthanagodavithana ,

I've had success with this internally using a Visual Studio Test task in our build pipeline. This functions similar to using [VSTest.Console.exe command-line options](https://docs.microsoft.com/en-us/previous-versions/jj155796(v=vs.140)).

You'll need to configure a runsettings file that your test would consume from. While most of our branches are setup using the app.config file in samples, you could take a look at our Features/PowerApps branch which makes use of a runsettings file (e.g. solutionchecker.runsettings) in the Microsoft.PowerApps.UIAutomation.Sample project.

- EasyRepro/Microsoft.PowerApps.UIAutomation.Sample/ModelDriven/RunSolutionChecker.cs

You can view a sample test in the example file show above that initializes TestContext. For your scenarios the OnlineUserName, OnlinePassword, OnlineURL, and BrowserType would be the key parameters required for running EasyRepro tests against Dynamics 365. You can add additional parameters as needed for your scenarios.

Once you've configured the runsettings file, you could call VSTest.Console.exe using the documentation example with the DLL where your tests are stored and the name of your settings file, plus any other params as required. The output location when the run is finished should contain a <>.trx file that contains a summary of all the tests.

Hope this helps! If you have any other follow-up or questions on this issue, please re-open the issue and we can discuss further.

Thanks,
Tyler
