### ISSUE TITLE
DuplicateDetection confirmation is not working

### ISSUE THREAD

**Issue by thathi** [Microsoft/EasyRepro#323]
DuplicateDetection confirmation is not working while trying to delete a duplicate contact **via quick create**. I think DuplicateDetection method in Dialog.cs needs same kind of logic as QualifyLead. I have updated in my local it is working.  (beta/v9.x)

**Comment by TYLEROL** [comment]
@thathi - I'm going to close this as there are no details in the description about an issue related to EasyRepro.

If you have an issue, please re-open this and add some details regarding your issue/question, or open a new issue. Look forward to any help we can provide.

Warm Regards,
Tyler

**Comment by thathi** [comment]
@TYLEROL sorry updated with the valid description.
