### ISSUE TITLE
Question: Select Lookup Value - Beta 9.0.2 - Unified Interface - Quick Create

### ISSUE THREAD

**Issue by JamesStuder** [Microsoft/EasyRepro#325]
I am working on a test to make sure that my process with JavaScript is working when a lookup field is populated.  I used the SetValue(string, string) that is outlined under QuickCreate.  When I run the test, the value is input and I can see the one record in the choices.  But, as soon as I click out of the field, the value goes away.  How can I select the lookup value to populate the lookup field on a QuickCreate.  For more information, you can't use new LookupItem because that method does not exist for QuickCreate.

**Comment by TYLEROL** [comment]
Thanks for raising this @JamesStuder . 

We'll need to add a method for QuickCreate fields to support this. We're in the process of finalizing a new master branch which will support version 9.1+ moving forward.

I'll discuss with my colleague who has been updating the Unified Interface to see if he can squeeze this in. We'll update once this is available.

Thanks,
Tyler

**Comment by TYLEROL** [comment]
@JamesStuder - We've released the new releases/v9.1 branch today that should bring parity to the QuickCreate forms for what was available on Entity form fields. Please let us know if you have any issues with the implementation of QuickCreate methods for Lookup controls.

Warm Regards,,
Tyler
