### ISSUE TITLE
No Remote WebDriver support

### ISSUE THREAD

**Issue by RusmanCool** [Microsoft/EasyRepro#326]
Hello, 
In issue #75, they said  that Remote WebDriver support is being implemented. What is a time frame for this functionality?

**Comment by TYLEROL** [comment]
Hello @RusmanCool,

I spoke with a colleague today who mentioned that this should be available (Remote WebDriver support) in the latest releases.

Are you facing any specific issues trying to use the remote webdriver? If so, could you please add any issues/questions here for further comment?

Warm Regards,
Tyler

**Comment by RusmanCool** [comment]
@TYLEROL got it, I have already implemented our own code for RemoteWebDriver support. I will close this issue.
