### ISSUE TITLE
Issue: Global OptionSets - Quick Create - Beta 9.0.2

### ISSUE THREAD

**Issue by JamesStuder** [Microsoft/EasyRepro#327]
Ran into an issue using the SetValue(string, string) on a Global OptionSet field on a quick create form.  I pass in the schema name (all lower case) as the first value and the label of the option set value in the second parameter.  I am getting an error that it can't find the field on the form.  The field is on the form and not locked or hidden.  Not sure if it is because it is a Global OptionSet or if it is because new OptionSet is not part of the Unified Interface Quick Create.

**Comment by TYLEROL** [comment]
Thanks for raising this one as well @JamesStuder .

Same concept as with LookupItem. I asked my colleague to review all supported field types (TwoOption, OptionSet, LookupItem, etc...) and make them available for QuickCreate.

The element tags between QuickCreate, Entity Form, Entity Header, Entity Footer, and Business Process Flow all vary slightly so we have to make tweaks to the methods to support each. We do have some gaps in parity (which you look to be running into) that we're continually evolving and working to support all aspects of the UI. 

Regards,
Tyler

**Comment by TYLEROL** [comment]
Hello @JamesStuder  - As mentioned in the other issue, we've added new functionality in the new releases/v9.1 branch. This should add parity between Entity and QuickCreate form capabilities. 

If you continue to have issues with the implementation, please let us know.

Warm Regards,
Tyler
