### ISSUE TITLE
Question/Missing Item in recent release

### ISSUE THREAD

**Issue by JamesStuder** [Microsoft/EasyRepro#337]
First, thank you team for the fast answers to my previous questions and for pushing out an update so fast.  The two issues I raised previously where in fixed in the latest update.  The issue I am running into now, is that the select lookup within entity is not in quick create.  I am assuming that I need the select lookup to choose the lookup item from the drop down that appears.

Prior to v9 of Dynamics 365, I would use GetElement and pass in the field name, then SendKeys(Keys.Tab).  That way it would simulate the user leaving the field and JavaScript I have on the field would fire.  If I take this same approach with UCI, it can't find the element using the field name on the quick create.  Any input would be greatly appreciated.  Thank you.

**Comment by jlattimer** [comment]
There is now a SetValue for Lookup fields specific to QuickCreate forms in the develop branch.
