### ISSUE TITLE
Any documentation  / tutorial, how to customize EasyRepro sample code to real time code.

### ISSUE THREAD

**Issue by rtulaila** [Microsoft/EasyRepro#342]
Hi All, 
Anyone can help me if there is any documentation/tutorial, how to customize EasyRepro sample code to real time. wrt ‘Microsoft.Dynamics365.UIAutomation.Sample.Shared’.  
As of now I could able to login but our On-premises Dynamics CRM 365 entities are different. 
Ex:  Instead of Sales we have ‘Service’
      Service > Contacts
      Service > Case
Thanks in advance - RT

**Comment by Dolph-Dragon** [comment]
Hi RT,

Is this still an issue or did u solve the Problem?

Could you please clarify your problem? What is your code and what do you want to do? 

Best Regards 
Dolph

**Comment by rtulaila** [comment]
Hi @Dolph-Dragon  , Thanks for looking into this issue. I have still the same issue.

Currently we  are running On-premises Dynamics CRM 365 and I am using EasyRepro sample code and trying to customize but the issue is  I cannot change the naming conventions.  

example :   We have  'Service' instead of 'Sales' I have attached the pic how our navigation shows. 
**Service > Case**

I was looking for a documentation or a guide how to customize  EasyRepro code.

![image](https://user-images.githubusercontent.com/37820128/53046435-0495b100-345e-11e9-950d-bde0ba9535c1.png)

Thank you,
RT

**Comment by Dolph-Dragon** [comment]
Hi @rtulaila,

Sorry for the long waiting time. 
So, if i get you right, you are trying to navigate to (for Example) "Cases".
The code for that would be :

<  xrmBrowser.Navigation.OpenSubArea("Service", "Cases"); >

"xrmBrowser" is the Api.Browser that you create before/during your tests. 
 
If you want to open any other region you can just use the names that you see on the page. For example, if you want to open "IT Support"  you go with :

< xrmBrowser.Navigation.OpenSubArea("Service", "IT Support"); >

As far as i can tell the "names" are not case sensitive. 

I hope i got your Problem right and my answer is useful for you. 

Best Regrads
Dolph

**Comment by Kumarwgl** [comment]
Hi @Dolph-Dragon
Please help me out on  How to click on drop down option in easyrepro framework..

Request Originator-->>

![Capture](https://user-images.githubusercontent.com/43398677/54191450-f0ccf000-44db-11e9-8417-68df56d5e774.PNG)

Thanks,
Kumar

**Comment by Dolph-Dragon** [comment]
Hi @Kumar,

this is the code that works for me with drop down fields (Option Fields) :

<< xrmBrowser.Entity.SetValue(new OptionSet { Name = "fieldname", Value = "desiredOption" }); >>

fieldname should be something like "Request Originator". ( Its the name that is configurated in your CRM Systemview)
desiredOption should be the name of the option that you want to click on. ( "... Provider") ( CaseSensitive)

I hope this helps you out. 

Best Regards 
Dolph

**Comment by Kumarwgl** [comment]
@Dolph - Thank you

**Comment by dolph** [comment]
@Dolph-Dragon ^

**Comment by kaleshashaik91** [comment]
Hi All,

Can you help me how to start working with EasyRepro  ?

Regards,
Kalesha
