### ISSUE TITLE
IEDriverServer64.exe

### ISSUE THREAD

**Issue by yoadster** [Microsoft/EasyRepro#381]
Hi, please could you add support for the 64bit IE driver. There are know performance issues when running the 32 bit driver on a 64 bit OS (it basically runs like a dog). Currently the IE option defaults to the 32 bit version.

Many thanks.

**Comment by jlattimer** [comment]
Guessing this one can be closed - the IE driver linked on the [main page](https://github.com/microsoft/EasyRepro#internet-explorer) is the 64 bit version
