### ISSUE TITLE
How to write in a HTML CKEditor

### ISSUE THREAD

**Issue by dnamrgrts** [Microsoft/EasyRepro#387]
i have in my Strategy Entity a HTML CKEditor and i would like to add a few lines. 
My First step is: 
xrmBrowser.Driver.SwitchTo().Frame("Webresource_example");   ////This works
IWebElement Text = xrmBrowser.Driver.FindElement(By.XPath("//*[@id=\"ckeditor\"]"));
Text.SendKeys("...........");   ////////this doesn't work

System.InvalidOperationException : unknown error : cannot focus element

Does anyone have a Solution?

**Comment by jlattimer** [comment]
Closing - off topic as this isn’t EasyRepro functionality but more base Selenium code
