### ISSUE TITLE
Search_Results pointing to wrong xpath value

### ISSUE THREAD

**Issue by troyyer** [Microsoft/EasyRepro#39]
In the file XrmElementReference.cs, the value for Search_Result is pointing to entityDiv_1, however when I have been testing in Dynamics 365 I dont see an element of entityDiv_1 so trying to select a search result would fail from the framework. When I changed the value to contentResult it was then able to find values.

            { "Search_Result"       , "id(\"entityDiv_1\")"},
should be changed to 

           { "Search_Result"       , "id(\"contentResult\")"},

**Comment by dtu11** [comment]
Which version were you using? I'll review that API and do some more testing.

**Comment by troyyer** [comment]
We are using Microsoft Dynamics 365 Version 1612 (9.0.0.2072) (DB 9.0.0.1103) online and I am using the current Master branch from this repository.

**Comment by dtu11** [comment]
Ok, as of now we only support 8.1 and 8.2 versions of Dynamics. We're currently in the process of refactoring to support v9.0.  I don't have an ETA yet but it will be in the coming weeks.
