### ISSUE TITLE
UII not working with newest Dynamics 365 version (North America)

### ISSUE THREAD

**Issue by s-bauer** [Microsoft/EasyRepro#391]
I've set up a new CRM Trial instance in North America and tried to execute the sample UCI tests provided in this repository. It failed for me as some XPaths are not correct anymore. I had to replace the following values so that it works again:

- `{ "Login_CrmMainPage", "//div[contains(@data-id,\"topBar\")]"},`
- `{ "Nav_AppMenuButton"       , "//button[@data-id=\"navbar-switch-app\"]"},`

In addition I'm having issues when running in the headless mode (Chrome), as it does not find the "Save" button. This might be caused by the window size as the "Save" button does not have any text, but just the save icon.

**Comment by triciasinclair** [comment]
thanks this worked for me too. Any new instance created this month in the uk has this change. 

Thanks for sharing @s-bauer

**Comment by GuySimcox** [comment]
I too am observing this. Save is not working with the xpath for the create account sample in headless chrome mode.

**Comment by s-bauer** [comment]
Probably outdated by now. Closing.
