### ISSUE TITLE
Version Of Current Release in NuGet

### ISSUE THREAD

**Issue by nlipkow** [Microsoft/EasyRepro#392]
Hello,

when will the current release branch be available on [nuget](https://www.nuget.org/packages/Dynamics365.UIAutomation.Api/9.1.0)? We need this for our CI environment.

Thanks in advance
Norman

**Comment by cnusrini** [comment]
@nlipkow Its seems that the latest is out in the nuget now . Please revisit .

**Comment by nlipkow** [comment]
Thanks, it is available now indeed!
