### ISSUE TITLE
v9.1 (UCI) Clear Value broken - does not clear value

### ISSUE THREAD

**Issue by watsonthecat** [Microsoft/EasyRepro#394]
Scenario: Testing to make sure form controls are working by testing invalid characters.

I want to set the field value (testing for invalid characters) and then clear the field's value, so we can set the field value again with other invalid characters.

_xrmApp.Entity.ClearValue("emailaddress1");  //does not clear the value of the field 

I've tried saving the record and then clearing the value and that doesn't work either. The new values are appended to the end of the previous value that was set (because clear value step does nothing).

**Comment by mVermaat** [comment]
Anybody found a good workaround for this issue?

**Comment by jlattimer** [comment]
Merged into 9.1 branch - closing
