### ISSUE TITLE
UCI Error on XrmApp.Navigation.OpenSubArea when there is just one Area in Sitemap

### ISSUE THREAD

**Issue by fahadmajeedrana** [Microsoft/EasyRepro#398]
Hi Team,

We are writing UI tests for UCI app. We have only one Area in the app to meet application's UI requirements. The problem we are facing is whenever there is just one area in the sitemap we receive "System.InvalidOperationException: No area with the name 'service management' exists." exception. Could you please advise if this issue is under you radar.

Cheers.

**Comment by NinjaSakshi** [comment]
Hi,

I am facing the same issue. Error Given is as following:

```
Code Snippet: 
xrmApp.Navigation.OpenSubArea("Service Management", "Service Requests");

Test Outcome:	Failed
Test Duration:	0:01:21.0845611

System.InvalidOperationException: No area with the name 'service management' exists.
```
The Area exists as per the screen shot below:

![image](https://user-images.githubusercontent.com/40410459/53151628-8f221000-3618-11e9-9aa9-9c5628e45fdc.png)

**Comment by gyepescalle** [comment]
Hi,

I'm having the same issue. Has anybody been able to fix this somehow?

Thanks.

**Comment by jlattimer** [comment]
Recently add a new method OpenGroupSubArea which should help to navigate while inside an already open app - regardless of the number areas.
