### ISSUE TITLE
SetValue for TwoOptions doesn't work for checkboxes

### ISSUE THREAD

**Issue by mVermaat** [Microsoft/EasyRepro#404]
When using the "SetValue(TwoOption option)" method, it doesn't properly work for checkboxes. It clicks next to the box, so the box doesn't get (un)checked.

It currently clicks the fieldelement and not the imput element that is a child of the fieldelement. the fieldelement is too big, so it clicks next to the box. If you click on the input element, it seems to work.

**Comment by NicolasPrats** [comment]
Hello,

We have the same issue. However the deprecated method SetValue(string, bool) is working fine.

**Comment by dtu11** [comment]
Thanks Nicolas for a workaround.   

Which version and which client are you working with?

**Comment by NicolasPrats** [comment]
Hello @dtu11 ,

We are working with Chrome and D365 Version 1710 (9.1.0.2640) online.

**Comment by mVermaat** [comment]
@dtu11 

For me exactly the same. Good plan to use the deprecated method for now.

**Comment by jlattimer** [comment]
When formatted as a list it doesn't work either. Going from false to true opens the drop down but never sets. Going from true to false doesn't open the drop down at all.
