### ISSUE TITLE
Composite Control is hard coded to fullname field

### ISSUE THREAD

**Issue by troyyer** [Microsoft/EasyRepro#41]
the composite control currently only works for fullname in an Add Contact test as the value in 
XrmElementReference.cs is hardcoded to fullname
`{ "SetValue_CompositionLinkControlId"       , "fullname_compositionLinkControl_"},`

it would need to be 
`{ "SetValue_CompositionLinkControlId"       , "[NAME]_compositionLinkControl_"},`

but I'm not certain what changes need to be done in the  SetValue(CompositeControl control) and GetValue(CompositeControl control)

**Comment by dtu11** [comment]
I made the changes to the composite control to pull the field name from the control.  Please pull the latest version and test again. 

Again, thanks for the feedback!
