### ISSUE TITLE
[UCI XrmApp Problem] test fails when trying to open sub area, corresponding xrmBrowser one doesn't

### ISSUE THREAD

**Issue by Haywaii** [Microsoft/EasyRepro#422]
Hi, 

I encounter the same problem than this issue (my work is a business project so difficult to share more screenshot or source): 
https://github.com/Microsoft/EasyRepro/issues/185

I tried the solution mentioned but i still got the same error. 
I know in settings you can choose to use a hybrid Unified Interface. That's what we do.
Even when we disable it, our test still doesn't work.

Here the code i used: 

**Current Interface**
 public void NavigateToAnAccount()
        {
             xrmBrowser.ThinkTime(500);
             xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");
            xrmBrowser.Grid.Search("RT_AT_EmLTest", "1000");
            xrmBrowser.Grid.OpenRecord(0, "500");
        }

**UCI Interface**
 public void NavigateToAnAccount()
        {
            xrmApp.Navigation.OpenApp("UCI");
            xrmApp.ThinkTime(500);
            xrmApp.Navigation.OpenSubArea("UCI", "Accounts");
            xrmApp.Grid.Search("RT_AT_EmLTest");
            xrmApp.Grid.OpenRecord(0);
        }

My xrmApp object and login function are declared outside.  It's working bc i can access the app without any problem but the problem occurs once i try to call OpenSubArea function.

![UCI](https://user-images.githubusercontent.com/4428186/54295986-f98cf700-45ab-11e9-93c0-23b659ac9c95.PNG)

I was wondering if:
1/ Does Hybrid Unified Interface change something for XrmApp object to navigate to subarea?
2/ How do we know that the app we are targeting (UCI or Customer Service Hub on the screenshot in my case) is based on the new Unified Interface (even if it looks like it)?

Thanks for the help!

**Comment by Haywaii** [comment]
Updating the package of the framework with the latest version solved the issue but now the system doesn't recognize the area i try to go to as part of this issue: https://github.com/Microsoft/EasyRepro/issues/252

@TYLEROL do you have an update if the change was pushed to the latest version please? (i can't find your code of 9.0.2 anymore and version other than the last one doesn't work)

**Comment by TYLEROL** [comment]
@Haywaii - When you access your Unified Interface app, do you have more than a single area in the navigation? Or just one area? My screenshot below has multiple areas (Sales, Service, etc...)

I have a backlog item opened with the team to update UCI to support apps that only have a single area, as it changes the element structure of the navigation which causes issues with the current implementation of OpenSubArea.

In your code sample you listed earlier, is UCI the name of the parent area containing Accounts? From my screenshow below, I'd adjust your code to this, assuming you want to access accounts under 'Service':

UCI Interface
```
public void NavigateToAnAccount()
{
xrmApp.Navigation.OpenApp("UCI");
xrmApp.ThinkTime(500);
**xrmApp.Navigation.OpenSubArea("Service", "Accounts");**
xrmApp.Grid.Search("RT_AT_EmLTest");
xrmApp.Grid.OpenRecord(0);
}
```

![image](https://user-images.githubusercontent.com/29415524/55090611-6ceb3a00-507d-11e9-97bd-6fe0d0c48811.png)

**Comment by Haywaii** [comment]
Hey @TYLEROL thanks for your answer! 

No, i just have one at the moment which is called "CRM" (your equivalent of "Service") 
Yes, If i had more i would see something like you next to "Service" i think. 

Yes i understand. In that case we will try to add another area just for our automation to work so we can keep working on it :)
Please let us know when the fix will be made or if we can change it directly on our code?

Thanks,

**Comment by jlattimer** [comment]
#398

**Comment by jlattimer** [comment]
Recently add a new method OpenGroupSubArea which should help to navigate while inside an already open app - regardless of the number areas.

**Comment by Haywaii** [comment]
Yes i saw that, it should help thanks!

**Comment by jlattimer** [comment]
Good deal - closing
