### ISSUE TITLE
How to Automation in Custom html pop up window?

### ISSUE THREAD

**Issue by bhomick** [Microsoft/EasyRepro#423]
Hi Team,

Need to Automation in Custom Html pop up window.

![Capture](https://user-images.githubusercontent.com/48288553/54408772-3c181600-4709-11e9-9862-6747d63fd618.PNG)

**Comment by Dolph-Dragon** [comment]
Hi @bhomick,

i ran into the same issue. In my case it was a warning from CRM. I used Selenium to solve this Problem.
This code was helping in my case : 

            IAlert alert = xrmBrowser.Driver.SwitchTo().Alert();
            alert.Accept();
            xrmBrowser.ThinkTime(1000);

As i said, this works for me. I dont know if this specific code helps you out. Your pop-up may not be handled as an alert.  But maybe ist does :)

Hope i could help!

Best regards 

Dolph

**Comment by bhomick** [comment]
Hi @Dolph-Dragon ,

Many Thanks for the response.
But Your mentioned code is not worked in this case. Because this pop is open in new window and its HTML content. If you know about this its really helpful for me.

Hope you could help me !

Regards
Bhomick

**Comment by rcjohnson113** [comment]
XrmBrowser.Driver.LastWindow().SwitchTo().ActiveElement();

Now that you are in a custom html web resource you are going to have to find the Ids of the fields and reference them using xpath. Here I get an image and it has an onClick event so I fire .Click().

XrmBrowser.Driver.FindElement(By.XPath("//*[@id=\"img_lookup_search_IccId\"]")).Click();

**Comment by bhomick** [comment]
Hi @rcjohnson113 ,

Many thanks for the response.
Your above mentioned code is worked for me.

Regards
Bhomick
