### ISSUE TITLE
Unable to use opensubarea in new UI

### ISSUE THREAD

**Issue by triciasinclair** [Microsoft/EasyRepro#424]
When using the new UI, the OpenSubArea method doesn't work. It throws the error 'Object reference not set to an instance of an object.'

xrmApp.Navigation.OpenSubArea("Customers", "Accounts");

**Comment by jlattimer** [comment]
@triciasinclair - if you use code from the current [develop](https://github.com/microsoft/EasyRepro/tree/develop) branch, do you still see the issue?

**Comment by triciasinclair** [comment]
Hi! Yes, unfortunately. However whereas before it didn’t work consistently, it now works intermittently.

**Comment by triciasinclair** [comment]
Hi! This works now thanks so much!
