### ISSUE TITLE
Dynamics 365 for Operations Support

### ISSUE THREAD

**Issue by rvora76** [Microsoft/EasyRepro#43]
I really like the look of this and seems to work well. I was wondering if there is a plan to support Dynamics 365 for Operations?

Would it work in any way in it's current state on Dynamics 365 for Operations?

Any info would be greatly appreciated.

**Comment by dtu11** [comment]
Currently there is no planned support for Dynamics 365 Finance & Operations.   The framework we've built would be a nice start to build you're own API's to support the Automation though.   Even though you would have to break down the UI for the API's...you will get the telemetry details if you follow the same pattern.

**Comment by dtu11** [comment]
If you do decide to build some API's for Operations and want to share with the community, feel free to do a pull request.  We will review the changes and get them added into the project.   That is not required though. 

Thanks

Daren
