### ISSUE TITLE
How to generate Test report ?

### ISSUE THREAD

**Issue by bhomick** [Microsoft/EasyRepro#435]
Hi Team,

How to generate Test report ?

I want to see my all test cases in a html file report like total test cases run, failed or how many pass etc.
Please help me how to generate such html file with example.

**Comment by jlattimer** [comment]
I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.

**Comment by madhusudhancogn** [comment]
Hi, Can you give me access to read your blog. This is my email: madhusudhan.usami@gmail.com
Thanks

**Comment by VictoriaB81** [comment]
> I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.

Please give access to read you blog - victoriabaretto81@gmail.com

**Comment by praneethar-qz** [comment]
> I did a [blog post](https://jlattimer.blogspot.com/2019/06/reporting-on-easyrepro-test-runs.html) which shows how to set up Extent Reports with an EasyRepro project.

Can you please provide me access to read our blog for mail ID- praneetha.ramireddy@gmail.com

**Comment by untoldstory69** [comment]
[@jal](https://github.com/jlattimer) looks like your blog is private.

**Comment by untoldstory69** [comment]
I got this working, the details are [here](https://kishorsharma69.wordpress.com/2023/11/13/extent-report-with-easyrepro/)
