### ISSUE TITLE
nuget

### ISSUE THREAD

**Issue by devkeydet** [Microsoft/EasyRepro#44]
Please make Microsoft.Dynamics365.UIAutomation.Api and Microsoft.Dynamics365.UIAutomation.Browser available as nuget packages.  This will make it *much* easier to get started running tests vs having to download a bunch of source code that I need to then put in my repo.  I just want to use the functionality, not clutter my repo with source code which I should be able to just reference as assemblies from nuget.

**Comment by devkeydet** [comment]
I could obviously build the binaries and put those into source control, but I don't want to do that either.

**Comment by dtu11** [comment]
We have this on our Backlog and going to work to get these assemblies added to Nuget.  I'll update this issue once that is complete.

**Comment by jynxeh** [comment]
+1 for this.

Many thanks.

**Comment by dtu11** [comment]
We're currently working to get the Nuget packages released.  We just released support for v9.0 and the packages should go out early this week.    I apologize for the delay.

**Comment by kaceyarnold** [comment]
I tried to use the easyrepro package I found in Nuget but...

Attempting to gather dependency information for package 'Dynamics365.UIAutomation.Api.8.2.0.1' with respect to project 'test', targeting '.NETFramework,Version=v4.6'
Gathering dependency information took 165.6 ms
Attempting to resolve dependencies for package 'Dynamics365.UIAutomation.Api.8.2.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Dynamics365.UIAutomation.Api.8.2.0.1'
Resolved actions to install package 'Dynamics365.UIAutomation.Api.8.2.0.1'
Retrieving package 'Dynamics365.UIAutomation.Api 8.2.0.1' from 'nuget.org'.
Install failed. Rolling back...
Package 'Dynamics365.UIAutomation.Api.8.2.0.1' does not exist in project 'test'
Package 'Dynamics365.UIAutomation.Api.8.2.0.1' does not exist in folder 'C:\Users\kcarn\Documents\Test Studio Projects\test\packages'
Executing nuget actions took 96.75 ms
Could not install package 'Dynamics365.UIAutomation.Api 8.2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:00.3791718

**Comment by dtu11** [comment]
We're looking into this issue now.

**Comment by DebeshDas** [comment]
One possible workaround will be to create a new project.
Set the .net version to 4.6.2
Then add the Nuget package to the project.
Sometimes the existing project with references creates problem installing the Nuget package.

Why this error occurs still needs investigation.

**Comment by kaceyarnold** [comment]
Yes you can install the Nuget package under 4.6.2 but
Test Name:	TestLogin
Test FullName:	MedSol_EasyRepro_Selenium.LoginTest.TestLogin
Test Source:	C:\Users\kcarn\source\repos\Quality Assurance\MedSol_EasyRepro_Selenium\MedSol_EasyRepro_Selenium\LoginTest.cs : line 20
Test Outcome:	Failed
Test Duration:	0:00:00.2963245

Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Browser.BrowserDriverFactory.CreateWebDriver(BrowserOptions options)
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.get_Driver()
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.Login(Uri uri, SecureString username, SecureString password, Action`1 redirectAction)
   at MedSol_EasyRepro_Selenium.LoginTest.TestLogin() in C:\Users\kcarn\source\repos\Quality Assurance\MedSol_EasyRepro_Selenium\MedSol_EasyRepro_Selenium\LoginTest.cs:line 24
Result Message:	
Test method MedSol_EasyRepro_Selenium.LoginTest.TestLogin threw exception: 
System.TypeLoadException: Could not load type 'OpenQA.Selenium.Edge.EdgeDriverService' from assembly 'WebDriver, Version=2.45.0.0, Culture=neutral, PublicKeyToken=null'.

My guess is that this is a result of an implicit cast in browser options.
 public EdgeOptions ToEdge()
        {
            var options = new EdgeOptions()
            {
                // PageLoadStrategy = EdgePageLoadStrategy.Normal   becomes the line below
                PageLoadStrategy =(PageLoadStrategy) EdgePageLoadStrategy.Normal    //Did an explicit cast
            };

            return options;
        }

**Comment by dtu11** [comment]
I've updated the Nuget Packages to include the latest builds.  Please let me know if there are any issues.

**Comment by randolphnz** [comment]
I run the API 8.2 version with .net framework 4.6/4.6.1/4.6.2 in VS 2015. But it always stucks at close guided page step and complains "Xrm not defined". Any solution to fix? Much appreciated in advance!
