### ISSUE TITLE
How to assert for mandatory/recommended fields?

### ISSUE THREAD

**Issue by Vishvajeetcse** [Microsoft/EasyRepro#449]
How to assert for mandatory/recommended fields?

**Comment by jlattimer** [comment]
If you aren't using UCI then you'd probably need to use an ExecuteScript call to find the value. Issue is that when labels aren't displayed the page elements don't really make it clear what is required or not.

```csharp
var reqiredLevel = xrmBrowser.Driver.ExecuteScript("return Xrm.Page.getAttribute('websiteurl').getRequiredLevel();");
```
That will return none, required, or recommended.

If using UCI you can do something like this:

```csharp
using OpenQA.Selenium;

var field = client.Browser.Driver.FindElement(By.XPath(AppElements.Xpath[AppReference.Entity.TextFieldContainer].Replace("[NAME]", "name")));
var requirementLevel =  field.GetAttribute("data-fieldrequirement");
```

That will return:
0 = none
1 or 2 = required
3 = recommended

Also note there that if you've got a field type that isn't text, you'll need to find which XPath constant to use to field the field. These are located in DTOs/AppElementReference.cs
