### ISSUE TITLE
Exception with data type "Two Options" and no default value

### ISSUE THREAD

**Issue by WinniB** [Microsoft/EasyRepro#46]
There is an exception when I try to set the value of an element with data type "Two Options" and no default value and when option was never set. Because of the unset state of the element the `GetAttribute("checked")` returns null. The parsing of null to a Boolean value throws an exception.

**Comment by dtu11** [comment]
Can you provide the version you're working with and the code of your test script?

Thanks

**Comment by WinniB** [comment]
Sorry, my description was bad, i try to explain it more detailed: I want to check a checkbox on page. The first error occured was that the element could not be found. This is because in the "SetValue" function the element id get the `"int_"` prefix.
In order to use the "SetValue" function i had to change the id from `"int_" + field` to `field`
After this change the driver is now able to find the checkbox, but when `.GetAttribute("checked")` is executed I get an exception: _"Value cannot be null. Parameter name: value"_

- We use Microsoft Dynamics 365 Version 1612 (8.2.2.136) on-premises
- The code I try to ckeck the checkbox : `entity.SetValue("my_checkbox", true);`
- The code after changing the "SetValue" function:

```
public BrowserCommandResult<bool> SetValue(string field, bool check)
{
	return this.Execute(GetOptions($"Set Value: {field}"), driver =>
	{
		if (driver.HasElement(By.Id(field)))
		{
			var input = driver.FindElement(By.Id(field));

			if (bool.Parse(input.FindElement(By.TagName("input")).GetAttribute("checked")) && !check)
				input.FindElement(By.TagName("input")).Click();
		}
		else
			throw new InvalidOperationException($"Field: {field} Does not exist");

		return true;
	});
}
```

**Comment by j621z** [comment]
@WinniB This fix will be pushed soon. In the mean time, please try running this code. The issue is the "checked" attribute is not present in the "input" tag. 

```
public BrowserCommandResult<bool> SetValue(string field, bool check)
{
	return this.Execute(GetOptions($"Set Value: {field}"), driver =>
	{
		if (driver.HasElement(By.Id(field)))
		{
			var input = driver.FindElement(By.Id(field));
			var checkBox = input.FindElement(By.TagName("input"));
			var bCheck = checkBox.GetAttribute("value") == "1";

			if (bCheck != check)
			{
				checkBox.Click();
			}
		}
		else
			throw new InvalidOperationException($"Field: {field} Does not exist");

		return true;
	});
}
```
