### ISSUE TITLE
EasyRepro Code update when new version comes out

### ISSUE THREAD

**Issue by deepak-surendar** [Microsoft/EasyRepro#460]
I am using v9.1 of Easy Repro now. I also did some modification to Microsoft.Dynamics365.UIAutomation.Api.UCI.dll. When the new version v9.2 of EasyRepro comes out later on GitHub, how do I update my v9.1 code to v9.2.

**Comment by TYLEROL** [comment]
@deepak-surendar - Thanks for raising this issue. We're starting to update the main releases/v9.1 branch to the latest and greatest as new builds of Dynamics start releasing.

The best way to utilize this will be via the NuGet packages made available. With this latest release, we plan to snap to specific versions of Dynamics 365. The newest package is 9.1.0.5230 and should support that version of Dynamics 365 and higher (and if an issue arises, we'll release a package for that version which you can then upgrade to).

Please let me know if you have any questions or concerns about this process - but in general, you should be able to adopt the latest NuGet packages as your Dynamics organizations are upgraded.

I'd recommend moving your custom modifications into a new project that can consume the latest via NuGet and avoid potential for overwrites as changes are made.

Best Regards,
Tyler
