### ISSUE TITLE
How to open a record from sub-grid?

### ISSUE THREAD

**Issue by bhomick** [Microsoft/EasyRepro#462]
Hello Team,

How to open a record from sub-grid?

![Capture](https://user-images.githubusercontent.com/48288553/56422433-f1b82500-62c4-11e9-881e-c1aa7882fd72.PNG)

**Comment by dnamrgrts** [comment]
Hello, i have a similar Problem. I want to delete a record from sub-grid. 
Does anyone have a solution?

**Comment by dnamrgrts** [comment]
@TYLEROL

**Comment by bhomick** [comment]
@jlattimer Can you please look into this?
Thanks in Advance

**Comment by jlattimer** [comment]
Does this work to open?

```csharp
xrmBrowser.Grid.OpenRecord(0);
```

**Comment by bhomick** [comment]
@jlattimer  
Hi,
Thanks for the Response,

xrmBrowser.Grid.OpenRecord(0) is not work for Opening SubGrid Record.

Can you please help me into this?

**Comment by bhomick** [comment]
![Subgrid](https://user-images.githubusercontent.com/48288553/58322837-c84c6500-7e3f-11e9-84a0-dac7475e0114.PNG)
@ggeiszle  Can you please look into this?  How to Open Sub-grid Record?

Thanks in Advance

**Comment by jlattimer** [comment]
@bhomick - just submitted a PR for this
