### ISSUE TITLE
Why is window.Xrm not used?

### ISSUE THREAD

**Issue by DigitalFlow** [Microsoft/EasyRepro#463]
Hey everyone,

first off, thanks for providing this framework, I tested it quite some times now and I very much appreciate the effort.

I was wondering however, why the window.Xrm functionalities are not used.
This would relax many issues with handling inputs, for example asserting values of controls that are not shown in the current tab of a UCI form.

Was it an active decision not to use it?

Kind Regards,
Florian

**Comment by jlattimer** [comment]
That wouldn't really be testing the UI in most cases. Example, if you use a JS method to update a field that is hidden it's going to succeed. If you try the same thing via the underlying Selenium it should fail because the field isn't visible which better simulates the user not actually being able to type into it.

**Comment by DigitalFlow** [comment]
Hi Jason,

Thanks for commenting.

I'd advocate against that: I'm checking whether the field is readonly or hidden and throwing an error in either of those cases.
It's more robust, supported and setting Lookups and Optionsets works flawlessly.
In addition to that, with the rising of custom controls I do not need to handle these separately.

Kind Regards,
Florian

**Comment by TYLEROL** [comment]
Hello @DigitalFlow - To Jason's point - we avoid usage of window.Xrm where possible as the intent behind EasyRepro is to simulate real user interactions with the Dynamics 365 application. 

We have an open ask to add methods that return the state of a field (e.g. is the field hidden / readonly, etc...) in which I could see us using window.Xrm to help us determine those without reliance on DOM elements which would be difficult in these scenarios. I can see usage of this specifically for the tester and test deisgner in checking the state of a field and only trying to use our SetValue/GetValue methods if the fields are available. I can see this being useful for testing of various security roles and making a test case more diverse without needing to design tests per security role.

As of today - more of our APIs expect that a record, field, button, or any other object should exist for the API to work - and the API would do this work with Click events just like a traditional user would. This ensures that if EasyRepro can perform the work, so should a traditional user be able to.

I don't have an ETA for when we'll be able to add the field state enhancements, but please let us know if you have any additional questions - or if I've missed the purpose of your original question and I can try to clarify as needed.

Warm Regards,
Tyler
