### ISSUE TITLE
GetValues from Lookup, OptionSet and Multioptionset (v9.1)

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#468]
I am trying to get the values from the fields and it worked with single line of text field but it failed with lookup and optionset fields.

Here is the snippet I used:
string acctName= xrmApp.Entity.GetValue(new Lookup { Name = "Account" });
string statusValue= xrmApp.Entity.GetValue(new OptionSet { Name = "statuscode" });

**Comment by Dolph-Dragon** [comment]
Hi @SachinAnnam,

have you tried to use xrmBrowser?  Like this :

xrmBrowser.Entity.GetValue(new OptionSet { Name = "statuscode" });

What kind of ErrorMessage do you get?

Best Regards

**Comment by kavitham1985** [comment]
Hi,
Any updates on this? I am using UCI and want to update statuscode. xrmApp.Entity.SetValue(new OptionSet { Name = "statuscode", Value = "Inactive" }); is throwing statuscode is not found error. 
Error Message "Field with name statuscode does not exist."

**Comment by jlattimer** [comment]
I believe the lookup issue was solved in an earlier PR and the latest should fix statuscode. It there are continued problems please raise a new issue.
