### ISSUE TITLE
Using EasyRepro on webpage written with React elements

### ISSUE THREAD

**Issue by sammcquistan** [Microsoft/EasyRepro#470]
I am trying to automate QA testing within our Dynamics 365 application using EasyRepro and I am currently stuck on automating elements written in React. My issue is that when I try to click a contact in the search box within what we call our "Draftboard", a record populates and it is clicked on so that the "Deal" records that are associated with that contact populate within another divider on that page. See below for example as to what I am outlining:

![draftboard before click](https://user-images.githubusercontent.com/49731029/56974768-14ec9b00-6b35-11e9-9a81-750ef4cc3810.PNG)

Red arrow shows where the click is registered. After click is registered:

![draftboard after click](https://user-images.githubusercontent.com/49731029/56975215-ec18d580-6b35-11e9-8ece-f432b3df2042.PNG)

In the EasyRepro code, when we try to click on the dropdown element, the element disappears after a click (which is by design of React). However, EasyRepro gets upset that the element does not exist on the webpage and fails out of the test with the error "Message: test method (test name here) threw exception: OpenQA.Selenium.StaleElementReferenceException: stale element reference is not attached to the page document". Code below:

public void testName()
{
  using (var xrmBrowser = new Browser(TestSettings.Options))
  {
     //code for system login here, redacted
     //code for clicking to draftboard, redacted
     var travelerName = "Name";
     var travelerInputElement = "XPath for textbox";
     var travelerSelect = "XPath for sug-0 on dropdown";

     xrmBrowser.Document.getElementByXPath(TravelerInputElement).SendKeys(travelerName);
     xrmBrowser.ThinkTime(2000); //waits for system to find record
     var wait = new WebDriverWait(xrmBrowser.Driver, TimeSpan.FromSeconds(30));
     var elementU = wait.Until(Condition(By.XPath(TravelerSelect)));
     elementU.Click(); //this is where the error occurs

The click registers successfully, but the system will not go further into any other code because of the stale element reference that is thrown. Are there any workarounds or suggestions to solve this problem?

**Comment by jlattimer** [comment]
Closing - off topic as this isn’t EasyRepro functionality but more base Selenium code

**Comment by jordimontana82** [comment]
Hi @sammcquistan!

Wondering... wouldn't it be better to use jest for testing custom react components ? 

Curious to know why do you need EasyRepro for this? Maybe end to end scenario?

**Comment by sammcquistan** [comment]
Hi @jordimontana82 ,

Relatively new to the QA realm, here. Just started doing automated testing (and manual, in fact) just a few months ago. I plan on implementing a few other tools into our automation suite after I have a majority of our suite automated with EasyRepro. The more I learn, the more I will implement! Jest has been on my radar and will probably be what I use in the future.

**Comment by jordimontana82** [comment]
Cool! Was just wondering thanks! :)
