### ISSUE TITLE
Help Wanted: Encrypt credentials in app.config

### ISSUE THREAD

**Issue by eduarddalm** [Microsoft/EasyRepro#471]
Hi,

I have  a requirement to encrypt the url, user and password in app.config.
Now when checking in the solution in Azure DevOps the credentials are not encrypted and can be read by anyone who has access.

![image](https://user-images.githubusercontent.com/25723165/57014627-45096c00-6c11-11e9-9865-052b7e7415b4.png)

` <appSettings>
    <add key="OnlineUsername" value="MI2VW41eUDA7eDT2muvm+p0bZ6+l0VcHNlly5i2Vt8g=" />
    <add key="OnlinePassword" value="vVynniqLUUf8kB+xa2lHpg==" />
    <add key="OnlineCrmUrl" value="8sLp4/8bFxmK9yg3eKGfPDRgmKra+iIG4s5lCK7vrZuabmF0d2s/zQRV4TSBrCffxsLacbh4UeDQ2xyO9LA8Vg==" />
    <add key="AzureKey" value="" />
`
How can I encrypt these three items, as in the example?

Regards,
Eduard Dalm

**Comment by bwmodular** [comment]
There are probably a few options, but the method we use is to use Azure KeyVault to store passwords.
You can then put the 'key' to your keyvault in you app.config so you're not storing passwords there. You can then restrict access to the keyvault either by App registration (so only registered applications are allowed to get secrets from the vault) or you can restrict by IP address, which means that even if someone gets hold of your key, they won't be able to do anything with it.
Your code will then need to get the 'key' to the vault from your app.config, and retrieve the values that you need from the keyvault as appropriate.
More on the keyvault here:
https://azure.microsoft.com/en-gb/services/key-vault/
Keyvaults usage is so cheap as to be virutally free and you get all of the lovely Azure benefits (alerts, monitoring, etc)

**Comment by eduarddalm** [comment]
@bwmodular Thanks for the suggestion! 
I am aware of Azure Key Vault option and mentioned it to my customer. My customer however does not have the option to use Azure Key Vault. It will take a while until the decision to use Azure will be made.

**Comment by jlattimer** [comment]
You're better off not checking in the sensitive bits in the first place. You could simply move those pieces to another file linked to the main app.config and the exclude that from source control and then you wouldn't have to worry. The new file will be additive to whatever is in the app.config appsettings already. 

So something like this:

``` xml
  <appSettings file="appsettings.config">
    <!-- IE,Chrome,Firefox,Edge-->
    <add key="BrowserType" value="Chrome"/> 

    <!-- 1. Create a file named 'appsettings.config' at same level of 'app.config' -->
    <!-- 2. Add the following content -->
    <!--<?xml version="1.0" encoding="utf-8"?>
    <appSettings>
      <add key="OnlineUsername" value="" />
      <add key="OnlinePassword" value="" />
      <add key="OnlineCrmUrl" value="" />
      <add key="AzureKey" value="" />
    </appSettings>-->
    <!-- 3. Change file property: Copy to Output Directory to Copy if newer -->
    <!-- 4. Add 'appsettings.config' to '.gitignore' or '.tfignore' -->
    <!-- 5. Contact (whoever) for the test account credentials -->
  </appSettings>
```

**Comment by eduarddalm** [comment]
@jlattimer 
Thanks.
