### ISSUE TITLE
Test Method throws exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sammcquistan** [Microsoft/EasyRepro#474]
In this particular test that is being run, I am unable to interact with the "Add a Phone Call" activity in a contacts page. Our developers do not believe this is code that we have written, but the issue has been narrowed down to the element's onclick attribute having an assignment of "return false;". Normally, a click on this element yields the intended result of the dropdown (second image attachment) being expanded; but, using various script actions do not yield this same result. See below attachments:

Contact page overview:
![contact page](https://user-images.githubusercontent.com/49731029/57148532-655f3500-6d8f-11e9-998e-ceb13611b4b2.PNG)
 
Add Phone Call tab expanded:
![contact page add phone call expanded](https://user-images.githubusercontent.com/49731029/57148557-727c2400-6d8f-11e9-894b-bbcd282416be.PNG)

Add Phone Call code:
![add phone call code](https://user-images.githubusercontent.com/49731029/57148577-790a9b80-6d8f-11e9-9490-2ec8a4c55274.PNG)

The code used that throws this exception in particular is:
xrmBrowser.Document.getElementByXPath("//*[@id='activityLabelinlineactivitybar4210']").Click();

I have also tried using xrmBrowser.Driver.ExecuteScript to include javascript code to edit the attribute to not have this returnfalse code. How can this element be clicked?

**Comment by sammcquistan** [comment]
Solution: Used xrmBrowser.ActivityFeed.AddPhoneCall("string",false,false);

**Comment by RohitNabhi** [comment]
Yes, getting the below error while i tried with Activityfeed
"The Activity Feed is not available. Please check that the Activities tab is selected."
