### ISSUE TITLE
can you help me with on how to use xpaths in new UCI interface in Easy repro

### ISSUE THREAD

**Issue by spasupuleti27** [Microsoft/EasyRepro#477]
EG: I have tried below code for entering value in lastname in contact entity.
Knew that we can use the xrmApp.Entity.SetValue("lastname", TestSettings.GetRandomString(5, 10));

but, I would like to know how we are going to use **xpaths** as we have many customer fields which would resolve me for those.
Here is a sample code i tried but its not working and getting **NullReference Exception: Object reference not set to an object.**

_**Please find below code and help me on this:**_
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Dynamics365.UIAutomation.Api.UCI;
using Microsoft.Dynamics365.UIAutomation.Browser;
using System;
using System.Security;
using OpenQA.Selenium;

namespace Microsoft.Dynamics365.UIAutomation.Sample.UCI
{
    [TestClass]
    public class CreateContactUCI
    {

        private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());
        public static IWebDriver driver;

        [TestMethod]
        public void UCITestCreateContact()
        {

            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

                xrmApp.Dialogs.CloseWarningDialog();
                xrmApp.Navigation.OpenApp(UCIAppName.Sales);

                xrmApp.Navigation.OpenSubArea("Sales", "Contacts");

                xrmApp.CommandBar.ClickCommand("New");
                xrmApp.Entity.SelectTab("Customer 360");
               

                xrmApp.Entity.SetValue("firstname", TestSettings.GetRandomString(5, 10));
                IWebElement lastname = driver.FindElement(By.XPath("//div/input[@id='id-1fed44d1-ae68-4a41-bd2b-f13acac4acfa-6-fullname_compositionLinkControl_lastname-fullname_compositionLinkControl_lastname.fieldControl-text-box-text']"));
                lastname.Click();
                lastname.SendKeys("sudha");
            }

        }

**Comment by sammcquistan** [comment]
Do you know if this page that you are testing is a custom-written page? Or is this a page that is native to Dynamics? I believe what you're trying to do is create a new contact, so I will detail what I did to get my script to work.

I believe what you are working with may look similar to this:
![full name](https://user-images.githubusercontent.com/49731029/57702326-73307800-7623-11e9-8db1-5bc0852c1564.gif)

As you can see, clicking on "Full Name" brings up a flyout where you'll be able to enter a first, middle, and last name. The way I dealt with this was by declaring a new CompositeControl with the following code:

var FirstName = "Test";
var LastName = "TestLast";
var nameFields = new List<Field>
{
   new Field() {Id = "firstname", Value = FirstName},
   new Field() {Id = "lastname", Value = LastName}
};
xrmBrowser.Entity.SetValue(new CompositeControl() {Id = "fullname", Fields = nameFields});

Where FirstName and LastName is the actual text you would like to pass into the CompositeControl, nameFields declares the fields in the flyout you would like to insert data into, and the Id's are the divider IDs of what you want to pass data into. See below for examples:

![fullDiv](https://user-images.githubusercontent.com/49731029/57702916-9d366a00-7624-11e9-9081-2e7ea99ffcbd.PNG)

![firstName](https://user-images.githubusercontent.com/49731029/57703034-da026100-7624-11e9-9ed3-e5a6f2b7b994.PNG)

![lastName](https://user-images.githubusercontent.com/49731029/57703113-fe5e3d80-7624-11e9-9884-af2aec991631.PNG)

Hope this helps or gives a little bit of guidance. If it doesn't, please give feedback on how your page is structured and the HTML code for these fields.

**Comment by spasupuleti27** [comment]
@sammcquistan, Thank you so much for your quick response and guidance.

Currently we are using the new "**Unified interface for Dynamics 365 CRM **". This UI looks different than **WEb Client** as shown below:
![contact](https://user-images.githubusercontent.com/42530506/57842308-da982480-77e9-11e9-82c7-5338df80ab96.png)

**__what am exactly trying to do here is:_**:  In Automation, if the elements are not found by the general locators like id, class, name, etc. then XPath is used to find an element on the web page. So I am trying to set the value for "Last Name" using Xpaths so that i can get an idea on how we can use the Xpaths in the new UI of CRM as well.

One of my friend helped me on how can use the Xpaths, for this first- we to initialise the drivers and all those setup is done in the predefined webclient class.
here is the code on how can implement this so that it can be helpful to someone:

**// different ways on how we can set a value to a field**

                // 1. setting value to the last name field using Xpath
                IWebElement lastname = client.Browser.Driver.FindElement(By.XPath("//div/input[@id='id-1fed44d1-ae68-4a41-bd2b-f13acac4acfa-6-fullname_compositionLinkControl_lastname-fullname_compositionLinkControl_lastname.fieldControl-text-box-text']"));
                lastname.Click();
                lastname.SendKeys("sri");

                //2. Setting Random value to last name
                xrmApp.Entity.SetValue("lastname", TestSettings.GetRandomString(5, 10));

                //3. Setting lastname value from predefined methods in the entity
                xrmApp.Entity.SetValue("lastname", "Sri Sudha");

**Comment by sammcquistan** [comment]
@spasupuleti27 Did you solve this? You are correct in being able to use XPaths as an alternative form of identifying an element. I haven't had to use this frequently when using EasyRepro (only have had a select few use cases for them that ID or name did not pick up the element). Your third suggestion on ways to set a field value were what I was going to suggest in the event your previous code did not work.

**Comment by spasupuleti27** [comment]
@sammcquistan, its resolved and able to set value to the field in different ways

Thanks!
