### ISSUE TITLE
[NuGet Package] Date of the next release?

### ISSUE THREAD

**Issue by Haywaii** [Microsoft/EasyRepro#488]
Hi there, 

Not really an issue but I would like to know when the next release for easyRepro as a package is planned. 
Indeed many fixes/new things are on master but not release yet in the package. 
So we can use nuget package without importing generate dll from the clone we make of the repo and use them as reference in our project :)

Thx a lot,

**Comment by TYLEROL** [comment]
Hi @Haywaii - We just published version 9.1.0.2 to the NuGet feed this afternoon. Please give this a try for any existing issues you've faced.

If any problems occur, open them as appropriate on the issues list.

Thanks,
Tyler

**Comment by Haywaii** [comment]
Lovely thanks a lot, I will try it!
