### ISSUE TITLE
Change value of lookup field enters linked old entity

### ISSUE THREAD

**Issue by WinniB** [Microsoft/EasyRepro#49]
When try to change the value of a lookup the field is clicked a second time to check if the focus is already on field. If the field already has a focus this leads in entering the linked entity and therfore leaving the current page.

**Comment by dtu11** [comment]
Ok, we'll test this scenerio and provide an update.  Which version are you working with?

**Comment by WinniB** [comment]
We use Microsoft Dynamics 365 Version 1612 (8.2.2.136) on-premises

**Comment by j621z** [comment]
@WinniB   Can you please provide exact steps or elaborate on the issue? Is this consistent or intermittent behavior? Unable to repro this issue.

**Comment by WinniB** [comment]
This always happens when I try to change the value of a lookup field which is already filled with data. 

Example steps could be:
```
xrmBrowser.Entity.SetValue("my_lookup", "TextA"); //Fill for first time
xrmBrowser.Entity.SetValue("my_lookup", "TextB"); //Fill for second time / change value
```

**Comment by j621z** [comment]
@WinniB Please try using this when changing the value of a lookup field. The code you referenced above is used to change a text field. Let me know if this works for you.

xrmBrowser.Entity.SetValue(new Lookup { Name = "primarycontactid", Value = "Rene Valdes (sample)" });

**Comment by WinniB** [comment]
I tried this before, but if the value I want to set does not equal one in the dialog items (but is an valid value for the lookup) I get an invalid operation exception : "List does not have XYZ."
