### ISSUE TITLE
problem to setup

### ISSUE THREAD

**Issue by lltiago** [Microsoft/EasyRepro#51]
hey , i dont know exactly javascript. so i have some problems to startup the solution and make some tests. do you have a brief tutorial? it is not clear for me what to do.
it comes the message "main not defined'

**Comment by kaceyarnold** [comment]
The code isn't JavaScript it is C#.  What Version of VisualStudio?  What have you done to try and get the sample project working?

**Comment by dtu11** [comment]
Thanks Kacey for the community support.   As mentioned, the project is C# and won't be a javascript based solution.   Try these steps to get going and let me know if you have any issues. 

1.  Download the code for the version of CRM you are currently on (Example v8.2 branch for CRM v 8.2)
2. Open the UIAutomation solution file with Visual Studio
3. Update the app.config in the "Samples" project to provide Org, Username, Password for your CRM organization
4 Build the Solution
5. Go to Test -> Windows -> Test Explorer
6. Right click one of the tests in the list like TestOpenActiveAccount
7. Click Run Selected Test

Let us know if you run into any issues.

**Comment by lltiago** [comment]
hi. I really appreciated your reply. now I found this. what would it be?
![image](https://user-images.githubusercontent.com/9066747/33567476-75eb9398-d90a-11e7-8aba-bcb39b98d0fa.png)

**Comment by kaceyarnold** [comment]
@lltiago,
Lines 2 and three would indicate that you do not the full EasyRepro solution.  See attached image.
![mseasyrepro](https://user-images.githubusercontent.com/11790668/33567840-5afad80e-d8d9-11e7-814a-51392b3a9238.jpg)

**Comment by lltiago** [comment]
I have began from the begining and I think it is almost working. now it shows this. you guys have an idea? thanks a lot a again?
![image](https://user-images.githubusercontent.com/9066747/33575359-7af0cb2e-d923-11e7-9071-1d97d964a059.png)

**Comment by kaceyarnold** [comment]
@lltiago 
try changing 
        public void TestCreateNewAccount()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password );  //Change this line

TO

                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, ADFSLoginAction );

**Comment by dtu11** [comment]
I'm assuming this issue is resolved.  Closing the issue.
