### ISSUE TITLE
Running in Headless mode not working

### ISSUE THREAD

**Issue by sri3bala** [Microsoft/EasyRepro#511]
Running tests in Visual Studio in headless mode is not working. 

I set the TestSettings.cs file like below

public static BrowserOptions Options = new BrowserOptions
        {
            BrowserType = (BrowserType)Enum.Parse(typeof(BrowserType), Type),
            PrivateMode = false,
            FireEvents = false,
            **Headless = true,**
            UserAgent = false

        };

It is still launching the IE browser that is set in app.config. any help ?

Thanks,

**Comment by jlattimer** [comment]
IE doesn't support headless mode: 
https://stackoverflow.com/questions/46645307/how-to-set-capability-for-ie-browser-to-run-in-headless-mode

**Comment by sri3bala** [comment]
Thank you.
