### ISSUE TITLE
Selecting the value from slow loading lookup field

### ISSUE THREAD

**Issue by praveenKumarCh** [Microsoft/EasyRepro#512]

**Comment by praveenKumarCh** [comment]
Selecting the value from lookup field : Lets consider i have entered a text which is present in lookup but taking more time to load and display in between that Script failing with error List does not contain the record with the name. SO how to handle this issue. I have used this code _xrmApp.Entity.SetValue(new LookupItem { Name = p0, Value = p1 });

Is there any option that we can pass time interval or condition function wait till required data get selected.

**Comment by sammcquistan** [comment]
xrmBrowser.ThinkTime(<time in milliseconds>);

Example: If you want the script to wait for 3 seconds to load the next element you are trying to identify, you would use the following code:
xrmBrowser.ThinkTime(3000);

**Comment by praveenKumarCh** [comment]
My Query is when i am trying to select value from lookup its taking time to load. May it is taking default time to load for searched text. If the searched text is not loaded within the default time then failing to select the text from lookup i think so...

**Comment by sammcquistan** [comment]
Yes, you can use xrmBrowser.ThinkTime() to delay your script from executing lines of code. If it is taking too long for your searched text to display, you can delay your script by using the ThinkTime line of code.

**Comment by triciasinclair** [comment]
I’m experiencing this issue too. I’ve tried extending the think time in the setvalue function. This doesn’t seem to work consistently. It seems that there needs to be someway to check that the lookup has completed its search for the lookup value before selecting it. Else you get the error lookup item not found although it later becomes visible on the screen.
Is this possible?

**Comment by TYLEROL** [comment]
@triciasinclair / @sammcquistan / @praveenKumarCh - We made some changes to SetValue methods in the most recent update of the releases/v9.1 branch.

Could you try out your scenarios again and let me know if they are still an issue. If this is persisting in the most recent update, I'll take another look at this problem.

Warm regards,
Tyler
