### ISSUE TITLE
Locate a element by xpath in easyrepro framework

### ISSUE THREAD

**Issue by kishantt** [Microsoft/EasyRepro#52]
Hi All,

Can any one guide me that how to locate a element by xpath in EasyRepro framework?

We have tried with below two options, but not identifying the control.
1. { "Nav_PhoneCallPage", "img[contains(@src,'/_imgs/incoming_call_32.png')]"},
2. { "Nav_PhoneCallPage", "id(\"notescontrolactivityContainer_notescontrol\")//img[contains(@src,'/_imgs/incoming_call_32.png']"},

Thanks in advance!

**Comment by dtu11** [comment]
What are you trying to do with the framework? Most of the API's are intended to handle all the xpaths for the action you want to do.  If there is not currently an API then post the details and we can see about adding the functionality.    

If you want to reference an xpath on a custom page then it would look something like this. 

xrmBrowser.Driver.FindElement(By.Xpath("id(\"crmGrid_JumpBar\")/tbody/tr/td[1]")).Click();

**Comment by kishantt** [comment]
Thanks for the reply.

It would be more help to me if you would add below xpath in the framework.

I tried below scenario, however not worked:
Trying to click on phone call icon using below Xpaths:
//{ "Nav_PhoneCallPage"       , "id(\"notescontrolactivityContainer_notescontrol\")//img[contains(@src,'/_imgs/incoming_call_32.png']"},
            //{ "Nav_PhoneCallPage"       , "id(\"notescontrolactivityContainer_notescontrol\")//img((@title,'Phone Call Incoming'))"},
            //{ "Nav_PhoneCallPage"       , "id(\"notescontrolactivityContainer_notescontrol\")/img([@title, 'Phone Call Incoming'])"},
            //{ "Nav_PhoneCallPage"       , "img(\"Phone Call Incoming\")"},

For more information, please see attached screenshot.
![phonecall](https://user-images.githubusercontent.com/13036936/33602270-caf79218-d9d4-11e7-98c9-b11bf8ab48de.jpg)


- Thanks

**Comment by kishantt** [comment]
Can you please tell me the xpath of above highlighted (in red color)?

-Thanks

**Comment by dtu11** [comment]
To get the xpath for an element just do the following in Chrome. 

From Chrome :

- Right click "inspect" on the item you are trying to find the xpath
- Right click on the highlighted area on the console.
- Go to Copy xpath

![image](https://user-images.githubusercontent.com/26821561/34162692-3907064c-e49a-11e7-8a37-a88c323843ca.png)

**Comment by kishantt** [comment]
Working as expected with below xpath:
 { "Nav_PhoneCallPage"       , "id(\"notescontrolactivityContainer_notescontrol\")/div[4]/div/div/div[2]/div/div/div/div/a/img"}

Hence closing this issue.

- Thanks

**Comment by prachiwalke** [comment]
hi..
please help me in finding an element wit the customized XPath. below is the code:

 string brandname = "car_cust" + userData.Brand.ToLower() + userData.CarType.ToLower().Remove(3,4) + "walkin";
 string custwalkin_xpath = "//div[@data-id='" + brandname + "']/div/div[2]/div/div/div[2]/div/div[2]/div/input";
IWebElement custwalkin = client.Browser.Driver.FindElement(By.XPath(custwalkin_xpath));

where, the UserDatas are the string which we are fetching from the Excel.
at the line of "IWebElement", i am getting an exception as "Object reference not set to an instance of an object".
I have no option but to customized XPath like this..

Thanks in Advance..
