### ISSUE TITLE
An "XYZ" element is present in a page but not in a view. So when i am trying to validate this element availability in page it's failing. But when i scroll down the page and making the "XYZ" element to be visible then scrip is working fine. So could you please have look into this issue.

### ISSUE THREAD

**Issue by praveenKumarCh** [Microsoft/EasyRepro#522]

**Comment by praveenKumarCh** [comment]
Since i am working with easyRepro i am noticing that whenever updating the new fixes the exiting methods or function are getting effected. I mean it is not stable...

**Comment by praveenKumarCh** [comment]
I am Facing the above issue occasionally.

**Comment by selvafelix** [comment]
Facing the same issue, how to solve or overcome this issue any idea?
