### ISSUE TITLE
chrome not reachable

### ISSUE THREAD

**Issue by praveenKumarCh** [Microsoft/EasyRepro#524]
When i am executing as batch i am facing this issue : chrome not reachable   (Session info: chrome=72.0.3626.121)   (Driver info: chromedriver=2.38.552522

**Comment by jlattimer** [comment]
Is this still an issue?

**Comment by TYLEROL** [comment]
This may be a duplicate of #577 . @praveenKumarCh please let us know via #577 how you're batching your tests.

I'd also recommend updating your version of the ChromeDriver to match your corresponding version of the Chrome browser.

http://chromedriver.chromium.org/downloads - If you're still using Chrome v72, then I'd suggest upgrading your project to use ChromeDriver v2.46.

If you've upgraded to a newer version of Chrome, please use the corresponding ChromeDriver for that Chrome browser version.

Warm Regards,
Tyler
