### ISSUE TITLE
Cannot open record from related entity view

### ISSUE THREAD

**Issue by JINK666** [Microsoft/EasyRepro#533]
Good morning,

I have an issue with opening records from related entity. 

If I navigate to a related entity like this:

xrmBrowser.Navigation.OpenRelated("Progress");

How do I select the first row of these related entities? I want to navigate to that partical entity, so simulate that a user clicks on this entity en do some tasks there.

Thanks in advance for your help.

Best regards,

Huub

**Comment by jlattimer** [comment]
In the sample project, search for the example test [WEBTestAccountRelated](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/Web/RelatedTest.cs)

Once you've navigated to the related records grid - use this to open the first record:
```csharp
xrmBrowser.Related.OpenGridRow(0);
```

**Comment by JINK666** [comment]
Thank you for the response, I tried this and ran into the following error:

Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.Create.CreateBericht.WEBTestCreateBericht threw exception: 
System.InvalidOperationException: unknown error: Element <iframe frameborder="0" id="contentIFrame1" name="contentIFrame1" title="Inhoudsgebied" style="border: 0px none; overflow: hidden; position: absolute; left: 0px; right: 0px; height: 100%; width: 100%; visibility: visible;" cd_frame_id_="85f6f91a258cd7cbd26fbfc3fb6dbe59"></iframe> is not clickable at point (165, 379). Other element would receive the click: 
 div class="navBarOverlay" id="navBarOverlay" style="display;block"></div>

  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.17134 x86_64)


My code is now:

        retry.goToRelated("Berichten"); //this is a method that retries  
                                                          xrmBrowser.Navigation.OpenRelated(string) three times

         xrmBrowser.ThinkTime(3000);

            retry.gotoFrame("contentIFrame1");
            xrmBrowser.ThinkTime(100);
            retry.gotoFrame("area_PV_Zaak_Pv_BerichtsFrame");
            xrmBrowser.ThinkTime(1000);

            xrmBrowser.Related.OpenGridRow(0);


I tries also without going to the frames, or going to one of the frames but that does not seem to be the issue. I read on google that the span element can be the problem, but I am not sure how to proceed. 

I even tried retrieving all the td elements with  ReadOnlyCollection<IWebElement> td = driver.FindElements(By.XPath("//td"));
But this gives the same kind of issue. Any suggestions on how I might be able to work around this?

Thank you any suggestions. 

Best regards,

Huub

**Comment by JINK666** [comment]
Somehow a part of the text above will not post: 

After 

Other element would receive the click:  
<div class="navBarOverlay" id="navBarOverlay" style="display: block;"></div>


Best regards Huub

**Comment by JINK666** [comment]
Somehow I am not able to post the text that is behind "Other element would receive the click":

<div class =”navBarOverlay” id=”navBarOverlay” style=”display: block; “></div>

**Comment by JINK666** [comment]
I have been able to solve it. 

Somehow the navbaroverlay blocked the element. I found a way to work around this by using:

var navbar = retry.findElementIdWithRetry("navBarOverlay");
            driver.ExecuteJavaScript("arguments[0].setAttribute('style', 'display: none')", navbar);

After that I navigated to the proper frame and was able to use:
xrmBrowser.Related.OpenGridRow(0);

This question can be closed. 

Best regards,

Huub
