### ISSUE TITLE
SelectForm not working on 9.0

### ISSUE THREAD

**Issue by crmassociates** [Microsoft/EasyRepro#54]
Hello,

I am using SelectForm and the test is failing because the wrong area of the form is clicked when trying to select a form.

**Comment by dtu11** [comment]
Do you have the error that was thrown?

**Comment by crmassociates** [comment]
![image](https://user-images.githubusercontent.com/2859638/33786740-e9d15d1a-dc2f-11e7-81ca-e1f697bba1fd.png)

The framework clicks on the area where you would typically quick select a new section/tab of the form, instead of above it where you would pick the actual form.

Does that make sense?

**Comment by dtu11** [comment]
Makes sense.  The team will look at this issue this week.

**Comment by j621z** [comment]
@crmassociates Can you please provide the thrown error? I am able to repro this issue. Here is the code I'm using and working as expected. I tested in 8.2 and 9.0 Crm versions.

```
public void TestOpenLeadSwitchForms()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();

                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Sales", "Leads");

                xrmBrowser.Grid.SwitchView("All Leads");

                xrmBrowser.Grid.OpenRecord(0);

                xrmBrowser.ThinkTime(1000);

                var form = "Details";
                xrmBrowser.Entity.SelectForm(form, 1000);

                form = "Summary";
                xrmBrowser.Entity.SelectForm(form, 1000);

            }
        }
```

**Comment by j621z** [comment]
@crmassociates Also, can you please provide a sample of the code you're running?

**Comment by j621z** [comment]
@crmassociates Can you please provide the thrown error? I am not able to repro this issue. Here is the code I'm using and working as expected. I tested in 8.2 and 9.0 Crm versions.

```
public void TestOpenLeadSwitchForms()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();

                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Sales", "Leads");

                xrmBrowser.Grid.SwitchView("All Leads");

                xrmBrowser.Grid.OpenRecord(0);

                xrmBrowser.ThinkTime(1000);

                var form = "Details";
                xrmBrowser.Entity.SelectForm(form, 1000);

                form = "Summary";
                xrmBrowser.Entity.SelectForm(form, 1000);

            }
        }
```
@crmassociates Also, can you please provide a sample of the code you're running?

**Comment by crmassociates** [comment]
Hello, Here is the code I'm using.  I'll test again using the example above.

public void TestCreateNewLead()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();
           
                xrmBrowser.Navigation.OpenSubArea("Sales", "Leads");
                
                xrmBrowser.Grid.SwitchView("All Leads");
                
                xrmBrowser.CommandBar.ClickCommand("New");
            
                xrmBrowser.ThinkTime(2000);
                xrmBrowser.Entity.SelectForm("Information");
                List<Field> fields = new List<Field>
                {
                    new Field() {Id = "firstname", Value = "test"},
                    new Field() {Id = "lastname", Value = "user"}
                };
                xrmBrowser.Entity.SetValue("subject", "test subject");
                xrmBrowser.Entity.SetValue(new CompositeControl() { Id = "fullname", Fields = fields });
                xrmBrowser.Entity.SetValue("mobilephone", "555-555-5555");
                xrmBrowser.Entity.SetValue("description", "test description.");

                xrmBrowser.CommandBar.ClickCommand("Save");
                xrmBrowser.ThinkTime(2000);
            
            }
        }
    }

**Comment by j621z** [comment]
Please let us know if this code provided earlier worked for you. Closing this issue. Should you incur an issue, please don't hesitate to open up a new GitHub issue. Thank you
