### ISSUE TITLE
[CRM UCI] Activities tab redirect to Activities area 

### ISSUE THREAD

**Issue by Haywaii** [Microsoft/EasyRepro#549]
Hi team,

We get a weird error from this morning when using UCI functions on CRM.

**Steps to replicate with automation script:**
Go to UCI 
Open an Account
Navigate to a tab (activities here, blue circle on the image) where the tab name matched the name of one sub-area ((red circle on the image) from the left side menu

**Expect:** We open the tab
**Current:** We open the area instead

Navigate to a tab with : xrmApp.Entity.SelectTab("Activities");
Usually if we want to navigate the the sub area then we use: xrmApp.Navigation.OpenSubArea("CRM", "Activities");
(Or Account if you want to open Account sub area)

**Actions taken:**
It was working fine 3 days ago and then when coming this morning and trying our automation test it was failing...
1/ If we change the name of the tab to "Activities1" it works again perfectly fine. 
2/ We checked if we release something like a plugin/workflow/ui change (that could have an impact) between 3 days ago and today but nothing.

**Hint so far:**
It looks like MS updated something and now selecTab do area opening.
We have a workaround using selenium but it's temporary, we need to use easyRepro again.

![image](https://user-images.githubusercontent.com/4428186/59110959-0c5b6180-8938-11e9-85eb-76dc47a35f34.png)

**Comment by TYLEROL** [comment]
@Haywaii - I've merged a change by @jlattimer into the develop branch if you want to test it out and validate that it will resolve your scenario.

We have a few more items that we want to fix, and then we'll be merging the latest from develop into the releases/v9.1 branch - probably a few more days out from that merge.

**Comment by Haywaii** [comment]
@TYLEROL and @jlattimer thanks for the super quick reactivity. 
I tested it on the dev branch and it works perfectly fine.

Do you know the root cause of the issue from MS side? (i guess it's not easyrepro because nothing change on the framework). 
Good improvement tho so at least it's more specific now!
