### ISSUE TITLE
Advance find - unable to get pagesource elements to automate

### ISSUE THREAD

**Issue by priyabratamahanta** [Microsoft/EasyRepro#564]
Is there any way to get the pagesource/webelements of advancefind page ?
trying to achieve that with extension methods after
 "  xrmBrowser.Navigation.OpenAdvancedFind();"

xrmBrowser.Driver still contains main page not advancefind page elements. Is there any way to get advance find page elements ?

**Comment by TYLEROL** [comment]
Hello @priyabratamahanta - We currently have very limited support of the Advanced Find window. We have an item in the roadmap to work on adding these capabilities, but I do not have an ETA.

We could potentially add more capabilities to interact with the CommandBar buttons on the AdvancedFind page, however query customization will be more difficult.

Could you please let us know some of the scenarios you're trying to accomplish using the Advanced Find window?

Warm Regards,
Tyler
