### ISSUE TITLE
[CommandBar Management] Number of button not accessible

### ISSUE THREAD

**Issue by Haywaii** [Microsoft/EasyRepro#565]
From one of my scenario i want to make sure all buttons in the top ribbon (command bar) on different entities are displayed.

So far i try to get acces through: 
xrmApp.CommandResults.Count

But it doesn't displayed the result i expected because it's not the commandBar button per se.

I also tried using xrmApp.CommandBar. but I can't find anything related to count the number of button. 

By going deeper i can't find a property or a specific function for it.

Do you know if we can do it or so far it's only with selenium? (which is fine for me)

Thanks,

**Comment by TYLEROL** [comment]
Hello @Haywaii 

There is not currently a Count method on the CommandBar - however this is something we could look at adding. I don't think it would be too difficult to add based on the existing logic for targeting CommandBar buttons in ClickCommand.

For now, you would need to do handle this with raw selenium code. Marking this as a feature enhancement for consideration.

Thanks,
Tyler

**Comment by Haywaii** [comment]
No problem @TYLEROL , thanks for your quick answer again.
It works fine with selenium code ;)

I don't think it will be too difficult either. I am busy with my automation but once it's in good shape i can take a look to add some enhancement if you are keen to :)

**Comment by TYLEROL** [comment]
@Haywaii - I've introduced a new method for UCI and WebClient under CommandBar.GetCommandValues(bool checkMoreCommandsMenu = false), currently in the develop branch via PR #591 .

This method will return a list of values from the command bar, with an option flag to return values from the more commands menu if desired. You should be able to use the Count property against the returned list of values.

Please let us know if you have any issues with this set of changes. I've assigned the milestone to the PR as a rough estimate for when this change should be merged into the releases/v9.1 branch.

_Edit: Please note that this change only returns primary menu options and does not account for "submenu" options._

Warm Regards,
Tyler

**Comment by Haywaii** [comment]
Hi @TYLEROL 

Thanks for the update! I tested it and it works like expected. I can now get value and number.
The parameters to get more command are super cool as well and work fine. 

You can merge it on master!

**Comment by Raji254** [comment]
Hi @TYLEROL,
 "CommandBar.GetCommandValues" is really helpful to get primary menu available on commandbar,  I need to check with submenu from available ribbon buttons also, could you please suggest is there any way for it.

Thanks,
Raji
