### ISSUE TITLE
GetValue from Ribbon Items

### ISSUE THREAD

**Issue by kishkk84** [Microsoft/EasyRepro#569]
Hi

I am quite a newbie to EasyRepro and trying to use it to automate Dynamic CRM 365.

I am trying to getValue from the items in the ribbon like Delivery, Enquiries, Marketing etc.

I am able to open the menu but not sure how to get the values or perform click on each.
xrmBrowser.Navigation.OpenMenu();

![image](https://user-images.githubusercontent.com/19428883/59518815-691dc580-8ebe-11e9-9816-04cba02812d0.png)

Any help is much appreciated!!!

Cheers

**Comment by TYLEROL** [comment]
Thanks for raising this inquiry @kishkk84 . We previously did not have this capability to return available Area values, however PR #570  was recently merged into the current develop branch. In the near future this will get merged into releases/v9.1

The PR has some samples available, so if you wished to test it, you could try through the develop branch for now.

To click one of the items, you should call the following method:

```
                var areaName = "Deliveries";
                var subAreaName = "Accounts";
                xrmBrowser.Navigation.OpenSubArea(areaName, subAreaName);
```

The example above will call the OpenSubArea method which will first look for an Area with the name 'Deliveries' and click that. Once this is clicked, the method will then try to retrieve all available SubAreas and click on the title that matches the provided value (e.g. Accounts).

We have samples in the Sample project, listed under the Web or UCI folder depending on the client type being used (Web for the example you've shown). I hope these are helpful in showing different ways to use the methods whether it be for Opening/Reading, Creating, Updating of records - or different ways to interact with the CommandBar buttons, general Navigation, or interacting with different Dialog types that may appear when performing certain actions in Dynamics 365.

Please let me know if you need any additional assistance in using EasyRepro for Dynamics 365. I'll update this post once PR #570 has been made available to the releases/v9.1 branch

Warm Regards,
Tyler
