### ISSUE TITLE
Pending email warning dialog box 

### ISSUE THREAD

**Issue by maichung77** [Microsoft/EasyRepro#57]
This is my first time using this tool.  What API can I use to close the Pending email warning dialog box that is automatically shown after login?  Thanks in advance for your help.

**Comment by gohiljayraj** [comment]
Even we are facing the same issue.

**Comment by dtu11** [comment]
This is an issue we're currently working on.  Once the update is made and released, I'll update the Issue here. 

Thanks for the feedback

**Comment by maichung77** [comment]
Great, thanks for looking into it!

**Comment by kaceyarnold** [comment]
Here is what I did to get around the email not sent dialog box.
 public static void ADFSLoginAction(LoginRedirectEventArgs obj)
        {
            IWebElement iframeElement;
            IWebDriver Cdriver = obj.Driver;
            Cdriver.FindElement(By.Id("passwordInput")).SendKeys(obj.Password.ToUnsecureString());

            //Cdriver.ClickWhenAvailable(By.Id("submitButton"), new TimeSpan(0, 0, 6));
            Cdriver.FindElement(By.Id("submitButton")).Submit();
            Cdriver.FindElement(By.Id("idSIButton9")).Submit();
            Cdriver.WaitForPageToLoad();
            try
            { //Workaround for the email not sent warning dialog in the QA environement.
                iframeElement = Cdriver.FindElement(By.Id("InlineDialog_Iframe"));
            }//close try
            catch (NoSuchElementException) { return; } //If there is no warning dialog we are done
            //TODO: Log presence of warning dialog 
            //Since we have an Iframe switch to it
            Cdriver.SwitchTo().Frame(iframeElement);

            Cdriver.FindElement(By.Id("crmDialogFooter"));
            Cdriver.FindElement(By.XPath("//*[@id=\"crmDialogFooter\"]/div[2]"));
            //Due to issues with the framework click is not handled correctly and throws a no such element error
            // Thus the try catch wrapper.
            try { Cdriver.FindElement(By.XPath("//*[@id=\"butBegin\"]")).Click(); }
            catch (NoSuchElementException)
            { //Log that we closed a dialog window.
            }//close catch for Click action

        }//close Internal ADFS login Action

**Comment by gohiljayraj** [comment]
Thanks for your help Kacey Arnold.. Its working for me now. Only concern I have here is if given Xpath or Ids get change in subsequent CRM product patch. We need to keep updating these id's

**Comment by kaceyarnold** [comment]
Yes, but at least you can move forward.  Which is what matters?  Do what I have taken to doing,
/* ---------------------- This is a hack to get around a bug --------------------------
code
*/ ---------------- End of Hack --------
Now when the fix comes through the hacks are easy to find.
On a side note I thought the email not set up issue was just the nature of tests systems, so I went around it out of habit not even thinking of it as a bug.  :)

**Comment by j621z** [comment]
This issue has been mitigated and should be pushed to GitHub soon.
