### ISSUE TITLE
can't create related lead from leads editable subgrid on account form

### ISSUE THREAD

**Issue by eduarddalm** [Microsoft/EasyRepro#575]
Help Wanted

Hi,
I am trying to access the new button on a related leads subgrid on an account form.

So far I have implemented this: 

```
                **//Open the Tab Leads and Opportunities and create a new Lead**
                xrmBrowser.Entity.ExpandTab("Leads and Opportunities");
                **//Click the lookup add button**
                xrmBrowser.Entity.ClickSubgridAddButton("Leads");
```

![image](https://user-images.githubusercontent.com/25723165/59661001-27d13280-91aa-11e9-9fcf-c7d2183e3c53.png)

![image](https://user-images.githubusercontent.com/25723165/59661186-88606f80-91aa-11e9-911b-c028021f5dc1.png)

```
                **//Select the lookup on the subgrid**
                xrmBrowser.Entity.SelectSubgridLookup("Leads");
```

![image](https://user-images.githubusercontent.com/25723165/59661275-bc3b9500-91aa-11e9-894e-745c94e43d3e.png)

Now I want to access the new button in the right lower corner, but can't find any function that allows me to do that.

I can invoke a new lead but this creates a NON related lead.
![image](https://user-images.githubusercontent.com/25723165/59665056-78e52480-91b2-11e9-98c5-cb7444407483.png)

Thanks in advance!
Eduard Dalm

**Comment by TYLEROL** [comment]
This has been replaced by the Unified Interface. The new APIs will be:

`xrmApp.Entity.SubGrid.ClickCommand(string subgridSchemaName, string commandButton, string subCommandButtonIfRequired);`
