### ISSUE TITLE
Chrome login failed - Test run fails due to login redirection

### ISSUE THREAD

**Issue by ArvindBhat83** [Microsoft/EasyRepro#576]
Hello!,

After making my required changes and executing the test case, chrome launches and it connects to CRM, it enters the specified credentials, then chrome redirects to my organization page where in it expects the credentials to be specified again.  The code isn't able to handle that as it expects CRM to be launched by then.  I am able to get over this during debug as I can manually key it in to proceed.  This should be something you have encountered?

**Comment by eduarddalm** [comment]
Hi,
The login procedure assumes single signon. 
If you are connecting out side your domain, you need to connect through a VPN for ADFS to work.
Hope this helps
Regards,
Eduard

**Comment by sammcquistan** [comment]
I believe you are running into an issue that I ran into right away when I was creating my automation test suite. Our previous QA engineer created a new class file called "LoginHelper" and this seemed to help a lot. Try this code and see if this works:

//create a new class under Microsoft.Dynamics365.UIAutomation.Sample.Web named "LoginHelper.cs".

using Microsoft.Dynamics365.UIAutomation.Api;
using Microsoft.Dynamics365.UIAutomation.Browser;
using OpenQA.Selenium;

namespace Microsoft.Dynamics365.UIAutomation.Sample.Web
{
    public class LoginHelper
    {
        public static void ADFSLoginAction(LoginRedirectEventArgs obj)
        {
            IWebElement iframeElement;
            IWebDriver Cdriver = obj.Driver;
            Cdriver.FindElement(By.Id("passwordInput")).SendKeys(obj.Password.ToUnsecureString());

            //Cdriver.ClickWhenAvailable(By.Id("submitButton"), new TimeSpan(0, 0, 6));
            Cdriver.FindElement(By.Id("submitButton")).Submit();
            Cdriver.FindElement(By.Id("idSIButton9")).Submit();
            Cdriver.WaitForPageToLoad();
            try
            { //Workaround for the email not sent warning dialog in the QA environement.
                iframeElement = Cdriver.FindElement(By.Id("InlineDialog_Iframe"));
            }//close try
            catch (NoSuchElementException) { return; } //If there is no warning dialog we are done
            //TODO: Log presence of warning dialog 
            //Since we have an Iframe switch to it
            Cdriver.SwitchTo().Frame(iframeElement);

            Cdriver.FindElement(By.Id("crmDialogFooter"));
            Cdriver.FindElement(By.XPath("//*[@id=\"crmDialogFooter\"]/div[2]"));
            //Due to issues with the framework click is not handled correctly and throws a no such element error
            // Thus the try catch wrapper.
            try { Cdriver.FindElement(By.XPath("//*[@id=\"butBegin\"]")).Click(); }
            catch (NoSuchElementException)
            { //Log that we closed a dialog window.
            }//close catch for Click action

        }//close Internal ADFS login Action

    }//close login helper class
}



Now, in your TestMethods, you're going to have this default code intended for SSO, looking like this: xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);

Edit that code and use this instead:
xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, LoginHelper.ADFSLoginAction);
xrmbrowser.GuidedHelp.CloseGuidedHelp();

**Comment by ArvindBhat83** [comment]
> Hi,
> The login procedure assumes single signon.
> If you are connecting out side your domain, you need to connect through a VPN for ADFS to work.
> Hope this helps
> Regards,
> Eduard

Hi Eduard - I am connecting from MS n/w itself.  Its just I am connecting with my v-id.  I don't think that should case the redirection and its something most of us would experience. 

Regards,
Arvind

**Comment by TYLEROL** [comment]
@ArvindBhat83 - As @sammcquistan suggested, and from your description of events, you'll need to utilize the alternate login method using a login helper redirect method. The intent behind this is to deviate from the standard O365 login experience and allow you to handle custom ADFS pages.

Depending on the element IDs for your custom forms login experience, you may need to make small tweaks to the suggested methods. Please let us know if you need any further assistance on this.

Regards,
Tyler
