### ISSUE TITLE
xrmApp.Entity.SelectLookup(customer) to create case in UCI not working

### ISSUE THREAD

**Issue by ArvindBhat83** [Microsoft/EasyRepro#578]
I tried several ways to make this xrmApp.Entity.SelectLookup(customer) work while trying to create case in UCI but its not working. I saw some suggestion that a timeout would work but it didn't.  Request your help.

**Comment by TYLEROL** [comment]
Thanks for raising this issue @ArvindBhat83 . I'm going to setup a repro similar to what you described. If I have any issues I'll reach back out - otherwise will let you know once a fix is made available.

Warm Regards,
Tyler

**Comment by SachchinAnnam** [comment]
@ArvindBhat83 : 
Update EasyRepro references and try the below snippet:
LookupItem parentID = new LookupItem { Name = "account", Value = "Testing Account" };
                xrmApp.ThinkTime(5000);
                xrmApp.Entity.SetValue(parentID);
                xrmApp.ThinkTime(3000);

**Comment by TYLEROL** [comment]
@ArvindBhat83 - We've published some changes today as a part of build 9.1.0.6210 and to the latest releases/v9.1 branch. Could you please test this again?

If the problem is not resolved, please re-open this issue and notify me for further investigation.

Regards,
Tyler
