### ISSUE TITLE
xrmBrowser.LoginPage.Login not working

### ISSUE THREAD

**Issue by gohiljayraj** [Microsoft/EasyRepro#58]
xrmBrowser.LoginPage.Login is not working if CRM is configured for token-based authentication and have a custom page to login which pass security token and redirect to CRM.

**Comment by gohiljayraj** [comment]
Below code opens the browser, inputs username and password and click submit button on login page. Page redirected to CRM Home page and after that I am getting below exception:
**Code**
           string userName = ConfigurationManager.AppSettings["Uname"].ToString();
            string password = ConfigurationManager.AppSettings["Pwd"].ToString();
            Uri xrmUri = new Uri(ConfigurationManager.AppSettings["CrmUrl"].ToString());
            
            xrmBrowser.GoToXrmUri(xrmUri);            
            xrmBrowser.Driver.FindElement(By.Id("UsernameTextBox")).SendKeys(userName);
            xrmBrowser.Driver.FindElement(By.Id("PasswordTextBox")).SendKeys(password);

            xrmBrowser.Driver.ClickWhenAvailable(By.Id("SubmitButton"), new TimeSpan(0, 0, 2));
            xrmBrowser.Driver.WaitForPageToLoad();

**Exception**

OpenQA.Selenium.StaleElementReferenceException occurred
  HResult=0x80131500
  Message=Element is no longer valid
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.get_Location()
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.EventDriver_ElementClicked(Object sender, WebElementEventArgs e)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.OnElementClicked(WebElementEventArgs e)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass2_0.<ClickWhenAvailable>b__0(IWebDriver d)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(IWebDriver driver, By by, TimeSpan timeout)

**Comment by j621z** [comment]
@gohiljayraj This issue has been mitigated and will be pushed to GitHub soon.

**Comment by tipsey** [comment]
Having similar issues with On-premise version: 
OpenQA.Selenium.StaleElementReferenceException: 'stale element reference: element is not attached to the page document
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565498 

Debug errors here:
public static IWebElement ClickWhenAvailable(this IWebDriver driver, By by, TimeSpan timeout)
        {
            var element = driver.FindElement(by);

            WaitUntilClickable(driver,
                                by,
                                timeout,
                                d => { element.Click(); },
                                e => { throw new InvalidOperationException($"Unable to click element."); });



            return element;
        }
` [TestClass]
    public class CustomLogin
    {
        string _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToString();
        string _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToString();
        Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());

        [TestMethod]
        public void TestCustomLogin()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.GoToXrmUri(_xrmUri);
                xrmBrowser.Driver.WaitForPageToLoad();

                ///Set Username, password and click Submit button
                xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_UsernameTextBox")).SendKeys(_username);
                xrmBrowser.ThinkTime(1000);
                xrmBrowser.Driver.FindElement(By.Id("ContentPlaceHolder1_PasswordTextBox")).SendKeys(_password);
                xrmBrowser.ThinkTime(1000);

                xrmBrowser.Driver.ClickWhenAvailable(By.Id("ContentPlaceHolder1_SubmitButton")).Click();
                xrmBrowser.Driver.WaitForPageToLoad();

            }
        }`
