### ISSUE TITLE
Issue with setting a phonecall format field in UCI

### ISSUE THREAD

**Issue by chfarr** [Microsoft/EasyRepro#580]
Hi, 

I am having difficulties trying to setvalue for single line of text fields on a CRM form which have a format other than Text. Example if you look at telephone1 field on a form i keep getting the following error when trying to set it 

_**Details: invalid element state: Element is not currently interactable and may not be manipulated
(Session info: chrome=75.0.3770.100)
(Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 6.1.7601 SP1 x86_64)**_  

all im doing is trying to set it normally and the field is active on the form 

xrmApp.Entity.SetValue("telephone1", "12345678");

Anyone experienced this? i habe also tried on a field having a duration format and whilst i could actually set that i couldnt get rid of the --- that now shows up on the form when there is no value so the format threw an exception. 

![Capture](https://user-images.githubusercontent.com/25501996/59852852-fd30d680-936f-11e9-8476-ce78edae6b30.PNG)

Thanks
Charmaine

**Comment by TYLEROL** [comment]
Thanks @chfarr for raising this. I'll quick setup a repro and assuming no issues getting it reproduced, will let you know once a fix is made available.

Warm Regards,
Tyler
