### ISSUE TITLE
Not able to click on command bar.I have shown the diff where it is not working with images. 

### ISSUE THREAD

**Issue by praveenKumarCh** [Microsoft/EasyRepro#587]
![Image-1](https://user-images.githubusercontent.com/50700992/60035224-f84e8880-96c9-11e9-8607-521cf06f5eb0.png)

**As shown in the above image code working fine.**

![Image-2](https://user-images.githubusercontent.com/50700992/60035237-013f5a00-96ca-11e9-8eff-2c36d865cb41.png)
**For this code is not working** 
_**xrmApp.CommandBar.ClickCommand("Add New Contact");**

**Comment by TYLEROL** [comment]
Hi @praveenKumarCh,

Could you try adjusting your last code line to this instead?

`                _xrmApp.RelatedGrid.ClickCommand("Add New Contact");
`

The idea behind this RelatedGrid.ClickCommand() method is that it focuses on the unique Command Bar objects that show up _within the context of a Related Grid_.

You'll notice from your provided screenshots, there are technically _two_ Command Bars present. One under the navigation header, and another within the grid.

I believe this should resolve the problem for you - and hopefully will help you adjust/design your tests accordingly depending on which Command Bar you're trying to interact with.

If you have further issues, or if this is not working as I described, please let us know.

Warm Regards,
Tyler

**Comment by praveenKumarCh** [comment]
after using **_xrmApp.RelatedGrid.ClickCommand("Add New Contact"); below error is coming.**
![image](https://user-images.githubusercontent.com/50700992/60093026-04882380-9766-11e9-8296-b269cca02089.png)

I tried with **_client.ClickRelatedCommand(p0)** but no luck...
![image](https://user-images.githubusercontent.com/50700992/60093302-bb849f00-9766-11e9-94ae-a5f11eee4db8.png)

**Comment by praveenKumarCh** [comment]
In first two images if you see the image screen size where we have more commands ("...") then 
**_xrmApp.CommandBar.ClickCommand("Add New Contact");** is working fine 

But not same with second screen here it is failing

**Comment by TYLEROL** [comment]
Thanks @praveenKumarCh . I'll take a look at this and report back my findings.

Regards,
Tyler

**Comment by TYLEROL** [comment]
@praveenKumarCh - Quick update for some context on my earlier replies. In the first screenshot below, I've shown the two different CommandBars and expected method use cases depending on which CommandBar you need to interact with.

![image](https://user-images.githubusercontent.com/29415524/60104724-a3d9f600-9727-11e9-8730-26a601165f77.png)

In the 2nd screenshot below, I've shown the F12 Dev Tools page elements using the Inspector for targeting the command list of the RelatedGrid.

![image](https://user-images.githubusercontent.com/29415524/60104838-dbe13900-9727-11e9-8646-84d1b019519b.png)

In your example, it appears the command objects are within the grid itself, and in neither of the places we would expect them for either CommandBar.ClickCommand(), or RelatedGrid.ClickCommand().

**ASK: Could you target the command for Add New Contact using Chrome Dev Tools and provide a screenshot of the page elements - which should look somewhat similar to the example I've shown above**

Thanks,
Tyler

**Comment by Haywaii** [comment]
@TYLEROL 
I think the issue here is the same than the one i reported as enhancement in https://github.com/microsoft/EasyRepro/issues/586 :)

I checked on my side as well and the command object are within the grid itself so neither the place the two method are looking hence the error we get.

**Comment by TYLEROL** [comment]
@Haywaii - Thanks for updating here. Reading your post, I agree these sound identical now.

Could you let me know what version of Dynamics you are testing against, as well as the Client Version listed on  your UCI app? I'll discuss with our internal UCI team on how to "shift" the command bar into the grid, assuming its not related to a newer update.

Regards,
Tyler

**Comment by Haywaii** [comment]
@TYLEROL i am using Dynamics v10 (the latest version). 
I don't have access to the client version listed on my UCI app right now but i will give you the details tomorrow when back to work! 

Thanks for your quick answer.

**Comment by praveenKumarCh** [comment]
> Could you target the command for Add New Contact using Chrome Dev Tools and provide a screenshot of the page elements - which should look somewhat similar to the example I've shown above

![image](https://user-images.githubusercontent.com/50700992/60157101-9dbd4580-980b-11e9-8c49-2a1b5be413c6.png)

**Comment by praveenKumarCh** [comment]
Can you please look into this issue as well Issue No:577

**Comment by Haywaii** [comment]
@TYLEROL by client version you mean the easyrepro client or the one for UCI in CRM?
EasyRepro i use the latest one, 9.1.0.5230
UCI in CRM, the client app version is 1.3.1894-190618-173044

**Comment by rcjohnson113** [comment]
@Haywaii @TYLEROL [Issue#279](https://github.com/Microsoft/EasyRepro/issues/279) has some code to help with this subgrid on the form clicking commands.

I did it by label of the sub grid as the actual metadata name of the sub grid I couldn't find.

**Comment by Haywaii** [comment]
@rcjohnson113 thanks a lot! It's on dev branch isn't it?

**Comment by praveenKumarCh** [comment]
Any updates on it...?

**Comment by remyanambala** [comment]
Hi,

I faced same issue with an Add button and on debugging found that the Xpath in App reference is different to what is in page. It worked for me after changing xpath slightly - removed the "Associated " text from search.

code:
xrmApp.RelatedGrid.ClickCommand("Add");

AppElementReference.cs
change below line:
{ "Related_CommandBarButton", "//button[contains(., '[NAME]') and contains(@data-id,'SubGridAssociated')]"},
to:
{ "Related_CommandBarButton", "//button[contains(., '[NAME]') and contains(@data-id,'SubGrid')]"},

I am not sure whether above will affect some other tests, so I added code to directly access the element instead. Please find below the code:
IWebElement elementAdd = client.Browser.Driver.FindElement(OpenQA.Selenium.By.XPath("//button[@aria-label='Add']"));
elementAdd.Click();

Hope this helps.

Regards
Remya

**Comment by rafism13** [comment]
> @Haywaii @TYLEROL [Issue#279](https://github.com/Microsoft/EasyRepro/issues/279) has some code to help with this subgrid on the form clicking commands.
> 
> I did it by label of the sub grid as the actual metadata name of the sub grid I couldn't find.

Hi rcjohnson113, the code you mentioned is not clicking on the button.code is getting executed but its not clicking on the Add button.
In the code which you have mentioned
 var items = parentElement.FindElements(By.TagName("li"));

this items count is coming as null. 

please suggest

**Comment by rafism13** [comment]
> Any updates on it...?

Did the issue got resolved for you

**Comment by Haywaii** [comment]
@rafism13 i didn't have a chance to take another look so can't help.
Maybe @rcjohnson113 or @TYLEROL will have more feedback.
