### ISSUE TITLE
[BUG] Set MultiValueOptionSet broken

### ISSUE THREAD

**Issue by mVermaat** [Microsoft/EasyRepro#598]
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Setting the value of a MultiValueOptionSet doesn't work. Getting an error that the given key is not present in de dictionary on the line listed below.

string xpath = AppElements.Xpath[AppReference.MultiSelect.SelectedRecord].Replace("[NAME]", Elements.ElementId[option.Name]);

It's because my own field is not in the Elements dictionary. Why does my field have to be in there? That doesn't make sense when relating to the rest of the EasyRepro functionality. Secondary when looking into the XPATH queries, they don't seem to be correct, so even if I would add my field to the elements dictionary, it doesn't work.

**Comment by rcjohnson113** [comment]
Add a screenshot of the multiselect field on the form and show how you called it in code.

**Comment by mVermaat** [comment]
`
[TestMethod]
        public void TestMultiSelect()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

                xrmApp.Navigation.OpenApp("CRM Hub");

                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.Entity.SetValue(new MultiValueOptionSet { Name = "mv_accounttype", Values = new string[] { "Supplier", "Buyer" } });

                xrmApp.Entity.Save();

            }
        }
`

This is the field on the form:

![image](https://user-images.githubusercontent.com/13309338/60947353-9eb4a380-a2f0-11e9-86d3-a406aeb6abb4.png)

And the customizations to see the logicalname

![image](https://user-images.githubusercontent.com/13309338/60947409-c60b7080-a2f0-11e9-8d26-fc9f11317fea.png)

**Comment by shijinzu** [comment]
I ran into the same issue with my project. Any idea when this issue will be resolved?

**Comment by ankitadeore19** [comment]
I am also not able to select values in the multiselect option set, any resolution for the above issue?

**Comment by shariquekhan1997** [comment]
Check out this blog for a workaround:
https://www.inogic.com/blog/2020/06/how-to-set-value-for-multi-select-attribute-in-dynamics-365-crm-using-xpath-in-easyrepro/

**Comment by shijinzu** [comment]
Thank you for posting this workaround. Could you share an example of get value on multi-select?

**Comment by shariquekhan1997** [comment]
> Thank you for posting this workaround. Could you share an example of get value on multi-select?
https://www.inogic.com/blog/2020/06/how-to-set-value-for-multi-select-attribute-in-dynamics-365-crm-using-xpath-in-easyrepro/

Selected Items are always stored in a div container with class name “msos-selecteditems-container”, the values are in the title attribute. To fetch the values from there please check the below code.

![image](https://user-images.githubusercontent.com/36981186/104844289-73ebd800-58f5-11eb-88d6-fc410140f84b.png)


var container = win.HasElement(By.XPath(“//*[@class=’msos-selecteditems-container’]”));
var selectedItems = container.GetAttribute(“title”);

Hope this helps,
Thanks!
