### ISSUE TITLE
Does this work for On-Premise CRM version?

### ISSUE THREAD

**Issue by gohiljayraj** [Microsoft/EasyRepro#60]
As per documentation:
Easy Repro supports below CRM Versions	
 -- Microsoft Dynamics® CRM Online 2016 Update (8.1.1.1003) (DB 8.1.1.1003)
 -- Microsoft Dynamics 365 Version 1612 (8.2.1.185) (DB 8.2.1.185) online
 +- Microsoft Dynamics® CRM Online 2016 8.1 (8.1.1.x) (DB 8.1.1.x)
 +- Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
 +- Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online

Can't we use this for Dynamics 365 on-premises version?

**Comment by dtu11** [comment]
You would have to handle the login for the application.  If you're using integrated authentication then you would just need to build in a wait time. It would look something like this. 

                xrmBrowser.Driver.WaitUntilVisible(By.XPath("id(\"crmTopBar\"")
                        , new TimeSpan(0, 0, 60),
                        e => { xrmBrowser.Driver.WaitForPageToLoad(); },
                        f => { throw new Exception("Login failed."); });

If you're using IFD then look at the ADFSLogin.cs  sample test.  After that then all of the API's should work. 

If you're getting the windows login prompt then the API's will not handle that.

**Comment by gohiljayraj** [comment]
Thanks Daren for your reply. I am able to login in CRM for IFD, but ADFSLogin sample does't seems to be working. This is what I have done:

public static void Login()
        {
 SecureString userName = ConfigurationManager.AppSettings["Uname"].ToSecureString();
            SecureString password = ConfigurationManager.AppSettings["Pwd"].ToSecureString();
            Uri xrmUri = new Uri(ConfigurationManager.AppSettings["CrmUrl"].ToString());
            xrmBrowser.GoToXrmUri(xrmUri);

            xrmBrowser.LoginPage.Login(xrmUri, userName, password, ADFSLoginAction);
}
public static void ADFSLoginAction(LoginRedirectEventArgs args)
        {
           
            args.Driver.FindElement(By.CssSelector("#UsernameTextBox")).SendKeys(args.Username.ToUnsecureString());
            args.Driver.FindElement(By.CssSelector("#PasswordTextBox")).SendKeys(args.Password.ToUnsecureString());
            
            args.Driver.FindElement(By.CssSelector("#SubmitButton")).Submit();
            //args.Driver.FindElement(By.Id("idSIButton9")).Submit();
            xrmBrowser.Driver.WaitUntilVisible(By.XPath("id(\"crmTopBar\"")
                    , new TimeSpan(0, 0, 60),
                    e => { xrmBrowser.Driver.WaitForPageToLoad(); },
                    f => { throw new Exception("Login failed."); });

            try
            { //Workaround for the email not sent warning dialog in the QA environement.
                var iframeElement = args.Driver.FindElement(By.Id("InlineDialog_Iframe"));
                args.Driver.SwitchTo().Frame(iframeElement);
            }//close try
            catch (NoSuchElementException) { return; } //If there is no warning dialog we are done
                                                       //TODO: Log presence of warning dialog 
                                                       //Since we have an Iframe switch to it
            
            args.Driver.FindElement(By.Id("crmDialogFooter"));
            args.Driver.FindElement(By.XPath("//*[@id=\"crmDialogFooter\"]/div[2]"));
            //Due to issues with the framework click is not handled correctly and throws a no such element error
            // Thus the try catch wrapper.
            try { args.Driver.FindElement(By.XPath("//*[@id=\"butBegin\"]")).Click(); }
            catch (NoSuchElementException)
            { //Log that we closed a dialog window.
            }//close catch for Click action
        }

**Comment by Kraviecc** [comment]
Hi,

@gohiljayraj - I've created pull request with my changes to make it work with onprem versions, check this out :) If you'll have any sugestions, let me know.

**Comment by th0car** [comment]
Thank you for this @Kraviecc ! I have started testing your sample solution and it seems to be working just fine this far. Does the fact that the CLA requirements were met mean that your branch will actually be merged into the official master? 
I work with products that needs to be continously tested for both On Prem and Online deployment so for me it would really be a great addition to Easyrepro if it officially started supporting also the latest On Prem CRM versions. Let me know if I can help out in any way!

**Comment by Kraviecc** [comment]
Thanks, @th0car !

Unfortunately, the CLA requirements are just one thing before real Microsoft's analyze takes place and before their decision whether it should be merged or not. I've done the really huge changes in the whole solution so I'm afraid it's too much, but who knows?

Regardless of whether it'll be merged or not, I plan to maintain and develop new features/functionalities inside my fork. I'll be glad if you want to help me out or give some advice or point some stuff which should be implemented (or bugs if any) - feel free to commit updates. To be honest, I don't have much time at this moment, so I'm afraid that in the near future there will be no updates.

Keep in touch!

**Comment by TYLEROL** [comment]
To close the loop on this thread. A new OnPremises release branch was created to track OnPremises specific scenarios. The branch should work as-is for now. If issues are identified we encourage to either raise new issues and we'll attempt to tackle them as time allows, or for the community to check in fixes for review.
