### ISSUE TITLE
[BUG] OpenEntity fails when first tab is hidden

### ISSUE THREAD

**Issue by mVermaat** [Microsoft/EasyRepro#602]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
When calling the following code and the form has its first tab disabled. It gets into a timeout as the method waits until the first tab is visible.

- Hide first tab on the account form and publish
- Call 'xrmApp.Entity.OpenEntity("account", Guid.Parse("{GUIDHERE}"));'

**Comment by mVermaat** [comment]
This can be fixed by waiting for the parent element (the tab list) to be clickable instead of the first tab. This way you don't need a certain tab to be visible. Created PR

**Comment by TYLEROL** [comment]
Thanks @mVermaat . This change that you submit will be included in a new PR #609  against the develop branch. I will be doing a push to the releases/v9.1 branch later today and updating the NuGet feed with a new package version to also include the change.
