### ISSUE TITLE
[BUG] EasyRepro doesn't recognize crm12.dynamics.com as an online domain

### ISSUE THREAD

**Issue by NicolasPrats** [Microsoft/EasyRepro#611]
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [X] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [X] Firefox
  - [X] IE
  - [X] Edge

**Describe the bug**  
When running EasyRepro on an organization whose host url ends with "crm12.dynamics.com", the login is not sent to the browser. After investigating, this is because the array ```Constants.Xrm.XrmDomains``` does not contain the value ".crm12.dynamics.com" (the new domain for the new datacenter in France).

**Code to reproduce**  

```csharp
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
```

**Comment by TYLEROL** [comment]
Related PR #688 . An updated NuGet package should be made available later today (9.1.0.7606).
