### ISSUE TITLE
Wrong selector for GridSearch

### ISSUE THREAD

**Issue by jacoblarsen** [Microsoft/EasyRepro#62]
Hi
Thanks for an easy-to-use test framework :-)

In 9.0` xrmBrowser.Grid.Search` didn't work for me. 
search action would not fire. 

Following change to "XrmElementReference.cs" worked for me

```
//{ "Grid_FindCriteriaImg"       , "id(\"crmGrid_findCriteriaImg\")"},
   { "Grid_FindCriteriaImg"       , "id(\"crmGrid_findCriteriaButton\")"},

```

**Comment by dtu11** [comment]
Ok, I'll look at this and get it updated. 

Thanks for the feedback

**Comment by TYLEROL** [comment]
@jacoblarsen - thanks again for raising this to us.

The code base has been updated and I've confirmed that the search action now functions as expected. I'll close the issue at this time however if you have any additional questions related to this, please re-open the issue.
