### ISSUE TITLE
UCI 9.1 :  After Search xrmApp.Grid.OpenRecord(index) method Is not Opening Searched Record.

### ISSUE THREAD

**Issue by vcinampudi** [Microsoft/EasyRepro#622]
I have searched a record in Grid in Account\Leads\Contacts \etc... Modules but when trying to open the Searched record from Results Grid is neither opening nor throwing an exception.

**Comment by Haywaii** [comment]
Can you give us more details of what you do please?
Screenshot, code will be useful to help you.

Unlikely people/dev from easyRepro will have time to help if you throw your error just like this :)

**Comment by vcinampudi** [comment]
1=>                xrmApp.Grid.Search("ABC");
2=>                if ((xrmApp.Grid.GetGridItems()).Count == 1)
3=>              {
4=>                    xrmApp.Grid.OpenRecord(1);
5=>              }

The above code is searching the specific record but when trying to open searched record(Line 4) from results it is not opening.

I don't see any error but not able to open after search the record.

**Comment by Haywaii** [comment]
Thanks,
It's because if you have only one record you need to do 
xrmApp.Grid.OpenRecord(0) instead of 1 to select the first one

Index start at 0 for the first element. 

Tell me if it solves your problem.

**Comment by vcinampudi** [comment]
Sorry, I didn't log in since a while. I have figured it out.
Thanks
