### ISSUE TITLE
Issue with selecting a tab in UCI

### ISSUE THREAD

**Issue by Ketanb03** [Microsoft/EasyRepro#627]
I am not able to select a tab which appears on clicking More Tabs(3 dots) using xrmApp.Entity.SelectTab("Manager's Decision") method. I get an error "The tab with name: Manager's Decision does not exist"

![image](https://user-images.githubusercontent.com/16450265/62920847-87bc1200-bdc4-11e9-9dc0-3f0bb8396f46.png)

**Comment by sagarbajad** [comment]
Hi Ketan,

If you want to select "Cases" from "Related" then try with xrmApp.Entity.SelectTab("Related","Cases");

**Comment by Haywaii** [comment]
Hi Ketan,

What you are trying to do isn't possible at the moment. "..." is not considered as a tab itself so you will have to use selenium to click and access it. 

If you look at the code for SelectTab function you can see it accept "More" as a tab only. 
A potential fix will be to add "..." in the function code. 
You can clone the dev branch and test by yourself if you want to see if it works and then open a PR :)

**Comment by mVermaat** [comment]
I needed this functionality too, so I created a PR for this.

**Comment by ashwinss91** [comment]
Do We need to use the syntax for more options as _xrmApp.Entity.SelectTab("...", "Manager's Decision") ? @mVermaat  @Haywaii
