### ISSUE TITLE
After getting latest v9.1 code, build solution gives "Syntax error, ',' expected"

### ISSUE THREAD

**Issue by sagarbajad** [Microsoft/EasyRepro#633]
After getting latest v9.1 code, build solution gives "Syntax error, ',' expected"
![image](https://user-images.githubusercontent.com/47889413/63431912-9a29f180-c43d-11e9-9c04-1cc2f508862e.png)

**Comment by sagarbajad** [comment]
EasyRepro/Microsoft.Dynamics365.UIAutomation.Api/Pages/Entity.cs
![image](https://user-images.githubusercontent.com/47889413/63433050-060d5980-c440-11e9-9e36-6b75a37fb4d9.png)
![image](https://user-images.githubusercontent.com/47889413/63433079-16bdcf80-c440-11e9-960b-522c1df38c59.png)

EasyRepro/Microsoft.Dynamics365.UIAutomation.Api/XrmPage.cs
![image](https://user-images.githubusercontent.com/47889413/63433230-6b614a80-c440-11e9-8dd7-bb62224fe2f3.png)

**Comment by mVermaat** [comment]
Are you by any chance using an old Visual Studio version (2015 or older)? This language feature was introduced in C# 7.0. 

https://www.c-sharpcorner.com/article/out-variables-in-c-sharp-7-0/ 
https://stackoverflow.com/questions/39461407/how-to-use-c-sharp-7-with-visual-studio-2015

**Comment by sagarbajad** [comment]
I am using:
![image](https://user-images.githubusercontent.com/47889413/63498693-09f2b780-c4e4-11e9-87fe-de3c3bf44f9b.png)

**Comment by mVermaat** [comment]
I recommend switching to a newer Visual Studio. If that's not an option, then you can try to follow the second link (https://stackoverflow.com/questions/39461407/how-to-use-c-sharp-7-with-visual-studio-2015) from my previous comment. I didn't try myself, but that might work.

**Comment by sagarbajad** [comment]
Thanks, switching to newer Visual Studio worked.
