### ISSUE TITLE
ClickCommand("Save & Close")

### ISSUE THREAD

**Issue by abubakarafzal** [Microsoft/EasyRepro#639]
## Question

**i want to know about ClickCommand("Save & Close")?**
i want to edit my other service right now using nurse recruitment.
i want to edit the Sales Sample.
For example i am having a scenario which i am going to implement another button and button name is Click Me . i just need to pass Click Me.
for eg
                xrmApp.CommandBar.ClickCommand("Click Me);

 .Is this command will click on button by the text or i have to define X path or id else where.

**Comment by Haywaii** [comment]
Hello,

@abubakarafzal if you look at the code of ClickCommand function in the file WebClient.cs of UCI repository, you will find an answer on how it's handled in the code and what you need to do :)

**Comment by abubakarafzal** [comment]
Found that
