### ISSUE TITLE
Create New Contact Records not saved

### ISSUE THREAD

**Issue by kaceyarnold** [Microsoft/EasyRepro#64]
When running a create contact test using version 8.2, without regard to setting detect duplicates to true or false the record is not saved.
The pop up that comes after hitting save is never told to save so cancel is assumed.
So new contact name new data save at end results in duplicate detection even if I set duplicatedetection to false record isn't saved.  Set duplicate detection to true and still record is not saved.
Duplicate Contact; Duplicatedetection true still no record saved.

**Comment by dtu11** [comment]
I'll troubleshoot this and see what is going on.  

Thanks

**Comment by TYLEROL** [comment]
@kaceyarnold - Daren and I both attempted to reproduce this issue but were unsuccessful. With DuplicateDetection = True, the record saved. With DuplicateDetection = False, the record is not saved.

I tested this successfully against both Lead (email comparison) and Contact (firstname / lastname comparison) entities. The organization version was **8.2.2.160**

**Please let us know if you are still facing this issue. If so, could you please supply the full organization version and the code from your tests?**

Thanks,
Tyler

**Comment by TYLEROL** [comment]
Closing this as no repro, however @kaceyarnold if you find this is still an issue please re-open the comment and provide the following bits of information:

- Organization Version
- Code from your test

Thanks,
Tyler

**Comment by kaceyarnold** [comment]
No longer working on that project


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: TYLEROL <notifications@github.com> Date: 3/22/18  1:53 PM  (GMT-08:00) To: Microsoft/EasyRepro <EasyRepro@noreply.github.com> Cc: Kacey Arnold <kcarnold@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Microsoft/EasyRepro] Create New Contact Records not saved (#64) 
Closing this as no repro, however @kaceyarnold if you find this is still an issue please re-open the comment and provide the following bits of information:

Organization Version
Code from your test


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/EasyRepro","title":"Microsoft/EasyRepro","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/EasyRepro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TYLEROL in #64: Closing this as no repro, however @kaceyarnold if you find this is still an issue please re-open the comment and provide the following bits of information:\r\n\r\n- Organization Version\r\n- Code from your test"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/EasyRepro/issues/64#issuecomment-375453946"}}}
