### ISSUE TITLE
[HOW-TO] Finish BusinessProcessFlow in UCI

### ISSUE THREAD

**Issue by phuocle** [Microsoft/EasyRepro#650]
## Question

I'm not found **xrmApp.BusinessProcessFlow.Finish()** in the UCI

But, i found it in **xrmBrowser.BusinessProcessFlow.Finish()**

Is it correct ?

**Comment by Haywaii** [comment]
Hello @phuocle 

You're right at the moment there is not method in UCI to finish a BPW. You will need to use selenium to do it.

Not sure if this feature is in the backlog of the dev team. 
If you're brave enough you can probably create one (not sure there will be a big difference between UCI and normal interface).

**Comment by phuocle** [comment]
Found solution here
```C#
client.Browser.Driver.FindElement(By.XPath("//button[contains(@data-id,'finishButtonContainer')]")).Click(true);
```
