### ISSUE TITLE
Grid.OpenRecord(0) opening Link instead of Record from Grid

### ISSUE THREAD

**Issue by vcinampudi** [Microsoft/EasyRepro#655]
## Bug Report

I am Opening a Case Record from the grid displayed in attached picture but Grid.OpenRecord(0) is opening Account Record instead of Case.

![image](https://user-images.githubusercontent.com/42735003/66913981-7e089200-f033-11e9-8715-d0455fabc9e1.png)

### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  

**Special formatting / display**  

**Code to reproduce**  

**csharp**
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

xrmApp.Navigation.OpenApp(UCIAppName.Sales);

xrmApp.Grid.OpenRecord(0);
 
**Expected behavior**  
Case Record Should open instead of Account.

**Screenshots**  
![image](https://user-images.githubusercontent.com/42735003/66914287-199a0280-f034-11e9-9a20-8420d52fb5b5.png)

**Additional context**

**Comment by brawat07** [comment]
Hi,
Experiencing similar issue on Accounts. It opens user rather than account. Is there any update on when this bug will be fixed?

It is opening the first link as we are finding element using div and hyperlink. I tried changing it to first label. didnt work 

![image](https://user-images.githubusercontent.com/41896860/68310220-8b9bbf80-00a7-11ea-84ca-eceacadac36b.png)

**Comment by VasanthChidambaram** [comment]
Try creating new method as below and use it,

![image](https://user-images.githubusercontent.com/33891447/69342100-d7965900-0c90-11ea-8ea4-99f9c1548e75.png)
