### ISSUE TITLE
[HOW-TO] <Select a single element from pane>

### ISSUE THREAD

**Issue by AndreSProgMine** [Microsoft/EasyRepro#662]
## Question

**I'm new to EasyRepro and need pointers on how to select a single element from a pane (see attached image) I want to select the Dashboard element but the following bits of code do not work:

**xrmBrowser.Navigation.OpenSubArea("Dashboard", "some-text-has-to-go-here");**
**xrmBrowser.Grid.SwitchView("Dashboard");**

The first demands 2 values, and the second throws up an exception.
**

![Dashboard](https://user-images.githubusercontent.com/57215518/67935088-1456bf00-fbc1-11e9-869c-bc5b6906b840.PNG)

**Comment by Paca** [comment]
Hello

You use the wrong part of the api. xrmBrowser is for legacy web interface.
You should use the XrmApp client describe here:  [XrmApp](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/UCI/Navigation/FormSelector.cs)

Regards,
Nicolas

**Comment by AndreSProgMine** [comment]
Thanks **Paca**, much appreciated
