### ISSUE TITLE
Grid Sort Column is not working

### ISSUE THREAD

**Issue by Murugadass** [Microsoft/EasyRepro#669]
Grid_SortColumn details are incorrect on AppReference. 

**The current value is :**
{ "Grid_SortColumn",            "//div[@id='btnheaderselectcolumn']/parent::*//div[text()='[COLNAME]'"},

**Expected value is :**
{ "Grid_SortColumn",            "//div[@data-id='btnheaderselectcolumn']/parent::*//div[text()='[COLNAME]']"},

Please update the repository.

**Comment by dtu11** [comment]
Just updated develop with a fix for the sort.  Please test the latest changes.
