### ISSUE TITLE
[FEATURE] TwoOption field support in Unified Interface

### ISSUE THREAD

**Issue by simonbridgwater** [Microsoft/EasyRepro#689]
**Describe the feature**  
Within the legacy interface there is the ability to set Two Option fields, and I haven't found a Unified Interface equivalent or an alternative solution.

**Explain why this feature is needed**  
To allow the population of Two Option field values.

**Additional context**  
The existing Legacy Interface code is `XrmBrowser.Entity.SetValue(new TwoOption { Name = "fieldname", Value = "value" });`

**Comment by jowells1** [comment]
This should be closed as TwoOption has been replaced with BooleanItem. BooleanItem type is expecting a true/false value.  If you review the values for each label of a Two Options field, you’ll see that the label with a value of 0 means it is a boolean value of false and the other, that has a value of 1, is a boolean value of true.  This example is from the Marketing Materials field within the Lead entity:
![image](https://user-images.githubusercontent.com/34693792/79612449-52d62c80-80c2-11ea-90b5-f72aed5f268e.png)

Sample code to set the "Marketing Materials field on the Lead entity to "Do Not Send" is as such:
`xrmApp.Entity.SetValue(new BooleanItem { Name = "donotsendmm", Value = true });`
