### ISSUE TITLE
System.InvalidOperationException: Column: Ownership Status Does not exist

### ISSUE THREAD

**Issue by jjbright** [Microsoft/EasyRepro#692]
I'm pretty new to easy repro.  I'm tasked to fix issues in the existing test code and build additionally on top of that.

In a custom grid displayed, which I click to sort that grid using a column name, it gives me this exception.

`
xrmBrowser.ThinkTime(2000);
xrmBrowser.Grid.Sort("Ownership Status", 3000);
xrmBrowser.Related.OpenGridRow(0);
`
The reason for sorting is to get the current owner in the first record of the grid.

I tried using this line as well
`xrmBrowser.Grid.Sort("Ownership Status", 3000);`

![image](https://user-images.githubusercontent.com/55202374/70525378-36067700-1b6d-11ea-8c78-307db4798479.png)

**Comment by jjbright** [comment]
@TYLEROL @jlattimer @dtu11 

Could you please help?

**Comment by dtu11** [comment]
I'm back from vacation and will look at this today.

**Comment by dtu11** [comment]
Just updated develop with a fix for the sort.  Please test the latest changes.

**Comment by jjbright** [comment]
> Just updated develop with a fix for the sort. Please test the latest changes.

@dtu11  I need to get the latest changes and try?

**Comment by dtu11** [comment]
Yes pull down the latest develop branch and test it.

**Comment by dtu11** [comment]
There are quite a few people on holiday leave so there is a hold on pushing this out to release and Nuget until Jan 3rd.   I'll work with Tyler to get this out to Nuget after the holidays.
