### ISSUE TITLE
[BUG] NoSuchElementException for email input field during login in system with single sign-on

### ISSUE THREAD

**Issue by VivianVoss** [Microsoft/EasyRepro#695]
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ ] UCI (XrmApp)
  - [x] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome (v73)
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Upon running the [test](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/Web/Create/CreateAccount.cs#L21) identified by `Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount`  following call `xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);` ([here](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/Web/Create/CreateAccount.cs#L25)) fails with the exception below as our system will auto-sign-in even in a Chrome incognito session. 

```
OpenQA.Selenium.NoSuchElementException
  HResult=0x80131500
  Message=no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='email']"}
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.18363 x86_64)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass45_0.<WaitUntilAvailable>b__0(IWebDriver d) in [redacted]\EasyRepro-develop\EasyRepro-develop\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 591
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
```

**Code to reproduce**  
See [this](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/Web/Create/CreateAccount.cs#L21).
 
**Expected behavior**  
The code should not throw an exception and continue on [line 26](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/Web/Create/CreateAccount.cs#L26).

**Additional context**  
The configuration files has been updated to fit our system.

When logging out in Dynamics 365, closing the browser, opening the browser and going to the Dynamics 365 page again. I am automatically logged in. This is also the case in Chrome incognito.

I am using Chrome 73 because we did not have newer available that was also older than 77, which is the latest Chrome.WebDriver package available in Nuget.

**Comment by AngelRodriguez8008** [comment]
Hi Vivian,

If you don't have to log-in, I guest you should remove this line from your test.
xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);

**Comment by VivianVoss** [comment]
Hi Angel, 

When commenting that line out, the browser does not load D365 page at all. It opens the browser window but it is empty and then the test fails. 

![viber_image_2019-12-19_07-59-25](https://user-images.githubusercontent.com/32089254/71152279-3e7a4400-2236-11ea-97a5-57ff19b9abdb.jpg)

**Comment by TYLEROL** [comment]
@VivianVoss - In the _login_ sequence after inputting your organization URL, do you still get asked to enter an email and then redirect to an external ADFS provider? Or does it immediately redirect with no input requirements for email?

We may need to add a scenario to more properly handle login for this if there is no initial email prompt. In past experiences, generally a user was required to input their email address before O365 would direct to an external provider for realm identity.

Thanks,
Tyler

**Comment by VivianVoss** [comment]
Hi Tyler, 
No, there is no email asked before. It immediately logs in and redirects to the apps page, where after a bit the test fails, because it can't find a place to put email. 

BR, Vivian

**Comment by TYLEROL** [comment]
@VivianVoss - We've merged a change into the develop branch via #694 . Could you try testing out this new Login method and see if it accommodates your scenario? Based on the description of events, I believe it should.

We're in a holiday code freeze at the moment, but could get this change into the core releases/v9.1 branch by January 3rd, 2020 if you can confirm this works.

Edit: For the legacy webClient APIs, the code should look like:

`xrmBrowser.LoginPage.Login(_xrmUri);`

**Comment by VivianVoss** [comment]
Hi Tyler,

When changing the Login statement to the one you provide above, the code behaves differently, but I am left with a new exception. The exception originates from [this statement](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Api/Pages/LoginDialog.cs#L165). It is looking for an XPath described as `id(\"crmTopBar\")` but this Top Bar element (unlike in our Dynamics 8.2 on-premise installation) does not exist, resulting in a [Login page failed](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Api/Pages/LoginDialog.cs#L174) exception message after 60 seconds of waiting as specified by the TimeSpan in the statement. I have looked through the page source on our Dynamics 9.1 online installation and confirmed that it is indeed the case that no such `crmTopBar` element exists.

I am thinking your change is working as expected and this issue may be a different problem. Are you aware of 9.1 online not having an element with the ID `crmTopBar`?

**Comment by VivianVoss** [comment]
Hi Tyler, any news on this?

**Comment by AngelRodriguez8008** [comment]
Hi @VivianVoss,

Why you are trying to use the Classic Web (XrmBrowser) for 9.1 online? It is mandatory for you? If you use the UCI methods, it will call a different Login method that expect a different page: see it [hier](https://github.com/microsoft/EasyRepro/blob/79229f9e28c4bf8a0e4bcc80dd06402430f1d2c2/Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs#L78)

See [samples](https://github.com/microsoft/EasyRepro/tree/develop/Microsoft.Dynamics365.UIAutomation.Sample/UCI)

When I try to open the Classic Web in my Trial Online Version this is not really the "Classic" one. It is more like UCI (Navigation, etc).  I think many other EasyRepro Logic will not work there.

**Comment by VivianVoss** [comment]
Hi all,
I have just tried the tests again but with UCI and it seems to work fine. Thanks for the help :)
