### ISSUE TITLE
EasyRepro: . Error message is “session not created: This version of ChromeDriver only supports Chrome version 77 (SessionNotCreated)

### ISSUE THREAD

**Issue by Shubh-saxena** [Microsoft/EasyRepro#699]
Hi All,
My EasyRepro Automation Test was working good on my Visual Studio 2019. Suddenly the below error starting coming which is as below:
Error message is “session not created: This version of ChromeDriver only supports Chrome version 77 (SessionNotCreated)”

![71155504-df332880-2263-11ea-839b-62c61030afaf](https://user-images.githubusercontent.com/59015119/71359272-e20a8200-25b1-11ea-9018-2bfbfa43f8df.png)

Fixes: I uninstalled my latest chrome version(i.e. 79 version) and installed an offline installer of chrome version 77 after which the test was successful.
This is an issue as this was running fine irrespective of the version of chrome browser but now suddenly it is failing.

**Comment by ikeselman** [comment]
I have same issue with VSTS 2017 Community Edition 
Chrome Browser updated version to version 79.0.3945.88 
Last time it happen I updated Chrome Driver to v.78.0.3904.70 and was already working fine 
If now I try install NuGet package Selenium.WebDriver.ChromeDriver latest 79.0.3945.3600 or even one before  v.78.0.3904.10500 I am getting same error:

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The 'packages' element is not declared.	Microsoft.Dynamics365.UIAutomation.Sample	C:\Users\ikeselman\Source\Repos\UIAutomationEasyRepro-develop\Microsoft.Dynamics365.UIAutomation.Sample\packages.config	4

**Comment by Shakevg** [comment]
You can find how to select right Chrome browser and chrome driver version: https://chromedriver.chromium.org/downloads

There are 2 fixes when you have "session not created: This version of ChromeDriver only supports Chrome version" error:
1. Update chrome driver to compatible with browser version
2. Rollback Chrome browser to previous version and disable chrome update:
https://stackoverflow.com/a/31939624/8951897

@ikeselman, Fix here (2nd, 3rd are are working for me): https://stackoverflow.com/questions/7684398/the-packages-element-is-not-declared

Also I faced with issue when after update chrome driver nuget Visual Studio cannot delete old ChromeWebdriver due it was locked by running ChromeWebdriver process. I checked bin folder and it contained old driver version. I just killed all ChromeWebdriver processes and clean bin folder.

**Comment by AngelRodriguez8008** [comment]
I just uninstall the old WebDriver and install this [Selenium.WebDriver.ChromeDriver by jsakamoto](https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/79.0.3945.3600) from nuget.

**Comment by Shubh-saxena** [comment]
Thanks for the replies.. I was able to fix this issue as follows:
) Using NuGet Package Manager in Visual Studio, you can manually update the version of the ChromeDriver on the Microsoft.Dynamics365.UIAutomation.Sample project. 
a.	Select the Selenium.Chrome.WebDriver from the list of packages 
b.	Choose the required version to match the version of ChromeBrowser on your test client, and then click Update
) Using NuGet Package Manager in Visual Studio, you can manually update the version of the ChromeDriver on the Microsoft.Dynamics365.UIAutomation.Sample project. 
a.	Select the Selenium.Chrome.WebDriver from the list of packages 
b.	Choose the required version to match the version of ChromeBrowser on your test client, and then click Update
![image](https://user-images.githubusercontent.com/59015119/72151322-ee724580-33cd-11ea-89ba-c1f1834ee3d0.png)

Now I have a second challenge when I am running the automated tests in Azure Devops, I get the same issue in the ado. How can I match the versions in Agent/VMs on which the tests are happening.
![image](https://user-images.githubusercontent.com/59015119/72151538-7a846d00-33ce-11ea-8181-d84fafb70e5d.png)

**Comment by Shakevg** [comment]
@Shubh-saxena Looks like on Agent in Azure DevOps you have Chrome browser version different from 79

You can find Chrome version using PowerShell task with next code:
`$ChromeVersion = (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo
Write-Host "ChromeVersion: " $ChromeVersion`

![image](https://user-images.githubusercontent.com/42133199/72205653-7b7cd380-348e-11ea-8bfd-c5521f9ec5cc.png)

What [type ](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser) of Agent do you use in Azure Devops?
You should update Chrome to latest version on Agent if it is possible or use local specific version of Chrome driver if tests are running on Agent (e.g. copy according Chrome driver version to Agent and use it for tests in Azure DevOps).

**Comment by VasanthChidambaram** [comment]
@Shakevg - Am also facing the same issue as above. 
As suggested, we have been Azure hosted build agent vs2017-win2016 and its specification below,
[(https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md)]

**Comment by Shakevg** [comment]
For "windows-2019", "vs2017-win2016" Microsoft-hosted agent next code can be used for generating correct WebDriver folder path for hosted MS Agents (windows-2019, vs2017-win2016): local Agent driver path will return from environment variable for Chrome, IE, Firefox and current working directory otherwise. 

```csharp
[TestMethod]
public void WEBTestOpenActiveContact()
{
	TestSettings.Options.DriversPath = GetWebDriverPath(TestSettings.Options.BrowserType);
	using (var xrmBrowser = new Api.Browser(TestSettings.Options))
	{
		xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
	}
}

/// <summary>
/// Get WebDriver path according to browser
/// </summary>
/// <param name="browserType">Browser type</param>
/// <returns>Web driver folder path from for hosted MS Agents (windows-2019, vs2017-win2016) and current working directory otherwise</returns>
private string GetWebDriverPath(BrowserType browserType)
{
	var driverPath = Path.Combine(Directory.GetCurrentDirectory());

	//get driver path for hosted MS Agent (windows-2019, vs2017-win2016)
	string envWebDriver = null;
	string driverFile = null;
	switch (browserType)
	{
		case BrowserType.Chrome:
			envWebDriver = Environment.GetEnvironmentVariable("ChromeWebDriver");
			driverFile = "chromedriver.exe";
			break;
		case BrowserType.Firefox:
			envWebDriver = Environment.GetEnvironmentVariable("GeckoWebDriver");
			driverFile = "geckodriver.exe";
			break;
		case BrowserType.IE:
			envWebDriver = Environment.GetEnvironmentVariable("IEWebDriver");
			driverFile = "IEDriverServer.exe";
			break;
	}
	if (!string.IsNullOrEmpty(envWebDriver) && File.Exists(Path.Combine(envWebDriver, driverFile)))
	{
		driverPath = envWebDriver;
	}
	return driverPath;
}
```

**Comment by TYLEROL** [comment]
Thanks @Shakevg for sharing this solution.

For others here -- This is a limitation of the current feature branch that we are looking to update soon, but the option shared above is a good one for now.

With recent changes to the ChromeDriver requiring version parity between Driver and Browser, this caused some difficulties with the version we were including within the branches. We made a decision to try and maintain the latest driver version in the branches, but this does present issues when using Azured DevOps Hosted Agents.

This link shows the options for [Microsoft Hosted Agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent). Each agent type has a link which shows the software versions included on the agent. This includes detail about which Chrome Browser version is installed, as well as the varying WebDrivers for Chrome, Firefox, and IE.

Thanks,
Tyler

**Comment by pikappp** [comment]
Can anyone please help me with this? I don't have the automated cases in DevOps.
I write scripts and the artifacts are built in the pipeline but when it runs on the server the error states - "This version of ChromeDriver only supports chrome version 95."
I have ChromeDriver of version 95 but it seems the chrome version on the server is 94. So how can I update the version on the server?

**Comment by Shakevg** [comment]
@pikappp Did you try the solution above https://github.com/microsoft/EasyRepro/issues/699#issuecomment-573856361?
I am using it now without any issues on Azure Hosted Agent
