### ISSUE TITLE
[BUG] Field.IsReadOnly not properly working for UCI Lookup control

### ISSUE THREAD

**Issue by jeffryvu** [Microsoft/EasyRepro#703]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Using the code below returns false for any Lookup field when I set the field to readonly in the form editor or setDisabled in JavaScript.
Field myLookupField = xrmApp.Entity.GetField("myLookupField");
Assert.IsTrue(myLookupField .IsReadOnly);

I debugged it and it appears that the selector: aria-readonly is not present on this field. It is present on some other fields I tested, such as text fields.

**Code to reproduce**  

```csharp
Field myLookupField = xrmApp.Entity.GetField("myLookupField");
Assert.IsTrue(myLookupField .IsReadOnly);
```
 
**Expected behavior**  
I expect the code to return true if the field is readonly.

BTW, I'm happy to help with fixing this code if needed.

**Comment by TYLEROL** [comment]
Thanks @jeffryvu for raising this. I've added it to our backlog and will try to see what we can get worked out in this milestone.

Regards,
Tyler

**Comment by lewginn** [comment]
Has there been any progress on this?
