### ISSUE TITLE
[BUG] <Easyrepro- When run a test case, once done successfully but the another time it throw different exceptions>

### ISSUE THREAD

**Issue by shahrukhshakil424** [Microsoft/EasyRepro#704]
Online
**Browser**
  - [x] Chrome
  - [x] Firefox
  - [ ] IE
  - [ ] Edge
Whenever I run the code it works fine only first time. However, if I run again the same code without any customization it throws different exceptions every time. 
Exceptions are :
-[ ]**OpenQA.Selenium.ElementNotInteractableException: 'Element <div class="ms-crm-Inline-Edit ms-crm-Inline-Lookup"> could not be scrolled into view'**
-[ ]**System.InvalidOperationException: 'Composite Control: fullname Does not exist'**

**Here is the code.**

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Dynamics365.UIAutomation.Api;
using Microsoft.Dynamics365.UIAutomation.Browser;
using System;
using System.Security;
using System.Collections.Generic;

namespace Microsoft.Dynamics365.UIAutomation.Sample.Web
{
    [TestClass]
    public class CreatePatient
    {

        private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());

        [TestMethod]
        public void WEBTestCreateNewOpportunity()
        {
            using (var xrmBrowser = new Api.Browser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();

                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Service", "Contacts");

                xrmBrowser.ThinkTime(200);
                xrmBrowser.Grid.SwitchView("Patients");

                xrmBrowser.ThinkTime(2000);
                xrmBrowser.CommandBar.ClickCommand("New");

                xrmBrowser.ThinkTime(6000);
                //xrmBrowser.Entity.SetValue("mzk_gender", "Male");
                xrmBrowser.ThinkTime(3000);
                var fields = new List<Field>
                {
                    new Field() {Id = "firstname", Value = "Shahrukh"},
                    new Field() {Id = "lastname", Value = "Easyrepro"}
                };
                xrmBrowser.Entity.SetValue(new CompositeControl() { Id = "fullname", Fields = fields });

                
                //xrmBrowser.Entity.SetValue("description", "Testing the create api for Opportunity");

                xrmBrowser.CommandBar.ClickCommand("SAVE");
                xrmBrowser.ThinkTime(2000);
            }
        }
    }
}

**Comment by shahrukhshakil424** [comment]
@TYLEROL I am highly thankful to you if you look into this issue. TIA

**Comment by shahrukhshakil424** [comment]
@microsoftopensource I am highly thankful to you if you look into this issue. TIA

**Comment by shahrukhshakil424** [comment]
@ggeiszle  @dtu11. I am highly thankful to you if you look into this issue. TIA

**Comment by TYLEROL** [comment]
@shahrukhshakil424 - A change was published the latest 9.1.0.11711 NuGet package this past Friday, as well as the latest releases/v9.1 branch.

Please let me know if this issue persists and I can take another look into this problem.

Warm Regards,
Tyler
