### ISSUE TITLE
[BUG] 'BrowserOptions' does not contain a definition for 'UCIPerformanceMode' after install easyRepro using NuGet

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#705]
'UCIPerformanceMode' is set in the TestSettings.cs of Sample project.
When I clone the easyRepro for dynamics365, 'UCIPerformanceMode' is set without error.
But when I install easyRepro using NuGet in my test project and copy over the TestSettings.cs with updated namespace, I get error "'BrowserOptions' does not contain a definition for 'UCIPerformanceMode' after install easyRepro using NuGet".
However the test runs without error when I comment out the 'UCIPerformanceMode' of the TestSetting.cs.

Do I still need to set  'UCIPerformanceMode'? What is the  'UCIPerformanceMode' for?

**Comment by TYLEROL** [comment]
Hi @xuejunh ,

Which NuGet package version did you test this with?

The 'UCIPerformanceMode' flag adds a query parameter '&perf=true' to the URL string which enables a performance widget in the Unified Interface. Once this widget is enabled, it will capture key performance properties and metrics that could be used to understand the performance you're seeing with your model-driven apps.

![image](https://user-images.githubusercontent.com/29415524/72388328-3a352f80-36eb-11ea-8226-895c08175dc0.png)

Another method, Telemetry.TrackPerformanceEvents() is available to track the information from the performance widget. There is a sample located [here](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/SharedAPI/AzureInsights/UploadTelemetryUCI.cs) with more details on the implementation

Thanks,
Tyler

**Comment by xuejunh** [comment]
I am using NuGet Manager 4.6.0 which is with Visual Studio 2017. Should I use Visual Studio 2019? Will easyRepro works with Visual Studio 2019 (Readme indicates easyRepro works with Visual studio 2017, 2015).

**Comment by TYLEROL** [comment]
@xuejunh - My apologies, for clarification, I am curious about the NuGet version of the EasyRepro package you are testing with. The latest package version available should be version 9.1.0.11711

In regards to Visual Studio versions, EasyRepro will work with VS 2015, VS 2017, and VS 2019.

Thanks,
Tyler

**Comment by xuejunh** [comment]
Tyler,

Thanks for your email. I checked easyRepro version just now it is 9.1.0.11711. the Nuget itself is v4.6.0.

I still have the code commented in the setting as //UCIPerformanceMode = true
To run my script.

Thanks for your help!

Best regards,

Xuejun

XUEJUN HUANG
IT QA Analyst II
T: (724) 416-9639

CROWN CASTLE
2000 Corporate Dr., Canonsburg, PA 15317
CrownCastle.com<http://www.crowncastle.com/>

**Comment by xuejunh** [comment]
I am sorry for the confusing. I just updated my package to 9.1.0.11711 and I do not see the error anymore. so I am closing this issue.
