### ISSUE TITLE
[HOW-TO] Is there a smart xrmApp.ThinkTime(500)

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#706]
I am trying easyRepro and see it is necessary to wait like 

xrmApp.ThinkTime(500)

to set lookup value. I am wondering if there is smart think time like wait until the lookup is ready to select as in selenium or protractor?

Thanks!

**Comment by TYLEROL** [comment]
Hi @xuejunh ,

The xrmApp.ThinkTime() method was introduced as a means to create your own artificial delays in a test. One example would be if you were showing the test as a demo, it allows you to artificially slow down the test and better visualize what is occurring on screen. In some scenarios, the test moves very quickly and much faster than a traditional user making things tougher to see.

For methods like SetValue(LookupItem control, int index), we generally rely on methods like driver.WaitUntilAvailable(), driver.WaitUntilVisible(), and driver.ClickWhenAvailable() to perform more natural waits and proceed as elements on the page become available.

Ideally, you shouldn't need to do these and just call the appropriate xrmApp.Entity.SetValue() method for the control type that you want to set. 

Are you experiencing any specific issues using SetValue() that aren't being handled as I described above?

Thanks,
Tyler
