### ISSUE TITLE
Web driver version issue between local and Azure build agent

### ISSUE THREAD

**Issue by VasanthChidambaram** [Microsoft/EasyRepro#709]
Hello, 
We are facing chrome web driver version difference and facing error. Using Selenium chrome web driver nuget package version 79 to run test in local, but when we run against Azure build hosted agent, it has only chrome browser version of 77.xxx.
Due to version conflicts,we are unable to find the solution to this issue. Please suggest any ideas

**Comment by Shakevg** [comment]
[For "windows-2019", "vs2017-win2016" Microsoft-hosted agent next code can be used for generating correct WebDriver folder path for hosted MS Agents](https://github.com/microsoft/EasyRepro/issues/699#issuecomment-573856361)

**Comment by TYLEROL** [comment]
Thanks @Shakevg for sharing this solution.

@VasanthChidambaram - This is a limitation of the current feature branch that we are looking to update soon, but the option shared above is a good one for now.

With recent changes to the ChromeDriver requiring version parity between Driver and Browser, this caused some difficulties with the version we were including within the branches. We made a decision to try and maintain the latest driver version in the branches, but this does present issues when using Azured DevOps Hosted Agents. 

This link shows the options for [Microsoft Hosted Agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent). Each agent type has a link which shows the software versions included on the agent. This includes detail about which Chrome Browser version is installed, as well as the varying WebDrivers for Chrome, Firefox, and IE.

Thanks,
Tyler
