### ISSUE TITLE
Build Microsoft.Dynamics365.UIAutomation.Api failing

### ISSUE THREAD

**Issue by sanjint** [Microsoft/EasyRepro#71]
After cloning the project, the build of Microsoft.Dynamics365.UIAutomation.Api fails with the following error:

'ReadOnlyCollection<IWebElement>' does not contain a definition for 'Any' and no extension method 'Any' accepting a first argument of type 'ReadOnlyCollection<IWebElement>' could be found (are you missing a using directive or an assembly reference?)

<img width="548" alt="easyrepro" src="https://user-images.githubusercontent.com/100386/34615893-a479d464-f236-11e7-95fd-59c647085479.PNG">

**Comment by j621z** [comment]
@sanjint Please go ahead and use .Count > 0
.Any() is failing due to missing using statement: using System.Linq;

**Comment by j621z** [comment]
@sanjint Please let us know if this fixed issue.

**Comment by sanjint** [comment]
@j621z Indeed, that works too!
