### ISSUE TITLE
Deprecated methods... 

### ISSUE THREAD

**Issue by jjbright** [Microsoft/EasyRepro#710]
## Question

**The automation testing code that I'm trying to enhance is having an older version of EasyRepro, now that I've to enhance it so I updated it thru the Nuget in VS2017 using the below command.**

`PM> Install-Package Dynamics365.UIAutomation.Api -Version 9.1.0.11711`

After getting this, I tried  a clean build which had completely broken the existing code.

Here are the errors -

> 

'ActivityFeed'   does not contain a definition for 'OpenActivity' and no accessible extension   method 'OpenActivity' accepting a first argument of type 'ActivityFeed' could   be found
--

> 

'Entity' does not contain a definition   for 'SwitchToNewWindow' and no accessible extension method   'SwitchToNewWindow' accepting a first argument of type 'Entity' could be   found
--

>
Argument 1: cannot convert from   'Microsoft.Dynamics365.UIAutomation.Api.Field' to   'Microsoft.Dynamics365.UIAutomation.Api.TwoOption'
--

>
'Entity' does not contain a definition   for 'SaveAndWait' and no accessible extension method 'SaveAndWait' accepting   a first argument of type 'Entity' could be found
--

>
'Entity' does not contain a definition   for 'GetLockedTextFieldValue' and no accessible extension method   'GetLockedTextFieldValue' accepting a first argument of type 'Entity' could   be found
--

>
'Entity' does not contain a definition   for 'IsUnsavedChangesMessageExistOnForm' and no accessible extension method   'IsUnsavedChangesMessageExistOnForm' accepting a first argument of type   'Entity' could be found
--

>
Entity' does not contain a definition for   'GetLockedLookupFieldValue' and no accessible extension method   'GetLockedLookupFieldValue' accepting a first argument of type 'Entity' could   be found
--

>
Entity' does not contain a definition for   'SelectMultiLookup' and no accessible extension method 'SelectMultiLookup'   accepting a first argument of type 'Entity' could be found
 --

`xrmBrowser.Entity.SelectLookup(field,   value, true); ` this line gives below   error
>
Argument 2: cannot convert from 'string'   to 'bool'
--

I tried to get some documentation to quickly identify the alternates but in vain.

@tylerco @dtu11 @TYLEROL

**Comment by TYLEROL** [comment]
Thanks for raising this @jjbright - do you know which version of EasyRepro you were upgrading from?

Prior versions like 8.1, 8.2, and 9.0 had some differences from when the latest v9.1 branch was created a while back. With the 'One Version' initiative, you shouldn't have to go through this again. Once I hear back, I'll try to provide some more specific guidance behind the APIs you're having issues with and trying to 

For at least one of them, xrmBrowser.Entity.SelectLookup(field, value, true), it looks like it's conflicting with an old, obsolete method. You can use  SelectLookup(LookupItem field, bool clearFieldValue = true, bool openLookupPage = true) instead

```
        /// <summary>
        /// DEPRECATED: Set Lookup Value for the field
        /// </summary>
        /// <param name="field">The Field</param>
        /// <param name="clearFieldValue">Remove Existing Field Value, if present. False = Click the existing value</param>
        /// <param name="openLookupPage">The Open Lookup Page</param>
        [Obsolete("SelectLookup is deprecated, please use SelectLookup(LookupItem field, bool clearFieldValue = true, bool openLookupPage = true) instead.")]
        public BrowserCommandResult<bool> SelectLookup(string field, bool clearFieldValue = true, bool openLookupPage = true)
```

Warm Regards,
Tyler

**Comment by jjbright** [comment]
Hi Tyler
I couldn't find the version of EasyRepro in my project.  I assume it could be an older version like 8.1/8.2 

Help me to find the version too.

I'll change to SelectLookUp as suggested, once you guide me thru on the other issues... so that I'll be upgrading to the newer version of EasyRepro.

Alongside, I've only two projects in my solution... please see screenshot.
![image](https://user-images.githubusercontent.com/55202374/72584520-5e258a80-3910-11ea-8488-0f1ec1a853b5.png)

Now I see the EasyRepro git is showing below projects
![image](https://user-images.githubusercontent.com/55202374/72584581-a04ecc00-3910-11ea-878d-ac755179f6cf.png)

Should I include the UCI project,  Asking as I know there was a bug related to Grid.Sort() fixed by @dtu11 which I see its in UCI.

**Comment by jjbright** [comment]
@TYLEROL Could you please look into this, it is quite critical for me to continue

**Comment by TYLEROL** [comment]
Hello @jjbright -

I am having difficulties locating the missing methods that you've listed above. In my time on this project, I've made a conscious effort to avoid removing existing methods. If a new, better method becomes available I've marked the old methods as Obsolete with reference pointers to the new replacement method.

- ActivityFeed.OpenActivity() --> **ActivityFeed.OpenActivitiesAssociatedView()** --> From here, **Related.OpenGridRow(int index)** should allow  you to open an activity record. There is not currently functionality to open directly from the Activity Feed (beyond creating a new activity record).

- Entity.SwitchToNewWindow() --> **Entity.SwitchToPopupWindow()** -- need additional context on how this was used. This is the closest I can decipher on this method.

- Entity.SaveAndWait() --> **Entity.Save()** -- can provide a configurable ThinkTime value to provide additional wait time if desired.

- Entity.GetLockedTextFieldValue() --> **Entity.GetValue(string field)** -- If this does not work, please file a bug accordingly

- Entity.IsUnsavedChangesMessageExistOnForm() --> No correlating method

- Entity.GetLockedLookupFieldValue() --> **Entity.GetValue(LookupItem control)** -- If this does not work, please file a bug accordingly

Please take a moment to review, and I'll try my best to answer any follow-up questions you may have.

Edit: In regards to the UCI project - this project contains APIs related to the [Unified Interface](https://docs.microsoft.com/en-us/power-platform/admin/about-unified-interface). As the legacy web client has been deprecated, I would encourage use of the UCI project to develop tests on the new Unified Interface platform.

Warm Regards,
Tyler

**Comment by jjbright** [comment]
Hi Tyler, 
@TYLEROL I'll try this in my end.

reg: UCI - I think Dynamics CRM we are using is not in Unified Interface as we have moved to Unified Service Desk to be used by the users.
How do I determine if this is Unified Interface
![image](https://user-images.githubusercontent.com/55202374/72905943-5d00bd00-3d57-11ea-9c1e-ba66aae4a809.png)

Thanks
John

**Comment by TYLEROL** [comment]
Hello @jjbright - while I am not that familiar with the USD client, the screenshot you provided appears to be a legacy web client control. I've linked a couple Microsoft Docs articles below with Web Client vs Unified Interface examples. It appears that the **Unified Service Desk Component Type** field on the hosted control should help given an indicator on your client interface type.

- [Web Client Example](https://docs.microsoft.com/en-us/dynamics365/unified-service-desk/walkthrough-1-build-a-simple-agent-application?view=dynamics-usd-4.1#step-1-create-the-basic-hosted-controls)

- [Unified Interface Example](https://docs.microsoft.com/en-us/dynamics365/unified-service-desk/walkthrough3-unified-interface-display-microsoft-dynamics-365-records-in-your-agent-application?view=dynamics-usd-4.1#step-1-create-unified-interface-page-type-of-hosted-controls-to-display-account-and-contact-records)

More general information about the Unified Interface and USD can be found [here](https://docs.microsoft.com/en-us/dynamics365/unified-service-desk/admin/support-unified-interfaces-apps-usd?view=dynamics-usd-4.1#what-is-unified-interface-supportability-in-unified-service-desk).

Hope this helps!

Thanks,
Tyler
