### ISSUE TITLE
[BUG] Pending email warning blocks test completion

### ISSUE THREAD

**Issue by ugreg** [Microsoft/EasyRepro#711]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ ] UCI (XrmApp)
  - [x] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [ ] Chrome
  - [x] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
The `CreateAccountTest` in `Microsoft.Dynamics365.UIAutomation.Sample.Web` finished unsuccessfully because the pending email warning window blocks the UI. If closed by the user manually the test runs successfully. This window first appears directly after the user automated login completes.

**Special formatting / display**  

**Code to reproduce**  

 
**Expected behavior**  
The `CreateAccountTest` in `Microsoft.Dynamics365.UIAutomation.Sample.Web` finished successfully. 

**Screenshots**  
![image](https://user-images.githubusercontent.com/8151045/72357868-b151d000-36b9-11ea-8dcd-24b72943bd11.png)

**Additional context**

**Comment by TYLEROL** [comment]
Hi @gregdegruy 

Could you give this snippet below a try, add it immediately following the call to LoginPage.Login()

```
//Handle Pending Email Warning
xrmBrowser.Dialogs.CloseWarningDialog();
```

Thanks,
Tyler

**Comment by ugreg** [comment]
That fixed it thanks so much! Created [PR 715](https://github.com/microsoft/EasyRepro/pull/715) for this change. 

Is the `CloseWarningDialog()` prepared to handle edge cases, like if there's no warning dialog on the page at runtime will the code continue to execute if this method is called with nor warning dialog on the page?
