### ISSUE TITLE
[BUG] Unable to Get/SetHeaderValue for Owner

### ISSUE THREAD

**Issue by jowells1** [Microsoft/EasyRepro#719]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  

When trying to get the Owner lookup from a header, you get the following error:
OpenQA.Selenium.NoSuchElementException
  HResult=0x80131500
  Message=no such element: Unable to locate element: {"method":"xpath","selector":"//div[@role='tabpanel']/parent::*//*[contains(@data-id, 'ownerid.fieldControl-Lookup_ownerid')]"}
  (Session info: chrome=79.0.3945.117)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass45_0.<WaitUntilAvailable>b__0(IWebDriver d) in C:\Source\Repos\Easy Repro\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 591
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)

**Special formatting / display**  

Owner field in the header.  Other fields appear to not be affected by the issue

**Code to reproduce**  

```csharp
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

                xrmApp.Navigation.OpenApp(UCIAppName.CustomerService);

                xrmApp.Navigation.OpenSubArea("Service", "Cases");

                xrmApp.Grid.SwitchView("Active Cases");

                xrmApp.Grid.OpenRecord(0);

                LookupItem ownerId = new LookupItem() { Name = "ownerid" };
                string ownerIdValue = xrmApp.Entity.GetHeaderValue(ownerId);

                OptionSet priorityCode = new OptionSet() { Name = "prioritycode" };
                string priorityCodeValue = xrmApp.Entity.GetHeaderValue(priorityCode);

                xrmApp.ThinkTime(2000);
```

 
**Expected behavior**  

Be able to retrieve and set the owner field from within the header

**Screenshots**  

**Additional context**  

The header owner field appears to be set to a data-id of "header_ownerid.fieldControl-Lookup-ownerid"
![image](https://user-images.githubusercontent.com/34693792/72576032-13fec380-3894-11ea-9909-3103797401fc.png)

**Comment by AngelRodriguez8008** [comment]
UPDATE: I note that a similar fix is done in #707 (but it don't work for me, in header the data-id don't match exactly)

I solve this problem by replacing the follow line:
![image](https://user-images.githubusercontent.com/27274469/72665324-893ed580-3a07-11ea-8715-6a127e50eed2.png)

The idea is remove the parent Tab Panel from the XPath.

You can copy it hier. 
`{ "Entity_TextFieldLookupFieldContainer", "//*[contains(@data-id, '[NAME].fieldControl-Lookup_[NAME]')]" },`

I tested it just in one Envieroment Online UCI v9.1, non others tests are broke, maybe it also works for you.

Hier is my Tests, Get / Set Owner:
```csharp    
            var owner = new LookupItem { Name = "ownerid" };
            string ownerIdValue = xrmApp.Entity.GetHeaderValue(owner);
            Assert.That(ownerIdValue, Is.Not.Null);
            Assert.That(ownerIdValue, Is.EqualTo("Angel Rodriguez"));

            owner.Value = "Test User";
            xrmApp.Entity.SetHeaderValue(owner);
            ownerIdValue = xrmApp.Entity.GetHeaderValue(owner);
            Assert.That(ownerIdValue, Is.Not.Null);
            Assert.That(ownerIdValue, Is.EqualTo(owner.Value));
```
Replace the user names with your own.

**Comment by jowells1** [comment]
@AngelRodriguez8008 I had come to a similar pattern but the problem is if you have the owner field within the form as well setting the owner throws an exception.  In fact, I believe this is an issue for all fields that are in the header and available on the form.    

AppElementReference.cs:
`{ "Entity_TextFieldContainer", "//*[contains(@id, \'[NAME]-FieldSectionItemContainer\')]" },`

![image](https://user-images.githubusercontent.com/34693792/72826479-85e15f00-3c3e-11ea-9c16-cf27324278ec.png)

I think we are going to need to do some conditional logic where SetValue will have to be passed a boolean value (default false) and set true for headers.  We will then have to extend the AppElementReference to xpath header fields, prefixed with header_.  I want to talk with @dtu11 to get his take on how we should handle this scenario.


  Message: 
    Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.OpenCaseUCI.UCITestOpenCaseRetrieveHeaderValues threw exception: 
    OpenQA.Selenium.ElementClickInterceptedException: **element click intercepted**: Element <button id="id-915f6055-2e07-4276-ae08-2b96c8d02c57-12-ownerid8-ownerid.fieldControl-LookupResultsDropdown_ownerid_3_selected_tag_delete_0" aria-label="Delete Christa Geller (Sample Data)" role="button" tabindex="-1" data-id="ownerid.fieldControl-LookupResultsDropdown_ownerid_selected_tag_delete" type="button" class="a rc rd s r vp gk de du t gr flexbox">...</button> is not clickable at point (662, 754). **Other element would receive the click:** <div aria-label="Item 3 of 3" role="listitem" class="listItemHorizontal-104 itemWrapper-333">...</div>

**Comment by KhoaAN** [comment]
@jowells1  Are you working on a fix for this? If you aren't, I wanna give it a go.

**Comment by AngelRodriguez8008** [comment]
Hi, @jowells1, Hi @KhoaAN. I 'm working on it. 

I fixed it in PR #747, can you please take a look, run some tests i need MFA to tests properly but I create this PR, independently of MFA. to make the changes more understandable.

@jowells1, I reproduce your test UCITestOpenCaseRetrieveHeaderValues as you describe it & also did some others in the same file. This logic should work fine for now just for OptionSets & Lookups. I will extended it to the others controls types. Sorry I don't follow your suggestion of a  "SetValue with a boolean value". I refactored the SetValue in TrySetValue with the Field Container & call this from SetValue & SetHeaderValue, this last one look for the fields just inside the Flyout that you popout in #718. Please review these methods. Thanks in advance.

The logic with delegates is a bit unreadable, everything in one big file, is not optimal. I prefer different controls classes with the methods get & set value. It is more simple and extendable.
ex: HeaderControls, FormContros, ProccessBarControls, etc. & foreach one a variant of OptionsSet, Boolean, Text, Lookup Controls, etc. 
Maybe in the next version.

br.

**Comment by KhoaAN** [comment]
@AngelRodriguez8008 Thanks! I will check it out.

**Comment by AngelRodriguez8008** [comment]
Hi @jowells1, 

How had works my fixes for you? I am changing the logic for the other controls types. Did you find some Issue?

BR
Angel A.
