### ISSUE TITLE
[HOW-TO] Anyone able to help with using date pickers in Dynamics?

### ISSUE THREAD

**Issue by JakeObrienMercuryXrm** [Microsoft/EasyRepro#722]
Is anyone able to help with using date pickers in Dynamics?

I'm attempting to select a from a date picker, I can select the element and then begin to type the the date but as the typing starts the date picker is displayed and then seems to stop the typing as the focus is taken from the textbox and to the date picker instead. 

xrmApp.Entity.SetValue("startdate", todaysDate);

![image](https://user-images.githubusercontent.com/59575810/72711514-18133580-3b61-11ea-82cd-0eec2cf3932f.png)

Any help is massively appreciated. 

I might be able to manipulate it using Selenium possibly but was wondering if there was any other way using the EasyRepro framework that might be a easier.

**Comment by AngelRodriguez8008** [comment]
Hi @JakeObrienMercuryXrm,

I found yesterday an Issue with the Date Input. 
First: check if your date is entered in the right format, default is ("M/d/yyyy h:mm tt") in German I use:
```csharp
            var format = "dd.MM.yyyy";
            DateTime expectedDate = DateTime.Today;
            xrmApp.Entity.SetHeaderValue(Opportunity.EstimatedCloseDate, expectedDate, format);
```
Second: 
in EasyRepro Code for UCI
![image](https://user-images.githubusercontent.com/27274469/72715939-b27b7500-3b71-11ea-97de-2846c1cdd58a.png)
I found that 1 is happening parallel (at the same time) to 2 that is the reason why some part of the date are removed or typed incorrectly.  Adding 3 some time to wait solve the problem, for me. 

Maybe this is not the best solution; my Date Field is in Header that can make also a difference.
Try it the Microsoft guys should say the last word.

Let me know if need help to compile a own Version of EasyRepro.

**Comment by JakeObrienMercuryXrm** [comment]
Thanks for the response but still no luck unfortunately. The focus is switched and then only half of the date entered before eventually closing .

**Comment by JakeObrienMercuryXrm** [comment]
I've managed to find a work around for now , it's not great as I would like to use GetDateTime.ToString to get today's date but I can input it just using a hard-coded string as follows: 

xrmApp.Entity.SetValue("startdate", "01/01/" + "2021");

Why this works, I don't know but I'm able to progress for now until I can put in a good fix for it.

**Comment by AngelRodriguez8008** [comment]
It may works because your are calling a different WebClient.SetValue Method, the same as for strings & numbers. I don't know why there is two different implementations, but seems to be with related the Time part of the Date Time.

It should work also with  "01/01/2021". It is the same. Or? 
What happen if you try a different day of January?

I will try to fix it.  Did you have the Time Part of the Control in Form?

**Comment by JakeObrienMercuryXrm** [comment]
Great, I can confirm it does work with alternative dates too.
There is no time, just date in the control dd/MM/yyyy format.

**Comment by AngelRodriguez8008** [comment]
I hope it is fixed now, i add two tests/samples. If it does not work for you, please add your tests hier. 

I think format is not longer required, i keep the parameters just in case. But it was required to split it in formatDate & formatTime. 

There is also a new GetValue(with DateTimeControl).

**Comment by JakeObrienMercuryXrm** [comment]
Great, I shall take a look and get back to you.
Thanks again :)

**Comment by JakeObrienMercuryXrm** [comment]
Yes, that has worked for me. Thank you!
