### ISSUE TITLE
Login to support multi-factor authentication

### ISSUE THREAD

**Issue by tristanperper** [Microsoft/EasyRepro#726]
**Describe the feature**  
Login to support supplying otp key.
Login method to have otp key parameter and must be able to supply the otp key during login.

**Explain why this feature is needed**  
D365 users (in our case) will be asked always for an otp key since MFA is a security feature for Dynamics 365. The key will be coming from Microsoft Authenticator App 
<img width="343" alt="Untitled" src="https://user-images.githubusercontent.com/56908856/72786178-e5a03000-3c67-11ea-8692-799e3b3afa13.png">
(instead of sms).

**Additional context**

**Comment by AngelRodriguez8008** [comment]
Hi @tristanperper,

I got yesterday the same Issue in a new Online Trial version. 

I solve it few weeks ago:
See my comment [hier ](https://github.com/microsoft/EasyRepro/issues/653#issuecomment-550516716). 
I will try to extract this feature from my Fork & merge to the mainstream, I will come back to you.

br

**Comment by jhandel** [comment]
Our organization uses Azure MFA which doesn't seem to provide a way to get the MFA Secret (it gets handed to the Microsoft Authenticator over a one time SSL call... Anyone have a suggestion on how to get MFA to work or is this an instance were I need to have an "interesting" conversation with IT and security as to why we need a non-MFA account with near "universal" permissions to our dev CRM?

**Comment by tristanperper** [comment]
> Hi @tristanperper,
> 
> I got yesterday the same Issue in a new Online Trial version.
> 
> I solve it few weeks ago:
> See my comment [hier ](https://github.com/microsoft/EasyRepro/issues/653#issuecomment-550516716).
> I will try to extract this feature from my Fork & merge to the mainstream, I will come back to you.
> 
> br

will check on this one.

**Comment by tristanperper** [comment]
> Hi @tristanperper,
> 
> I got yesterday the same Issue in a new Online Trial version.
> 
> I solve it few weeks ago:
> See my comment [hier ](https://github.com/microsoft/EasyRepro/issues/653#issuecomment-550516716).
> I will try to extract this feature from my Fork & merge to the mainstream, I will come back to you.
> 
> br

thank you very much.. i've seen your code... i also have tried to create a local branch forked from release v9.1 and made that same solution as yours (Login with MFA) / jsakamoto solution. it also worked in my local branch.

though my questions are, 1] when will it be merged and into what release? 2] will it be available as an official package (Visual Studio -> reference -> Manage Nuget Packages) ?

**Comment by jhandel** [comment]
I also tried the fix, I got it merged in fine, but ( at least for me) there is no way to get the MFA secret with how our Azure AD and MFA is configured.

**Comment by AngelRodriguez8008** [comment]
Hi @tristanperper,

I'm glad to ear that it is working for you. I create a branch & I want to merge it to develop. But I found at least an Issue with the UCIPerformanceMode and I want to tests it before I create a pull request. See #731. I hope it will be official soon.

Thanks & br

**Comment by AngelRodriguez8008** [comment]
Hi @jhandel,

> I also tried the fix, I got it merged in fine, but ( at least for me) there is no way to get the MFA secret with how our Azure AD and MFA is configured.

Try to navigate
1. From your [Profile](https://account.activedirectory.windowsazure.com/r#/profile) to [`Additional security verification `](https://account.activedirectory.windowsazure.com/Proofup.aspx)
2. Click button "Set up Authenticator app"
![image](https://user-images.githubusercontent.com/27274469/72993474-b9b2b500-3df5-11ea-8290-fda0acff29df.png)
3.  Click link "Configure app without notifications"
4.  Get the in table bellow the "Secret Key" & remove the spaces.
5. Add it to app.config or Variable in Build Pipeline ... whatever your configuration look like.
```xml
<add key="MfaSecrectKey" value=""/>
```
Related to: [wiki: Azure-DevOps-Test-Execution](https://github.com/Microsoft/EasyRepro/wiki/Azure-DevOps-Test-Execution)
That work for me.

br

**Comment by jhandel** [comment]
@AngelRodriguez8008 our IT had moved us to the "preview" version of the MFA UI.. Once we rolled it back to the current UI (like your screen shot) I was able to find it.

Thanks

**Comment by tristanperper** [comment]
> Hi @tristanperper,
> 
> I'm glad to ear that it is working for you. I create a branch & I want to merge it to develop. But I found at least an Issue with the UCIPerformanceMode and I want to tests it before I create a pull request. See #731. I hope it will be official soon.
> 
> Thanks & br
Hi @AngelRodriguez8008

Is this somehow related to UCIPerformanceMode being missing? I encountered that in my local... what I do is remove then replace the UIAutomation.Browser binary (dll coming from EasyRepro release v9.1) reference in my solution ...

**Comment by AngelRodriguez8008** [comment]
Hi @tristanperper,

Thanks for the Info. After merge with #734 the Issue with the UCIPerformanceMode was solved. Maybe was required just Clean & Rebuild of the Solution. I create the Pull Request #735 for this branch.

br

**Comment by tristanperper** [comment]
Hi @AngelRodriguez8008 ,

Will check on this pull request and skim-thru those changes. Will monitor this pull request until it closed. Thank you very much!! :)

**Comment by tristanperper** [comment]
Hi @AngelRodriguez8008 ,

I already have the new Dynamics365.UI.Automation.Api referenced in our automation solution/project.
The version is v9.1.0.12.013 as referenced thru NuGet Package Manager. It carries the feature Login With MFA.

But upon using or testing the new login (it does convert the mfa/otp), there is an error upon page redirection. Please see attached screenshot.
<img width="945" alt="MFAError" src="https://user-images.githubusercontent.com/56908856/75008015-d522e580-54b1-11ea-86ff-f7f7c6d138da.png">

This kind of error does not occur in previous login implementation (wherein i would just manually supply the otp on the page).

I have also check/test the login manually the system-under-test seems to work fine.

**Comment by AngelRodriguez8008** [comment]
Hi @tristanperper,

In which point of the execution are you getting this error? How your "app.config" look like? Which format has your mfa-secrect-key? Did you see the OTC dialog? How look your tests results like, there is some errors printed? Are you getting redirected like in #770? Url? Browser?

I will appreciate more information about this error. You can also open an Issue for that.

Thanks & br

**Comment by tristanperper** [comment]
> Hi @tristanperper,
> 
> In which point of the execution are you getting this error? How your "app.config" look like? Which format has your mfa-secrect-key? Did you see the OTC dialog? How look your tests results like, there is some errors printed? Are you getting redirected like in #770? Url? Browser?
> 
> I will appreciate more information about this error. You can also open an Issue for that.
> 
> Thanks & br

Hi @AngelRodriguez8008 ,
1. The error is happening after the login.
2. My app.config looks something like this

```
> <configuration>
>   <runtime>
>     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
>       <dependentAssembly>
>         <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
>       </dependentAssembly>
>       <dependentAssembly>
>         <assemblyIdentity name="Otp.NET" publicKeyToken="38a48df817e173a6" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-1.2.2.0" newVersion="1.2.2.0" />
>       </dependentAssembly>
>     </assemblyBinding>
>   </runtime>
>   <appSettings>
>     <add key="OnlineUsername" value="" />
>     <add key="OnlinePassword" value="" />
>     <add key="OnlineCrmUrl" value="https://somesitefordynamics.com/" />
>     <add key="OTP" value="" />
> 

```
3. add key="OTP" value=""      ---->    this parameter carries the mfa-secret key

4. Yes I see the OTC dialog and otp has been successfuly converted and submitted.

5. There is a server application error (please refer to the attached screenshot from my previous comment)

6. I was redirected in this URL   https://somesitefordynamics/&flags=easyreproautomation=true,testmode=true&perf=true

7. The browser I used is Firefox 73.0.1 (64-bit)

I also tried the solution in https://github.com/microsoft/EasyRepro/commit/44f8cd99e5ae47f1a2d60b411caf8931886d4436?diff=split

driver.WaitForPageToLoad();
But unfortunately, same server application error is displayed.

I tried putting the following line in method InitializeModes:
**Thread.Sleep(10000);**
driver.WaitForPageToLoad();
Page redirection seems to working fine now.
Regards,

Created issue/bug in this link https://github.com/microsoft/EasyRepro/issues/778

Tristan Perper

**Comment by haidykhaled** [comment]
@tristanperper did you find any solution for logging with authentication?

**Comment by DotaABhash** [comment]
@AngelRodriguez8008 I was trying to bypass MFA in one of my CRM application using the secret key, I did everything right the steps ask to, but it seems to be stuck on the OTP screen can you please help me out ....
![Screenshot 2024-03-25 142225](https://github.com/microsoft/EasyRepro/assets/164859253/970c2a7e-9ee4-4376-8a46-02d0bbca7f33)
![image](https://github.com/microsoft/EasyRepro/assets/164859253/56e0f9be-d3b2-437f-affd-c63f00e35499)

**Comment by Shakevg** [comment]
[DotaABhash](https://github.com/DotaABhash) Please create separate issue, I will post workaround
