### ISSUE TITLE
[HOW-TO] How do I click a button related to a sub-grid?

### ISSUE THREAD

**Issue by JakeObrienMercuryXrm** [Microsoft/EasyRepro#727]
How do I click a button related to a sub-grid?

Using: C#, Selenium, ChromeDriver

So, I have an issue where I can't click buttons related to a subgrid. 
Take the following code: 

`xrmApp.RelatedGrid.ClickCommand("SubGridAddExistingAssociate);`

The above is a custom button but I have also tested using the following code to click the standard Refresh button with no luck.
``xrmApp.RelatedGrid.ClickCommand("Refresh);``

The form looks like this: 
![image](https://user-images.githubusercontent.com/59575810/72799865-0eabcb00-3c3e-11ea-9a2a-249f1a3bac4e.png)

And the HTML is as follows:
![image](https://user-images.githubusercontent.com/59575810/72799919-297e3f80-3c3e-11ea-9d0e-3765c71c1805.png)

Regardless of what I have tried elsewhere in the system I just can't seem to be able to click any buttons on any sub-grids.

Any idea?

**Comment by mikhailchub** [comment]
Yes, I had the same issue and solved it by adding a custom method to CommandBar.cs - ClickSubGridCommand, + added missing subgrid locators to AppElementReference.cs and adjusted a bit the original method ClickCommand in WebClient.cs (to switch to subgrid if it gets 'true' as a third parameter).

Shortly: there are no proper locators for subgrid container in AppElementReference.cs, and if you add them and few lines of code to work with them - should be fine.

In my case it looks like this for AppElementReference.cs:
was:
```
        public static class CommandBar
        {
            public static string Container = "Cmd_Container";
            public static string ContainerGrid = "Cmd_ContainerGrid";
            public static string MoreCommandsMenu = "Cmd_MoreCommandsMenu";
            public static string Button = "Cmd_Button";
        }
...
            //CommandBar
            { "Cmd_Container"       , "//ul[contains(@data-lp-id,\"commandbar-Form\")]"},
            { "Cmd_ContainerGrid"       , "//ul[contains(@data-lp-id,\"commandbar-HomePageGrid\")]"},
            { "Cmd_MoreCommandsMenu"       , "//*[@id=\"__flyoutRootNode\"]"},
            { "Cmd_Button", "//*[contains(text(),'[NAME]')]"},
```
is:
```
        public static class CommandBar
        {
            public static string Container = "Cmd_Container";
            public static string ContainerGrid = "Cmd_ContainerGrid";
            public static string ContainerSubGrid = "Cmd_ContainerSubGrid";
            public static string MoreCommandsMenu = "Cmd_MoreCommandsMenu";
            public static string Button = "Cmd_Button";
        }
...
            //CommandBar
            { "Cmd_Container"       , "//ul[contains(@data-lp-id,\"commandbar-Form\")]"},
            { "Cmd_ContainerGrid"       , "//ul[contains(@data-lp-id,\"commandbar-HomePageGrid\")]"},
            { "Cmd_ContainerSubGrid"       , "//ul[contains(@data-lp-id,\"commandbar-SubGrid\")]"},
            { "Cmd_MoreCommandsMenu"       , "//*[@id=\"__flyoutRootNode\"]"},
            { "Cmd_Button", "//*[contains(text(),'[NAME]')]"},

```

PS   maybe I need to make it as a pull-request to this repo

**Comment by JakeObrienMercuryXrm** [comment]
Thank you very much for this, I'll give it a go now

**Comment by JakeObrienMercuryXrm** [comment]
Yes, got it working, thank you very much!
