### ISSUE TITLE
[HOW-TO] How do I handle a popup after an Entity.Save command?

### ISSUE THREAD

**Issue by JakeObrienMercuryXrm** [Microsoft/EasyRepro#728]
How do I handle a popup after a Entity.Save command?

On some forms when I use Entity.Save() there is an alert displayed which is custom as a warning to users about what will happen when saved. However, I am unable to accept the alert before the test fails. I'm guessing this is down to the Save command not being able to complete and therefore failing but I can't seem to work around it in any way. 

I have tried the following code: 
`xrmApp.Entity.Save();
xrmApp.ThinkTime(5000);
IAlert alert = Driver.driver.SwitchTo().Alert();
alert.Accept();`

Any ideas?

**Comment by tipsey** [comment]
Have you tried using a try statement?

 try
                {
                //code to save the form
                }
                catch (Exception)
                {

                   //code to dismiss the alert and proceed
                }

**Comment by JakeObrienMercuryXrm** [comment]
Hi, yeah, I've manged to fix this with code similar to the above. Thanks
