### ISSUE TITLE
Sample UploadTelemetry.cs uses hard-coded Azure Key, although it is defined in app.config

### ISSUE THREAD

**Issue by sanjint** [Microsoft/EasyRepro#73]
EasyRepro/Microsoft.Dynamics365.UIAutomation.Sample/UploadTelemetry.cs; Lines 52 & 58.

The key is hard-coded in the test script:
new Telemetry().AzureKey("[AZURE KEY GOES HERE]")

But the parameter is available in the app.config:
<add key="AzureKey" value="" />

**Comment by dtu11** [comment]
The pull request is approved and the fix is in the 9.0 build.
