### ISSUE TITLE
[HOW-TO] create testing framework employing easyRepro for multiple envs and users 

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#738]
We need to test in different staging envs (UAT, QA, PSUP). I am required to create a test framework to use easyRepro for all our staging envs. We also need to switch users during the test, so the expected framework would also handle the different users. For CI, CD the expected framework should also generate reports for validate the test results after all the tests are triggered automatically by the build. I am using Nunit framework. Could you help in building such framework to employ easyRepro in real test?

Thanks!

**Comment by AngelRodriguez8008** [comment]
Hi @xuejunh,

You can create in DevOps different Pipelines with different Variables & Triggers, for each of your Env & users that you have, also associate this to different branches in your code, for diff stages of the code.

see: [Wiki: Azure DevOps Test Execution](https://github.com/Microsoft/EasyRepro/wiki/Azure-DevOps-Test-Execution)

in #729 i put an example for File Transform & Variables Substitution in Pipeline, check also the app.config & app.build.config in this PR.

If you configure DevOps properly you will see the tests results in the Pipeline, you can filter & navigate through these. I will also add some improvements in Traces in the next days, i have already done in my fork. after that you should be able to see in DevOps (test attachments) step by step what your tests did.

I am running also my tests in NUnit, it is not a problem. You just need to add the right configuration for the step Publish Test Results in the pipeline. NUnit Runner use *.trx files instead *.xml for tests results.

I don't understand your last question: " Could you help in building such framework to employ easyRepro in real test?". But maybe that answer this: I use EasyRepro in a "real" customer project, together other types of tests. 

Your question is not easy to answer in a comment. At the moment there is none Step by Step Guide how to do this. It take will take some time until you get everything running as you want. I hope that it help you. Good Luck!

BR.

**Comment by xuejunh** [comment]
@AngelRodriguez8008 For different env there is different CRM url. Where in the above Azure DevOps Test Execution is this different CRM url passed in to the tests?

**Comment by AngelRodriguez8008** [comment]
CRM url is a parameter in app.config

I wrote:
> Different Pipelines with different Variables ... in #729 i put an example for **File Transform & Variables Substitution in Pipeline**, check also the app.config & app.build.config in this PR.

![image](https://user-images.githubusercontent.com/27274469/73430936-7f8a6b80-433f-11ea-9277-2d9fe37d6c98.png)

![image](https://user-images.githubusercontent.com/27274469/73431178-19521880-4340-11ea-9531-7230e1f9fade.png)

You can also use Tests Filters if you want to run diff tests in diff Envs.

**Comment by bwmodular** [comment]
Another option is to use Visual Studio RunSettings files.
These are documented here:
https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

You can have a number of different RunSettings files in your project, and the values will be available in the test run context.

You can switch between the different settings files in Visual Studio so you can test against different environments in the IDE:
![image](https://user-images.githubusercontent.com/1889586/73433496-bdd25b80-433c-11ea-9195-7817c7fa102e.png)

If you publish these files as build artefacts in your build pipeline, you can then refer to them in your release pipeline in your test tasks.
![image](https://user-images.githubusercontent.com/1889586/73433587-f2461780-433c-11ea-8a3a-ed148871413b.png)

**Comment by xuejunh** [comment]
Thanks for all the details! If I want to run my test suites in Chrome first then in Edge, how should I setup this through AZure DevOp and pipeline?

**Comment by AngelRodriguez8008** [comment]
This is posible in the way that we has already explain you. Check the configuration paramenter in app.config & try it is easy.

Please close the Issues that you got already clarified.

BR

**Comment by jaithunsheik** [comment]
Hi @AngelRodriguez8008 ,
Could you please tell me how this transform file can be tested locally in visual studio before testing it in devops?
Your help is highly appreciated.
Thanks
