### ISSUE TITLE
[HOW-TO] add WaitUntilAvailable to the test

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#739]
I have the following code piece where I try to add waitUntilAvailable for SubArea("Sales", "Contacts"). How can I do this? Thanks!

[Test]
        public void UCITestCreateContact()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
                xrmApp.ThinkTime(5000);
                //xrmApp.Navigation.OpenApp(UCIAppName.Sales);
                client.Browser.Driver.WaitUntilAvailable();
                xrmApp.Navigation.OpenSubArea("Sales", "Contacts");

                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.Entity.SetValue("firstname", TestSettings.GetRandomString(5, 10));
                xrmApp.Entity.SetValue("lastname", TestSettings.GetRandomString(5, 10));

                xrmApp.Entity.Save();
            }

**Comment by AngelRodriguez8008** [comment]
You don't need to Wait. This is already included in the call to OpenSubArea in the latest version
![image](https://user-images.githubusercontent.com/27274469/74067476-a9a3f380-49f9-11ea-8021-aa0891c2ee77.png)

**Comment by AngelRodriguez8008** [comment]
Hi @xuejunh, 

Are you already familiar with the Wait-Methods?

Ex: `var input = client.Browser.Driver.WaitUntilClickable(By.XPath("//input[@aria-label='Customer  Lookup']"));`

here is another way, full example ([at the end, expand to see it](https://github.com/microsoft/EasyRepro/issues/769#issuecomment-589473653)) 
                
Can we close this Issue? Can I help you in some way?

br.

**Comment by xuejunh** [comment]
Thanks! I am closing this one.
