### ISSUE TITLE
Stay signed in message

### ISSUE THREAD

**Issue by maichung77** [Microsoft/EasyRepro#74]
Hi,
I'm using CRM online version.  I got the "Stay signed in" message after logging in and couldn't proceed further.  Is there an API that I can use to close this dialog box?

Thanks,
Mai

**Comment by dtu11** [comment]
The latest update should address this change.  Let me know if you have the latest changes and the login api doesn't get past this issue.

**Comment by maichung77** [comment]
Is it fixed in 8.2 version?  I just downloaded the 8.2 version and this issue is still there.

**Comment by dtu11** [comment]
That branch has the update. If you check the LoginPage.cs  there should be code that looks like below. 

 if (driver.IsVisible(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])))
                        {
                                driver.ClickWhenAvailable(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])); 
                                driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])).Submit();
                        }
 You may be running into another issue.  Does it just stop on that page?

**Comment by maichung77** [comment]
The LoginPage.cs does have the code you mentioned.  The following exception was thrown when executing the following line in the Login method.                    driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(password.ToUnsecureString());

Error Message: {"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@type='password']\"}\n  (Session info: chrome=61.0.3163.91)\n  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.14393 x86_64)"}

I'm using Office 365 authentication, so a password is not needed when logging in from the browser.  I have confirmed that the correct online user name and password are stored in App.config.

**Comment by dtu11** [comment]
Ok, the login process is expecting the password input to be there.   If your authentication is bypassing that step then the API will not work.   You will need to either 1) modify the Login API to skip that step or 2) Look at the ADFSLogin.cs sample and use that to build you're own login logic that bypass the password input.    Make sense?

**Comment by maichung77** [comment]
Interesting, I was able to get it working by putting the thread to sleep for 1 second and commenting out a few lines of code in the Login method as shown below.  Is this a valid workaround?

//Wait for a second
Thread.Sleep(1000);
                   //driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(password.ToUnsecureString());                   //driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(Keys.Tab);
//driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).Submit();

if (driver.IsVisible(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])))
{
    driver.ClickWhenAvailable(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])); 
    driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])).Submit();
}

**Comment by dtu11** [comment]
That is a valid workaround that will work for your environment.  Just keep in mind that if the authentication changes and requires a password then it will stop working.    It's either that or look at the ADFSLogin.cs as an alternative.  That sample basically enters the email address, waits for the redirect and then calls your custom method that handles your login page.   In your case it won't require a password. 

Let me know if you need anything else.

**Comment by maichung77** [comment]
Got it, thanks very much Daren for your help!

**Comment by dtu11** [comment]
You're welcome!
