### ISSUE TITLE
Two Option Set Set Value Issue

### ISSUE THREAD

**Issue by manas3487** [Microsoft/EasyRepro#743]
Hi I am unable to set the two option set value using the following code for UCI 
xrmApp.Entity.SetValue(new OptionSet { Name = "gendercode", Value = "1" })

Can you please provide me the solution to set the value for UCI

**Comment by AngelRodriguez8008** [comment]
Try to use the DisplayName, not the Value (Male or Female).

**Comment by manas3487** [comment]
I tried with that approach too but i am unable to set the value.
xrmApp.Entity.SetValue(new OptionSet { Name = "gendercode", Value = "Male" });

**Comment by mVermaat** [comment]
There is an overload specifically for boolean fields like this:

app.Entity.SetValue(new BooleanItem { Name = LogicalName, Value = true });

**Comment by AngelRodriguez8008** [comment]
Hi @manas3487 ,

The follow code run perfectly in the current version. Check that you are moving to the right Tab.
(Details in my case). If this do not work for you, please post hier the error that you get and a screenshot of your form.

```csharp  

[TestMethod]
public void UCITestCreateContact_SetGender()
{
    var client = new WebClient(TestSettings.Options);
    using (var xrmApp = new XrmApp(client))
    {
        xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

        xrmApp.Navigation.OpenApp(UCIAppName.Sales);

        xrmApp.Navigation.OpenSubArea("Sales", "Contacts");

        xrmApp.CommandBar.ClickCommand("New");

        xrmApp.Entity.SetValue("firstname", "Test " +TestSettings.GetRandomString(5,10));
        xrmApp.Entity.SetValue("lastname", "Contact " + TestSettings.GetRandomString(5,10));
        
        xrmApp.Entity.SelectTab("Details");

        xrmApp.Entity.SetValue(new OptionSet{ Name ="gendercode" , Value = "Male"} );
        string gender = xrmApp.Entity.GetValue(new OptionSet { Name ="gendercode" } );
        Assert.AreEqual("Male", gender);
    }   
}
```
br

**Comment by manas3487** [comment]
Hi @AngelRodriguez8008 your code works perferly now. 
The mistake what i am making is not selecting the tab and now with your code i am able to execute perfectly.Just wanted to know some information on this. 
1.For suppose if the field is not available on the form and if we need to set the value to that field and test could it be possible
 2. How do we set the statecode and status code as they are not part of any tab.

**Comment by AngelRodriguez8008** [comment]
EasyRepro (like Selenium) is intended to Simulate the normal User Interaction, without Chrome Extensions like "Level up" that simulate God Mode or similar. See more Details in #463

That mean with the "standard" EasyRepro you will not be able to do 1. nor 2. 

Also Using JS code & window.Xrm functionalities, the fields should be in the Form, but can be hidden.
With this idea I created PR #172 that allow you to do such thinks, 

 xrmApp.FormJS.SetValue("gendercode", 1) 

See hier the [samples](https://github.com/microsoft/EasyRepro/blob/f84b08a94e25a1cb55567f071c484dc57e114fd5/Microsoft.Dynamics365.UIAutomation.Sample/Web/FormJS/CreateAccount.cs)

But this was never accepted.

**Comment by AngelRodriguez8008** [comment]
Set the statecode and status code can you maybe use the commands buttons "Activate" & "Deactivate" in ribbon. Analog Open, Close & Reopen in Opportunities. This is already implemented.

**Comment by manas3487** [comment]
Thanks @AngelRodriguez8008 . I am closing the ticket as i am able to achieve the functionality with your Inputs.

Thanks,
Manas
