### ISSUE TITLE
Login using AD authentication

### ISSUE THREAD

**Issue by furqansafdar** [Microsoft/EasyRepro#744]
How to login into Dynamics 365 using Active Directory credentials? 

When navigating to main page, it is prompting me to key in AD username and password. Tried different options but no luck.

**Comment by AngelRodriguez8008** [comment]
Can you explain you question bit more? Is about EasyRepro? Or just Dynamics 365?

Try [Getting-Started](https://github.com/Microsoft/EasyRepro/wiki/Getting-Started) step 7.

**Comment by furqansafdar** [comment]
I am talking Active Directory authentication in CRM on-premise version. Does it support on-premise?

**Comment by AngelRodriguez8008** [comment]
What you means with: 
>"When navigating to main page, it is prompting me to key in AD username and password. Tried different options but no luck."

Are you manually navigating or EasyRepro? Which options you tryed? Which Automated UI Tests are you running?

**Comment by AngelRodriguez8008** [comment]
By the way it can partially work depending of your CRM version, but officially EasyRepro do not support CRM On-premise. See the [list of supported versions](https://github.com/microsoft/EasyRepro#crm-versions)

**Comment by furqansafdar** [comment]
Ok so i started again with another search particular to on-repmise and got my hands on this [post](https://github.com/Microsoft/EasyRepro/issues/60) and eventually on this on-premise [release](https://github.com/microsoft/EasyRepro/tree/releases/OnPremise) and could able to run the sample to login with AD authentication successfully. Perhaps i was using online packages trying to login into on-premise envionment earlier. Thanks anyways.
