### ISSUE TITLE
Issue on GetValue From Lookup 

### ISSUE THREAD

**Issue by ejfdejesus** [Microsoft/EasyRepro#756]
I tried to run this test method from the UIAutomation.Sample project and it is failing when the lookup field contains a value. It is showing "System.InvalidOperationException: 'Field: primarycontactid Does not exist'"

public void UCITestGetValueFromLookup()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecrectKey);
                xrmApp.Navigation.OpenApp(UCIAppName.Sales);
                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");
                xrmApp.Grid.OpenRecord(0);
                xrmApp.ThinkTime(2000);
                string lookupValue = xrmApp.Entity.GetValue(new LookupItem { Name = "primarycontactid" });
            }
        }

**Comment by AngelRodriguez8008** [comment]
Hi @ejfdejesus,

I fixed it in PR #754, there is three posibilites for this to fail 
1. there is not Records in the Default View in this case use  `xrmApp.Grid.SwitchView("Active Accounts")` before OpenRecord. 
2. The DobleClick it not working read the  Description on PR #754,
Please check that in  this PR is also working for you.
3. The Field: primarycontactid  really do not exist in the Form, in this case please fix your form.

Thanks & br

**Comment by ejfdejesus** [comment]
Thanks, Angel!

"primarycontactid" lookup field exists however when this field contains a value the above test is failing but when it is null the test is passed.

![image](https://user-images.githubusercontent.com/34220212/74179041-7edbc880-4ca1-11ea-8321-8dc4a006d8fe.png)

**Comment by AngelRodriguez8008** [comment]
Strange. This Test pass for me. Is OpenRecord(0) working fine in the fail case, did you get the Account Form Open?

**Comment by ejfdejesus** [comment]
Yes. I created a test record so that I don't need to switch view and I'm able to open the record using the OpenRecord(0) then it fails on the GetValue step. 

When I tried to remove the value on the lookup, this test pass for me, but when I enter a value and re run the test it is failing. 

This specific step started failing after the CRM service update on 9 Feb (https://support.microsoft.com/en-us/help/4532168/service-update-132-for-microsoft-dynamics-365-9-1-0).

**Comment by AngelRodriguez8008** [comment]
You mention today that you has testet in develop. Can you try please to tests this error in the code from PR #754 (no approved jet)?

I have none better idea now.

Thanks

**Comment by ejfdejesus** [comment]
Yes, I tested this on the latest develop branch and still the same result.

**Comment by AngelRodriguez8008** [comment]
Hi @ejfdejesus, 

The PR #754 is not in 'develop' jet, you can get it from [hier](https://github.com/AngelRodriguez8008/EasyRepro/tree/users/angel/fixSamples). Can you try this?

Thanks & br

**Comment by ejfdejesus** [comment]
Hi @AngelRodriguez8008 ,

Apologies on late reply. I have tested with your branch and the test passed however the lookupValue is incorrect. My expected value is "test test" based on my screenshot on my previous comment.

![image](https://user-images.githubusercontent.com/34220212/74679718-806a3b00-5223-11ea-9129-9c9f918c903b.png)

**Comment by AngelRodriguez8008** [comment]
Ok. I was able to reproduce it. Look like we are getting the wrong XPath value.
![image](https://user-images.githubusercontent.com/27274469/74687905-0fe8fd00-51d6-11ea-8db1-cb5dbb89931e.png)

I will check that!

**Comment by AngelRodriguez8008** [comment]
Checking the Code there is two different implementations for GetValue From Lookup:
1. for one value GetValue(LookupItem)
2. activity party fields GetValue(LookupItem[])

It look like 2. should work fine for 1. too, but the current implementation of 1. is no longer working. At least in the cases that I check for 5 lookups.

I will change the  implementation of 1. 
In the middle time: Can you check please that the follow code works for you?
```csharp
string[] lookupValues = _xrmApp.Entity.GetValue(new[]{ new LookupItem {Name = "primarycontactid"} });
Assert.IsNotNull(lookupValues);
Assert.AreEqual(1, lookupValues.Length);
Assert.AreEqual("test test", lookupValues[0]);
```

This logic was added in PR #515 & is related to #371

**Comment by thathi** [comment]
Hi @AngelRodriguez8008 Entity.GetValue(new LookupItem() { Name = Metadata.LogicalName }) is returning value in lower case?

**Comment by AngelRodriguez8008** [comment]
Thanks @thathi. PR is created.
