### ISSUE TITLE
Would you please add assert to your sample tests to make your tests complete as the expected results are validated?

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#762]
It would be very helpful if you could add assert to all your sample tests to show us what the object should we assert and what the attribute of the object should we use for the assert to validate the operations in the sample tests are working as expected. Use createAccount as an example, after save, what the object and its attribute in the page really indicate the createAccount is done successfully.

Your sample tests do not look completed without assert.

Thanks!

**Comment by gbhuvanesh** [comment]
I will add few.
