### ISSUE TITLE
[HOW-TO] What is the recommended way to access Browser.Driver based on your sample code

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#763]
How to access Bowser.Driver to use the selenium stuff in the following code context?

using NUnit.Framework;

namespace NunitCRMTestProject
{
    [TestFixture]
    public class CreateAccountNunit : TestsBase
    {
        [SetUp]
        public override void InitTest() => base.InitTest();

        [TearDown]
        public override void FinishTest() => base.FinishTest();

        public override void NavigateToHomePage() => _xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

        [Test]
        public void UciTestCreateAccount()
        { 
            _xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

            _xrmApp.CommandBar.ClickCommand("New");

            _xrmApp.Entity.SetValue("name", TestSettings.GetRandomString(5, 15));

            _xrmApp.Entity.Save();
        }
    }
}

**Comment by AngelRodriguez8008** [comment]
_client.Browser.Driver

if you don't have it already get this version of [TestsBase.cs](https://github.com/microsoft/EasyRepro/blob/c9ff50dbdd31d108ecb7bb42c19c57e42f49b92b/Microsoft.Dynamics365.UIAutomation.Sample/UCI/TestsBase.cs),

See also this [samples ](https://github.com/microsoft/EasyRepro/tree/c9ff50dbdd31d108ecb7bb42c19c57e42f49b92b/Microsoft.Dynamics365.UIAutomation.Sample/UCI/QuickStart)to learn how to use the TestsBase, deppends of your needs.

To replace the TestsBase with the latest version your don't need to recompile the DLLs. Just your examples.

**Comment by AngelRodriguez8008** [comment]
In your Code this lines are repeating the same action:

```csharp
    [TearDown]
    public override void FinishTest() => base.FinishTest()

    public override void NavigateToHomePage() => _xrmApp.Navigation.OpenSubArea("Sales", "Accounts"); // run at the start of each tests.

    [Test]
    public void UciTestCreateAccount()
    { 
        _xrmApp.Navigation.OpenSubArea("Sales", "Accounts"); // do the same 

``` 

You have some options:
```csharp
// option 0. keep just this Line
    public override void NavigateToHomePage() => _xrmApp.Navigation.OpenSubArea("Sales", "Accounts"); 
// option 1. Replace this with:
   public override void NavigateToHomePage() => NavigateTo(UCIAppName.Sales, "Sales", "Accounts"); // That will happen before all tests see the samples.
// option 2. If you don't want to go to Accounts in all tests just do that, and choose the areas in each test.
   public override void NavigateToHomePage() => NavigateTo(UCIAppName.Sales); // That will happen before all tests see the samples.

    [Test]
    public void UciTestCreateAccount()
    { 
        _xrmApp.Navigation.OpenSubArea("Sales", "Accounts"); // <=== Remove this for option 0. &1. keep for option 2.
// option 3.: You can also do, in this case you can remove the "override void NavigateToHomePage() => "
        NavigateTo(UCIAppName.Sales, "Sales", "Accounts"); // You are choosing in each test where you want to NavigateTo
// You can also navigate to different Areas in the same test.
```

**Comment by xuejunh** [comment]
//_xrmApp.Navigation.OpenApp(UCIAppName.Sales);
I commented out the above line of code since it breaks my test -- always pops up error saying object not found. Without the above line, the script works. I am using the trial link now since we are still in the design phase and the company url is not available ye.

**Comment by AngelRodriguez8008** [comment]
I updated my comment, its looks like you need the option 0.
if I understand well: You use a link that bringt you direct to the "Sales Hub App"

**Comment by AngelRodriguez8008** [comment]
[UPDATE] I solve the Issue. TestsBase change again, for good :-)

Hi @xuejunh,

I found an Issue in MSTests with the TestsBase class. Can you please confirm that it is not happening NUnit?

By running the follow Test the browser still open in MSTest.

```csharp
    [TestClass]
    public class CreateAccount : TestsBase
    {
        [TestInitialize]
        public override void InitTest() => base.InitTest();

        [TestCleanup]
        public override void FinishTest() => base.FinishTest();

        public override void NavigateToHomePage() => _xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

        [TestMethod]
        public void UCITestCreateAccount()
        {
            throw new Exception("Browser do not get closed");
        }
    } 
```

Thanks.

**Comment by xuejunh** [comment]
The browser was closed running your test in Nunit. But my TestsBase is as follows:
// Created by: Rodriguez Mustelier Angel (rodang)
// Modify On: 2020-01-23 02:51

using System;
using System.Configuration;
using System.Security;
using Microsoft.Dynamics365.UIAutomation.Api.UCI;
using Microsoft.Dynamics365.UIAutomation.Browser;

namespace NunitCRMTestProject
{
    public class TestsBase
    {
        protected readonly Uri _xrmUri = new Uri(ConfigurationManager.AppSettings["OnlineCrmUrl"]);
        protected readonly SecureString _username = ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        protected readonly SecureString _password = ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        //protected readonly SecureString _mfaSecrectKey = ConfigurationManager.AppSettings["MfaSecrectKey"].ToSecureString();
        protected readonly bool _usePrivateMode = Convert.ToBoolean(ConfigurationManager.AppSettings["UsePrivateMode"]);

        protected XrmApp _xrmApp;
        protected WebClient _client;
        protected string _timed(string value) => $"{value} {DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}";

        public virtual void InitTest()
        {
            CreateApp();
            NavigateToHomePage();
        }

        public virtual void FinishTest()
        {
            CloseApp();
        }

        public void CreateApp(bool privateMode = true)
        {
            BrowserOptions options = TestSettings.Options;
            //options.PrivateMode = privateMode || _usePrivateMode;
            options.UCIPerformanceMode = false;

            //var client = new WebClient(options);
            _client = new WebClient(options);
            _xrmApp = new XrmApp(_client);

            //_xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecrectKey);
            _xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
            _xrmApp.ThinkTime(5000);
            //_xrmApp.Navigation.OpenApp(UCIAppName.Sales);
        }

        public void CloseApp()
        {
            _xrmApp.Dispose();
            _xrmApp = null;
            _client = null;
        }

        public virtual void NavigateToHomePage() { }
    }
}

**Comment by AngelRodriguez8008** [comment]
Great!
replace the InitTest with the follow code, just for the case that the Login or Navigation Fail. You will be able to the right error & the browser get closed. 
```csharp
        public virtual void InitTest()
        {
            try
            {  
                CreateApp();
                NavigateToHomePage();
            }
            catch
            {
                CloseApp();
                throw;
            }
        }
```
Thanks
