### ISSUE TITLE
How often do you update the nuget package ?

### ISSUE THREAD

**Issue by imartinflores** [Microsoft/EasyRepro#767]
## Question
Hi Guys, How often do you update the nuget package ? There are some fixes that needs to be implemented I think. At the moment, we are not able to run our tests on a pipeline cause the only way we can get the updates are locally, but not from Nuget.

Thanks

**Comment by TYLEROL** [comment]
Hi @imartinflores - We currently do not have a set release cadence for the NuGet packages. Some of this depends on how many fixes have come into the develop branch. I was planning one a couple weeks ago - but we've had a flurry of PR activity and fixes come in during that time.

With the latest PRs merged and confirmation on some of the fixes, I'll start putting one together for release later today.

Warm Regards,
Tyler

**Comment by TYLEROL** [comment]
Hello @imartinflores - Dynamics365.UIAutomation.Api version 9.1.0.12013 has been released as of a few minutes ago.

Please post new issues as appropriate for any problems you encounter.

Thanks,
Tyler
