### ISSUE TITLE
[BUG] Get 404 after login successfully to CRM in Edge while in Chrome works

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#770]
I updated to the latest easyRepro, I can start Edge inPrivate mode and login to CRM but after login successfully, I got the following:
![image](https://user-images.githubusercontent.com/59613444/74937795-cd344a00-53ba-11ea-8584-6ceb0fff9b06.png)

**Comment by xuejunh** [comment]
I login manually in Edge I can access the CRM:
https://org09856ed2.crm.dynamics.com/main.aspx?appid=ac28c4b1-e739-ea11-a813-000d3a1a1100&pagetype=dashboard&id=2701de60-8f2a-48a4-8262-4a35ca7441fa&type=system&_canOverride=true

it looks the links are different, is there anyting wrong in the automation settings which embedded in the url after logged in?

**Comment by AngelRodriguez8008** [comment]
Hi @xuejunh,

After Login the URL will get to add some Parameters, required to render the App properly, everything that you have after &flag= in your screenshot.  Maybe Edge is redirecting too slow & this method is getting the wrong URL (login.microsoft.com) and redirecting back to it.

Can you set a breakpoint in : 
`WebClient.cs -> method InitializeModes  -> Line 57 ->  driver.Navigate().GoToUrl(testModeUri);`
And check which URL are you getting in `testModeUri`? 
You should get:

first time: 
`https://org09856ed2.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=apps&flags=easyreproautomation=true,testmode=true&perf=true`

second time: 
`https://org09856ed2.crm.dynamics.com/main.aspx?appid=ac28c4b1-e739-ea11-a813-000d3a1a1100&flags=easyreproautomation=true,testmode=true&perf=true`

Thanks & br

**Comment by xuejunh** [comment]
I tried to set breakpoint with my project with easyRepro installed using NuGet. I have the following which is different from the cloned version. I set the endpoint at the line of gotourl but when I debug I did not see the test stopped at the line. for the cloned project I need more setup including if (TestSettings.Options.BrowserType == BrowserType.Edge)
            {
                var edgeDriverPath = @"C:\Windows\SysWOW64\";
                TestSettings.Options.DriversPath = edgeDriverPath;
            }, right? or I can simply set the driverpath in App.config?

internal BrowserCommandResult<bool> InitializeModes()
    {
      return this.Execute<bool>(this.GetOptions("Initialize Unified Interface Modes"), (Func<IWebDriver, bool>) (driver =>
      {
        string url1 = driver.Url;
        string str = "&flags=easyreproautomation=true";
        if (this.Browser.Options.UCITestMode)
          str += ",testmode=true";
        if (this.Browser.Options.UCIPerformanceMode)
          str += "&perf=true";
        if (!url1.Contains(str) && !url1.Contains(HttpUtility.UrlEncode(str)))
        {
          string url2 = url1 + str;
          driver.Navigate().GoToUrl(url2);
        }
        this.WaitForMainPage(new TimeSpan?(), (Action<IWebElement>) null, (Action) null);
        return true;
      }));
    }

**Comment by xuejunh** [comment]
![image](https://user-images.githubusercontent.com/59613444/74972953-a1cc5200-53f0-11ea-92e5-b1cb7ac5e68c.png)

**Comment by AngelRodriguez8008** [comment]
Yes, That is what I expected. The redirect in Edge happen too slow. We need to add some wait for this case. 

Can you add this & check if this work for you?
![image](https://user-images.githubusercontent.com/27274469/74988761-07dfc600-543f-11ea-8fb4-88ffa1a42a06.png)

**Comment by AngelRodriguez8008** [comment]
Hi @xuejunh, 

Thanks for close this Issue. Works  it now with this fix (`WaitForPageToLoad`) or without? Should I add this line to the standard implementation?

br
Angel A.

**Comment by xuejunh** [comment]
@AngelRodriguez8008 it works now with this fix (WaitForPageToLoad), should add this line to the standard implementation.
