### ISSUE TITLE
[BUG] Set path to chromedriver does not work for Nunit while works for UnitTesting

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#771]
![image](https://user-images.githubusercontent.com/59613444/74939283-9c094900-53bd-11ea-8bd9-37037c24759e.png)
 I have 3 tests in the project, I set the following in the App.config:
<add key="DriversPath" value="C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\bin\Debug" />
but only the UnitTesting test passed while other 2 Nunit tests failed at not finding the chromedriver at the temp path

**Comment by AngelRodriguez8008** [comment]
I work also with NUnit, this is another path as MSTest. You should find the right one. Try first an absolute one. Depends also from the runner

**Comment by xuejunh** [comment]
@AngelRodriguez8008 I do not quite get you. I have the following settings in the App.config:
<add key="DriversPath" value="C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\bin\Debug" /> but my Nunit test is still complaining not find chromedriver in the temp path while UnitTesting test passed. What should I try to make the Nunit tests work with the driverspath set?

**Comment by xuejunh** [comment]
add key="DriversPath" value="C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\bin\Debug"

**Comment by AngelRodriguez8008** [comment]
I guest [this comment](https://github.com/microsoft/EasyRepro/issues/770#issuecomment-589267621) belongs to this thread.
>if(TestSettings.Options.BrowserType == BrowserType.Edge)
{
var edgeDriverPath = @"C:\Windows\SysWOW64";
TestSettings.Options.DriversPath = edgeDriverPath;
}, right? or I can simply set the driverpath in App.config?

If the version of the [TestSettings](Microsoft.Dynamics365.UIAutomation.Sample/TestSettings.cs) is correct you can simply put the this path in the `app.config`.

Check this line:
```csharp
TestSettings:37-38:            
     DriversPath = Path.IsPathRooted(DriversPath) ? DriversPath : Path.Combine(Directory.GetCurrentDirectory(), DriversPath) 
```
Remember that the Sample Project is no included in the NUGet package. This files will not be updated automatically.

If you change in `app.config` that will affect all tests


**Note**: I see that you have Resharper installed, also I. When I use the Reshaper Test Runner
in my NUnit Project; (I have the drivers also in `"\bin\Debug"` by default installed via NUGet). I don't need to specify the Path in the `app.config`. I let this empty, but maybe for Edge is different.

this is a Resharper option
![image](https://user-images.githubusercontent.com/27274469/74991045-3496dc00-5445-11ea-9f98-e0482b246653.png)

Look like: VSTest set the Temporary Folder,  i will look for more infos about this, check this [Issue](https://github.com/Microsoft/vstest/issues/504).
