### ISSUE TITLE
Password is not set because unable to locate the Password field 

### ISSUE THREAD

**Issue by ejfdejesus** [Microsoft/EasyRepro#777]
When I run _xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecrectKey);

It always show this error: Unable to locate element:{"method":"xpath","selector":"//input[@type='password']"}

Upon checking, it is because the page is not too fast to load in order to locate the password field. I tried to increase the thinkTime from 1000 to 2000 and this issue is fixed  (LoginResult function).

![image](https://user-images.githubusercontent.com/34220212/75121037-58804900-56f5-11ea-9a0f-f00adfc35d4d.png)

For the meantime what is the best workaround for this on the current release in the nuget package?

**Comment by AngelRodriguez8008** [comment]
Hi @ejfdejesus,

Thanks for the feedback. I have a different approach for some cases. I describe it in #774. I don't like to add extra time because the Tests are already taking too much. I have the idea of retry (if needed) or a global TimeFactor that can accelerate or slow the tests depending of the performance of the Client & the Environment.

What do you think?

br

**Comment by ejfdejesus** [comment]
Hi @AngelRodriguez8008 , 

Thank you. Yes looks like a good idea. But for now is there any workaround on this? My login is always failing because of this so I just increased the thinktime to 2000 and reference the api.uci dll to my project.

**Comment by AngelRodriguez8008** [comment]
Sorry. I don't understand your question. You already find a workaround, if this work for you, perfect! I will come to you again, when I re-implement the Retry mechanism & we can check if these works fine for you. OK?

**Comment by ejfdejesus** [comment]
Thank you. I'll wait for your enhancement. :)

**Comment by AngelRodriguez8008** [comment]
#1151

**Comment by AngelRodriguez8008** [comment]
@ejfdejesus Can you close this Issue?
