### ISSUE TITLE
I am seeing an exception while running my tests in Debug mode.

### ISSUE THREAD

**Issue by sujaybarooah** [Microsoft/EasyRepro#78]
When I run the test in debug mode I get an exception. This happens with the sample tests as well (tried with TestCreateNewCase), running version 9 of EasyRepro.
```
Exception thrown: 'OpenQA.Selenium.NoSuchElementException' in WebDriver.Support.dll
An exception of type 'OpenQA.Selenium.NoSuchElementException' occurred in WebDriver.Support.dll but was not handled in user code
no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='email']"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.15063 x86_64)
```

**Comment by dtu11** [comment]
I apologize for the delay in response.  So everything will work fine when you run the test regularly but throws an exception when you step through it?    Can you provide the test you are trying to run as well as the stacktrace?

Thanks

**Comment by TYLEROL** [comment]
@sujaybarooah - Are you still encountering this issue? I have attempted to reproduce this problem but have been unsuccessful so far.

As we have not received a reply I will close this issue, however if you are still encountering this problem, please re-open the issue and supply the following:

- Test Case / code (if not using sample CreateCase.cs file)
- Full Stack Trace
- TestSettings.Options values if modified
