### ISSUE TITLE
[BUG] Not able to SetValue for flipswitch boolean control 

### ISSUE THREAD

**Issue by kalyanip1** [Microsoft/EasyRepro#786]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Currently SetValue doesnt support Flip Switch control 

**Special formatting / display**  

![image](https://user-images.githubusercontent.com/61614329/75622150-51de4f80-5b95-11ea-8a39-d42cadb8e5d4.png)

**Code to reproduce**  

 
**Expected behavior**  
flip switch should be selected true or false
**Screenshots**  

![image](https://user-images.githubusercontent.com/61614329/75622180-99fd7200-5b95-11ea-91ed-bd820eb8bbd4.png)

**Additional context**

**Comment by badarmunir** [comment]
@kalyanip1 did you find any solution or work around

**Comment by badarmunir** [comment]
@TYLEROL  is there a solution or work around to this problem

**Comment by kalyanip1** [comment]
@badarmunir fix has been checked in. use the latest code it will work as expected.

**Comment by badarmunir** [comment]
@kalyanip1 i have added latest nuget package in solution and tried following solutions
mApp.Entity.SetValue(  "mzk_diagnosisrequired", "true" );
xrmApp.Entity.SetValue( new BooleanItem { Name = "mzk_diagnosisrequired", Value = true });

but still unable to setValue in flipswitch

**Comment by kalyanip1** [comment]
@badarmunir may be this hasn't made to nuget yet. Here is the original pull request https://github.com/microsoft/EasyRepro/pull/787
