### ISSUE TITLE
Unable to set DateTime in UCI

### ISSUE THREAD

**Issue by anaprikho** [Microsoft/EasyRepro#788]
xrmApp.Entity.SetValue("contactdate", DateTime.Today, "dd/MM/yyy") does not work for me. The value will be entered and then deleted again. I also take ThinkTime 3 sec
What would you suggest me?

**Comment by AngelRodriguez8008** [comment]
Also if you remove the Format ("dd/MM/yyy")? Try with the default one, remove the parameter

**Comment by anaprikho** [comment]
Thank you, it did work for me!
