### ISSUE TITLE
EasyRepro is not working in Unified Interface

### ISSUE THREAD

**Issue by abrahamjoji** [Microsoft/EasyRepro#79]
1. I would like to know whether this EasyRepro will work on Unified Interface. I try few scenarios but it    seems like not working. I gone deeper into EasyRepro the reference for element ID and Xpath and CssClass is different due to this its failed to identify the controls. (Correct me if I am wrong).

2.  How to switch between the Apps? 
For eg: I am working in Dynamics 365 - Custom, I need to go to Sales Hub apps 
I try to add ElementId, CssClass in _XrmElementRefernce_ but its not able to identify the control in the apps, its throwing exception.

**Comment by dtu11** [comment]
We are currently working on this functionality but don't have a release date just yet.  There are a few things that we need to work out around the driver interaction with the new client to ensure that the API can track when the rendering is complete.

**Comment by abrahamjoji** [comment]
I would like to know the details regarding new UI called Unified UI for D365. So it will be great if you let us know the tentative release dates of Unified UI along with this we want to know Unified UI EasyRepro libraries are also releasing with same UI.

As we already started UI automation using existing EasyRepro libraries. By any chance do we need to re-script/modify when we migrate to Unified UI and any major changes in libraries?
