### ISSUE TITLE
[HOW-TO] <set value on option/two set in business process flow stage>

### ISSUE THREAD

**Issue by anaprikho** [Microsoft/EasyRepro#790]
I tried to change the vlaue to "yes" with 
 xrmApp.BusinessProcessFlow.NextStage("Identify"); xrmApp.ThinkTime(2000); xrmApp.BusinessProcessFlow.SetValue(new OptionSet { Name = "themabestaetigt", Value = "Ja" }) 
but it throws an exeption. I have also tried to increase the think time to wait until the element is visibale.
<img width="245" alt="Unbenannt" src="https://user-images.githubusercontent.com/42543248/75785496-1ba2fa80-5d64-11ea-8cbe-ab1cdaef2ebf.PNG">

<img width="471" alt="Unbenannt2" src="https://user-images.githubusercontent.com/42543248/75785627-54db6a80-5d64-11ea-9d4c-2d43e1933bf0.PNG">

**Comment by kavitham1985** [comment]
I am receiving error too. May I know what is the fix @anaprikho

**Comment by anaprikho** [comment]
That is how it did  work for me @kavitham1985. BooleanItem method
![image](https://user-images.githubusercontent.com/42543248/76800394-db1b9600-67d3-11ea-9fc8-8275bc2e1b1f.png)
