### ISSUE TITLE
[BUG] Entering a value in Date control fails

### ISSUE THREAD

**Issue by aalad** [Microsoft/EasyRepro#795]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
When entering a value in a Date control, the field is not filled correctly. Examples in GIFs  below.

What I do is calling the SetValue function on the estimated close date with a common european date format. The entered value get erased before the driver is finished entering it which results in an invalid value. 
I tried with different formats for the DateTime as well (e.g. "MM/dd/yyyy"), but unsuccessfully.

Please assist, thank you.

**Special formatting / display**  

**Code to reproduce**  
```c#
public void OpportunityCreateTest()
{
    using (var xrmApp = new XrmApp(_client))
    {
        xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _loginAction)
        xrmApp.Navigation.OpenApp(_myApp);
        xrmApp.Navigation.OpenSubArea("My CRM", "Opportunities");
        xrmApp.CommandBar.ClickCommand("New");
        xrmApp.Entity.SetValue("estimatedclosedate", DateTime.Today.AddMonths(1), "dd.MM.yyyy"); 
    }
}
```

**Screenshots**  
These are animated GIFs to illustrate what happens.

![easyrepro_uci_datetime](https://user-images.githubusercontent.com/48445423/75993111-483c4b00-5ef9-11ea-9dfe-9899542c306b.gif)

and
![easyrepro_uci_datetime2](https://user-images.githubusercontent.com/48445423/75993130-4d999580-5ef9-11ea-8281-0f47b7fba7ad.gif)

**Comment by AngelRodriguez8008** [comment]
Can you check #788? Maybe is the same problem.

**Comment by aalad** [comment]
Thanks Angel, it's similar but not the same problem. In #788 it was solved by removing the format option, which did not work for me.
Without the format option, the time is also entered. The field is date-only, so that cannot work from my point of view. 

I tried changing the date format of the test user's personal options from German to English (US) as well, but no luck either.

**Comment by nareshbak** [comment]
Do we have resolution for the above issue. I too face the same issue while entering dates in Date fields

**Comment by TYLEROL** [comment]
@aalad - Using _English (United States)_ personal format options, and example formatting below. I was able to set a value on the DateTimeControl for both DateOnly and Date+Time control formats. 

I'll have this change reviewed and merged into the develop branch today, could you kindly let me know if you are successful with this sample code below? 

```
xrmApp.Entity.SetValue("actualclosedate", DateTime.Today.AddMonths(1), "MM/dd/yyyy");

xrmApp.Entity.SetValue("new_actualclosedatetime", DateTime.Today.AddMonths(1), "MM/dd/yyyy", "hh:mm tt");
```

Warm Regards,
Tyler
