### ISSUE TITLE
Enhancement: Enable API access to JavaScript XRM Object

### ISSUE THREAD

**Issue by daggen** [Microsoft/EasyRepro#80]
Hi,

I've just found your tool and it will most likely solve a lot of my issues. 
Please ignore this if this feature already exist. It would be great if if was possible to be able to access the XRM JavaScript object in the content frame and get the return values.
Some features that this would enable
- Get ID from newly created records
- Verify settings on fields like (in)visible, required level

Thanks

**Comment by dtu11** [comment]
There is a method to execute script and access the things you are looking for.  I like the idea of extending the API's to access certain details like the ID or properties on a field though.   Here is the methods to execute script to access those things in the interim. 

                xrmBrowser.Document.SwitchToContentFrame();
                xrmBrowser.Driver.ExecuteScript("alert('My script executed');");
