### ISSUE TITLE
[HOW-TO] Does CRM support basic authentication?

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#801]
Is there a way to let Online CRM land at homepage by passing the user credential in the CRM url? My colleague asks me this question but my trial is not successful. I ask this question in case there is a way for the CRM basic authentication works. Thanks!

**Comment by jowells1** [comment]
@xuejunh Dynamics 365 Online only supports Azure AD authentication methods:
https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods

When setting the username and password within the app.config file, you would use the same username and password that you would use when logging into Dynamics.
