### ISSUE TITLE
How to use Selenium Driver using XrmApp

### ISSUE THREAD

**Issue by dynamicsk** [Microsoft/EasyRepro#803]
Hi

I am using the latest version of API, with Selenium and Spcflow framework.

How can i call Browser/Driver using XrmApp?.

I am Initiating the xrmApp in the "Hooks.cs" as below :

            _BrowserOptions options = BrowserSettings.Options;

            client = new WebClient(options);
            xrmapp = new XrmApp(client);
            _container.RegisterInstanceAs(xrmapp);_

I login to D365 using

_XrmApp.OnlineLogin.Login(_url, _username, _password, _mfaSecrectKey);_

As part of specflow feture files, for my next steps i use different classes and functions.

But if i have to use selenium Driver to capture some text Or to identify some objects, how do i do?

If i use "client.Browser.Driver" it is opening a different window.

Please help..

**Comment by mVermaat** [comment]
Are you sure you are using the same instance of the 'XrmApp? in your code you initialize 'xrmapp' variable and then in your comment the name of the variable is '_XrmApp'. 

client.Browser.Driver should be the way to go. Take at look at my example here: https://github.com/mVermaat/Crm.Specflow/blob/master/Vermaat.Crm.Specflow/EasyRepro/UCIApp.cs

**Comment by dynamicsk** [comment]
Hi mVermaat,

Thanks for your reply.  
"_" just came up here when i tried to make the below line as Italic. :)
_XrmApp.OnlineLogin.Login(_url, _username, _password, mfaSecrectKey);

Any how this issue is solved bu using this in Hooks.cs.

container.RegisterInstanceAs(client);

Thanks

**Comment by mVermaat** [comment]
@dynamicsk Good to hear it is solved :) You should close this issue then.
