### ISSUE TITLE
[BUG] getValue from Lookup item returns value in lowercase (lose the case information of the value)

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#809]
I use getValue for a lookup item, the value I expect is in mix case but the value returned is in lower case, so cannot compare exact string when using getValue

**Comment by TYLEROL** [comment]
@xuejunh - Thanks for raising this. This is fixed and merged with the latest develop branch. I plan to update the NuGet packages and releases/v9.1 by end of next week.

Warm Regards,
Tyler

**Comment by TYLEROL** [comment]
@xuejunh - A few days late, but we've merged the latest changes from develop into the releases/v9.1 branch and the 9.1.0.17138 NuGet package.

Warm Regards,
Tyler
