### ISSUE TITLE
[BUG] Login with certain password(s) doesn't work

### ISSUE THREAD

**Issue by jeffryvu** [Microsoft/EasyRepro#810]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Trying to login with a certain auto-generated strong 16 character password gives a message: "your account or password is incorrect".

When I change the password to something else the login works. To double check I changed it back to the failing password and it failed again.

When I try to login with the failing password manually, I can login.

**Expected behavior**  
Logging in with a valid password should work.

**Screenshots**  

**Additional context**

**Comment by mVermaat** [comment]
I assume you write your password in app.config. Can you check if it hasn't got anything to do with escaping?

In example is your password is: 'Some&Password', you need to set in the app.config as 'Some&amp;Password'.

**Comment by jeffryvu** [comment]
I think github removed your escaping :). Do you mean that I should escape `&` to `&amp;`? Do you mean escaping or encoding? And is that documented somewhere?

**Comment by mVermaat** [comment]
Yes, exactly like that. It's not part of easyrepro. It's because an app.config file is a XML file.

You can find it here: https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents
