### ISSUE TITLE
[BUG] - Add Phone Call - Description

### ISSUE THREAD

**Issue by imartinflores** [Microsoft/EasyRepro#813]
Hi guys, I have noticed that when you Add a Phone Call on the timeline, the method is taking the "Description" field in the main form (Case) and not the PhoneCall form.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ ] UCI (XrmApp)

**Online or On Premise**
  - [ ] Online

**Browser**
  - [ ] Chrome

**Describe the bug**  
XrmApp.TimeLine.AddPhoneCall(); -> Is trying to type "Description" in the Case form and not in the PhoneCall form.

**Screenshots**  

<img width="242" alt="descriptionPC" src="https://user-images.githubusercontent.com/17011557/77894455-36866300-726d-11ea-99a5-734bf5e16e02.PNG">

<img width="565" alt="DescriptionCase" src="https://user-images.githubusercontent.com/17011557/77894467-39815380-726d-11ea-9707-eda2b9ad1b58.PNG">

**Code to reproduce**  

```csharp
XrmApp.Timeline.AddPhoneCall("Subject", "1111", "My Description", "");
 -->
 
**Expected behavior**  
Description should be populated in the PhoneCall form

**Error Message**
OpenQA.Selenium.ElementClickInterceptedException: element click intercepted:

**Comment by TYLEROL** [comment]
@imartinflores - This should also be fixed in the latest releases/v9.1 branch and the 9.1.0.17138 NuGet package.

Please re-open this issue if you continue to observe the problem.

Warm Regards,
Tyler
