### ISSUE TITLE
[HOW-TO] <Open record in subgrid >

### ISSUE THREAD

**Issue by badarmunir** [Microsoft/EasyRepro#815]
## Question

**How to open record in subgrid- i have multiple grids - i am able to click on first grid record by using
global.xrmApp.Grid.OpenRecord(0);

![Capture](https://user-images.githubusercontent.com/23335796/77919256-c9b19f80-7251-11ea-9d5c-a0b64a9b1329.PNG)
but i dont know how to open record on second grid (Delivery Frequency)

**Comment by nareshbak** [comment]
Do we have solution for this? I too have same issue.

**Comment by jowells1** [comment]
Please see and track #852 as @TYLEROL is currently doing work to address this.
