### ISSUE TITLE
SetValue results in blank field even with the bugfix

### ISSUE THREAD

**Issue by KiavashS** [Microsoft/EasyRepro#82]
When setting a value in text field in CRM V9 the value seems to blank out again.

Using V9 branch at line 147 I can see there is a note about the bugfix, but looks to be still occurring in our case.
https://github.com/Microsoft/EasyRepro/blob/e34b5cae67393f7cc789313fd60536ae326f4fdb/Microsoft.Dynamics365.UIAutomation.Api/XrmPage.cs#L147

**Comment by dtu11** [comment]
I'll take a look at it.

**Comment by TYLEROL** [comment]
@KiavashS - I attempted to reproduce this on the latest versions using both Chrome and Internet Explorer and both Single Line of Text and Multiple Lines of Text field types, but have been unsuccessful. The supplied input values are saved successfully. My Dynamics organization is running version v9.0.1.459

Please try again and if you can still reproduce this then reopen the issue and supply the following:

- Dynamics org version
- Browser type/version
- Code used during your test

Thanks,
Tyler
