### ISSUE TITLE
Unable to set Date field in UCI 

### ISSUE THREAD

**Issue by krishnacs1993** [Microsoft/EasyRepro#820]
Facing issue with Date field in UCI. I see multiple bugs been raised for this issue but none of the solutions worked for me. Below is the line of code I'm using

xrmApp.Entity.SetValue("new_dateonly", DateTime.Now, "dd/MM/yyyy");

Sometimes hard coding of date field value works fine but not always.

xrmApp.Entity.SetValue("new_dateonly", "06/04/2020")

Can someone help me out here

**Comment by badarmunir** [comment]
@krishnacs1993 try this method 

DateTime birthday = new DateTime(1995, 3, 1);
xrmApp.ThinkTime(500);
xrmApp.Entity.SetValue("birthdate", birthday);

if this dosent work try this 
DateTime startdate = DateTime.Today.AddDays(1);
xrmApp.Entity.SetValue("mzk_startdate", startdate);

Or add some think-time

**Comment by prashantThakuri** [comment]
A force feed code can be written to enter he value as below in the SetValue Field:

   int counter = 1;
                    fieldElement.SendKeys(date.ToString(format));
                    String st = date.ToString(format);
                    
                    while(!(fieldElement.GetAttribute("value") == date.ToString(format)) && counter<=3)
                    {
                        
                        fieldElement.SendKeys(date.ToString(format));
                        counter++;
                    }
