### ISSUE TITLE
Login detection issue when Pending Emails exist

### ISSUE THREAD

**Issue by KiavashS** [Microsoft/EasyRepro#83]
When the logged in user has any pending emails older than 24 hours, then CRM displays a popup notifying it. EasyRepro now tries to detect a successful login by looking for the ribbon, but when the pending emails pop-up is visible, the ribbon is not accessible.

Maybe the pending emails pop-up can also be one of the triggers to identify a successful login?

Also is it possible to provide a commend to dismiss that pop-up?

**Comment by dtu11** [comment]
There is a command for that.   Let me know if this works. 

//Handle Pending Email Warning
                xrmBrowser.Dialogs.CloseWarningDialog();

**Comment by dtu11** [comment]
I'm assuming this issue is resolved due to no other feedback.  If you need further assistance with this please reopen the issue.

Thanks
