### ISSUE TITLE
[BUG] Lookup SetHeaderValue fails to clear value when there is another element with same name in part of page

### ISSUE THREAD

**Issue by keval71** [Microsoft/EasyRepro#836]
### When there are more than one fields present on form one in header and one in other part of page representing same field and having same name an exception is thrown

Exception: 

### Stale element reference: element is not attached to page document

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Trying to set value in header fields gives exception as instead of clicking and clearing value in lookup from header it goes to other element which is read only.
Click on it and flyout is closed.. leading to stale element reference excption

**Special formatting / display**  

**Code to reproduce**  
@@ -3034,7 +3034,7 @@ private static void TryRemoveLookupValue
.
.
.
IWebElement fieldCon
 var xpathToHoveExistingValue = By.XPath(AppElements.Xpath[AppReference.Entity.LookupFieldHoverExistingValue].Replace("[NAME]", controlName));
                var found = fieldContainer.TryFindElement(xpathToHoveExistingValue, out var existingList);
                if (found)
                    existingList.Click(true);
            }
 
**Expected behavior**  
Value should be set in Lookout field in header

**Comment by TYLEROL** [comment]
@keval71 - I've checked in changes for this issue and issue #837. These are currently in the Develop branch. Please let me know if these have not resolved the problem.

Warm Regards,
Tyler
