### ISSUE TITLE
[BUG] Trygetvalue does not return value for lookup item in header

### ISSUE THREAD

**Issue by keval71** [Microsoft/EasyRepro#837]
### When used GetHeaderValue to get value of look up from header Trygetvalue method fails to identify existing element and code fails.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  

**Special formatting / display**  

**Code to reproduce**  
 private string[] TryGetValue(IWebElement fieldContainer, LookupItem[] controls)
        {
            var controlName = controls.First().Name;
            var xpathToExistingValues = By.XPath(AppElements.Xpath[AppReference.Entity.LookupFieldExistingValue].Replace("[NAME]", controlName));
            var existingValues = fieldContainer.FindElements(xpathToExistingValues);

**Comment by TYLEROL** [comment]
@keval71 - I've checked in changes for this issue and issue #836 . These are currently in the Develop branch. Please let me know if these have not resolved the problem.

Warm Regards,
Tyler
