### ISSUE TITLE
Alerts Grid Canary Env

### ISSUE THREAD

**Issue by imartinflores** [Microsoft/EasyRepro#839]
Hi guys, just wanted to drop a question because I have seen that some of out test are failing on Canary env, so just to be aware if there will be any changes that can break easyrepro methods.

The GetGridItems() is not working correctly on Canary env, so not sure if thats a locator that has changed. When we execute GetAttribute<string>("win_description") it returns null on Canary, but works fine on Test.

Here you can see the difference between out Test and Canary Env.
Canary:
<img width="592" alt="canaryalerts" src="https://user-images.githubusercontent.com/17011557/80582467-acb1ed00-8a06-11ea-9c58-498dfcfea347.PNG">

Test:
<img width="562" alt="alertstest" src="https://user-images.githubusercontent.com/17011557/80582481-b0de0a80-8a06-11ea-9d09-ed4c0df5f706.PNG">

Please, let me know if you need something else.

Thanks.
Regards.

**Comment by TYLEROL** [comment]
@imartinflores - I believe this issue should be fixed by pending changes in #864 

We hope to have these merged into the release branch and NuGet packages very soon.

-Tyler
