### ISSUE TITLE
Delete Button is not detecting in headless mode

### ISSUE THREAD

**Issue by jayarajpmca** [Microsoft/EasyRepro#85]
Delete Button is not detecting in headless mode while executing delete account or contact

**Comment by dtu11** [comment]
Could you provide the test that you are running and I'll troubleshoot it.  

Thanks

**Comment by jayarajpmca** [comment]
Hi,
Please  do the following two updates and try:
1.Add below lines of code in "Open Account" test class line number 35.
 xrmBrowser.ThinkTime(2000);
 xrmBrowser.CommandBar.ClickCommand("Delete");
2. In test settings add below line in browser settings:
Headless = true

I am able to reproduce the issue with these changes. Please let me know if any additional information required.

**Comment by TYLEROL** [comment]
After reproducing internally, the resolution of the browser in Headless mode is impacting the scaling of the ribbon controls during the test.

To resolve this problem, try the following:

	xrmBrowser.CommandBar.ClickCommand("Delete", "", true);

This will traverse the More Commands tree and select the Delete button from there. We've confirmed this change will resolve the issue.

I'll close the issue at this time. If you encounter the problem again you can create a new issue or reopen the existing one.

Thanks!
