### ISSUE TITLE
Unable to open record from editable subgrid

### ISSUE THREAD

**Issue by krishnacs1993** [Microsoft/EasyRepro#852]
Hi there,

I'm trying to open a record from the editable subgrid using the below lines of code

xrmApp.Entity.SelectTab("Related", "Booking Products");
xrmApp.Entity.OpenSubGridRecord("Booking Product Associated View", 0);

looks like there is some issue with OpenSubGridRecord, I am not getting any error but no action is being performed, control moves to the next line of code. 

I have many tests to open a record from subgrid , any help here please.

**Comment by krishnacs1993** [comment]
@TYLEROL Can you please help me out here.

**Comment by TYLEROL** [comment]
@krishnacs1993 - Thanks for raising this. I have an open work item to take a look at the grid experience when editable. I'll let you know once I have a set of changes posted to the develop branch that you can test, hopefully in the next couple days. 

Warm Regards,
Tyler

**Comment by krishnacs1993** [comment]
@TYLEROL @jowells1 @jlattimer Any update on this, please?

**Comment by krishnacs1993** [comment]
I tried the alternative way for this and I could find the solution with the help of Actions in selenium.
The below code helps in opening the record from Grid/SubGrid/Editable Subgrid

 Actions actions = new Actions(client.Browser.Driver);
 IWebElement elementLocator = client.Browser.Driver.FindElement(By.XPath($".//div[@data-id='cell-{0}-1']"));
actions.DoubleClick(elementLocator).Build().Perform();
xrmApp.ThinkTime(5000);

**Comment by TYLEROL** [comment]
This has been merged into releases/v9.1 and the latest 9.1.0.17138 NuGet package. It should work with all grids.

`xrmApp.Entity.SubGrid.OpenSubGridRecord(string subGridSchemaName, int index);`
