### ISSUE TITLE
Unable to load Dynamics 365 Apps page in UCI once login is successful

### ISSUE THREAD

**Issue by veerasekharbathala** [Microsoft/EasyRepro#863]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X ] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X ] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [ X] Online
  - [ ] On Premise

**Browser**
  - [ X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
I tried with releases/v9.1 and develop branches code. 
I am executing the easyrepro sample test cases and tried with CreateAccountUCI. UCITestCreateAccount sample test case. 

Below ADFS Login redirect code is used to login to Dynamics 365 online UCI app. The code is executing as expected, user name, password entered and authentication is successful. However, the page is redirected to office 365 home page instead of Dynamics 365 apps. 

Do we have different ADFS Login redirect code for UCI? Can you share ADFS Login redirect code for UCI?

**Special formatting / display**  

**Code to reproduce**  
```csharp
using Microsoft.Dynamics365.UIAutomation.Api.UCI;
using Microsoft.Dynamics365.UIAutomation.Browser;
using OpenQA.Selenium;
using System;

namespace Microsoft.Dynamics365.UIAutomation.Sample
{
    class ADFSLogin
    {
        public static void ADFSLoginAction(LoginRedirectEventArgs args)
        {
            //Login Page details go here.  You will need to find out the id of the password field on the form as well as the submit button. 
            //You will also need to add a reference to the Selenium Webdriver to use the base driver. 

            //Example
            //--------------------------------------------------------------------------------------
            var d = args.Driver;
            d.FindElement(By.Id("passwordInput")).SendKeys(args.Password.ToUnsecureString());

            try
            {
                d.ClickWhenAvailable(By.Id("submitButton"), new TimeSpan(0, 0, 2));

            }
            catch (Exception)
            {

            }
            d.WaitForPageToLoad();

            if (d.IsVisible(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])))
            {
                d.ClickWhenAvailable(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn]));
            }
        }
    }
}
 ```

Used below code in CreateAccountUCI. UCITestCreateAccount to call Login method

```csharp
 xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, ADFSLogin.ADFSLoginAction);
 ```
Please find CreateAccountUCI class code below.
 
```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Dynamics365.UIAutomation.Api.UCI;
using Microsoft.Dynamics365.UIAutomation.Browser;
using System;
using System.Security;

namespace Microsoft.Dynamics365.UIAutomation.Sample.UCI
{
    [TestClass]
    public class CreateAccountUCI
    {

        private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        private readonly SecureString _mfaSecretKey = System.Configuration.ConfigurationManager.AppSettings["MfaSecretKey"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());

        [TestMethod]
        public void UCITestCreateAccount()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey, ADFSLogin.ADFSLoginAction);

                xrmApp.Navigation.OpenApp(UCIAppName.Sales);

                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.Entity.SetValue("name", TestSettings.GetRandomString(5,15));

                xrmApp.Entity.Save();
                
            }
            
        }
    }
}
 ```

**Expected behavior**  
Expecting to see below Dynamics 365 apps page once the authentication is successful. 
![image](https://user-images.githubusercontent.com/35842369/81985078-c9077980-9603-11ea-84f8-a510dd63907f.png)

**Screenshots**  

Once the authentication is successful, below page is visible to user.

![image](https://user-images.githubusercontent.com/35842369/81984493-db34e800-9602-11ea-8a0f-39fb550f0cd8.png)

**Comment by veerasekharbathala** [comment]
Please find online crm Url config from app.config file.
```csharp
  <add key="OnlineCrmUrl" value="https://****.crm3.dynamics.com/" />
```

**Comment by AngelRodriguez8008** [comment]
Your are trying to open the Sales App. Do you has it installed?

Maybe you should choose the right App, at this line: 
        `xrmApp.Navigation.OpenApp(UCIAppName.Sales);`

**Comment by veerasekharbathala** [comment]
I tried to open the apps which are already installed. The page is still redirected to office 365 home page once the login is successful and xrmApp is not able to load appropriate app.

Please find screenshots below.

![image](https://user-images.githubusercontent.com/35842369/82006556-16044380-9636-11ea-9a81-7ae8273a5dec.png)


![image](https://user-images.githubusercontent.com/35842369/82006605-33391200-9636-11ea-841e-db3199093d52.png)

**Comment by AngelRodriguez8008** [comment]
Sorry, i misunderstood your question.

What if you navigate to D365 in your Redirect Action or after Login,
 ` driver.Navigate().GoToUrl(_xrmUri);`
