### ISSUE TITLE
[BUG] Unable to SelectTab using Entity.SelectTab Method

### ISSUE THREAD

**Issue by badarmunir** [Microsoft/EasyRepro#868]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**

  
**UCI or Classic Web**
  - [ ] UCI (XrmApp)

**Online or On Premise**
  - [ ] Online

**Browser**
  - [ ] Chrome

**Describe the bug**  
I am trying to select the General tab using Entity.SelectTab() but it's giving me error -as you can see in the screenshot general tab is displayed the same is happening for other tabs too. 

**Code to reproduce**  
global.xrmApp.Entity.SelectTab("General");

 -->
 
**Expected behavior**  
Entity.SelectTab() should select the displayed tab

**Screenshots**  
![image](https://user-images.githubusercontent.com/23335796/82190449-77643500-990a-11ea-8ca7-9f6f29aaa43b.png)
![image](https://user-images.githubusercontent.com/23335796/82190501-8945d800-990a-11ea-8f58-b7eb415ac469.png)

**Comment by noor4263** [comment]
even though its a bug, it can be easily made to work as below...
change your Entity_TabList as role rather id... it works

            { "Entity_TabList", "//ul[@role=\"tablist\"]" },
            //{ "Entity_TabList", "//ul[@id=\"tablist\"]" },

why someone messing with the code already proven working ?

**Comment by badarmunir** [comment]
@noor4263 I am using nugget package

**Comment by TYLEROL** [comment]
@badarmunir - Thanks for raising this. This was an issue that popped up on our end as well. The fix is slightly different from your proposal, but is confirmed working in the develop branch via #859 .

I hope to merge this into the latest code branches + NuGet package very soon.

Warm Regards,
Tyler

**Comment by TYLEROL** [comment]
This has been merged into releases/v9.1 and the latest 9.1.0.17138 NuGet package.
