### ISSUE TITLE
Browser is closing after each test when we do Ordered Test 

### ISSUE THREAD

**Issue by abrahamjoji** [Microsoft/EasyRepro#87]
I try to run different test case together one after the other using ordered test in the same browser. After each test, browser is getting closed. Due to this my test is failing. 
I try to add CloseOnPlaybackCleanup in the files
- BrowserDriverFactory 
- BrowserOption 
But it is not accepting my CloseOnPlaybackCleanup option.

Is there a way to put "_browserWindow.CloseOnPlaybackCleanup = false_;"
It will maintain the browser so each test will run on the same browser.

**Comment by dtu11** [comment]
The browser driver is setup with the XrmBrowser so once that is disposed of we clean up the Selenium drivers as well as the browser driver.    If you don't want to the browser to close then you would need to use the existing XrmBrowser for multiple scenarios as it's currently designed.    If we don't clean up those resources it could cause problems for future tests.

**Comment by abrahamjoji** [comment]
Is it a better option to maintain a singleton class for XrmBrowser so i can maintain the same instance across the tests.

**Comment by dtu11** [comment]
You can do that but just make sure you are aware where you are in the application.  You may want to start each test at the Home page.

**Comment by abrahamjoji** [comment]
I made the changes in (XrmBrowser) based on my requirement. Its working fine now.

**Comment by dtu11** [comment]
Thanks I'll close the issue and if you need anything else just let us know.

**Comment by praveenKumarCh** [comment]
could you please share the logic how you handle this. lets consider i have 3 scripts in that for fist script browser is able to close but for second script it executing fine but not able to close the browser.due to this 3rd test case is failing.

**Comment by ychandra888** [comment]
how to stop the close a browser, what is the line of code
