### ISSUE TITLE
[HOW-TO] Close the "Pending Email Warning" message

### ISSUE THREAD

**Issue by MikeBristol** [Microsoft/EasyRepro#874]
## Question
Currently running 8.2 OnPrem. When starting an EasyRepro test, we get the "Pending EMail Warning" message. 

How can I close this?

**Comment by TYLEROL** [comment]
@MikeBristol - I'm not sure if this method is in your branch, but if so, you can give this a try (present in the releases/v8.2 branch).

```
// Handle Pending Email Warning
xrmBrowser.Dialogs.CloseWarningDialog();
```

**Comment by MikeBristol** [comment]
Hi, Yes both the OnPrem and 8.2 branches have this, however, the dialog doesn't close. The WaitUntilAvailable throws the timeout exception.

What can I try?
