### ISSUE TITLE
Possibility to check if the test was successful (feature request)

### ISSUE THREAD

**Issue by mggrand** [Microsoft/EasyRepro#88]
For example if you leave the "Name" field empty while creating a contact through the test, the test will go green while it actually should fail, because the "Name" field is a required field. So it would be great if there was a possibility to verify that all required fields were filled in and the save command was successful. This would leave the possibility to use assert functions at the end of the test

**Comment by dtu11** [comment]
Ok, I've added this feature request to our backlog.  Here are the details that we decided on. 

1. The Entity.Save() method will now check for CRM Exceptions by default and throw the exception if one is encountered.    It will also have a parameter that will suppress the exception and allow you to check the BrowserCommandResult for the exception but allow the test to continue. 

2. Add a method for Entity.SaveAndClose() that will do the save action and close the record if no exception is thrown. 

3. Add a method for Entity.SaveAndNew() that will do the save action and start a new record if no exception is thrown. 

I'm going to close this issue for now but will update it when the feature is released.
