### ISSUE TITLE
[HOW-TO] <Select from a drop-down menu>

### ISSUE THREAD

**Issue by sakib5** [Microsoft/EasyRepro#886]
## Question I am trying to select Phone Call from the + New Activity drop-down menu but as this a little bit different different then a regular data field

Using:
Branch: Develop
UCI ()xrmApp)
Online
Browser: Chrome

Code: 
xrmApp.Navigation.OpenSubArea("Customers", "Clients");
xrmApp.Grid.OpenRecord(0);
xrmApp.Entity.SelectTab("Related", "Leads");
xrmApp.RelatedGrid.OpenGridRow(0);
xrmApp.Entity.SelectTab("Related", "Activities");

[*** Performing the upper lines get me to this page ***]
![image](https://user-images.githubusercontent.com/47485407/84310913-66d16400-ab30-11ea-85af-075424218284.png)

**What is your question?**
 I am trying to select Phone Call from the + New Activity drop-down menu but as this a little bit different different then a regular data field, I an can not find a way out. 
N.B: I can make it work by using XPath but I am mainly looking for a solution that does not require XPath.

**Comment by shariquekhan1997** [comment]
After this,
xrmApp.Entity.SelectTab("Related", "Activities"); 
try this,
xrmApp.RelatedGrid.ClickCommand("New Activity");
xrmApp.RelatedGrid.ClickCommand("Name of Activity");

If the last line doesn't work then find the XPath and use the "Click()" method.

**Comment by shariquekhan1997** [comment]
Hey, Did it work? @sakib5

**Comment by sakib5** [comment]
Hi @shariquekhan1997 , the solution will be xrmApp.RelatedGrid.ClickCommand("New Activity", "Name of Activoty"); But thank you for the response.
