### ISSUE TITLE
[HOW-TO] Select an OptionSet or LookupItem with Entity.SetValue in 8.2

### ISSUE THREAD

**Issue by todstanis** [Microsoft/EasyRepro#888]
## Question

I'm having an issue working with selecting options. It seems to just open the selection box and never actually pick anything.

I'm not overly familiar with Selenium from the Dynamics365.UIAutomation.Api side and I'm not a Dynamics developer so I'm even sure what the control type is for certain.
The class of the "select" tag contains "ms-crm-SelectBox ms-crm-Inline-OptionSet-AutoOpen"

Using any of following opens the selection options:
- xrmBrowser.Driver.FindElement(By.Id("ID OF ASSOCIATED LABEL")).Click();
- xrmBrowser.Entity.SetValue(new OptionSet() { Name = "ID OF ASSOCIATED LABEL", Value = "select option value" });
- xrmBrowser.Entity.SetValue(new LookupItem { Name = "ID OF ASSOCIATED LABEL", Index = 2 });

Using anything else I've tried simply throws a not found or null exception.

While the first option does what I'd expect (opens the selects box and does nothing else), the other 2 options do the same thing. They don't actually select anything and the box stays open. I can send a click to close it, but nothing is selected.

The output of those Entity.SetValue() commands show as Success = false and
- Exception: {"no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"select\"}\n  (Session info: chrome=83.0.4103.61)"}
- and
- Exception: {"no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".Lookup_RenderButton_td\"}\n  (Session info: chrome=83.0.4103.61)"}

I'm using the latest Selenium NuGet package: 9.1.0.17139, but against a Dynamics version 8.2.5.4 on-premises.

Is this an API compatibility issue or am I missing a step? Note that I tried the Entity.SelectLookup approach, but it has the same issues and more.

**Comment by sakib5** [comment]
Can you try: 
xrmApp.Entity.SetValue(new OptionSet { Name="name", Value="value" });

**Comment by todstanis** [comment]
Actual there's no name in any tag related to this control. After a bit more testing I have determined how to get it to work:

```
<div id="header_process_approveproject" data-attributename="approveproject">
	<div>
		<label for="approveproject_label" id="Approve Project_label">
			<div>Approve Project click to enter</div>
			click to enter
			<div></div>
		</label>
		<span>
			<div></div>
		</span>
	</div>
	<div>
		<select id="header_process_approveproject_i" attrname="approveproject" size="3">
			<option value="" title=""></option>
			<option value="12345" title="Yes">Yes</option>
			<option value="67890" title="No">No</option>
		</select>
	</div>
</div>
```
This is what's generated in relation to that select control with the classes stripped out. It turns out the ID to get it to work is "header_process_approveproject", which makes sense based on the error, as the id needed to be a parent to the "select" tag. The funny thing here is that I can also use the id of the parent to that parent and also make it work.

I need to look at the Form definition for this page because I'm pretty sure the control is not called "header_process_approveproject". I believe its called "approveproject", but I'm not a Dynamics developer and don't have access to the Form definitions, as is often the case. Unfortunately this makes using this API worse for a Selenium tester than simply using base Selenium, as they are still required to essentially diagnose the generated page and then figure out how to match up the DOM to the API.

At least I now know how to handle this particular type of control.
