### ISSUE TITLE
I cannot seem to expand on the tests as XRM just fails

### ISSUE THREAD

**Issue by bloodcurse** [Microsoft/EasyRepro#89]
Having issues with expanding on the tests you have provided.
I need to ad a single step to the log in to allow the tests to log in.
Its the I have more than 1 account under the email address. I need to select the button for work or school account before I enter my password. However I have tried a few different ways. adding the xpath to the "reference page" however i just get an XRM error the moment it performs the task. even i i just put the raw selenium in the Login code.

driver.FindElement(By.Id("aadTile")).Click(); 

Above is the line im adding works then crashes. is there another way of dealing with this page or do i need to write my own framework in Selenium?

**Comment by TYLEROL** [comment]
We're reviewing this problem internally as we've reproduced the same behavior and are looking at possible ways to handle it. We'll update again once more info is available on how we can handle this scenario.

In the meantime, the behavior driving this stems from Id overlap between Azure AD (AAD) and Microsoft (MSA) accounts. A blog article was written discussing the behavior and the Microsoft strategy moving forward: https://cloudblogs.microsoft.com/enterprisemobility/2016/09/15/cleaning-up-the-azure-ad-and-microsoft-account-overlap/

If you find that this overlap is no longer required, you may consider renaming the personal account to remove the overlap between identity services. This would alleviate the prompt and allow the tests to function as-is. The following KB was created to walk through the renaming process: https://support.microsoft.com/en-us/help/11545/microsoft-account-rename-your-personal-account **Please be aware of the note regarding statellite services like the Xbox Developer community and Visual Studio / MSDN subscription services. Renaming the account can cause access to be lost**

**Comment by dtu11** [comment]
Adding to Tyler's recommendation.  If you do want to continue with the two accounts and handle the selection please use the example below.  I've created a PR to add a fix for the ClickWhenAvailable to ignore the StaleElementReference that was initially causing your exception.  

Try this example.  

```

[TestMethod]
        public void TestCustomLogin()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, CustomLoginAction);
            }
        }

        public void CustomLoginAction(LoginRedirectEventArgs args)
        {
            //Login Page details go here.  You will need to find out the id of the password field on the form as well as the submit button. 
            //You will also need to add a reference to the Selenium Webdriver to use the base driver. 

            //Example
            //--------------------------------------------------------------------------------------
            var d = args.Driver;

            //Handle Multiple accounts with same email
            d.ClickWhenAvailable(By.Id("aadTile"));

            //Enter Password
            d.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(args.Password.ToUnsecureString());
            d.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).SendKeys(Keys.Tab);
            d.FindElement(By.XPath(Elements.Xpath[Reference.Login.LoginPassword])).Submit();

            //Click Do not stay signed in
            if (d.IsVisible(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])))
            {
                d.ClickWhenAvailable(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn]));
                d.FindElement(By.XPath(Elements.Xpath[Reference.Login.StaySignedIn])).Submit();
            }

            //Wait for CRM Page to load
            d.WaitUntilVisible(By.XPath(Elements.Xpath[Reference.Login.CrmMainPage])
                , new TimeSpan(0, 0, 60),
                e => { e.WaitForPageToLoad(); },
                f => { throw new Exception("Login page failed."); });
            //--------------------------------------------------------------------------------------
        }
```

**Comment by bloodcurse** [comment]
Thanks Gents,

I have had a new specific user created to get round the problem. But thanks thats a great help!

**Comment by dtu11** [comment]
Np at all.   I'll close the issue and if you need anything just let us know. 

Thanks
