### ISSUE TITLE
[BUG] Cannot add Timeline note due changes Note Text control from textarea to text editor field

### ISSUE THREAD

**Issue by Shakevg** [Microsoft/EasyRepro#907]
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  

**Special formatting / display**  
Note Text control cannot be found due it was changes from textarea field to complex text editor field

**Code to reproduce**  
```csharp
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
xrmApp.Navigation.OpenApp(UCIAppName.Sales);
xrmApp.Navigation.OpenSubArea("Sales", "Accounts");
xrmApp.Grid.OpenRecord(0);
xrmApp.Timeline.AddNote("Lions and Tigers", "Note - They do not get along !");
```
 
**Expected behavior**  
Need to change AddNote method to support new edit control type

**Screenshots**  
![image](https://user-images.githubusercontent.com/42133199/85421744-72d01380-b57d-11ea-86a7-984431d9bbf3.png)

**Comment by ryanpiran** [comment]
I'm also experiencing this. It affects quite a few of our regression tests and we've had to revert to a previous version of EasyRepro for now.
