### ISSUE TITLE
How to get column attributes from Grid.GetGridItems()

### ISSUE THREAD

**Issue by Martin138** [Microsoft/EasyRepro#909]
I had some code that previously worked but at some point Dynamics 365 must've changed and it no longer works.
GetGridItems() returns a list of records on a grid and each record contains attributes which were accessible using the GetAttribute<>() method.

The attributes used to be properly named such as "accountnumber" or "name" but recently they have changed into "Grid754ff515-8cf0-6241-9442-93d30de38e8c-accountnumber" and "Grid754ff515-8cf0-6241-9442-93d30de38e8c-name".

My question is, is there an easier way of doing this solely with EasyRepro methods or does something need to change in order to fix this issue?

I am using Dynamics365.UIAutomation.Api version 9.1.0.17139

Example of code that previously worked:
            var accountList = _app.Grid.GetGridItems();
            foreach (GridItem account in accountList)
            {
                if (account.GetAttribute<string>("name").Equals(accountName))
                {
                    return true;
                }
            }

**Comment by todstanis** [comment]
I logged this issue (https://github.com/microsoft/EasyRepro/issues/903) a couple of weeks back, but haven't received any response. I actually reviewed the underlying code, so I know why it doesn't work and wrote my own work around, which I'll post in a few  minutes.

**Comment by todstanis** [comment]
I found the number of bugs in the 9.1 Unified Interface version of the library to be a major road block and ended up writing a set of mirror classes that wrap the existing framework. Most of the methods are passthrough, but it makes it easy to pop in a fix and then pull it out when the framework is updated.

I added this in my Grid class wrapper:

```
        private List<GridItem> FixGridItems(List<GridItem> items)
        {
            // TODO:
            // Due to a bug in the API the ids used to store row data have random GUIDs in front of the
            // real column names and the GridItem object provides no direct access to the attributes dictionary.
            // This block of code makes a copy of every attribute to a new attribute with the correct name.
            // When that bug is fixed this code will throw a duplicate key violation and it can then be deleted.
            IWebElement gridContainer = PageClass.Client.Browser.Driver.WaitUntilAvailable(By.XPath("//div[@data-type=\"Grid\"]"));
            IWebElement columnGroup = gridContainer.FindElement(By.ClassName("wj-colheaders"));
            IWebElement columnHeader = columnGroup.FindElement(By.ClassName("wj-row"));
            IEnumerable<IWebElement> rowHeaders = columnHeader.FindElements(By.CssSelector("div.wj-cell.wj-header[title][id][data-id]"))
                .Where(c => !string.IsNullOrEmpty(c.GetAttribute("title")) && !string.IsNullOrEmpty(c.GetAttribute("id")));
            Dictionary<string, string> idToDataIdMapping = new Dictionary<string, string>();
            foreach (var header in rowHeaders)
            {
                string id = header.GetAttribute("id");
                string dataId = header.GetAttribute("data-id");
                idToDataIdMapping.Add(id, dataId);
            }
            foreach (GridItem item in items)
            {
                foreach (string id in idToDataIdMapping.Keys)
                    item[idToDataIdMapping[id]] = item[id];
            }

            return items;
        }
```

```
        public List<GridItem> GetGridItems()
        {
            List<GridItem> items = PageClass.App.Grid.GetGridItems();
            return FixGridItems(items);
        }
```

Hopefully it'll be fixed in the near future, but in the meantime maybe you can use this as the basis to your own workaround.

**Comment by Martin138** [comment]
>         private List<GridItem> FixGridItems(List<GridItem> items)
>         {
>             // TODO:
>             // Due to a bug in the API the ids used to store row data have random GUIDs in front of the
>             // real column names and the GridItem object provides no direct access to the attributes dictionary.
>             // This block of code makes a copy of every attribute to a new attribute with the correct name.
>             // When that bug is fixed this code will throw a duplicate key violation and it can then be deleted.
>             IWebElement gridContainer = PageClass.Client.Browser.Driver.WaitUntilAvailable(By.XPath("//div[@data-type=\"Grid\"]"));
>             IWebElement columnGroup = gridContainer.FindElement(By.ClassName("wj-colheaders"));
>             IWebElement columnHeader = columnGroup.FindElement(By.ClassName("wj-row"));
>             IEnumerable<IWebElement> rowHeaders = columnHeader.FindElements(By.CssSelector("div.wj-cell.wj-header[title][id][data-id]"))
>                 .Where(c => !string.IsNullOrEmpty(c.GetAttribute("title")) && !string.IsNullOrEmpty(c.GetAttribute("id")));
>             Dictionary<string, string> idToDataIdMapping = new Dictionary<string, string>();
>             foreach (var header in rowHeaders)
>             {
>                 string id = header.GetAttribute("id");
>                 string dataId = header.GetAttribute("data-id");
>                 idToDataIdMapping.Add(id, dataId);
>             }
>             foreach (GridItem item in items)
>             {
>                 foreach (string id in idToDataIdMapping.Keys)
>                     item[idToDataIdMapping[id]] = item[id];
>             }
> 
>             return items;
>         }


Excellent! That worked for me. Glad I'm not the only one who has this issue.
I had managed a crude workaround using purely Selenium, but had to change a lot elsewhere in order for it to work, so I'm happy to revert it back to how it was.

Thanks for your help. I'll close this issue and mark it as a duplicate to yours.

**Comment by Martin138** [comment]
Duplicate of #903
