### ISSUE TITLE
[BUG] Assign is not working if the command is not displayed but available in extra commands

### ISSUE THREAD

**Issue by vcinampudi** [Microsoft/EasyRepro#933]
## Bug Report
when trying to assign a record but the assign command is displayed within vertical three dots menu.
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ X] UCI (XrmApp)

**Online or On Premise**
  - [ X] Online
**Browser**
  - [ X] Chrome

**Describe the bug**  

**Special formatting / display**  

**Code to reproduce**  

**Screenshots**  

**Additional context**

**Comment by TYLEROL** [comment]
@vcinampudi - Could you try validating this with the latest samples from the develop branch? A contribution was merged today that impacted this area specifically.

Thanks,
Tyler

**Comment by vladimir-goncharov** [comment]
Hi Tyler,

I have tried out the latest changes from the develop branch and can still reproduce the issue. We love to use the easy repro framework and would appreciate very much to get a fix for the reported issue.

Cheers,
Vladimir
