### ISSUE TITLE
How to create a new record in a subgrid

### ISSUE THREAD

**Issue by sujitkoganti** [Microsoft/EasyRepro#934]
Hi there

I have multiple tabs and each tab contains multiple subgrids.
I am trying to create new records from the sub grids.. (Screenshot attached)

I tried below options.. but no luck :(

XrmApp.CommandBar.ClickCommand("New Medical Review Notification");
XrmApp.RelatedGrid.ClickCommand("New Medical Review Notification");
XrmApp.Entity.SubGrid.ClickCommand("Active Medical Review Notifications", "New Medical Review Notification");

![image](https://user-images.githubusercontent.com/13937838/89478842-97521900-d7d4-11ea-91da-73b4719c5be2.png)

**Comment by TYLEROL** [comment]
Hi @sujitkoganti - You'll want to pass the _schema name_ of the subgrid control, not the name of the view. As the View Picker and Name options can be hidden, the schema name is the consistent/reliable way to always locate the subgrid.

You can find this by looking at the 'name' of the ListItemControl on an entity form, or by using the browser dev tools (f12) inspector . In the example below, the _schema name_ will show up after datasetRoot_ -- **AssociatedAnalysisResults** in this example is what I would provided have I wanted to click the refresh button.

![image](https://user-images.githubusercontent.com/29415524/89580679-56b9c600-d7fb-11ea-97e9-ace65c37096e.png)

`XrmApp.Entity.SubGrid.ClickCommand("AssociatedAnalysisResults", "Refresh");`


Thanks,
Tyler

**Comment by sujitkoganti** [comment]
Thanks Tylerol
