### ISSUE TITLE
How to handle pop up windows/browser?

### ISSUE THREAD

**Issue by abrahamjoji** [Microsoft/EasyRepro#94]
I have a scenario on a click of add/new a new browser or popup window will appear.
i try to use  xrmBrowser.Entity.SelectForm("xyz");
*xyz - browser title name
its able to identify the browser but i cant able to setvalue to the edit fields and other controls.

**Comment by dtu11** [comment]
If it's a new window or tab then you can use the following to switch to it. 

xrmBrowser.Driver.LastWindow();

**Comment by abrahamjoji** [comment]
Thank you... Its working.

I am not sure its a valid question.
Do you have any documentation related to the functions and its use, Like this

xrmBrowser.Driver.LastWindow();                     Switch to new window or tab
...
...

Such kind of info is there it would be helpful for me.

**Comment by TYLEROL** [comment]
Thanks for the feedback @abrahamjoji. Currently most existing documentation is in the form of code comments.

We have documentation initiatives underway and plan to publicly document all of the APIs/Methods/Functions etc. I don't have an ETA to share for when that will be ready but it's something we want to make available as soon as possible.

Regards,
Tyler

**Comment by abrahamjoji** [comment]
@TYLEROL that sounds good ... Hope we get the documentation as soon as possible.

I would like to know how to handle the report generation part and Traces/logs of this EasyRepro. Once the test completed we need a detail report of the test case and the traces. 

Currently the EasyRepro give whether the test is passed or fail. Apart from that if it is a detailed report like BDD or  Debug.WriteLine(DateTime.Now + "--COMMENTS-- "); then it can be understand by any folks. 
And for the traces/logs. When we run the test along with the build then traces or logs will help to understand where the failure occurred.
I would like to know do you have any suggestion for this.

**Comment by TYLEROL** [comment]
@abrahamjoji - Were you thinking of something like this? I've added some basic examples below using the CreateAccount test and implementing a basic try/catch to push the error to console and a text file. 

If this is what you had in mind, please let me know and I can discuss with the team about adding a sample "Logger" example to the code base.


**app.config addition**

```
  <appSettings>
    <add key="OnlineUsername" value="" />
    <add key="OnlinePassword" value="" />
    <add key="OnlineCrmUrl" value="" />
    <add key="AzureKey" value="" />
    <add key="LogFileLocation" value="ErrorLog.txt"/>
  </appSettings>
```

**Logger.cs example:**

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Microsoft.Dynamics365.UIAutomation.Sample
{
    public static class Logger
    {

        public static void LogMessage(String MessageToLog)
        {
            Console.WriteLine(MessageToLog);
            WriteToErrorLog(MessageToLog);
        }
        public static void WriteToErrorLog(String MessageToLog)
        {
            using (StreamWriter writer = new StreamWriter(System.Configuration.ConfigurationManager.AppSettings["LogFileLocation"].ToString(), true))
            {
                writer.WriteLine(String.Format("{0} \t {1}", DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss.fff"), MessageToLog));
            }
        }

    }
}
```
**CreateAccount.cs sample:**

```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Dynamics365.UIAutomation.Api;
using Microsoft.Dynamics365.UIAutomation.Browser;
using System;
using System.Security;

namespace Microsoft.Dynamics365.UIAutomation.Sample
{
    [TestClass]
    public class CreateAccountTests
    {

        private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());

        [TestMethod]
        public void TestCreateNewAccount()
        {
            try
            {
                using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
                {

                    xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                    xrmBrowser.GuidedHelp.CloseGuidedHelp();

                    xrmBrowser.ThinkTime(500);
                    xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");

                    xrmBrowser.ThinkTime(2000);
                    xrmBrowser.Grid.SwitchView("Active Accounts");

                    xrmBrowser.ThinkTime(1000);
                    xrmBrowser.CommandBar.ClickCommand("Neww");

                    xrmBrowser.ThinkTime(4000);
                    xrmBrowser.Entity.SetValue("name", "Test API Account");
                    xrmBrowser.Entity.SetValue("telephone1", "555-555-5555");
                    xrmBrowser.Entity.SetValue("websiteurl", "https://easyrepro.crm.dynamics.com");

                    xrmBrowser.CommandBar.ClickCommand("Save & Close");
                    xrmBrowser.ThinkTime(2000);
                }

            }
            catch (Exception ex)
            {
                Logger.LogMessage(String.Format("{0}/r{1}", ex.Message, ex.StackTrace));
                Assert.Fail("An error has occurred. Please see ErrorLog in \bin\debug folder for more details.");
            }
        }
    }
}
```

Thanks,
Tyler

**Comment by abrahamjoji** [comment]
@TYLEROL This is working fine for me. Thank you.
