### ISSUE TITLE
[BUG] Grid Sort not working in UCI | No more 1 click sort

### ISSUE THREAD

**Issue by samadane** [Microsoft/EasyRepro#942]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Running unit test in OpenAccount called UCITestGetActiveGridItems. It is failing on
 xrmApp.Grid.Sort("Account Name");
Does this sort work now that one click sorting is disabled?  Sort for all fields must choose a - z, etc.

Version - 9.1.0000.20460

**Code to reproduce**  
Take unit test UCITestGetActiveGridItems and run on vanilla online instance with develop branch (Sales module installed)

```csharp
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecretKey);

                xrmApp.Navigation.OpenApp(UCIAppName.Sales);

                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

                xrmApp.Grid.SwitchView("Active Accounts");

                xrmApp.Grid.GetGridItems();

                xrmApp.Grid.Sort("Account Name");

                xrmApp.ThinkTime(3000);
```

 
**Expected behavior**  
Grid should sort

**Comment by thathi** [comment]
@samadane can you be able to check if that solves your issue?
