### ISSUE TITLE
Selenium.WebDriver  and EdgePageLoadStrategy

### ISSUE THREAD

**Issue by seagn** [Microsoft/EasyRepro#95]
Hi

When I update Selenium to a version greater than 3.6.0 I get the error below. 

BrowserOptions.cs

Error	CS0266	Cannot implicitly convert type 'OpenQA.Selenium.Edge.EdgePageLoadStrategy' to 'OpenQA.Selenium.PageLoadStrategy'. 
An explicit conversion exists (are you missing a cast?)	Microsoft.Dynamics365.UIAutomation.Browser

**Comment by TYLEROL** [comment]
Thanks @seagn for raising this. Currently the highest supported version is v3.5.1 as we have not tested the latest available versions.

I'd advise you to use v3.5.1 for now - however I'll take a look at verifying that I can generate these same errors for internal review to consider support for the latest Selenium versions.

**Comment by TYLEROL** [comment]
@seagn - Could you share more details on the steps you took to upgrade Selenium to a newer version?

- Browser / Version
- Update Process (to update the Selenium drivers)
- Test code being utilized (if error is during a test and not the driver update)

Using steps from the [NuGet Package Manager UI](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui/), I updated both the Selenium.WebDriver and Selenium.Support packages to v3.6.0. I received no errors during the update process and test execution in all browsers, including Edge, were successful.

Thanks,
Tyler

**Comment by seagn** [comment]
Hi

Visual Studio 2017 Community & Windows 10

1. Download the package to desktop - > EasyRepro-releases-v9.0
2. Unzip
3. Open the solution in VS 2017 -> UIAutomation.sln
4. Right click on the solution and then 'Restore Nuget Packages'
5. After restoring, build the solution. OK builds fine
6. Right click on 'Microsoft.Dynamics365.UIAutomation.Browser' project and select 'Manage Nuget Packages'
7. The package manager indicates there's updates available for Selenium.WebDriver and Selenium.Support from v3.5.1 to v3.10.0
8. Select and update the packages
9. Build again. I get the error

Error	CS0266	Cannot implicitly convert type 'OpenQA.Selenium.Edge.EdgePageLoadStrategy' to 'OpenQA.Selenium.PageLoadStrategy'. An explicit conversion exists (are you missing a cast?)	Microsoft.Dynamics365.UIAutomation.Browser	Downloads\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser	Downloads\EasyRepro-releases-v9.0\Microsoft.Dynamics365.UIAutomation.Browser\BrowserOptions.cs	114	Active

Hope this helps

**Comment by TYLEROL** [comment]
Thanks again @seagn . It looks like I misread your original post and had interpreted this as broken in v3.6.0. As you originally indicated, I have also confirmed this issue reproduces in v3.7.0 and higher of the Selenium.WebDriver.

In v3.7, a change was introduced which removed PageLoadStrategy from EdgeOptions.cs. Instead this now resides in DriverOptions.cs and is also no longer declared as an enumeration.

We've logged a bug which will require updates to bring compatibility with the latest WebDriver versions. I do not have an ETA for completion of this work, but will update once the changes for compatibility are made available. **I would encourage reverting back to v3.5.1 for full functionality until this compatibility work has been completed**

If you have any additional questions - please let us know.

Regards,
Tyler

**Comment by seagn** [comment]
Thank's

That's what I'll do. Use v3.5.1

Regards

**Comment by TYLEROL** [comment]
@seagn - We just released an updated version of the EasyRepro APIs last night with bug fixes, support for v8.2, v9.0, and v9.0.2. The v9.0.2 branch includes support for the new Unified Interface within Dynamics 365.

We also updated the projects to support v2.38 of the Chrome WebDriver and v3.11.2 for Selenium.Support and Selenium.WebDriver.

If you encounter any issues with the updated code, please don't hesitate to raise any new issues as required.

Regards,
Tyler
