### ISSUE TITLE
Login with ADFS not working

### ISSUE THREAD

**Issue by rbasten** [Microsoft/EasyRepro#96]
Hi, 

I'm new to EasyRepro, so hope someone can help me out.
When I run a test the browser starts up and the username is put in, so far so good.
In the next screen there is no option for putting in the password because it is SSO, even with private mode on. So the application crashes here.
Can someone help me setting the applicaiton up for handling SSO?

Thanks.

**Comment by TYLEROL** [comment]
@rbasten - I'd suggest using a custom login action like the sample below. The custom login action should trigger after supplying the Username credentials. For SSO scenarios you can cut out the password inputs since they would not be required. 

If you have any additional questions for this, please let us know.

Thanks!
Tyler

```
[TestMethod]
        public void TestCustomLogin()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, CustomLoginAction);
            }
        }

        public void CustomLoginAction(LoginRedirectEventArgs args)
        {
            //Login Page details go here.  You will need to find out the id of the password field on the form as well as the submit button. 
            //You will also need to add a reference to the Selenium Webdriver to use the base driver. 

            //Example
            //--------------------------------------------------------------------------------------
            var d = args.Driver;

            //Insert any additional code as required for the SSO scenario

            //Wait for CRM Page to load
            d.WaitUntilVisible(By.XPath(Elements.Xpath[Reference.Login.CrmMainPage])
                , new TimeSpan(0, 0, 60),
                e => { e.WaitForPageToLoad(); },
                f => { throw new Exception("Login page failed."); });
            //--------------------------------------------------------------------------------------
        }
```

**Comment by rbasten** [comment]
Hi Found the way to select the correct login account with this code"
                    if (driver.IsVisible(By.Id("aadTile")))
                    {
                        driver.FindElement(By.Id("aadTile")).SendKeys(Keys.Enter);
                    }

Tnx for the help

**Comment by TYLEROL** [comment]
Thanks @rbasten . It appears I slightly misinterpreted your initial issue. The code above will be helpful for this unique scenario in which an account resides in AAD and MSA directories with the same email/username. I've provided the snippet below to others in the past, sharing it to you as well if having to click the aadTile is not desired. I'll go ahead and close out this issue. If you have any additional questions you can re-open for further discussion.

> The behavior driving this **aadTile** stems from Id overlap between Azure AD (AAD) and Microsoft (MSA) accounts. A blog article was written discussing the behavior and the Microsoft strategy moving forward: https://cloudblogs.microsoft.com/enterprisemobility/2016/09/15/cleaning-up-the-azure-ad-and-microsoft-account-overlap/ 
> 
> If you find that this overlap is no longer required, you may consider renaming the personal account to remove the overlap between identity services. This would alleviate the prompt and allow the tests to function as-is. The following KB was created to walk through the renaming process: https://support.microsoft.com/en-us/help/11545/microsoft-account-rename-your-personal-account **Please be aware of the note regarding statellite services like the Xbox Developer community and Visual Studio / MSDN subscription services. Renaming the account can cause access to be lost**

Thanks,
Tyler

**Comment by kamranRehman** [comment]
Hi,

I'm having similar issue where USER ID and PASSWORD was successfully accepted during the automation, however on the YES/NO screen, the automation doesn't work, I'm on 9.02Beta.

![loginscreen](https://user-images.githubusercontent.com/45043140/48495783-86b87d00-e852-11e8-9273-ebcb059eb4d8.PNG)

I'm using the following code for login.

  public class PatientCRUD
    {
        private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());

   public void TstContactCRUD()
        {
            using (var xrmBrowser = new Api.Browser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, xrmBrowser.LoginPage.ADFSLoginAction);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();
}
}

Wondering is there anything I'm missing?

**Comment by adhawan325** [comment]
@kamranRehman - Kamran - did you ever figure this out?  What was the fix?  We have the same issue.

**Comment by rbasten** [comment]
Hi, I've not tried this in version 9, but will try next week and will let you know if my previous fix (with other command ofcourse) can resolve this as well.

Kind regards,

**Comment by kamranRehman** [comment]
> @kamranRehman - Kamran - did you ever figure this out? What was the fix? We have the same issue.

In order to by pass this issue temporary, when you run your automation and when this particular dialog appears, you just need to manually click the YES button in order to MOVE FORWARD, this is the only way I've been doing in order to proceed until we get the fix from GITHUB.

Thanks
-Kamran.

**Comment by kamranRehman** [comment]
> Hi, I've not tried this in version 9, but will try next week and will let you know if my previous fix (with other command ofcourse) can resolve this as well.
> 
> Kind regards,

Hi rbasten,

Not sure what other command you're referring to? can you please put code snippet for that so that either myself or adhawan325 will give it a try?

Thanks.
-Kamran.

**Comment by TYLEROL** [comment]
@kamranRehman - Could you share your code from xrmBrowser.LoginPage.ADFSLoginAction?

Thanks,
Tyler

**Comment by prachiwalke** [comment]
Hi All,
I'm facing the issue of "Stay Signed-in" pop-up during Login, while executing automation script. Username and Password are entered into the text boxes and after this Stay signed in pop-up appears. Manually clicking on Yes/No button won't help in my case, as i need to execute the scripts in bulk. Need the solution urgently.
Kindly help.
Thanks in Advance.
My code:
 private SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername1"].ToSecureString();
        private SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword1"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());
xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
