### ISSUE TITLE
[BUG] Command not found inside "More Commands" of form or subgrid

### ISSUE THREAD

**Issue by Fietlux** [Microsoft/EasyRepro#969]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  

Using ```App.CommandBar.ClickCommand("Copy Opportunity")``` fails for existing ribbon on entity form.
This also affects **subgrids** if the desired action is placed in the "More Commands" submenu.
The method is pretending to also check the "More Commands" submenu but does not find the desired command/ribbon.

**Special formatting / display**  
none

**Code to reproduce**  

```csharp
App.CommandBar.ClickCommand("Copy Opportunity");
```
 
**Expected behavior**  

The method is able to click the desired command and executing the action behind.

**Screenshots**  

WebClient

![image](https://user-images.githubusercontent.com/70751142/92337176-15d9f900-f0a8-11ea-9f92-1a08ab02dd69.png)

Occurring Exception

![image](https://user-images.githubusercontent.com/70751142/92337104-892f3b00-f0a7-11ea-8b7f-9d0a3f51e9cf.png)

CommandBar

![image](https://user-images.githubusercontent.com/70751142/92337107-8f251c00-f0a7-11ea-8e9e-57209e02fdb5.png)

**Additional context**  
Related Issue #893

**Comment by TYLEROL** [comment]
@Fietlux - This is fixed in the develop branch. The release branch and NuGet package should be updated on Monday.

Thanks,
Tyler
