### ISSUE TITLE
Support to Dynamics 365 Finance and Operations

### ISSUE THREAD

**Issue by abrahamjoji** [Microsoft/EasyRepro#97]
Hi,
I know that EasyRepro works well with Dynamics CRM. Just wanted to know whether the existing libraries support Dynamics 365 Finance and Operations?

**Comment by mspilde** [comment]
Definitely understand the need and this is currently on our roadmap but we don't have a date yet.

**Comment by abrahamjoji** [comment]
@mspilde Thank you...
if any update is there please let us know.
