### ISSUE TITLE
[BUG] Selecting a sub-tab (e.g. Related -> Documents) doesn't work if the Related tab is within the overflow menu

### ISSUE THREAD

**Issue by ewingjm** [Microsoft/EasyRepro#979]
## Bug Report

**EasyRepro Version**
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)

**Online or On Premise**
  - [x] Online

**Browser**
  - [x] Chrome

**Describe the bug**  

Selecting a sub-tab (e.g. Documents within Related) works fine unless the number of tabs and screen size is such that the Related tab is within the overflow menu.

**Code to reproduce**  
```csharp
XrmApp.Entity.SelectTab("Related", "Documents");
```
 
**Expected behaviour**  

The documents sub-tab should be selected regardless of whether the Related tab is within the overflow menu or not.

**Screenshots**  

![image](https://user-images.githubusercontent.com/34515225/93452266-6b14d680-f902-11ea-81f5-2c12a38751b6.png)

**Additional context**  

The overflow menu is clicked - resulting in the screenshot above - and an exception is thrown: 

>System.Exception : The tab with name: Related does not exist

**Comment by TYLEROL** [comment]
@ewingjm - Could you provide version details from the organization you tested with? I have pushed several fixes over the weekend into the Develop branch and in a few scenarios I was calling this exact scenario when testing. 

I did not observe any issues, however I am also testing with the latest from a First Release Environment (9.1.0.23435). I plan to publish the latest from develop to NuGet and releases/v9.1 tomorrow if you want to re-test with the latest code at that time.

Thanks,
Tyler

**Comment by ewingjm** [comment]
Hi Tyler,

Here's the version information from our organisation - 

> 2020 release wave 2 enabled
> Server version: 9.1.0000.22845
> Client version: 1.4.1440-2008.5

We've got series of tests which are very similar and it's working fine in the scenarios where the 'Related' tab is not pushed into the overflow menu. I'll retry with the latest version when it's available.
