### ISSUE TITLE
Not able to interact with the elements not visible in the form or page even after UCITestMode is set to true

### ISSUE THREAD

**Issue by hrathiko** [Microsoft/EasyRepro#983]
Hi @TYLEROL 

We are not able to set / get the value of the field which is not visible on the form (sections below the visible screen) even after setting the UCITestMode to true.

In Testsetting file , we use like below

        public static BrowserOptions Options = new BrowserOptions
        {
            BrowserType = (BrowserType)Enum.Parse(typeof(BrowserType), Type),
            PrivateMode = true,
            FireEvents = true,
            Headless = false,
            UserAgent = false,
            UCITestMode = true,
            UCIPerformanceMode = false
        };
Please note that ,in the XrmApp.Login() method, We have the  @_client.InitializeModes(, where this method uses UCITestMode, that is set as true.

We already referred Easyrepro Issues **#489 and #631** and created this issue, considering that even after setting the UCITestMode to true, not able to interact with the elements.

Note: We are using Easyrepro Framework 9.0(NugetSpecs)

**Comment by IshaAnshu** [comment]
Facing the same issue, until last Friday easyrepro was interacting with the elements which were not visible, but suddenly tests have started to fail.

**Comment by ismail4u** [comment]
Please let us know when the fix will be available for this issue ?

**Comment by hrathiko** [comment]
After getting the latest version of easyrepro UCI library, the issue got resolved.

**Comment by hrathiko** [comment]
The issue is resolved after updating with the latest version of UCI Easyrepro library.

**Comment by Gtam12** [comment]
@hrathiko I have latest version - 9.1.0.27021. Still i face the issue(unable to find elements not visible, though UCITesMode is true). What version should i upgrade or downgrade to make it work.
