### ISSUE TITLE
[BUG] SetValue For Lookup Taking too much time .

### ISSUE THREAD

**Issue by badarmunirr** [Microsoft/EasyRepro#997]
## Bug Report

  - [ ] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ ] UCI (XrmApp)

**Online or On Premise**
  - [ ] Online

**Browser**
  - [ ] Chrome

**Describe the bug**  
SetValue For LookupItem is taking more than 50sec .its increasing test time 

**Code to reproduce**  

            LookupItem LookupVeriable = new LookupItem { Name = LookupFieldName, Value = LookupFieldValue, Index = 0 };
            xrmApp.Entity.SetValue(LookupVeriable);

 
**Expected behavior**  
It Should Not take more time when the field is visible it should just select the displayed result

**Comment by Shakevg** [comment]
@badarmunirr  Issue in XPath that used to search value in lookup located in DOM root now. I will add a fix.

**Comment by badarmunirr** [comment]
@Shakevg  when this fix will be available?

**Comment by ismail4u** [comment]
Waiting for the fix , please let us know when this will be available ?

**Comment by Deep4569** [comment]
Also waiting for the fix. Currently, the execution time is too long. Please provide a fix to this issue ASAP @Shakevg

**Comment by badarmunirr** [comment]
Still, waiting for the update?

**Comment by Shakevg** [comment]
@badarmunirr Not yet committed, I created a pull request with a fix and waiting for code review (but looks like @TYLEROL on vacation).

**Comment by badarmunirr** [comment]
@Shakevg Oh okay Thanks for the response once its done please let me know

**Comment by SriVHari** [comment]
Fix available for Issue in XPath that used to search value in lookup located in DOM root ??

**Comment by Shakevg** [comment]
> Fix available for Issue in XPath that used to search value in lookup located in DOM root ??

Yes

**Comment by Shakevg** [comment]
Anyone can apply to [fix](https://github.com/microsoft/EasyRepro/pull/1008) locally until the pull request will be approved

**Comment by badarmunirr** [comment]
the problem is I am using the nugget package

**Comment by badarmunirr** [comment]
@TYLEROL  any update on this issue

**Comment by sudipmandal** [comment]
Please push fix to nuget

**Comment by badarmunirr** [comment]
@Shakevg this fix will work for quick create lookup too? and ETA for this fix @TYLEROL

**Comment by Shakevg** [comment]
> @Shakevg this fix will work for quick create lookup too? and ETA for this fix @TYLEROL

Fix already in dev branch.
@sudipmandal I suppose yes, but you should check

**Comment by badarmunirr** [comment]
@TYLEROL, please release updated nugget package

**Comment by badarmunirr** [comment]
@Shakevg setvalue for lookup item in quick create is still taking too much time .

**Comment by Shakevg** [comment]
@badarmunirr Could you please post a code example

**Comment by badarmunirr** [comment]
@Shakevg 
  LookupItem LookupQuickVeriable = new LookupItem { Name = LookupFieldName, Value = LookupFieldValue, Index = 0 };
   xrmApp.QuickCreate.SetValue(LookupQuickVeriable);

**Comment by Shakevg** [comment]
@badarmunirr
I checked on the contact quick create form. It is working very fast (about 2 seconds per lookup) on the dev branch and also with the latest NuGet.
Could you check that you really use the latest fixes?
![image](https://user-images.githubusercontent.com/42133199/100383864-bac4fc00-302f-11eb-920a-c2551fe3c064.png)

**Comment by badarmunirr** [comment]
@Shakevg it's working fine thanks.
