### ISSUE TITLE
[BUG] GetValue for LookupItem returns value twice

### ISSUE THREAD

**Issue by Fietlux** [Microsoft/EasyRepro#998]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
After the latest update getting values from lookup items, the resulting string appears as "Value; Value" instead of just "Value".
The used lookup attributes have definitely one single element.

**Special formatting / display**  
none

**Code to reproduce**  
```csharp
string countryValue = App.Entity.GetValue(new LookupItem(){ Name="tk_countryregionid" });
Assert.AreEqual("Germany", countryValue);
```
_Result:_ ```'Message: Error at "Assert.AreEqual". Expected:<Germany>. Current:<Germany; Germany>.'```

**Expected behavior**  
GetValue for LookupItem shall return single display name only.

**Screenshots**  

**Additional context**

**Comment by BenjaminP-GitHub** [comment]
We are also experiencing this issue

**Comment by chrizz-msweb** [comment]
Is this bug fixed ?

**Comment by imartinflores** [comment]
seems it is not fixed, I am still having the issue

**Comment by ismail4u** [comment]
Any workaround ? when this will be fixed ?

**Comment by chrizz-msweb** [comment]
Temporary workaround:   Assert.IsTrue(countryValue.Contains("Germany"));

**Comment by imartinflores** [comment]
I'd suggest to split it before Asserting

**Comment by chrizz-msweb** [comment]
Right!!..     Here the method

        protected void checkLookupValue(XrmApp xrmApp, string idLookup, string value)
        {
            string val = xrmApp.Entity.GetValue(new LookupItem { Name = idLookup });
            string[] correction = val.Split(';');
            Assert.AreEqual(value, correction[0]);
        }
